### ISSUE TITLE
Latest container images are not on GCR

### ISSUE THREAD

**Issue by EppO** [kubernetes/kube-state-metrics#1000]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**: Tried to 
```
$ docker pull k8s.gcr.io/kube-state-metrics:v1.8.0
Error response from daemon: manifest for k8s.gcr.io/kube-state-metrics:v1.8.0 not found: manifest unknown: Failed to fetch "v1.8.0" from request "/v2/kube-state-metrics/manifests/v1.8.0".
```

**What you expected to happen**:
Image pulled successfully from GCR registry. 
It works fine on Quay

```
$ docker pull quay.io/coreos/kube-state-metrics:v1.8.0
v1.8.0: Pulling from coreos/kube-state-metrics
e8d8785a314f: Pull complete
e5cd5b31650b: Pull complete
Digest: sha256:f75c3e5c5c7f65846ddd6883d6187b38f77721a3938f241c9e5d0ebe7beb8e19
Status: Downloaded newer image for quay.io/coreos/kube-state-metrics:v1.8.0
quay.io/coreos/kube-state-metrics:v1.8.0
```

**How to reproduce it (as minimally and precisely as possible)**:
`docker pull k8s.gcr.io/kube-state-metrics:v1.8.0`

**Anything else we need to know?**:
Latest container images is 1.7.2: https://gcr.io/google-containers/kube-state-metrics

**Environment**:
- Kubernetes version (use `kubectl version`): 
- Kube-state-metrics image version: 1.8.0

**Comment by brancz** [comment]
These are maintained manually by google people. Pinging some to hopefully get these uploaded. @piosz @serathius @DirectXMan12 @logicalhan

**Comment by serathius** [comment]
I can get those uploaded. 

Frederic are you looking into https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io for kube-state-metrics?

**Comment by brancz** [comment]
We've done the first bits yes https://github.com/kubernetes/k8s.io/pull/384

Automation still pending.

**Comment by serathius** [comment]
```
kube-state-metrics $  docker pull k8s.gcr.io/kube-state-metrics:v1.8.0
v1.8.0: Pulling from kube-state-metrics
Digest: sha256:9d9632128f94b82dce5cf343340bb36a94bee002e8f5fb334b9cf649f47d0ea5
Status: Image is up to date for k8s.gcr.io/kube-state-metrics:v1.8.0
k8s.gcr.io/kube-state-metrics:v1.8.0
```
/close
