### ISSUE TITLE
Update compatibility matrix to include Kubernetes 1.16

### ISSUE THREAD

**Issue by tlereste** [kubernetes/kube-state-metrics#1007]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
The compatibility matrix on overview README is not up to date.

**What you expected to happen**:
Include Kubernetes 1.16 on compatibility matrix.

**Anything else we need to know?**:
We can see on Kubernetes 1.16 deprecated API document https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ that kube-state-metrics 1.7.2 and 1.8.0 is compatible with Kubernetes 1.16.

**Comment by tariq1890** [comment]
As per the comment [here](https://github.com/kubernetes/kube-state-metrics/pull/1008#issuecomment-566985710), we can close this issue.

**Comment by tlereste** [comment]
Ok thanks, I had not seen that ! I will close the issue.
