### ISSUE TITLE
Errors with ReplicationController metrics

### ISSUE THREAD

**Issue by tmegow** [kubernetes/kube-state-metrics#101]
Love this app! It's always worked great with zero issues, thank you.

Today, I excitedly tried out commit b68036d, however I'm getting errors like these in the logs and no rc metrics in /metrics.

```
E0307 14:41:26.060729       1 reflector.go:199] github.com/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.ReplicationController: the server could not find the requested resource
E0307 14:41:27.064053       1 reflector.go:199] github.com/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.ReplicationController: the server could not find the requested resource
E0307 14:41:28.066296       1 reflector.go:199] github.com/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.ReplicationController: the server could not find the requested resource
```

**Comment by brancz** [comment]
@dominikschulz ^ ?

**Comment by tmegow** [comment]
If it helps here is my kubernetes version and kube-apiserver runtime-config arg:

`Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.8", GitCommit:"c5fcb1951afb8150e4574bc234aed957cb586eb0", GitTreeState:"clean", BuildDate:"2017-01-12T02:14:29Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}`

`--runtime-config=api/all,batch/v2alpha1`

**Comment by brancz** [comment]
Thanks for all the info I currently don't have time to look into it, but will make sure it works when we do the release.

**Comment by brancz** [comment]
Actually I had a glimpse over the code and I think I spotted the error. Opened #104. At least where it error-ed before it doesn't anymore and I see `ReplicationController` metrics in `/metrics` :slightly_smiling_face: .

**Comment by tmegow** [comment]
#104 seems to do the trick :)
