### ISSUE TITLE
Signed images

### ISSUE THREAD

**Issue by MrDienns** [kubernetes/kube-state-metrics#1015]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

/kind feature

## Proposal
**Use case. Why is this important?**
Docker Content Trust allows us to verify if the images downloaded are indeed the images that Kubernetes published. Security measures can be setup to only download signed images.

This goes for all Kubernetes images, not just specific to this repository.

Is there any particular reason why signed images haven't been added, or is it simply a feature which hasn't been looked into yet?

https://docs.docker.com/engine/security/trust/content_trust/

**Comment by brancz** [comment]
I think this would generally be a great thing to have, there are a few things that prevent us from doing this today though:

1) all image repos for kube-state-metrics are maintained manually and synced across each other, kube-state-metrics is not even using a k8s.gcr.io image repo at the moment, when we have that we can look into 2.
2) there is no established key handling protocol, ideally that could be handled via a signing server maintained by the kubernetes project as a whole
