### ISSUE TITLE
kube-state-metrics without cluster-reader role

### ISSUE THREAD

**Issue by stevebail** [kubernetes/kube-state-metrics#1018]
I am trying to deploy kube-state-metrics where I don't have cluster-reader role.
Your documentation indicates the following RoleBinding for handling such case:

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-state-metrics
  namespace: project1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole <---- IS THIS CORRECT?
  name: view
subjects:
     kind: ServiceAccount
     name: kube-state-metrics
     namespace: your-namespace-where-kube-state-metrics-will-deployed

Such RoleBinding still shows the ServiceAccount is using a ClusterRole.
Is this a typo?
Did I miss something?
Thanks for your help

**Comment by brancz** [comment]
Using a namespaces role binding against a cluster role gives the target entity the cluster roles rules scoped to the namespace the role binding exists in.

**Comment by stevebail** [comment]
Thank you Frederic :)
Let me try it...

**Comment by stevebail** [comment]
@brancz 
It does work :) 
Thanks again for the tip.
I also tried successfully with a Role using  more or less the same definition as the ClusterRole and it also works from a deployment point-of-view. 
I am surprised to see the Role definition can actually include cluster-scope resources !
