### ISSUE TITLE
kube-state-metrics cant get some resource？

### ISSUE THREAD

**Issue by loveyang2012** [kubernetes/kube-state-metrics#1024]
I deploy a po named curl-xxxx, and I can get the cpu and memory that this pod used by kubectl top,
but I can't get  cpu or mem resource by "kube_pod_container_resource_requests_cpu_cores" of kube-state-metrics , why?

![image](https://user-images.githubusercontent.com/24237714/72199006-a6582f00-3470-11ea-85d7-7d04638f254f.png)
![image](https://user-images.githubusercontent.com/24237714/72199018-c38cfd80-3470-11ea-8ae2-d37ba8696cd3.png)

**Comment by brancz** [comment]
kubectl top gives you the real usage not the request, which is the metric you are looking for. The resource request metrics will only show up when actually set on the container.

**Comment by SoerenHenning** [comment]
Does kube-state-metrics also provide cpu/memory real usage data. If not, how can I get these data to be scraped by Prometheus?

**Comment by brancz** [comment]
You want to scrape the cAdvisor endpoints (`/metrics/cadvisor`) on the kubelets for this data with Prometheus.
