### ISSUE TITLE
invalid memory address on k8s 1.16.3

### ISSUE THREAD

**Issue by diogoserrano** [kubernetes/kube-state-metrics#1027]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Upgraded kube-state-metrics from 1.8.0 to 1.9.2
after upgrade, kube-state-metrics observed a panic:
[kube-state-metrics.log](https://github.com/kubernetes/kube-state-metrics/files/4066544/kube-state-metrics.log)

**What you expected to happen**:
the new version doesn't work with this version of k8s

**How to reproduce it (as minimally and precisely as possible)**:
install docker 18.9 and run kube-state-metrics with the flag --kubeconfig

**Anything else we need to know?**:
This was tested running k8s v1.16.3 with centOS VM

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.3
- Kube-state-metrics image version 1.9.2

**Comment by LiliC** [comment]
Thanks for the bug report. Seems like a problem with hpa metrics. Can you provide the specific hpa resource so we know what caused the segfault, thanks!

**Comment by diogoserrano** [comment]
Currently we have hpa with the API versions: 

- autoscaling/v1
- autoscaling/v2beta2

and all the hpa are targeting deployments.

is this information useful?

**Comment by LiliC** [comment]
We need more specific things like concrete numbers, is it possible to post the actual hpa resource, you can change any names or omit details, its more about the values. Thanks! I just want to be able to reproduce to fix. Or if you feel like you can't share feel free to also submit a fix for it.

**Comment by diogoserrano** [comment]
This is all the HPA that we have right now:
[hpa.txt](https://github.com/kubernetes/kube-state-metrics/files/4071562/hpa.txt)

**Comment by LiliC** [comment]
Thanks for the bug report, we reverted the hpa metrics that were causing this problem, we will cut a new release asap. Will leave this issue open as it has valid hpa examples we need if we decide to reimplement this. Thanks again!
