### ISSUE TITLE
expected type *v1.Namespace, but watch event object had type *v1.NetworkPolicy

### ISSUE THREAD

**Issue by mariusgrigoriu** [kubernetes/kube-state-metrics#1029]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Errors like 
```
E0104 20:10:10.371363       1 reflector.go:382] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: expected type *v1.Namespace, but watch event object had type *v1.NetworkPolicy
``` 
are appearing in logs.

**What you expected to happen**:
No errors

**How to reproduce it (as minimally and precisely as possible)**:
Seems like just running KSM in our environment does this.

**Anything else we need to know?**:
We are configured for 5 shards, so the message does not appear on all instances.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.2
- Kube-state-metrics image version: 1.9.2

**Comment by LiliC** [comment]
This is a client-go msg nothing to do with ksm from what I can tell. You should see this in most apps dealing with kubernetes clients.

cc @brancz for thoughts

**Comment by mariusgrigoriu** [comment]
In our case, only one out of five shards are logging this message.

**Comment by mindw** [comment]
Seeing this message as well - single instance:
* Kubernetes version (use kubectl version): 1.16.6
* Kube-state-metrics image version: 1.9.3

**Comment by JensErat** [comment]
There is a PR (linked just above) saying this would be fixed?

**Comment by tariq1890** [comment]
Yes, this is fixed. This should have been closed.

Are you still facing this issue @JensErat?

**Comment by JensErat** [comment]
> Yes, this is fixed. This should have been closed.
> 
> Are you still facing this issue @JensErat?

No, I was just wondering why it is still left open.
