### ISSUE TITLE
kube state metrics container failed to start if default PSP is enabled.

### ISSUE THREAD

**Issue by olegmayko** [kubernetes/kube-state-metrics#1031]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> kind bug

**What happened**:
After deploying the default manifests, the next error appeared "
kubernetes PodSecurityPolicy set to runAsNonRoot, container has runAsNonRoot and image has non-numeric user (nobody), cannot verify user is non-root"
**What you expected to happen**:
Container should be created without any issue. 
**How to reproduce it (as minimally and precisely as possible)**:
Cluster should have default PSP enabled. 
**Anything else we need to know?**:
Can be fixed by adding  "container.mixin.securityContext.withRunAsUser(65534);" 
I can submit PR if you agree. 
**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.10
- Kube-state-metrics image version: v.1.9.2

**Comment by brancz** [comment]
I'm happy with adding `container.mixin.securityContext.withRunAsUser(65534)`.

**Comment by olegmayko** [comment]
Yes, will submit it soon.

**Comment by olegmayko** [comment]
fixed in #1034
