### ISSUE TITLE
Monitor ephemeral-storage disk usage

### ISSUE THREAD

**Issue by jtslear** [kubernetes/kube-state-metrics#1046]
/kind feature

**What happened**:

Some application/services may require a scratch space to perform work.  This is most easily configured using an `EmptyDir`.  For safety reasons, it would be wise to ensure the `EmptyDir` configuration has a size limitation.  Example:

```yaml
   volumes:
     - emptyDir:
         sizeLimit: 50G
       name: sidekiq-shared
```
This allows Kubernetes to Evict a Pod that has exceeded a threshold.  Currently, at least I cannot find it, we don't have a method for monitoring the space utilized by an `EmptyDir`.

**What you expected to happen**:

Having exposed a metric for `EmptyDir` space utilized would provide a mechanism to assist operators in monitoring the health of a Pod and potentially the cluster.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a small cluster
1. Create a Pod with an `EmptyDir` scratch space
1. Fill that scratch space with random data

Either the disk on the node will run out, causing the `DiskPressure` flag to flip, or if configured with a size limitation, Kubernetes will evict the Pod.

**Anything else we need to know?**:

Sometimes it might be hard to find the appropriate scale required for both Pods and Nodes at the same time.  When shared storage is not readily available, an `EmptyDir` with a size limit is the current best option, but there exists times where the scale of the application, and amount of scratch space utilized will drive node(s) out of available disk capacity causing both failed operations in the Pods that are running, and other general cluster issues.  Having this information logged will be helpful when troubleshooting situations where full `EmptyDir`s are root cause for incidents.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.7
- Kube-state-metrics image version: 1.9.3

**Comment by LiliC** [comment]
So if I understand correctly, you want a metric for empty disk size limit?

Is this info available to request via the kubernetes API?

**Comment by brancz** [comment]
It’s not to my knowledge. I think I read that ephemeral volume metrics (emptydir, configmap, etc) is on sig storage’s roadmap. I would expect these metrics to be on the kubelet’s metrics endpoint.

**Comment by STRRL** [comment]
Hi @lilic, @brancz, these metrics can be scraped from kubelet `/stats/summary`, via Kubernetes API proxy to kubelet like `https://x.x.x.x:8443/api/v1/nodes/${node_name}/proxy/stats/summary/`.
Here are `volumes` field in each `pods`, contains empty dir used bytes and used inodes.

Since kube-state-metric hasn't done things like "fetching from kubelet" ever, is there a more elegant way (another exporter) to expose these metrics to prometheus?

**Comment by brancz** [comment]
The kubelet's metrics endpoint should expose these if it doesn't already I think. Cardinality could potentially be high, but I think those metrics are worth it.

**Comment by paulfantom** [comment]
As @brancz said, this is covered by kubelet metrics, especially:
- `kubelet_volume_stats_capacity_bytes`
- `kubelet_volume_stats_used_bytes`
- `kubelet_volume_stats_available_bytes`
- `kubelet_volume_stats_inodes`
- `kubelet_volume_stats_inodes_free`
- `kubelet_volume_stats_inodes_used`

**Comment by brancz** [comment]
Do those metrics include emptydir volumes though? I'm not certain, but awesome if they do :)

**Comment by jtslear** [comment]
In doing a short query in my environment, I do not see `emptyDir` volumes populated in any of the above metrics noted.  Rather I only see data from PVC's.

**Comment by brancz** [comment]
Yes that is what I was under the impression of as well.

**Comment by STRRL** [comment]
I have the same situation with @jtslear , these metrics do NOT contains anything about `emptyDir`, my kubernetes version is 1.16.6.

**Comment by STRRL** [comment]
@brancz @jtslear @paulfantom , I found a issue about these prometheus metrics: https://github.com/kubernetes/kubernetes/issues/69507

**Comment by voodoodror** [comment]
Anything new regarding this issue? We need that too.

**Comment by boniek83** [comment]
I would change title to "Monitor ephemeral-storage disk usage" and reopen it. This is not solved and this is very important. Any data that is written inside container to directory that is not specifically mounted from persistend storage is written into local (to the machine the pod is running on) disk storage, doesn't matter if directory is marked as EmptyDir or it is not volume at all. Ephemeral-storage is a resource with limits and requests and it can be exhausted. It is critical for proper operations of the cluster to have monitoring of ephemeral-storage.

**Comment by jrenggli** [comment]
Just discovered a new issue #1488 (with a linked PR #1561) handling this feature.

**Comment by kd7lxl** [comment]
> Just discovered a new issue #1488 (with a linked PR #1561) handling this feature.

Those tickets don't mention monitoring usage, just the requests and limits. Seems like a different (but related) thing.

**Comment by matJC** [comment]
I'm looking for this feature and will likely have to switch to using a persistent volume for my use case only so that I can get metrics. I think this should be reopened 🙂

**Comment by jtslear** [comment]
/reopen

With at least a few persons asking to reopen, let's do so...

Please be mindful that this issue is over 2 years old.  If there are duplicates or if the landscape has changed, I have not yet performed such research ahead of time.

**Comment by dgrisonnet** [comment]
Closing in favor of: https://github.com/kubernetes/kubernetes/issues/69507. As mentioned in https://github.com/kubernetes/kube-state-metrics/issues/1046#issuecomment-582782252, these metrics are mostly out of scope for kube-state-metrics, and it would be better to investigate adding them in Kubernetes directly.
