### ISSUE TITLE
kube_pod_container_resource_requests will be exposed for already completed Jobs / Pods

### ISSUE THREAD

**Issue by tiwalter** [kubernetes/kube-state-metrics#1051]
**What happened**: If you watch the metric "kube_pod_container_resource_requests", i found out that this metric is also exposed for already completed Jobs / Pods. 

**What you expected to happen**: If a Job / Pod is completed, this metric will be removed for them.

**How to reproduce it (as minimally and precisely as possible)**: Start a Job and let it complete. Then watch the metric "kube_pod_container_resource_requests".

**Environment**:
- Kubernetes version (use `kubectl version`): 
  - Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- Kube-state-metrics image version: v1.8.0
  - Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"windows/amd64"

**Comment by brancz** [comment]
This is intentional. kube-state-metrics exposes metrics for any Pod that the Kubernetes API has available. You will need to exclude the states that you are not interested in or query precisely for the states that you _are_ interested in in your PromQL query.

**Comment by tiwalter** [comment]
I know that this is the initially intention.

But this behaviour is not suitable for the metric name "kube_pod_container_resource_requests". Because if they are completed, the container resources will be released. Exposing them already is provides the wrong information.

**Comment by brancz** [comment]
It's perfectly possible to limit the pods to a certain status, by joining the status onto the metric, then you can select with any logic you might want. An example of this can be found in the kubernetes-mixin: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/8e370046348970ac68bd0fcfd5a15184a6cbdf51/rules/apps.libsonnet#L64-L75

**Comment by tiwalter** [comment]
Yes, i did this also in our system. 

Nevertheless, i think it is more suitable to expose only the metrics if they are **really** requested.
I think joining is only a workaround.

**Comment by brancz** [comment]
As the second paragraph in the [readme](https://github.com/kubernetes/kube-state-metrics#overview) says, we make this choice explicitly and intentionally, so we can be 100% consistent with what the kube API offers, otherwise we get into all sorts of inconsistencies and the experience would suffer overall.

**Comment by tiwalter** [comment]
Okay, that makes sense for the whole application.

This means, the resources are wrongly exposed by the kube API?
So, the issue should be fixed there.

**Comment by brancz** [comment]
Yes and no. I agree that this is an awkward situation, because the completed state is an odd one in Kubernetes. For completed pods not to show up in, they would simply need to be deleted.

**Comment by taideng** [comment]
How about add a new label like podPhase(string(p.Status.Phase)}) for this metrics? 
I do it in my env,and it works fine for me..

**Comment by brancz** [comment]
That's exactly what happens when you join the phase metric onto another pod metric :)

**Comment by PickledChris** [comment]
For the benefit of other people who find this, you might want to look at the Kubernetes Monitoring Mixin [Explained here in Grafana](https://grafana.com/docs/grafana-cloud/monitor-infrastructure/kubernetes-monitoring/configuration/manage-configuration/#recording-rules) recording rules 
[Compiled source in kube-prometheus](https://github.com/prometheus-operator/kube-prometheus/blob/f0986d548803f79da6dcc1562f37223eefce416b/manifests/kubernetesControlPlane-prometheusRule.yaml#L1255)

- cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests
- cluster:namespace:pod_memory:active:kube_pod_container_resource_limits
