### ISSUE TITLE
Add metric for owner of ReplicationController - kube_replicationcontroller_owner

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#1055]
We do not have a metric with the information about the owner of `ReplicationController`. 

/kind feature

**Comment by lilic** [comment]
@olivierlemasle let me know if you need any more info! Thanks for tackling this! :)

**Comment by olivierlemasle** [comment]
Thanks @lilic; I've created a PR to add this metric (#1058).
