### ISSUE TITLE
Strange values of statefulset_* metrics

### ISSUE THREAD

**Issue by hawran** [kubernetes/kube-state-metrics#1057]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I've been investigating some metrics of ours and stumbled across strange values as follows:
(omitting the `kube_statefulset_` prefix)

metric | v | v | v | v | v |
-------- | - | - | - | - | - |
status_replicas | 2 | 2 | 2 | 2 | 2
replicas | 2 | 2 | 2 | 2 | 2
replicas_current | 2 | 1 | 0 | 0 | 2
replicas_ready | 2 | 1 | 1 | 0 | 2

**What you expected to happen**:
I've got two questions:

1. According to https://github.com/kubernetes/kube-state-metrics/issues/63#issuecomment-324826017 I'd expect the `kube_statefulset_status_replicas` metric somehow correlates to the `kube_statefulset_status_replicas_current` metric.

2. How is it possible there is one replica **ready** here even with zero replicas **current**? 

**How to reproduce it (as minimally and precisely as possible)**:
I'd say it's hard to reproduce, I've been digging into one rather old incident. Not repeated since then.
Just run a statefulset with two replicas and wait...

**Anything else we need to know?**:
According to out data this incident happened with some "old" version of kube-state-metrics (see below), I was just curious what happened and whether those are correct numbers.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.14.6
- Kube-state-metrics image version: 1.8.0 (built from GitHub)

**Comment by brancz** [comment]
Can you kubectl get the object in question and see different values in the status/spec? Kube state metrics just mirrors that, so if it’s the same then this would rather be a question for the Kubernetes people who work on the workloads api.

**Comment by hawran** [comment]
> Can you kubectl get the object in question and see different values in the status/spec? Kube state metrics just mirrors that, so if it’s the same then this would rather be a question for the Kubernetes people who work on the workloads api.

Unfortunately there are not such objects here which have caused mentioned strange values.
However - looking at a `kubectl describe sts ...` report for a current statefulset - there might be some misunderstanding here between `kubectl ...` report and metrics (a small snippet of the cli's output):
```
...
Replicas:           2 desired | 2 total
Pods Status:        2 Running / 0 Waiting / 0 Succeeded / 0 Failed
...
```
What is intended mapping between the metrics I'd reported and the `kubectl describe ...` report?

**Comment by brancz** [comment]
If you do 

kubectl get sts ... -oyaml

You should get exactly the values that are reflected in the metrics. Is that not the case?

**Comment by hawran** [comment]
> If you do
> kubectl get sts ... -oyaml
> You should get exactly the values that are reflected in the metrics. Is that not the case?

Oops, you're right! It's obvious.
I had to write a table though, :wink::
```
kube_statefulset_replicas | spec: replicas
kube_statefulset_status_replicas | status: replicas
kube_statefulset_status_replicas_current | status: currentReplicas
kube_statefulset_status_replicas_ready | status:readyReplicas
kube_statefulset_status_replicas_updated | status: updatedReplicas
```
However, sill can't see a difference between `kube_statefulset_status_replicas` and `kube_statefulset_status_replicas_current`...

**Comment by brancz** [comment]
If the output of the API is equal to kube-state-metrics metrics, then everything is ok here, and your question is merely why `kube_statefulset_status_replicas` and `kube_statefulset_status_replicas_current` are the same? That would be a question for the people maintaining the workloads APIs.

**Comment by hawran** [comment]
> If the output of the API is equal to kube-state-metrics metrics, then everything is ok here, and your question is merely why `kube_statefulset_status_replicas` and `kube_statefulset_status_replicas_current` are the same? That would be a question for the people maintaining the workloads APIs.

OK, point taken.
And thank you!

**Comment by brancz** [comment]
I assume since there were no further comments, that kube-state-metrics mirrors the correct numbers, this was just about understanding the numbers themselves. If there are more questions feel free to comment or open a new issue should you believe there is an issue with kube-state-metrics.

**Comment by JanKowalik** [comment]
I have the same issue. However I can see that yaml from `kubectl get sts <name> -o yaml` has values under `status` section for `replicas`, ` readyReplicas`, `updatedReplicas` but **not** for `currentReplicas`. Any idea why and how to fix that? 
Is it where metrics take it from?

**Comment by jessequinn** [comment]
yes this is very strange. Using Victoria Metrics for instance,

Loki returns - 

```
status:
  collisionCount: 0
  currentReplicas: 1
  currentRevision: loki-58fbb7cfc9
  observedGeneration: 5
  readyReplicas: 1
  replicas: 1
  updateRevision: loki-58fbb7cfc9
  updatedReplicas: 1
```

and  `vmalertmanager-victoria-metrics-k8s-stack` returns:

```
status:
  collisionCount: 0
  currentRevision: vmalertmanager-victoria-metrics-k8s-stack-8577b6fb89
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updateRevision: vmalertmanager-victoria-metrics-k8s-stack-877b46dcd
  updatedReplicas: 1
```

Why is the API not returning currentReplicas ?
