### ISSUE TITLE
Add metrics for container images on nodes

### ISSUE THREAD

**Issue by olivierlemasle** [kubernetes/kube-state-metrics#1060]
Should we add a metric with the information about the container images on nodes (info available on nodes status: like in `kubectl get nodes -o json | jq ".items[].status.images"`)?

I'd be glad to implement it myself if this metric is accepted.

/kind feature

**Comment by brancz** [comment]
I’m afraid this would be too high cardinality. I think this would be a good case for a more generic configurable kube aggregation exporter, as most likely individual images are not of interest and even if they are I imagine such an exporter to be highly configurable.
