### ISSUE TITLE
kube-state-metrics 

### ISSUE THREAD

**Issue by SibiSS3575** [kubernetes/kube-state-metrics#1061]
I need a kube-state-metrics version v1.3.1 and v1.9.4. Can you one help on this

**Comment by olivierlemasle** [comment]
What exactly are you trying to achieve?

/triage support

**Comment by lilic** [comment]
All images are located here https://quay.io/repository/coreos/kube-state-metrics?tag=v1.9.5&tab=tags or you can build form tags or releases. If you feel like this was not clear, feel free to reopen issue. :)
