### ISSUE TITLE
Documentation on pod status queries is incorrect

### ISSUE THREAD

**Issue by olivierlemasle** [kubernetes/kube-state-metrics#1063]
Example PromQL queries relative to pod status have been added to Pod metrics documentation [here](https://github.com/kubernetes/kube-state-metrics/blob/c1895cd/docs/pod-metrics.md#useful-metrics-queries), as part of #1013.

However, these queries seem to be incorrect.

For example, `count(kube_pod_status_phase{phase="Running"}) by (namespace, pod)` is always 1, even for pods in phases e.g. PENDING, because in that case the value of `kube_pod_status_phase{phase="Running"}` is 0, but the count is 1.

That's why, when I test `count(kube_pod_status_phase{phase="Running"}) by (namespace, pod) * count(kube_pod_status_reason{reason="NodeLost"}) by(namespace, pod)`, I get **all** pods, not PENDING ones.

NB: I've also proposed typo fixes (including on PromQL) in that document with PR #1062

cc @clamoriniere

/kind documentation
/kind bug

**Comment by brancz** [comment]
You’re right it should either be a sum or a count where the inner expression is == 1

**Comment by brancz** [comment]
Would you like to open a PR to change this? I tend to prefer the sum as that’s a bit lighter in promql but it’s mainly a style choice.

**Comment by olivierlemasle** [comment]
Ok
/assign

**Comment by clamoriniere** [comment]
Sorry for the late reply, this error in the documentation. 

I confirm that `sum` what I used during my test.

**Comment by olivierlemasle** [comment]
Thanks @clamoriniere 

Actually, it seems to be more than just replacing `count` by `sum`:

1. **Unknown**

    ```
    sum(kube_pod_status_phase{phase="Running"}) by (namespace, pod)
    * sum(kube_pod_status_reason{reason="NodeLost"}) by(namespace, pod)
    ```
  
   This query (with both __sum__) will return the pods with status phase "Running" and status reason "NodeLost".
    However, the logic discussed in #410 and removed in #1050 seems to be that pods are "Unknown" if:
    - they have status phase "Unknown"
    - OR (they have a deletion timestamp AND status reason "NodeLost")

1. **Terminating/Terminated**
  
    ```
    sum(kube_pod_status_phase{phase="Running"}) by (namespace, pod)
    * count(kube_pod_deleted) by (namespace, pod)
    * sum(kube_pod_status_reason{reason!="NodeLost"}) by (namespace, pod)
    ```

    This query (with **count** for `kube_pod_deleted` and **sum** for the other metrics) will return pods in status phase "Running", with a deletion timestamp and a status reason "Evicted" (if reason is neither NodeLost nor Evicted, metrics for both labels will have value `0`).
    Is that supposed to be **Terminated** (as in sentence _"For Pods in Terminated state..."_ or **Terminating** (as in the name of the alert: `PodsBlockInTerminatingState`)? I'm actually unsure of `kubectl` logic behind pod statuses display...

**Comment by brancz** [comment]
What exactly are you trying to answer?

**Comment by olivierlemasle** [comment]
@brancz That's the right question ;-)
I'm trying to write PromQL queries that mimics what `kubectl` does to print pod status. I've finally found that logic in K8s code and updated the queries accordingly in PR #1073.
