### ISSUE TITLE
Metrics usage in gcloud stackdriver logging

### ISSUE THREAD

**Issue by whitecolor** [kubernetes/kube-state-metrics#1066]
I've installed `kube-state-metrics` using helm chart. And new metrics did appear in configuring alerting policies dialog of the google cloud console.

Could you just consult how to use them correctly, can not figure out.

So for I want to get the alert when pod/container restarted. 

I've chosen metric `kube_pod_container_status_restarts_total`

What `Aggregator` and condition Configuration should I use to make it work?

`The condition triggers if...`
![image](https://user-images.githubusercontent.com/736697/74764523-af27f600-52a3-11ea-98ba-5dd41916c7cc.png)

I tried different options but seem to have no effect.

`No data is available for the selected time frame.` is stated on the graph.
![image](https://user-images.githubusercontent.com/736697/74764699-0201ad80-52a4-11ea-9fe8-1804d94f76a0.png)
Maybe something not functioning correctly?

**Comment by brancz** [comment]
We don’t maintain or support anything about google cloud. Please open a ticket with them first and if it turns out to actually be a problem with kube state metrics follow up here. Thanks!

**Comment by whitecolor** [comment]
Ok, will close for now.
