### ISSUE TITLE
Pod Readiness Alert

### ISSUE THREAD

**Issue by nid06** [kubernetes/kube-state-metrics#1071]
I want to monitor Pod Readiness Alert .
Current options which i have also captures Completed pods also , how to filter it.

**Comment by brancz** [comment]
There are metrics on the kubelet about readiness probes, available at `/metrics/probes`. I recommend basing your alerts on those metrics, instead of on kube-state-metrics alerts.

**Comment by nid06** [comment]
Could you help to describe more about it.

**Comment by brancz** [comment]
I don't know what you're asking, I recommend you to check out those metrics as they are exactly what you are looking for.
