### ISSUE TITLE
provide status condition reason label for hpa objects

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes/kube-state-metrics#1072]
/kind feature

The hpa metric kube_hpa_status_condition contains the `ScalingLimited` label which denotes whether the hpa has reached its minimum or maximum replica count. Unfortunately kubernetes leaves the `AbleToScale` condition true also if the scaling is actually limited.

For alerts that a hpa is limited the reason would be useful as it is commonly the case that hpa objects have a minimum replica count above the requirement (e.g. 2 replicas for a low load service which still needs to be available during eviction events). These objects always have the `ScalingLimited` condition set to true but the reason denotes it cannot downscale.

If the metric contains the reason one could add an alert for failing to upscale:

```
kube_hpa_status_condition{condition="ScalingLimited", status!="false", reason="TooManyReplicas"} == 1
```

Without the reason the only option I see is the more complicated:

```
(kube_hpa_status_condition{condition="ScalingLimited", status!="false"} == 1 and on(namespace, hpa) kube_hpa_status_current_replicas != kube_hpa_spec_min_replicas)
````

Though adding metrics for reasons does increase the amount of exported metrics depending on how many possible reasons there are and one could argue that scaling can be limited but `AbleToScale` is still true is a kubernetes bug.

kubernetes 1.7.3,
kube-state-metrics 1.9.5

**Comment by olivierlemasle** [comment]
Looking in https://git.k8s.io/kubernetes/pkg/controller/podautoscaler/horizontal.go, I found that hpa objects can have at least the following condition reasons:

- DesiredWithinRange
- FailedGetExternalMetric
- FailedGetObjectMetric
- FailedGetPodsMetric
- FailedGetResourceMetric
- FailedGetScale
- FailedUpdateScale
- InvalidMetricSourceType
- InvalidSelector
- ReadyForNewScale
- ScaleDownLimit
- ScaleDownStabilized
- ScaleUpLimit
- ScaleUpStabilized
- ScalingDisabled
- SucceededGetScale
- SucceededRescale
- TooFewReplicas
- TooManyReplicas
- ValidMetricFound

Adding this reason would increase metric cardinality. I don't known if it's worth it.

**Comment by brancz** [comment]
It does seem a little excessive, but I can still see the benefit. How about we introduce feature gates for these types of metrics?
