### ISSUE TITLE
e2e: check labels documentation

### ISSUE THREAD

**Issue by olivierlemasle** [kubernetes/kube-state-metrics#1078]
As @lilic [pointed out](https://github.com/kubernetes/kube-state-metrics/pull/996#pullrequestreview-351396437) recently, CI checks thats every metric is documented (`make doccheck`), but there's no check on labels documentation.

That led to PR where labels documentation was not updated and CI did not catch this (#996).

Actually, it's more difficult to check labels:

- metric names are extracted from source code by a static analysis (with regex `"(kube_[^"]+)"`); labels are not easily found by basic static analysis; 
- some labels have a dynamic name (e.g. `label_JOB_LABEL`)

What do you think of using e2e to check labels documentation? We already check metrics from `/metrics` endpoint; we could also list labels for each metric and check if they're in documentation (even if it is not exhaustive).

**Comment by brancz** [comment]
I think this is a great idea!
