### ISSUE TITLE
kube_node_info should add node labels

### ISSUE THREAD

**Issue by SleepyBrett** [kubernetes/kube-state-metrics#108]
We run several node pools and use labels to differentiate them (as well as taints). One node pool in particular is built to be a canary for future versions of our underlying OS. I'd like to be able to build an alert the fires if that node goes away (assumably because some change in the lower env causes it's kubelet to fail). 

Being able to to say sum(kube_node_info{mynodelabel="canary"}) == 0 would be awesome.

**Comment by SleepyBrett** [comment]
I did a quick hack that joins all the labels, comma seperates them a puts them in a kubernetes_labels field. Though I'm not sure if this is the right approach. It's a bit of a prometheus question, is it possible/better strategy to reduce all the labels names to lowercase with underscores names and append those labels to the metrics object directly? Or do I have to predefine the labels in the deceleration of the gauge?

**Comment by brancz** [comment]
In Prometheus a unique set of labels is one time-series, which means that it is a new time-series if the labels change. We would have to change slightly how the `kube_node_info` metric is instantiated to be able to add all the labels of the node, but it's definitely possible. Best would be to add a label per Kubernetes label which is prefixed. So something like `kube_label_<label-key>`. Note that this will require some flattening of the key of the label, which Prometheus already performs in the Kubernetes service discovery.

**Comment by andyxning** [comment]
@SleepyBrett @brancz Any updates on this? 

I am  not familiar with Prometheus, now. Can we update labels dynamically instead predefining all the labels?

**Comment by andyxning** [comment]
It seems that we can do this outside of kube-state-metrics with adding this to Prometheus by enabling [this](https://github.com/prometheus/prometheus/issues/1099#issuecomment-204584257)

**Comment by cemo** [comment]
@brancz Is there a workaround for now?

**Comment by cemo** [comment]
Let me to explain my use case as well. 
We have a multi tenant cluster and each tenant has multiple container. I had labeled them in a meaningful way to group them easily and display `pods count` in grouped by `tenant name`.

**Comment by brancz** [comment]
makes sense, we'll likely add this soon for pods and nodes

**Comment by andyxning** [comment]
​Any info about implementing this.​

Yours Sincerely,
Andy Xie


2017-04-26 21:16 GMT+08:00 Frederic Branczyk <notifications@github.com>:

**Comment by brancz** [comment]
For one it's probably best to put this in it's own metric, something like `kube_node_labels` and `kube_pod_labels`. And then each label of a pod or node becomes a prefixed label in the metric representation. So it will end up looking something like this:

```
kube_pod_labels{pod="example-1",namespace="default",pod_label_app="example_app"} 0
```

I'm currently finishing up something, then I should be able to get to implementing this in the next few days. After that I think we should have collected enough changes since the last release that we can do another release.
