### ISSUE TITLE
lables  is available for every metric

### ISSUE THREAD

**Issue by guleng** [kubernetes/kube-state-metrics#1080]
**FEATURE REQUEST**:

**What happened**: （kube_pod_status_phase,kube_pod_container_status_terminated_reason,kube_pod_container_status_restarts_total, kube_pod_container_status_restarts_total  ）I think I can get the custom tags of these pods discovered by metrics

such as：`kube_pod_container_status_restarts_total{endpoint="https-main",instance="10.1.84.1:8443",job="kube-state-metrics",label_name="nginx-test",label_owner="glsiri",label_pod_template_hash="68f8bbcc9f",label_projecctname="test-2-25",namespace="default",pod="nginx-test-68f8bbcc9f-wthtp",service="kube-state-metrics"}`
But what I actually got was：`kube_pod_container_status_restarts_total{container="nginx-test",endpoint="https-main",instance="10.1.84.1:8443",job="kube-state-metrics",namespace="default",pod="nginx-test-68f8bbcc9f-wthtp",service="kube-state-metrics"}`

kube-state-metrics:v1.7.2
kubernetes:v1.14.1

**Comment by olivierlemasle** [comment]
Hi @guleng, You can do a `join` between metric `kube_pod_labels` and other pod metrics.
There's examples on such `join` PromQL requests here: https://github.com/kubernetes/kube-state-metrics/tree/master/docs#join-metrics

**Comment by guleng** [comment]
Okay  thanks for you help me!
