### ISSUE TITLE
kube_pod_deletion_timestamp not kept long enough

### ISSUE THREAD

**Issue by efeller** [kubernetes/kube-state-metrics#1083]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I am trying to make use of the kube_pod_deletion_timestamp time series. However, it seems that data for this time series is not kept long enough in order for Prometheus to scrape it on time. Specifically, we are running Prometheus with a scrape interval of 30 seconds. When a pod is deleted, I can see an entry in kube_pod_deletion_timestamp for a very short period of time (order of seconds). However, since the Prometheus scrape interval is 30 seconds, it does not seem that Prometheus gets a chance to scrape the deletion timestamps.  As a result of that, pod deletion times remain under the radar.

**What you expected to happen**:
I would expect kube-state-metrics to keep/cache the data for a configurable interval (e.g., 60 seconds) so that Prometheus gets a chance to scrape data.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy latest version of kube-state-metrics from master.
- Start a pod and delete it shortly after.
- Keep curling kube-state-metrics /metrics endpoint and observe the kube_pod_deletion_timestamp time series. Pod deletion time will appear and disappear within seconds.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.2
- Kube-state-metrics image version: master as of 03/25/2020

**Comment by efeller** [comment]
@clamoriniere Would be great to get your input. Thanks.

**Comment by brancz** [comment]
This seems to work as expected. Kube state metrics removes any metric about objects that are truly gone in Kubernetes/etcd.

**Comment by lilic** [comment]
To add to Frederic point, kube-state-metrics just reflects the state of kubernetes objects, it is not designed to be an aggregator.

**Comment by lilic** [comment]
This is not a bug, so removing bug label.

**Comment by efeller** [comment]
@brancz @lilic Thanks tons for your feedback. Wonder in this case how to best use the kube_pod_deletion_timestamp time-series since pods are immediately (in the order of seconds) removed?

**Comment by clamoriniere** [comment]
Hi @efeller 

> Wonder in this case how the kube_pod_deletion_timestamp metric is intended to be used since pods are immediately removed (in the order of seconds)? 

You are right, pods should be deleted immediately, but things don't always go as planned. For example, if the container runtime is not able to delete the container, or the process didn't catch the "terminating" signal.
So being able to get the `kube_pod_deletion_timestamp` for a pod, helps to monitor cleanup problems. 

> What I would like to achieve is to capture pod deletion times.

I think to achieve this, you could look at the API-server [events] resource (https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#event-v1-core) and select pod's events.

**Comment by efeller** [comment]
Cool, thanks @clamoriniere. Makes sense. It would be great if we could somehow capture this in the docs. I thought I could use this time series to generally find out when a pod was deleted.

**Comment by brancz** [comment]
Do you want to create a PR to add this to the docs? :)

**Comment by efeller** [comment]
@brancz Sorry took some time. Done.
