### ISSUE TITLE
Add test to check that no kube-state-metrics own alerts are firing in the e2e test

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#1084]
We have [alerts](https://github.com/kubernetes/kube-state-metrics/blob/master/examples/prometheus-alerting-rules/alerts.yaml) relavant to kube-state-metrics, KubeStateMetricsListErrors and KubeStateMetricsWatchErrors, we need to add a test to our e2e tests that checks the results of the alerting expressions. The expression should be evaluated during the entire run of the e2e tests.

Adding this check in our e2e tests will allow us to make sure that when adding a new metric the resource we are trying to add a list/watch to are not erroring out.

/kind feature

**Comment by olivierlemasle** [comment]
@lilic I think that would be very useful, but what exactly had you in mind?

- simply checking that there's no `kube_state_metrics_list_total` (or `kube_state_metrics_watch_total`) with result `error` on exposed metrics? That's not _testing the alerts_, but it is sufficient to know there's no error.
- or really testing the alerts (which means setting up a Prometheus server, and probably adding a pause in e2e tests, to give time for the alert rule to be pending).

**Comment by lilic** [comment]
We don’t aim at testing the alert so your first point is what I had in mind. We just want to make sure there are no list/watch errors. 

Adding integration with prometheus would not be necessary here, we can just simply check the value of the metric itself. We already check values or presence of certain metrics so we can reuse the same logic for this.
