### ISSUE TITLE
Use image promoter release process 

### ISSUE THREAD

**Issue by serathius** [kubernetes/kube-state-metrics#1089]
Using k8s release process would allow to migrate to official k8s repositories without depending on Googlers. It also supports automated build process which will make it more auditable and secure. 

We should also stop depending on quay.io registry if official option can be used.

Staging repo was already setup by @brancz https://github.com/kubernetes/k8s.io/pull/384

/kind feature
Tasks based on https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io

Migrate to promotion process:
* [x] Create google group image release (@dims)
* [x] Create staging repo (@justinsb)
* [x] Add image promotion config in [test-infra](https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing)
* [X] Add image promotion instructions in [RELEASE.md](https://github.com/kubernetes/kube-state-metrics/blob/master/RELEASE.md)
* [X] Replace quay.io repository with k8s.gcr.io as default - we decided to support both

Automate builds:
* [x] Create cloudbuild.yaml [instructions](https://github.com/kubernetes/test-infra/blob/master/config/jobs/image-pushing/README.md) [example](https://github.com/kubernetes-sigs/metrics-server/pull/460)
* [x] Add image build [job in prow](https://github.com/kubernetes/test-infra/tree/2657fccb7bd5af5ff2d6fb6d7f1349cf14d2cc1e/config/jobs/kubernetes-sigs)
* [x] Update image build instructions in [RELEASE.md](https://github.com/kubernetes/kube-state-metrics/blob/master/RELEASE.md)

/cc @lilic please confirm that plan makes sense for you.

**Comment by serathius** [comment]
@dims Can you create k8s-infra-staging-kube-state-metrics@kubernetes.io google group?

**Comment by serathius** [comment]
/cc @justinsb 
Can you create staging repo for kube-state-metrics?

**Comment by lilic** [comment]
Last time there was still an issue with the tool, is this solved now? https://github.com/kubernetes/k8s.io/pull/384#issuecomment-536551561

**Comment by serathius** [comment]
I think yes, because gcr.io/google-containers is deprecated. Googler no longer can release new images to it.
https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io/images/DO-NOT-MODIFY-legacy-backfill

I will confirm it with someone from sig-release

**Comment by serathius** [comment]
@bartsmykla Can you confirm that new pipeline is fully functional?

**Comment by bartsmykla** [comment]
Yes, it's working :-)

**Comment by bartsmykla** [comment]
@serathius it looks like staging repo already exists: https://console.cloud.google.com/gcr/images/k8s-staging-kube-state-metrics/GLOBAL and as https://github.com/kubernetes/k8s.io/pull/384 was merged almost half a year ago I'm sure the google group was already created. :-)

**Comment by serathius** [comment]
How can I verify this? I can mark it as done

**Comment by bartsmykla** [comment]
These are the IAM roles for this project: https://github.com/kubernetes/k8s.io/blob/master/audit/projects/k8s-staging-kube-state-metrics/iam.json

I'm not entirely sure how to verify that but if I would guess looking at IAMs members of this group should have access to GCB for the project. Try to go here: https://console.cloud.google.com/navigation-error;errorUrl=%2Fcloud-build%3ForganizationId%3D&project%3Dk8s-staging-kube-state-metrics and check if it will let you in :-)

**Comment by bartsmykla** [comment]
Oooor... actualy it should be easier to just check if you are a member of that group: https://groups.google.com/a/kubernetes.io/forum/#!myforums :-D

**Comment by serathius** [comment]
I'm not owner of kube-state-metrics so I cannot check that.

**Comment by bartsmykla** [comment]
@serathius so the only way is to wait for [one of the members](https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml#L753-L755) or @dims to look and confirm, but the only case when the group would not exist is when the [reconcile tool](https://github.com/kubernetes/k8s.io/blob/master/groups/reconcile.go) would not work and as far as I'm aware it's not the case and every project which was added later is able to get the access to its repositories and push images to them.

**Comment by serathius** [comment]
@lilic Can you confirm that group exits?
It should be visible in https://groups.google.com/a/kubernetes.io/forum/#!search/k8s-infra-staging-kube-state-metrics

**Comment by lilic** [comment]
I am part of k8s-infra-staging-kube-state-metrics group yes and I can confirm I can access the. https://console.cloud.google.com/cloud-build/builds?organizationId=&project=k8s-staging-kube-state-metrics
But only for staging, do we need the production ones as per @nikhita comment:

> When it is ready, we can start having prod ones too.

**Comment by serathius** [comment]
Acces to production images should only be done by automated CI. This is done by image promoter, which watches content of file https://github.com/kubernetes/k8s.io/blob/master/k8s.gcr.io/images/k8s-staging-kube-state-metrics/images.yaml

**Comment by bartsmykla** [comment]
It's exactly as @serathius said :-)

**Comment by lilic** [comment]
@tariq1890 said he is interested in doing this, if not I can take it. Tariq do you have time for this?

**Comment by lilic** [comment]
Both of my PRs are merged. Now how to check the process actually works 🤔

**Comment by serathius** [comment]
Thanks for handling this Lili
When we were migrating Metrics Server it required additional changes in our build rules. 
* Fixing version tagging to be compatible with cloudbuild https://github.com/kubernetes-sigs/metrics-server/pull/475
* Stop building binary locally and docker use multi stage build https://github.com/kubernetes-sigs/metrics-server/pull/352

Hope this helps

**Comment by mrueg** [comment]
@lilic @tariq1890 anything I can do to help out here? I would be interested in getting kube-state-metrics images for arm64.

**Comment by lilic** [comment]
@mrueg the above mentioned by Marek sounds like great two things to be done in kube-state-metrics as well, thanks! :)

**Comment by mrueg** [comment]
Looks like it's not working as expected, see: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/post-kube-state-metrics-push-images/1285961432038379522 anyone with access to gcp can look at those logs?

**Comment by lilic** [comment]
Yes opened PR to fix this, looking at the current failure as well.

**Comment by lilic** [comment]
I believe everything was done on this list. Last PR should be https://github.com/kubernetes/kube-state-metrics/pull/1175 We can close this issue now?

**Comment by serathius** [comment]
Could we make one full release using new pipeline before? Would make sense to test if everything works e2e

**Comment by lilic** [comment]
Sounds good, we plan on doing this with the 2.0 release.

**Comment by mrueg** [comment]
@serathius @lilic looking at https://console.cloud.google.com/gcr/images/k8s-staging-kube-state-metrics/GLOBAL/kube-state-metrics@sha256:23eb6eda398dca8a488dd49817605b914dea8ccf740168a8bf7328bc8fc5cbb6/details?tab=info it seems like there is no non-amd64 image pushed. anything that's missing here?

**Comment by mrueg** [comment]
Ah I figured, cloudbuild.yaml is calling `make push`here: https://github.com/kubernetes/kube-state-metrics/blob/master/Makefile#L114  which only creates and pushes a regular and am64 container image. That will require some rework in the Makefile then. I'll try to have a look at that in the next couple of days.

**Comment by lilic** [comment]
Seems like this worked, we are now seeing multiple arch images in gcr. Thanks @mrueg for the work!

**Comment by mrueg** [comment]
Great, let me know if you want a backport to 1.9 (I already see a 1.9.7 tag appeared on gcr?).

**Comment by lilic** [comment]
Backport sounds great!

**Comment by mrueg** [comment]
> Great, let me know if you want a backport to 1.9 (I already see a 1.9.7 tag appeared on gcr?).

I can do the backport, one thing I'm wondering about is, that Makefile defines the version per cat VERSION (which leads to the docker image being updated on every push so a version becomes a moving target).

I would suggest the following logic:
 
* Read VERSION file
* Check if current commit is tagged with that version
* If it does, create a docker image with the version of VERSION -> 
`kube-state-metrics:v1.9.8`
* If it does not, create a docker image with the version of VERSION and add git shortcommit (that creates a tag per commit) e.g. `kube-state-metrics:v1.9.8-aabbccdd`
 or add "-next" or similar (that's a moving target then) `kube-state-metrics:v1.9.8-next`

**Comment by lilic** [comment]
Yes, I noticed as well have plans to correct this for when we do the 2.0 release as we are not using the image promotion process until 2.0 release, we have not discussed this yet with the maintainers. Do you mind opening a separate issue instead thanks!

**Comment by lilic** [comment]
Since this image promotion now works and we have a good workflow, closing this issue. Thanks all!
