### ISSUE TITLE
Wrong Version of admissionregistration API for older k8s versions

### ISSUE THREAD

**Issue by AlexMichaelJonesNC** [kubernetes/kube-state-metrics#1090]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
 /kind bug
> /kind feature

**What happened**:
Deploying Kube State Metrics 1.9.5 into a 1.14 k8s cluster, we get logs similar to the following:
```
E0309 14:57:02.411880       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ValidatingWebhookConfiguration: the server could not find the requested resource
E0309 14:57:03.413702       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ValidatingWebhookConfiguration: the server could not find the requested resource
E0309 14:57:04.415417       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ValidatingWebhookConfiguration: the server could not find the requested resource
```
**What you expected to happen**:
Not get logs related to using v1 rather than v1beta1 for the admissionsregistrationAPI

**How to reproduce it (as minimally and precisely as possible)**:
Deploy kube-state-metrics into a 1.14 kubernetes cluster

**Anything else we need to know?**:
This seems to have been caused by https://github.com/kubernetes/kube-state-metrics/issues/1039
That patch changed the api to v1 to support new versions. I believe an appropiate fix would require dynamically selecting the api version based on kubernetes version. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14
```
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.9-eks-502bfb", GitCommit:"502bfb383169b124d87848f89e17a04b9fc1f6f0", GitTreeState:"clean", BuildDate:"2020-02-07T01:31:02Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Kube-state-metrics image version
1.9.5

**Comment by lilic** [comment]
>  I believe an appropiate fix would require dynamically selecting the api version based on kubernetes version.

Using 1.8.x version of kube-state-metrics should work for you, correct?

**Comment by AlexMichaelJonesNC** [comment]
> Using 1.8.x version of kube-state-metrics should work for you, correct?

Deploying v1.8.0 does make the error go away, however the [compatibility matrix](https://github.com/kubernetes/kube-state-metrics#compatibility-matrix) shows that kubernetes 1.14 is fully supported by kube-state-metrics 1.9.5, so I wouldn't expect any errors to be occurring from differences in kubernetes api versions.

**Comment by lilic** [comment]
Yes that is a mistake on our end, can you do a PR to adjust that in the README, thanks!

**Comment by AlexMichaelJonesNC** [comment]
What mark would I use to indicate it's not compatible? I only see the checkmark for fully supported, and a dash for "k8s has features we don't support yet"

**Comment by lilic** [comment]
I would suggest `-` and feel free to clarify something like: " (additional API objects, deprecated API objects)." Whatever makes most sense to you.

Not sure there is a mention of yet? 🤔 

We tend to go by what client-go says https://github.com/kubernetes/client-go#compatibility-matrix and they dropped support for 1.14 it seems for client-go.

**Comment by lilic** [comment]
I think we can close this now. :) Feel free to reopen.

**Comment by rpherrera** [comment]
I was having this issue with a cluster on `v1.15.12-gke.20` version.

The most recent version of `kube-state-metrics` that worked for me without flooding the logs with these errors was: `v1.9.4`

**Comment by lilic** [comment]
As mentioned in the linked issue:
yes you are using a too new version of kube-state-metrics, see compatibility matrix here https://github.com/prometheus-operator/kube-prometheus#kubernetes-compatibility-matrix or the one in kube-state-metrics https://github.com/kubernetes/kube-state-metrics/#compatibility-matrix neither claim to support 1.15 version of Kubernetes, so might be easier to roll back to 1.9.4 or earlier supported versions. We fixed a bug in that version of Kubernetes to add support for newer versions, so that is what you are seeing.
