### ISSUE TITLE
missing values for kube_deployment_status_replicas_unavailable

### ISSUE THREAD

**Issue by dcroe** [kubernetes/kube-state-metrics#1099]
hi,
we have randomly missing data for the metric:

kube_deployment_status_replicas_unavailable

when using the image:
quay.io/mxinden/kube-state-metrics:v1.4.0-gzip.3

Environment: 
Google Cloud, kubernetes v1.14.10-gke.17

thus i have tried the newest versions without success:

image: quay.io/coreos/kube-state-metrics:v1.9.5: no values
image: quay.io/coreos/kube-state-metrics:v1.9.4: no values
image: quay.io/coreos/kube-state-metrics:v1.9.3: no values
image: quay.io/coreos/kube-state-metrics:v1.9.2: no values
image: quay.io/coreos/kube-state-metrics:v1.9.1: no values
image: quay.io/coreos/kube-state-metrics:v1.9.0: no values
image: quay.io/coreos/kube-state-metrics:v1.8.0: no values
image: quay.io/coreos/kube-state-metrics:v1.7.0: no values
image: quay.io/coreos/kube-state-metrics:v1.6.0: no values
image: quay.io/coreos/kube-state-metrics:v1.5.0: data available, to be observed if sometimes missing 
image: quay.io/mxinden/kube-state-metrics:v1.4.0-gzip.3: sometimes missing data

start parameters:
        command:
          - /pod_nanny
          - --container=kube-state-metrics
          - --cpu=100m
          - --extra-cpu=1m
          - --memory=100Mi
          - --extra-memory=2Mi
          - --threshold=5
          - --deployment=kube-state-metrics

is this a bug, or an invalid/missing configuration for the newer versions ?
best regards,
 david

**Comment by lilic** [comment]
We get this from deployments status and UnavailableReplicas count. Can you verify the output of the deployment status where you have those `unavailableReplicas` are actually set and the metric do not match. I do not have any unavailableReplicas to test this right now.

**Comment by dcroe** [comment]
it's a bit unclear which informations do you need?

the output in 1.5.0 looks like this:
# HELP kube_deployment_status_replicas_unavailable The number of unavailable replicas per deployment.
# TYPE kube_deployment_status_replicas_unavailable gauge
kube_deployment_status_replicas_unavailable{namespace="ournamespace",deployment="deploymentname"} 0
in all higher versions its missing

**Comment by lilic** [comment]
Is this the same as if you do `kubectl get deployment -oyaml`? 

You mean when you spin up a 1.18 k8s cluster and using which version of kube-state-metrics is this missing? But the deployment replicas status is set to unavailable?

**Comment by dcroe** [comment]
output of kubectl get deployment -oyaml (i've skipped the first part):
status:
  conditions:
  - lastTransitionTime: "2020-04-01T07:54:18Z"
    lastUpdateTime: "2020-04-01T07:54:18Z"
    message: ReplicaSet "slide-6575bd4f4b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-04-01T08:19:06Z"
    lastUpdateTime: "2020-04-01T08:19:06Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 5
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1

**Comment by dcroe** [comment]
Environment:
Google Cloud, kubernetes v1.14.10-gke.17

**Comment by lilic** [comment]
Thanks! And which release version of kube-state-metrics was used in this 1.14 cluster? Are you able to see other kube_deployment_status_* metrics?

**Comment by dcroe** [comment]
yes there are some values. 
for version question please have a look at the list in the issue text. 
i've listed all versions which i've tested ,
all versions higher than 1.5.0 are affected
