### ISSUE TITLE
Need support with node group queries

### ISSUE THREAD

**Issue by Asgoret** [kubernetes/kube-state-metrics#1101]
Need support with node grouping.

How can I get CPU utilization on master nodes if `machine_cpu_cores` doesn't provide any group information just IPs with ports? I saw some familiar issues, but can't get point how to transfer nodes from `kube_node_labels{label_node_role_kubernetes_io_infra="true"}` to `machine_cpu_cores`. Can somebody help with it plz?

**Comment by brancz** [comment]
You can achieve this with joins: https://github.com/kubernetes/kube-state-metrics/tree/master/docs#join-metrics. The same that works for pods works for nodes, you just need the same label on each side that you are joining. You may need to rewrite labels with `label_replace` to get them into the right shape, but it does work.

**Comment by Asgoret** [comment]
> You can achieve this with joins: https://github.com/kubernetes/kube-state-metrics/tree/master/docs#join-metrics. The same that works for pods works for nodes, you just need the same label on each side that you are joining. You may need to rewrite labels with `label_replace` to get them into the right shape, but it does work.

Is there any way to add just label or get label from 'kube_node_labels'?

**Comment by brancz** [comment]
You might need to do multiple joins. There is also the `kubelet_node_name` metric that might be useful for this, for example used in this rule to alert on max pods on a node: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/ea905d25c01ff4364937a2faed248e5f2f3fdb35/alerts/kubelet.libsonnet#L43

**Comment by Asgoret** [comment]
> You might need to do multiple joins. There is also the `kubelet_node_name` metric that might be useful for this, for example used in this rule to alert on max pods on a node: https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/ea905d25c01ff4364937a2faed248e5f2f3fdb35/alerts/kubelet.libsonnet#L43

Hm...Ok, I'll use multiple joins, but it doesn't work. No errors, just empty output.
`container_memory_working_set_bytes * on (pod) group_left(node) kube_pod_info * on (node) group_left() kube_node_labels{label_node_role_kubernetes_io_master="true"}`

If I delete `container_memory_working_set_bytes * on (pod) group_left(node)` part query show me all pods on master nodes. But ay this point how I transfer this out to `container_memory_working_set_bytes`
