### ISSUE TITLE
Fix typo in statefulset metrics documentation

### ISSUE THREAD

**Issue by jangdm** [kubernetes/kube-state-metrics#1105]
**What this PR does / why we need it:**:

> Fix typo in statefulset metrics documentation
>

**Comment by lilic** [comment]
Hello, there is no need to open an issue for typos, feel free to just open a PR to fix all of them at once. :) Thanks!

**Comment by jangdm** [comment]
ok thank u @lilic

**Comment by lilic** [comment]
Thank you! :)
