### ISSUE TITLE
Update Kubernetes dependencies 

### ISSUE THREAD

**Issue by tariq1890** [kubernetes/kube-state-metrics#1109]
Since `v1.18.x` is out, we need to update the `client-go`, `k/api`, and `k/apimachinery` dependencies

/help
/good-first-issue

**Comment by tariq1890** [comment]
Once the latest kubernetes versions are specified in `go.mod`, be sure to run `go mod vendor` and check-in the resulting changeset.

**Comment by lilic** [comment]
client-go is not out yet from what I can tell. So this might need to wait for that.

**Comment by lilic** [comment]
The problem with this its a larger change due to the client-go changing its signature of the functions. So this might be a larger contribution. There is a tool that help with the migration.

**Comment by tariq1890** [comment]
@lilic Thanks for pointing that out. I’ll remove the labels for now.

Since @Prabhakar-17 has already contributed to this repo, he should be able to take this on :)

**Comment by Prabhakar-17** [comment]
@tariq1890 Thank you, I will work on this.
@lilic Thank you for the info. Could you please tell the name of the tool.

**Comment by lilic** [comment]
This is the repo that should help with migration from client-go 1.17 and client-go 1.18 https://github.com/kubernetes-sigs/clientgofix

**Comment by lilic** [comment]
@Prabhakar-17 are you still interested in working on this, otherwise lets unassign you? :)

**Comment by Prabhakar-17** [comment]
@lilic yes, I am interested. I was getting few errors,  will give another try over this weekend.

**Comment by lilic** [comment]
Okay, feel free to write here the issues you faced, thanks!

**Comment by tariq1890** [comment]
If I remember correctly, the `verticalpodautoscaler` dependency didn't support the `v0.18.x` versions of client-go

**Comment by tariq1890** [comment]
I have raised this issue. Hoping for a response from the autoscaler maintainers: https://github.com/kubernetes/autoscaler/issues/3219

**Comment by mcristina422** [comment]
I opened a PR with those changes here https://github.com/kubernetes/autoscaler/pull/3098

**Comment by lilic** [comment]
Seems like new PR is this one https://github.com/kubernetes/autoscaler/pull/3225

**Comment by lilic** [comment]
The PR was merged @Prabhakar-17 do you have time within the next week to do this change, as we want to do an alpha release next week. Thanks! :)

**Comment by Prabhakar-17** [comment]
@lilic I can take a look this weekend.

**Comment by tariq1890** [comment]
Thanks! Let us know if you need any help :). This will need some code changes since you'll have to add the extra context parameter

**Comment by lilic** [comment]
This tool helps with that https://github.com/kubernetes-sigs/clientgofix

**Comment by Prabhakar-17** [comment]
Update: have created a draft PR, facing some issues. I was not able to find much time to fix it, will take a look again. thanks
Updated the dependency version and ran the tool lilic suggested.

error:
```
# k8s.io/kube-state-metrics/internal/store
internal/store/poddisruptionbudget.go:90:31: p.Status.PodDisruptionsAllowed undefined (type "k8s.io/api/policy/v1beta1".PodDisruptionBudgetStatus has no field or method PodDisruptionsAllowed)
internal/store/verticalpodautoscaler.go:262:74: not enough arguments in call to vpaClient.AutoscalingV1beta2().VerticalPodAutoscalers(ns).List
	have ("k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions)
	want (context.Context, "k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions)
internal/store/verticalpodautoscaler.go:265:75: not enough arguments in call to vpaClient.AutoscalingV1beta2().VerticalPodAutoscalers(ns).Watch
	have ("k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions)
	want (context.Context, "k8s.io/apimachinery/pkg/apis/meta/v1".ListOptions)
FAIL	k8s.io/kube-state-metrics [build failed]
```
