### ISSUE TITLE
Add healthz info for kubelet and kube-proxy

### ISSUE THREAD

**Issue by andyxning** [kubernetes/kube-state-metrics#111]
How about we add health check metrics about `apiserver`, `scheduler`, `controller-manager`, `kubelet` and `kube-proxy`. 

/ping @brancz @piosz

**Comment by brancz** [comment]
All these components expose Prometheus metrics themselves, so once discovered there are already `up` metrics for these created by Prometheus as it scrapes them.

**Comment by piosz** [comment]
All core Kubernetes components should export metrics in Prometheus format
https://github.com/kubernetes/kubernetes/issues/40736

**Comment by andyxning** [comment]
apiserver, scheduler, controller-manager should be fine cause we may not change them frequently. For kubelet and kube-proxy, with nodes adding or off-line for maintenance, we may need to update the prometheus configuration frequently. 

Under this situation, i think we may utilize the node discovery ability through apiserver's node list api  and make kube-state-metrics handle this automatically. On this way, we may only need Prometheus scrape metrics from dedicated kube-state-metrics endpoints.

**Comment by brancz** [comment]
That's something you'll have to do anyways as you want to scrape the kubelet either way for its metrics. Using a cloud provider that shouldn't be a problem, as all major cloud providers have build in discovery mechanisms for Prometheus to discover the VMs.

The Prometheus Operator actually has a feature that allow you to sync kubelet IPs into an endpoints object to be discovered like any other Endpoints object, independent of cloud providers.

**Comment by andyxning** [comment]
@brancz Could you please give more info about Prometheus Operator. BTW, How is the discovery mechanism?

**Comment by brancz** [comment]
The [Prometheus Operator](https://github.com/coreos/prometheus-operator) simply watches the nodes resource of the Kubernetes API server to populate the endpoints object. The object you want it to write to can be specified as a flag (`--kubelet-object` IIRC).
