### ISSUE TITLE
Consider dropping vendor dir in favour of GOPROXY

### ISSUE THREAD

**Issue by tariq1890** [kubernetes/kube-state-metrics#1111]
In kube-state-metrics, we have managed to maintain a clean dependency tree. This puts us in a good position and we can consider using the `GOPROXY` feature available in go.13+.

Some advantages I can think of with `no vendor directory`:

- Decreased build times since the dependencies are cached in the `https://proxy.golang.org/` server. I have heard great things about the build times.
- Decrease the size of the repository

Disadvantage:
- This could cause issues in regions where the `GOPROXY` is accessible. One example would be China. But we can get around this by allowing for GOPROXY to be configurable.

@brancz @lilic 

/help

**Comment by lilic** [comment]
> Decreased build times since the dependencies are cached in the https://proxy.golang.org/ server. I have heard great things about the build times.

Do we suffer from this? For now the Disadvantages are too high over the gain, but would say lets leave it open in case that changes. WDTY?

**Comment by lilic** [comment]
I would say lets go ahead and do this?
