### ISSUE TITLE
Unexpected label is not unique error

### ISSUE THREAD

**Issue by dwbrown2** [kubernetes/kube-state-metrics#1115]
/kind bug

**What happened**:
We had a pod get created with `ops-managed` and `ops_managed` labels in our cluster. In this scenario, all metrics from kube-state-metrics are getting rejected by Prometheus with label is not unique error message. 

```
level=warn ts=2020-04-06T15:07:36.476Z caller=scrape.go:972 component="scrape manager" scrape_pool=kubernetes-service-endpoints target=http://10.4.263.218:8080/metrics msg="append failed" err="label name \"label_ops_managed\" is not unique: invalid sample"
```

**What you expected to happen**:
Metrics to be ingested... with either one or two separate labels in this scenario. 

**How to reproduce it (as minimally and precisely as possible)**:
Add `ops-managed` and `ops_managed` labels to a single pod. 

**Anything else we need to know?**:
I could not find a duplicate issue, my apologies if I overlooked one. Thank you for the help and the great work on this project! 

**Environment:**
v1.9.5 for ksm
v2.16.0 for prometheus

**Comment by brancz** [comment]
I don't think we have an existing issue for this. This is a difficult one, as for correctness in Prometheus we have to normalize the labelnames, causing these collisions. It's a fundamental incompatibility between the systems. There are various other problems around label/annotations, as described in https://github.com/kubernetes/kube-state-metrics/issues/1102. Would you even need these labels in Prometheus or would just not having them at all work for you?

https://github.com/kubernetes/kube-state-metrics/issues/1102 would at least allow to somewhat control this by excluding contending labels, but it could always happen, that users intentionally attack the system by abusing allowed labels in this way. Maybe we need a strict mode for labels, where we only allow labels that already conform to Prometheus label name requirements to actually propagate. Wdyt @tariq1890 @lilic dgrisonnet?

**Comment by dwbrown2** [comment]
Definitely see what you mean, let me know if I can help in any way. 

One quick idea on my end... if you have a collision, prefer the one that meets the Prometheus label name requirements over others. This might be too specific to this situation but as a user this feels optimal, assuming we can't find a way around the incompatibility between k8s and prom. 

Not having these labels in Prometheus at all would likely lead to some real confusion, but definitely an improvement on the current behavior.

**Comment by tariq1890** [comment]
I think to drop one label in favour of another is rather dangerous and could leave an unsuspecting user guessing for days when they are trying to troubleshoot. While I understand the need here, I still lean towards sticking with the current behaviour. We should strive towards simplicity here; my 2cents.

**Comment by dwbrown2** [comment]
Just want to add some additional context on current behavior. We have a cluster with 1000s of pods running and this single "malformed" pod prevented us from getting ALL kube-state-metrics data.

**Comment by dgrisonnet** [comment]
To have a similar behavior with #1102 a user would need to allow both "ops-managed" and "ops_managed" labels which is very unlikely. If only the "ops-managed" label was allowed, the metric would have been scraped from all the pods except the malformed one.

To avoid any attack related to this we could introduce a validator verifying that no allowed labels are conflicting.

**Comment by dgrisonnet** [comment]
Since allowed labels would be defined via the arguments, ksm would exit due to conflicting allowed labels. What do you think?

**Comment by dwbrown2** [comment]
Sounds like an improvement to me! 

This issue in its current form was hard for us to identify because Prometheus rejects all ksm data without any indication of the pod causing the error. It actually didn't even tell what the (second) conflicting label was. 

So exiting with an error that says either this pod or this set of conflicting labels is causing the issue sounds like it would be helpful!

**Comment by w4rgrum** [comment]
We got the same issue (with duplicate labels using - and _ as separators, and same value) and found a workaround to avoid issues even with crappy pods labeling.
We added a dedicated metric_relabel_configs to our kube-state-metrics scrape job in Prometheus using a labelmap to force the replacement of all the labels matching the regexp "^(label_.+)$". This will force Prometheus to remove all the duplicate labels (if different values were assigned the behavior of the resulting value is unknown else the value is kept and ok, but at least it will generate a valid sample).

```yaml
- job_name: kube-state-metrics
  [...]
  # Force removal of duplicate 'label_.+' labels
  metric_relabel_configs:
  - action: labelmap
    regex: ^(label_.+)$
```

NB: we are currently using prometheus v2.28.0 but should work on older versions, hoping this behavior will be kept in next versions.
