### ISSUE TITLE
Update deprecated Ingress API version ?

### ISSUE THREAD

**Issue by tlereste** [kubernetes/kube-state-metrics#1127]
To follow issue #802 : 
kube-state-metrics still use deprecated Ingress API version `extensions/v1beta1` for `Ingress` resources.

The blog post : https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ have been updated and now says that Ingress API version `extensions/v1beta1` will be removed in **v1.22**.

The Ingress API version has been deprecated since **v1.14**.

Should we keep it more or update now ?

**Comment by tariq1890** [comment]
Thanks for filing this issue. We are fine with moving to the new apiVersion once the K8s 1.18.x dependencies are added to ksm. Please feel free to contribute that as a PR if you wish :)

**Comment by tlereste** [comment]
Thanks ! I will do that :)
/assign

**Comment by tlereste** [comment]
I tried to update **KSM** to use **K8S** **1.18.2**.
Unfortunately, `vertical-pod-autoscaler` is not yet compatible with **client-go** **v0.18.x**.  

I  have the following errors : 
```
vendor/k8s.io/autoscaler/vertical-pod-autoscaler/pkg/client/clientset/versioned/typed/autoscaling.k8s.io/v1/verticalpodautoscaler.go:74:5: not enough arguments in call to c.client.Get().Namespace(c.ns).Resource("verticalpodautoscalers").Name(name).VersionedParams(&options, scheme.ParameterCodec).Do
        have ()
        want (context.Context)
```
Because now **client-go** rest request must set **context** on **Do** call : 
https://github.com/kubernetes/client-go/blob/5159cff060fb98cd98592f6663f322c982066d7e/rest/request.go#L939

**VPA** use a old client-go version : **v0.0.0-20191109102209-3c0d1af94be5** since 
November 15, 2019.
