### ISSUE TITLE
Add Support for kube_state_metrics_build_info

### ISSUE THREAD

**Issue by stevebail** [kubernetes/kube-state-metrics#1132]
This is a FEATURE REQUEST.

Please add support for kube_state_metrics_build_info as part of the metrics exposed on telemetry port 8081. 
kube_state_metrics_build_info shall include the version of the kube-state-metrics.
Most Prometheus exporters are currently supporting such metric.

**Comment by brancz** [comment]
Love this :+1: do you want to shoot us a PR to add it? :)

**Comment by stevebail** [comment]
@brancz 
I am new :)
Sorry to ask but what is the process to create a PR?

**Comment by mcristina422** [comment]
Prometheus does provide a helper for this https://github.com/prometheus/common/blob/7680068d4af7bd5cb3043381494f956c22c034b2/version/info.go#L38, but we are not setting those exact vars. So something similar could probably be added to https://github.com/kubernetes/kube-state-metrics/blob/17ddeca348130ead2f893295ea093429c388887c/pkg/version/version.go

**Comment by Prabhakar-17** [comment]
@stevebail I recently did some contributions to this project, I would be happy to help you with the process if you are willing to create a PR. Let me know.
