### ISSUE TITLE
PV Capacity (kube_persistentvolume_capacity_bytes)

### ISSUE THREAD

**Issue by stevebail** [kubernetes/kube-state-metrics#1134]
What is kube_persistentvolume_capacity_bytes? 
Is it the fixed total capacity regardless of usage?
Or is it the currently available capacity?
I think we should considered improving the metric name.

**Comment by brancz** [comment]
It's the total capacity of the volume. The name is aligned with the naming conventions in kube-state-metrics in regards to their location in the API object. If you think the description/documentation can be better, I'd be more than happy about a PR to improve it! :slightly_smiling_face:

**Comment by stevebail** [comment]
@brancz 
Thank you Frederic for the clarification.
I guess we are missing a new counter called kube_persistentvolume_usage_bytes.
Without it, it is not possible to know how much is available.
Do you agree?

**Comment by brancz** [comment]
kube-state-metrics is strictly about converting Kubernetes API objects to Prometheus style metrics. The metric you are looking for to monitor volume usage already exists on the kubelet:

* kubelet_volume_stats_inodes_used
* kubelet_volume_stats_used_bytes
* kubelet_volume_stats_available_bytes
* kubelet_volume_stats_capacity_bytes
* kubelet_volume_stats_inodes
* kubelet_volume_stats_inodes_free

**Comment by stevebail** [comment]
Thanks @brancz  for the clarification but I cannot find them in my system.
I am scrapping at /api/v1/nodes/<node-name>/proxy/metrics and k8s  is running v1.17.0.
There is no metrics starting with kubelet_volume.
Did I miss something?

**Comment by brancz** [comment]
Your CSI driver has to implement some handlers make sure with your CSI driver that it does actually implement them.

**Comment by stevebail** [comment]
Now that I understand all the pieces, I think I am OK with the metric name  kube_persistentvolume_capacity_bytes.
No PR needed :)
Thank you Frederic!

**Comment by Sahb13** [comment]
Hi Team,

I'm using Vmware environment and when i checked prometheus its not showing below metrics.

    kubelet_volume_stats_inodes_used
    kubelet_volume_stats_used_bytes
    kubelet_volume_stats_available_bytes
    kubelet_volume_stats_capacity_bytes
    kubelet_volume_stats_inodes
    kubelet_volume_stats_inodes_free

 I looked at the prom stack yaml and found only below jobs defined. Do you think i need to add some jobs related to kubelet ? if yes where and how shall i configure it. Also, if you can just give me basic idea as to how metrics are being pulled by prometheus. To what i understood it periodically fetches these metrics from prom stack yaml. correct me if i'm wrong.



Thanks

**Comment by Gbotttt** [comment]
Hi Team,

I'm using Vmware environment and when i checked prometheus its not showing below metrics.

kubelet_volume_stats_inodes_used
kubelet_volume_stats_used_bytes
kubelet_volume_stats_available_bytes
kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free

I looked at the prom stack yaml and found only below jobs defined. Do you think i need to add some jobs related to kubelet ? if yes where and how shall i configure it. Also, if you can just give me basic idea as to how metrics are being pulled by prometheus. To what i understood it periodically fetches these metrics from prom stack yaml. correct me if i'm wrong.

Thanks

**Comment by guettli** [comment]
There are metrics. Currently, Alpha, but working (for me): kubelet_volume_stats_*

https://kubernetes.io/docs/reference/instrumentation/metrics/#list-of-alpha-kubernetes-metrics

Example:

```console
k get --raw /api/v1/nodes/$NODE/proxy/metrics  | grep kubelet_volume_stats
```
