### ISSUE TITLE
Has 1.9.6 been suddenly removed?

### ISSUE THREAD

**Issue by alonisser** [kubernetes/kube-state-metrics#1137]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
 /kind bug

**What happened**:
Suddenly my pod fails because they can't download the 1.9.6 image, but older one do works with it (Or seem so)
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
try to use 
https://raw.githubusercontent.com/kubernetes/kube-state-metrics/release-1.9/examples/standard/deployment.yaml
for deployment and see it trys state metrics server with 1.9.6 version which is now non existentk
**Anything else we need to know?**:

**Environment**:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.7", GitCommit:"169db3bff4b5fb7722e967c5b6356713f05f15ed", GitTreeState:"clean", BuildDate:"2020-04-03T16:14:09Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

**Comment by brancz** [comment]
@tariq1890 I think you started the 1.9.6 release but it looks like it wasn't entirely finished up?

**Comment by tariq1890** [comment]
Yes. We need to push it to gcr and quay. I currently lack the permissions to do that

**Comment by tariq1890** [comment]
@alonisser 1.9.6 was never released in the first place

I recommend fetching the latest release from here: https://github.com/kubernetes/kube-state-metrics/releases

**Comment by brancz** [comment]
An you push the tag and publish the release? Then I can at least publish the quay image.

**Comment by tariq1890** [comment]
@brancz I've created the release draft. You can publish it once you're ready to push the quay image :)

**Comment by brancz** [comment]
1.9.6 should be published

**Comment by lilic** [comment]
This is published, closing issue.
