### ISSUE TITLE
Joining kube_node_labels with kube_pod_labels

### ISSUE THREAD

**Issue by efeller** [kubernetes/kube-state-metrics#1148]
Hi all,

I would like to join kube_node_labels with kube_pod_labels to retrieve the instance type on which my pod is running. The time series "kube_node_labels" seems to have a label called "label_beta_kubernetes_io_instance_type". However, I cant seem to find a field in kube_pod_labels on which I could join with kube_node_labels.

Would be great to receive your help/example on how I can make it work. Thank you very much in advance.

/feature

**Comment by brancz** [comment]
You're going to have to do two joins, easiest would be to start with joining `kube_pod_info` with `kube_pod_labels` on the `namespace` and `pod` labels, and then `kube_node_labels` on the `node` label.

**Comment by efeller** [comment]
Thanks a lot @brancz. I got it to work using:

`kube_pod_info * on(pod,namespace) group_right(node) kube_pod_labels * on(node) group_left(label_beta_kubernetes_io_instance_type) kube_node_labels`
