### ISSUE TITLE
Provide a new home for the helm chart

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#1153]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
https://github.com/helm/charts#deprecation-timeline helm/charts repository which currently hosts the kube-state-metrics chart will become obsolete in Nov 2020.
**What you expected to happen**:
Figure out a new place for the kube-state-metrics chart. Ideally, it could live in this repository as a directory (similar to the jsonnet mixin) and get published on helm hub. 
Currently @tariq1890 and I are maintainers of the helm/charts chart and could maintain it here as well.

**Comment by lilic** [comment]
cc @tariq1890

**Comment by tariq1890** [comment]
I am okay with adding the helm chart to this repository. Thoughts @brancz and @lilic ?

**Comment by brancz** [comment]
I'd be fine with that as well, ideally we could even generate it from the jsonnet code we have, but I wouldn't block it if it wasn't. The only think that I would be a bit strict about is that everything has to be equally automated as the jsonnet things we have, so that releasing a new version doesn't have any other steps than the current `VERSION` file bump.

**Comment by lilic** [comment]
Yes fine as well, not to familiar with Helm charts so don't think I can contribute much to it, but no objections.

**Comment by mrueg** [comment]
Would you be comfortable with a `contrib/` folder structure that includes a `charts` subfolder? This could potentially include `jsonnet` and other deployment options as well.

**Comment by brancz** [comment]
That's effectively what we used to have, and that didn't work out well.

**Comment by scottrigby** [comment]
I have started a draft PR for this: https://github.com/kubernetes/kube-state-metrics/pull/1237

Looking for feedback on the to-do items I added, before I do too much more on this. Happy to finish after feedback 🙂
