### ISSUE TITLE
kube_pod_started_time is missing

### ISSUE THREAD

**Issue by stevebail** [kubernetes/kube-state-metrics#1159]
@brancz 

 ksm is currently supporting the following pod timestamps:

- kube_pod_created
- kube_pod_status_scheduled_time
- kube_pod_start_time

The kube_pod_started_time is missing.
This the time after all the images have been pulled, all containers have been created and all containers have been started.

Any plans to support such metric?
New feature enhancement?

**Comment by lilic** [comment]
@stevebail thanks for the issue, does Pod resource expose this time in the API?

**Comment by stevebail** [comment]
Good question!
When looking at the running YAML (kubectl get pods <pod-name> -o yaml), I do see the following for each container:
    state:
      running:
        startedAt: "2020-06-18T13:19:03Z"

The largest value should be used for the pod started time.

**Comment by Drugoy** [comment]
@stevebail 
What is kube_pod_start_time?
Isn't this what you are looking for? Or what would be the difference between it and kube_pod_started_time?

p.s.: I came here to file a ticket about kube_pod_start_time being broken: restarting a pod doesn't affect it, but maybe it's just a metric for something else and you know it, while I don't, so instead of filing new ticket I stumbled upon yours, since it seems to be pretty much relevant.

**Comment by Drugoy** [comment]
My current problem is that I can't use ksm to get pod's uptime.
Someone, please, either fix kube_pod_start_time or introduce kube_pod_started_time.

**Comment by stevebail** [comment]
The current kube_pod_start_time and the proposed kube_pod_started_time are not the same.
kube_pod_start_time is the time when the pod is starting but is not executing yet (not ready to receive requests yet).
kube_pod_started_time is the time when the pod is executing and ready to receive requests. 
The time difference between them can easily be in the order of many seconds and vary greatly depending on many factors.

**Comment by Drugoy** [comment]
Well, judging by your explanation I should file a bug ticket, because kube_pod_start_time doesn't get update upon pod's reboot.

**Comment by lilic** [comment]
@stevebail 
> Good question!
When looking at the running YAML (kubectl get pods -o yaml), I do see the following for each container:
state:
running:
startedAt: "2020-06-18T13:19:03Z"

> The largest value should be used for the pod started time.

Where is this in the k8s api? I only found `StartTime` via the `PodStatus` which is what we use for `kube_pod_start_time `
```
    // RFC 3339 date and time at which the object was acknowledged by the Kubelet.
    // This is before the Kubelet pulled the container image(s) for the pod.
    // +optional
```

If you can provide link to code where that is defined, or create PR for it, seems very valid!

**Comment by lilic** [comment]
> Well, judging by your explanation I should file a bug ticket, because kube_pod_start_time doesn't get update upon pod's reboot.

@Drugoy can you open issue for this, thanks! Can you provide a minimal reproduce manifest, thanks!

**Comment by Drugoy** [comment]
> > Well, judging by your explanation I should file a bug ticket, because kube_pod_start_time doesn't get update upon pod's reboot.

> @Drugoy can you open issue for this, thanks! Can you provide a minimal reproduce manifest, thanks!

#1167
