### ISSUE TITLE
Support for API-groups and other kinds like the openshift objects

### ISSUE THREAD

**Issue by bjartek** [kubernetes/kube-state-metrics#116]
What are the plans regarding supporting other non core
API groups?

We are using OpenShift and are seriously looking into this, but it would be nice to support kinds like DeploymentConfig, BuildConfig and ImageStreams. 

Currently they exist in the oapi API server but it is changing with the introduction of API groups. https://github.com/openshift/origin/pull/12986

I am at kubecon in Berlin so if any of you are here I would love to chat about this. Ping me as @bjartek on twitter or just reply here.

**Comment by brancz** [comment]
I'm wondering what implications this has for users running it against a vanilla kubernetes cluster, I would like to avoid the confusion whether this project is meant for openshift clusters or vanilla kubernetes clusters. I guess we would have to see what the integration would look like as in a first pull request and then we can decide, whether it may be better to be continued a fork to avoid odd compatibility issues.
