### ISSUE TITLE
kube_pod_start_time doesn't get updated upon pod reboot

### ISSUE THREAD

**Issue by Drugoy** [kubernetes/kube-state-metrics#1163]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
kube_pod_start_time doesn't get updated upon pod reboot.

**What you expected to happen**:
kube_pod_start_time should represent pod's start time

**How to reproduce it (as minimally and precisely as possible)**:
Just execute `kill -s TERM 1` in a pod.

**Anything else we need to know?**:
ocp 3.11

**Environment**:
- Kubernetes version (use `kubectl version`): 1.11
- Kube-state-metrics image version 1.9.6

**Comment by brancz** [comment]
kube-state-metrics just mirrors what the Pod API exposes. If you think this should be different, then that should be a bug against Kubernetes, not kube-state-metrics.

**Comment by Drugoy** [comment]
@brancz but Cluster's GUI (we have OpenShift 3.11) shows pod uptime right. I bet it takes data from Pod API as well.

**Comment by brancz** [comment]
kube-state-metrics exposes the value of whatever is in `.status.startTime` of the Pod object. Could you share the output of this command?

```
kubectl get -n <namespace> pod account-v0-8-sfc9z -oyaml
```

**Comment by Drugoy** [comment]
```kubectl get pod account-v0-8-j7j4l -o json | jq '.status.startTime'
"2020-07-03T10:11:12Z```

**Comment by brancz** [comment]
And that's what you expected to see in the metric or not?

**Comment by Drugoy** [comment]
Well, crap, turns out you are right: it is k8s issue: a pod's reboot doesn't affect it.
Sorry for bothering you.
