### ISSUE TITLE
Missing container start time metric kube_pod_container_state_started

### ISSUE THREAD

**Issue by Drugoy** [kubernetes/kube-state-metrics#1167]
**What happened**:
`kubectl describe pod`'s output has
```
...
Containers:
  containername:
    ...
    State: Running
      Started: %timestamp
    ...
...
```
This represents container's (and thus monocontainer pod's) start time (and **is the only way to calculate its uptime**).
I need this metric **badly**.
It is way more important than `kube_pod_start_time` metric (which is kinda useless, since restarting a pod doesn't affect this metric).
Judging by the metric's 'path' in `kubectl describe pod`'s output the metric should be named `kube_pod_container_state_started`.

**Environment**:
- Kubernetes version: 1.11
- Kube-state-metrics image version: 1.9.6

/kind feature

**Comment by brancz** [comment]
Seems reasonable to me to add this.

**Comment by lilic** [comment]
@Drugoy sounds good, do you want to contribute this or should we mark it as help wanted?

**Comment by Drugoy** [comment]
@lilic please mark it as help wanted, I don't know golang.

**Comment by lilic** [comment]
No worries! Marked with that! I will see if I have some time if no one looks at it in the near future to add.

**Comment by vikkyomkar** [comment]
@lilic shall I contribute to this request ?

**Comment by lilic** [comment]
@vikkyomkar if you feel like the issue is clear enough for you go ahead?
