### ISSUE TITLE
MetricsHandler errors are silently dropped

### ISSUE THREAD

**Issue by Sayrus** [kubernetes/kube-state-metrics#1169]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When an error occurs in MetricsHandler, the error is never logged and do not trigger an unhealthy state. In my case, this happens when the ServiceAccount does not have enough permission for AutoSharding:
https://github.com/kubernetes/kube-state-metrics/blob/2415ca281c81039353adb90931acb8495b3df7f8/pkg/metricshandler/metrics_handler.go#L106

This means that with my invalid configuration (https://github.com/helm/charts/pull/23210), nothing happened. Kube-State-Metrics was "healthy", nothing in the logs but zero metrics were returned.

**What you expected to happen**:

Kube-State-Metrics should have logged:
```
Detect failed with retrieve shard's StatefulSet: myns/prometheus-operator-kube-state-metrics: statefulsets.apps "prometheus-operator-kube-state-metrics" is forbidden: User "system:serviceaccount:myns:prometheus-operator-kube-state-metrics" cannot get resource "statefulsets" in API group "apps" in the namespace "myns"
```

And (IMHO), it should be in an unhealthy state. Autosharding is enabled but configuration failed.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy a kube-state-metrics with Autosharding enabled but no Kubernetes API permissions
- Start it (it will not print anything after `metrics_handler.go:101] Auto detecting sharding settings.`)
- Done, your kube-state-metrics is unhealthy, no metrics are coming and no errors were reported

**Anything else we need to know?**:

From my understanding, this is because there is no code to handle reported errors when calling MetricsHandler: https://github.com/kubernetes/kube-state-metrics/blob/2415ca281c81039353adb90931acb8495b3df7f8/main.go#L224

**Environment**:
- Kubernetes version (use `kubectl version`): v1.16.8-gke.15
- Kube-state-metrics image version: 1.9.5, 1.9.7

**Comment by tariq1890** [comment]
I am okay with this idea. I think exiting with a non-zero code is only appropriate and won't leave users guessing. @lilic @brancz Your thoughts on this? I think this is a good change to include in v2.0

**Comment by brancz** [comment]
I think this makes sense. I think this would be best solved by running this and the http server go routines as [run.Group](https://github.com/oklog/run)s.

**Comment by lilic** [comment]
Sounds good to me!

**Comment by lilic** [comment]
Is this something @Sayrus you are interested in contributing?

**Comment by Sayrus** [comment]
@lilic At the very, I'd be interested in trying !

**Comment by lilic** [comment]
Please go ahead! :)

**Comment by Sayrus** [comment]
Correct me if I'm wrong about what you are trying to achieve by moving to Run Groups.

Currently we have:
- Telemetry Server run as a Goroutine (with errors ignored?)
- MetricsHandler run as a Goroutine with errors ignored
- The Metric HTTP Server run as a blocking call in serve metrics

The goal is to move to a run group with these three and an error in any of the three lead to an unhealthy state / exit, right?

**Comment by brancz** [comment]
Correct, exiting when any of these error is what we want. And one to listen to signals like here https://github.com/thanos-io/thanos/blob/8b9665098283538cda2ff0284ef9589370726e0a/cmd/thanos/main.go#L189-L197
