### ISSUE TITLE
prometheus-kube-state-metrics returning kube_deployment_status_replicas_available is wrong

### ISSUE THREAD

**Issue by garysdevil** [kubernetes/kube-state-metrics#1170]
**Environment**:
- Kubernetes version (use `kubectl version`):  v1.15.0
- Kube-state-metrics image version：v1.4.0

The prometheus graph show: There are kube_deployment_status_replicas_available{deployment='hk-mail',namespace='xx'}=0 withing 1 hour.

kubectl get po -n namespace xx | grep hk-mail pod 
RESATRT=0，AGE=40d

It will cause the wrong alert. I want to know why did it happen?

**Comment by brancz** [comment]
could you restart your kube-state-metrics pod and see if it's still there?

**Comment by garysdevil** [comment]
> could you restart your kube-state-metrics pod and see if it's still there?

I restarted. The old data are already stored in Prometheus.  The new data is normal. There should be always two but once got zero.
![image](https://user-images.githubusercontent.com/41293784/88007592-e7787c80-cb40-11ea-8a64-3e7aeadfe2ea.png)

**Comment by brancz** [comment]
It appears to me that this is https://github.com/kubernetes/kube-state-metrics/issues/694 then probably.

**Comment by Adhira-Deogade** [comment]
It gives me completely wrong information too. It doesn't give me old metrics, only wrong numbers. Example instead of 160MiB, it gives 5MiB. Something's up. How do I solve this issue?

**Comment by brancz** [comment]
@Adhira-Deogade could you please open an issue for each individual issue you are seeing? Thanks!

**Comment by Adhira-Deogade** [comment]
I think, I know what my issue was. I had a job which ran only for 42 seconds but my prometheus scraping interval was set to 15s, so it had only 2 metrics points in the end and I am assuming, this might be my issue. I might however need to open an issue to address the problems of monitoring shorter duration jobs. Thanks @brancz
