### ISSUE TITLE
Add DaemonSet observed generation metric

### ISSUE THREAD

**Issue by brancz** [kubernetes/kube-state-metrics#1176]
/kind feature

**What happened**:

The correct way to determine whether a previous DaemonSet rollout is complete is by checking the following:

```
observedGeneration == generation &&
currentNumberScheduled == desiredNumberScheduled &&
numberMisscheduled == 0 && 
updatedNumberScheduled == desiredNumberScheduled &&
numberAvailable == desiredNumberScheduled
```

As well as checking that `kube_daemonset_updated_number_scheduled` hasn't changed in some time (as in the rollout hasn't progressed). (big thanks to @tnozicka for all the pointers!)

**What you expected to happen**:

All of those numbers to be available to alert on, but `observedGeneration` is not available.

**How to reproduce it (as minimally and precisely as possible)**:

This is a feature, so no previous kube-state-metrics version has this feature :)

**Anything else we need to know?**:

**Environment**: any
- Kubernetes version (use `kubectl version`): any
- Kube-state-metrics image version: any

@lilic @tariq1890

**Comment by vishnukarthikl** [comment]
I'd like to pick this up if no one is working on it.

**Comment by brancz** [comment]
@vishnukarthikl go ahead :)
