### ISSUE TITLE
Auto sharding scaling based on ready replicas

### ISSUE THREAD

**Issue by djjayeeta** [kubernetes/kube-state-metrics#1187]
**FEATURE**:
 /kind feature

**What happened**:
Auto sharding calculates the total number of shards based on the number of replicas https://github.com/kubernetes/kube-state-metrics/blob/master/pkg/metricshandler/metrics_handler.go#L219. This implies some downtime in the number of metrics streams reported due to the fact that replicas take time to come up. 

I have done some testing on a setup  with auto sharding enabled and HPA on the memory metric. The KSM pods are scraped by prometheus server at a frequency of 1 minute. I observed that I see a downtime in the number of metrics reported as HPA scales up the KSM statefulset (with scale this downtime might go up). Is it possible to calculate the totalshard based on the number of ready replicas, this have some drawbacks too
1) might result in duplicate metrics reported, in my opinion this might be better than loosing metrics.
2) latency and resource usage will not decrease ASAP, it will be decreased eventually when all the replicas are ready.

Ex 300 nodes (30 pods/node) KSM +HPA scales up to 3 pods : downtime 1 minute
500 nodes (30/pods/node) KSM+HPA scales up to 10 pods: downtime 4 minutes

I am open to other ideas to tackle this issue.

**What you expected to happen**:
Minimal loss of metrics 

**How to reproduce it (as minimally and precisely as possible)**:
Deploy KSM autosharding https://github.com/kubernetes/kube-state-metrics/tree/master/examples/autosharding with memory request 100Mi on 300 nodes (30 pods/node)
Prometheus server to scrape KSM sts.
 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+",  GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
- Kube-state-metrics image version: 1.9.5

**Comment by brancz** [comment]
I think this would be interesting to explore indeed.

**Comment by djjayeeta** [comment]
I would be happy to help out if you have any ideas in mind
