### ISSUE TITLE
Exposing pod annotation

### ISSUE THREAD

**Issue by sky-philipalmeida** [kubernetes/kube-state-metrics#1191]
Hi guys in order to have more flexibility exposing pod annotations would be a great plus.
I am refering to the pod annotation from where the metrics are taken not the annotation of kube-state-metrics itself.

There is not much info on the net but I come accross:
https://stackoverflow.com/questions/53066488/getting-pod-or-deployment-annotations-from-kube-state-metrics
and 
https://github.com/kubernetes/kube-state-metrics/issues/574

This would really be a plus for power use cases.

Well thanks for your attention,
Kind regards,
Philip Almeida

**Comment by brancz** [comment]
There is work in progress that allows this feature in a safe way: https://github.com/kubernetes/kube-state-metrics/pull/1125
