### ISSUE TITLE
Version detection during build time

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#1198]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
Docker images get build in prow and currently overwrite the existing tag in the staging repository
**What you expected to happen**:
Tags are a stable target and don't change over time

See also: https://github.com/kubernetes/kube-state-metrics/issues/1089

**Possible solution**
    * Read VERSION file (if there's a need to keep it and it can't be replaced with a build-time variable that ingests a git tag)
    * Check if current commit is tagged with that version
    * If it does, create a docker image with the version of VERSION -> kube-state-metrics:v1.9.8
    * If it does not, create a docker image with the version of VERSION and add git shortcommit (that creates a tag per commit) e.g. `kube-state-metrics:v1.9.8-aabbccdd`
    or add "-next" or similar (that's a moving target then) `kube-state-metrics:v1.9.8-next`

**Comment by tariq1890** [comment]
This is a valuable feature to have 👍 

/help

**Comment by lilic** [comment]
I believe we can close this now @mrueg, correct? :)

**Comment by mrueg** [comment]
Yes I think the way it works for containers is fine

**Comment by lilic** [comment]
Thanks!!
