### ISSUE TITLE
Help me! We will used Kubernetes v1.18.2 ,What version should  I  used of kube-state-metrics?

### ISSUE THREAD

**Issue by sober-wang** [kubernetes/kube-state-metrics#1209]
**What happened**:
We will used Kubernetes v1.18.2 ,What version I should used of kube-state-metrics?
**What you expected to happen**:
Can you help me? 
The READE.md only tell me kubernetes 1.17 should do something . But my k8s version  than this high, maybe you should update the READ.md

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): kubernetes v.118.2
- Kube-state-metrics image version

**Comment by tariq1890** [comment]
Please use the latest release: https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.9.7

**Comment by sober-wang** [comment]
> Please use the latest release: https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.9.7

Thanks for your suggest!

**Comment by tariq1890** [comment]
You're welcome :)
