### ISSUE TITLE
Alertrule for pulling if more PODs in a node report CrashLoopBackOff error.

### ISSUE THREAD

**Issue by tlkanthan2020** [kubernetes/kube-state-metrics#1211]
Whats the Prometheus Query(expression) to set a Alertrule which notifies if more than 3 PODs in a node goes to CrashLoopBackOff.

**Comment by lilic** [comment]
@tlkanthan2020 hey! kube-state-metrics provides metrics only, I would suggest to look at https://github.com/kubernetes-monitoring/kubernetes-mixin for example for examples of alerting rules, a lot of them are based on kube-state-metrics metrics. Hope that helps. :)
