### ISSUE TITLE
expose kubernetes pod labels for kube_pod metrics

### ISSUE THREAD

**Issue by boatmisser** [kubernetes/kube-state-metrics#1212]
> /kind bug
**What happened**:
I am going with bug but I am quite likely wrong, I just can't find any information on this one way or the another.

kube-state-metrics alerts such as kube_pod_status_phase do not seem to expose my pod's labels.
For instance my pod has labels such as appname, severity, owner etc.
Alerts only seem to have endpoint, instance, job, namespace, phase, pod, service

**What you expected to happen**:
I expected to see all my pod's labels and I expect them to be available for alert management.

**How to reproduce it (as minimally and precisely as possible)**:
Trigger kube_pod_status_phase on a pod with a kubernetes label

**Anything else we need to know?**:
As I said, I am not sure this is a bug or not; I can not find any information or documentation that says one way or the other whether or not my labels should be exposed. If this is not a bug and just can't be done, or there is a way of doing it that just isn't well documented, I apologise for raising this as a bug incorrectly!

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Kube-state-metrics image version
v1.9.7

**Comment by carlosjgp** [comment]
You could enrich that metric that comes from an endpoint using the `group_xxx` function for vector matching

something like this should work ([Reference](https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching))
`kube_pod_status_phase * on (pod,namespace) group_left kube_pod_labels`
