### ISSUE TITLE
sharding not support kubernetes v1.10?

### ISSUE THREAD

**Issue by daxwang** [kubernetes/kube-state-metrics#1219]
there no metrics  when open sharding in kube-state-metrics(version: v1.9.7), but when i closed the sharding, i can get the metrics. sharding not support kubernetes v1.10?

**Comment by lilic** [comment]
@daxwang Thanks for your issue. Can you explain a bit more what do you mean by autoscale?

**Comment by daxwang** [comment]
> @daxwang Thanks for your issue. Can you explain a bit more what do you mean by autoscale?

sharding

**Comment by lilic** [comment]
cc @brancz here as he implemented it. But v1.10 Kubernetes is not supported for 1.9.7 altogether, so might be some API problems https://github.com/kubernetes/kube-state-metrics#compatibility-matrix

**Comment by brancz** [comment]
I think v1.10 is too old for the APIs used by auto sharding (it requires StatefulSets in apps/v1).
