### ISSUE TITLE
[ingress]feature request

### ISSUE THREAD

**Issue by zouyee** [kubernetes/kube-state-metrics#122]
gentle ping  @brancz 
I will work on adding some metrics,here is the relevant information . would you have some suggeustions？
#### service
| Metric name| Metric type | Labels/tags |
| ---------- | ----------- | ----------- |
| kube_service_spec_servicetype | Gauge | `clusterIP `=&lt;cluster ip&gt; <br> `namespace`=&lt;service-namespace&gt; <br>`service`=&lt;service-name&gt;<br>`type`=&lt;ClusterIP\|NodePort\|None\&gt;
#### pv
| Metric name| Metric type | Labels/tags |
| ---------- | ----------- | ----------- |
| kube_persistentvolume_status | Gauge | `persistentvolume`=&lt;pv-name&gt; <br> `namespace`=&lt;pvc-namespace&gt; <br>`phase`=&lt;Bound\|Failed\|Pending\|Available\|Released&gt;<br>`volume`=&lt;pvc-namespace&gt;

 #### namespace
| Metric name| Metric type | Labels/tags |
| ---------- | ----------- | ----------- |
| kube_namespace_status_phase | Gauge | `name`=&lt;namespace-name&gt; <br> `namespace`=&lt;pvc-namespace&gt; <br>`phase`=&lt;Terminating\|Active&gt;<br>`create_time`=&lt;date-time the server time when this object was created&gt;  

#### ingress
| Metric name| Metric type | Labels/tags |
| ---------- | ----------- | ----------- |
| kube_ingress_info | Gauge | `name`=&lt;ingress-name&gt; <br> `namespace`=&lt;ingress-namespace&gt; <br>`create_time`=&lt;date-time the server time when this object was created&gt;
| kube_ingress_metadata-generation | Gauge | `name`=&lt;ingress-name&gt; <br> `namespace`=&lt;ingress-namespace&gt;
|kube_ingress_loadbalancer|Gauge|`name`=&lt;ingress-name&gt; <br> `namespace`=&lt;ingress-namespace&gt;<br>`IP`=&lt;IP set for loadbalancer&gt; <br>`hostname`=&lt;loadbalancer hostname based on dns&gt;

**Comment by brancz** [comment]
These all sounds reasonable @zouyee ! :slightly_smiling_face:

**Comment by zouyee** [comment]
thanks,sorry for my late reply

**Comment by zouyee** [comment]
namespace DONE

**Comment by zouyee** [comment]
added ingress metric https://github.com/kubernetes/kube-state-metrics/pull/225
