### ISSUE TITLE
We need a new release for Kubernetes 1.17

### ISSUE THREAD

**Issue by serhatcetinkaya** [kubernetes/kube-state-metrics#1220]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Kubernetes v1.17 is not supported by latest release. According to [documentation](https://github.com/kubernetes/kube-state-metrics#compatibility-matrix) `master` branch supports Kubernetes `v1.17` but there are no published docker images that we can use as master branch. Currently we are using custom build from commit ID `5fd7281987d57c02e65ca5479c90099814e68ee5`.

**What you expected to happen**:

I'd expect another release with proper version (maybe release candidate ?) that covers missing commits to cover 1.17.  

**How to reproduce it (as minimally and precisely as possible)**:

Deploy latest image to Kubernetes `v1.17`

**Anything else we need to know?**:

N/A

**Environment**:
- Kubernetes version (use `kubectl version`): `v1.17.9-eks-4c6976`
- Kube-state-metrics image version: `v1.9.7`

**Comment by brancz** [comment]
We're in the process of finishing up the 2.0 release of kube-state-metrics. We should soon be releasing a first alpha release for this. cc @lilic

**Comment by lilic** [comment]
You can use v1.9.7 of kube-state-metrics for v1.17 Kubernetes version, we used it ourselves with no problems so far. As for master, we are right about to release a huge breaking v2.0 alpha release candidate of kube-state-metrics with a lot of breaking changes, hence no release in some time. See issue https://github.com/kubernetes/kube-state-metrics/issues/569 for more details.

But until then you can either use v1.9.7 or master if you want to, you just need to build images yourselves right now.

**Comment by serhatcetinkaya** [comment]
Is there a chance that GCR repo is not working ? @brancz @lilic 
```
➜  ~ docker pull k8s.gcr.io/kube-state-metrics:v1.9.7
Error response from daemon: manifest for k8s.gcr.io/kube-state-metrics:v1.9.7 not found: manifest unknown: Failed to fetch "v1.9.7" from request "/v2/kube-state-metrics/manifests/v1.9.7".
```

**Comment by serhatcetinkaya** [comment]
@piosz @serathius I guess I need one of you to take care of this

https://github.com/kubernetes/kube-state-metrics/issues/1000#issuecomment-565363658

**Comment by lilic** [comment]
Hm You mean the "k8s.gcr.io/kube-state-metrics:v1.9.7" image is not working? If yes will have a look at that, maybe something went wrong with promotion or we forgot a step there, we only recently added automation job for k8s.gcr.io. But either building your own or using quay.io/coreos/kube-state-metrics:v1.9.7 should work for now. 

We are aiming for 2.0 to get gcr working correctly, as it was manual until now. :)

**Comment by serhatcetinkaya** [comment]
Ok, thanks for the info. We can use quay.io temporarily I guess 👍

**Comment by superawesome7070** [comment]
Hi there! Any updates on this? I'm about to update my K8s from 1.16 to 1.17. I'm currently running v1.9.7 of kube-state-metrics. Do I need to update kube-state-metrics as well? Or can I keep using v1.9.7? Thanks.

@lilic @brancz
