### ISSUE TITLE
Some tags do not exist in GCR

### ISSUE THREAD

**Issue by sozercan** [kubernetes/kube-state-metrics#1225]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
Some tags do not exist in GCR. For example, for v1.9, GCR only contains v1.9.0 and v1.9.5 currently, but not latest v1.9.7 or anything in between.

**What you expected to happen**:
All tags are available in both GCR and Quay.

**How to reproduce it (as minimally and precisely as possible)**:
`docker pull k8s.gcr.io/kube-state-metrics:v1.9.7`

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version

**Comment by tariq1890** [comment]
Hey @sozercan  👋 !

We are aware of this and we apologise for the inconvenience. We as maintainers don't have write access to the GCR repo (only google employees have it). We recommend pulling images from `quay` for the time being.

Once we move to kube-state-metrics v2.0.0, we will be pushing images to prow container registry https://github.com/kubernetes/test-infra/pull/17916

**Comment by lilic** [comment]
As stated, we have images from v2.0.0 pre-releases for gcr and before that we have quay images, otherwise you can also build your own image easily and push to your own registry in the mean time. Feel free to open a new issue if you run into any problems with the new gcr images. Thanks!
