### ISSUE TITLE
kube_pod_container_resource_requests_cpu_cores value does not tally with kubectl

### ISSUE THREAD

**Issue by kmmanto** [kubernetes/kube-state-metrics#1228]
/kind bug

**What happened**:
From `grafana/prometheus`, the cpu core request(per node) is lower than the kubectl one.
In effect, the cluster would seem to have a lot of cpu cores free than what it actually has.

**What you expected to happen**:
Values from metrics should be equal or close to kubectl describe node figure

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Grafana/Prometheus**
CPU Core Request
30580m

**kubectl describe no**
```
 Resource                   Requests           Limits
  --------                   --------           ------
  cpu                        31475m (98%)       48 (150%)
  memory                     84726568960 (62%)  93288490240 (69%)
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Kube-state-metrics image version
`quay.io/coreos/kube-state-metrics:v1.9.5`

**Comment by lilic** [comment]
Hey @kmmanto sorry this was somehow overlooked, are you still able to reproduce this issue?
