### ISSUE TITLE
kube_pod_status_reason Not working

### ISSUE THREAD

**Issue by DcardosoJS** [kubernetes/kube-state-metrics#1229]
/kind bug

Hello,

I'm trying to expose the kube_pod_status_reason metric to be consumed by prometheus but it is not appearing. I have seen that other experimental metrics do not show, but some do.
The reason I need this metric is to list Evicted pods and I seem to have no other metric like it.

Can you please provide some sort of help?

Thanks

K8s version is 1.18.3
Kube-state-metrics version is 1.9.7

**Comment by dgrisonnet** [comment]
Hey @DcardosoJS, this metric is not available in 1.9.7 as it was added after the 1.9.0 release.
If you want to start using it, it was recently added to the 2.0.0-alpha pre-release.

**Comment by DcardosoJS** [comment]
> Hey @DcardosoJS, this metric is not available in 1.9.7 as it was added after the 1.9.0 release.
> If you want to start using it, it was recently added to the 2.0.0-alpha pre-release.

Thank you very much! It works :)
