### ISSUE TITLE
kube_pod_init_container_resource_requests not showing in metrics

### ISSUE THREAD

**Issue by kmmanto** [kubernetes/kube-state-metrics#1230]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
kube_pod_init_container_resource_requests metrics is not showing up in grafana/prometheus. Although kube_pod_init_container_resource_limits is showing.

**What you expected to happen**:
kube_pod_init_container_resource_requests should show up and can be used

**How to reproduce it (as minimally and precisely as possible)**:
- deploy `stable/kube-state-metrics` helm chart
- make a grafana dashboard panel
- Filter for kube_pod_init_container_resource_requests, which can't be selected

**Anything else we need to know?**:
- Prometheus version:
```
docker.io/prom/prometheus:v2.16.0
```
- Grafana version:
```
docker.io/grafana/grafana:7.0.0
```

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:10:45Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Kube-state-metrics image version:
```
quay.io/coreos/kube-state-metrics:v1.9.7
```

**Comment by lilic** [comment]
Hey, that is not part of 1.9.x only part of the 2.0.x release. For all available metrics see release branch https://github.com/kubernetes/kube-state-metrics/blob/release-1.9/docs/pod-metrics.md. Note if using 2.0 release it's still an alpha release but you are welcome to test it out, but there were bunch of breaking changes. https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0-alpha

Hope that answers your question?

**Comment by kmmanto** [comment]
Thanks for the prompt reply @lilic. That's my bad. Will check out 2.0.x in the meantime.

**Comment by lilic** [comment]
@kmmanto no problem! Let us know how 2.0 goes, even if everything goes smoothly would be great to get feedback, thanks!
