### ISSUE TITLE
tags/labels missing for daemonset, deployment, and replicaset metrics

### ISSUE THREAD

**Issue by jimmyseto** [kubernetes/kube-state-metrics#1239]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
metrics for daemonset, deployment, and replicaset no longer export tags/labels

**What you expected to happen**:
metrics for daemonset, deployment, and replicaset to include tags/labels

**How to reproduce it (as minimally and precisely as possible)**:
create daemonset, deployment, or replicaset.  poll kube-state-metrics endpoint.  look at, for example, kube_replicaset_created metrics.  observe no tags/labels are attached to it.

**Anything else we need to know?**:
v1.9.7 does not exhibit this issue.  below is a sample comparison with kube_*_created.  the same behavior is observed with all daemonset, deployment, and replicaset metrics.

v2.0.0-alpha:
kube_replicaset_created 1.600788121e+09

kube_deployment_created 1.600788121e+09

kube_daemonset_created 1.600790245e+09=

kube_configmap_created{namespace="openshift-console",configmap="console-config"} 1.600780846e+09

v1.9.7:
kube_replicaset_created{namespace="openshift-console",replicaset="console-fcbd85f55"} 1.600780846e+09

kube_deployment_created{namespace="openshift-web-console",deployment="webconsole"} 1.600780806e+09

kube_daemonset_created{namespace="openshift-node",daemonset="sync"} 1.600780702e+09

kube_configmap_created{namespace="openshift-console",configmap="console-config"} 1.600780846e+

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-15T09:45:30Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-09-04T19:45:00Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Kube-state-metrics image version
quay.io/coreos/kube-state-metrics:v2.0.0-alpha

**Comment by jimmyseto** [comment]
@lilic fyi.  thanks.

**Comment by lilic** [comment]
@jimmyseto Thanks for the issue, can you share the deployment for kube-state-metrics itself, thanks!

**Comment by jimmyseto** [comment]
> @jimmyseto Thanks for the issue, can you share the deployment for kube-state-metrics itself, thanks!

 @lilic i just deployed using what's in example/standard (https://github.com/kubernetes/kube-state-metrics/tree/master/examples/standard).

**Comment by jimmyseto** [comment]
just as another datapoint, using the same deployment (and simply changing the image to 1.9.7), i see the expected results.

**Comment by lilic** [comment]
@jimmyseto thanks, I could reproduce it locally, looking into what was causing the problem, I have a suspicion. Thank you so much for your testing and the report, its super useful! 🎉

**Comment by jw-s** [comment]
@lilic Looks like it's a closure loop issue with the label filtering. I fix it here #1041

**Comment by Rmond** [comment]
I met same problem on v2.0.0-alpha

![image](https://user-images.githubusercontent.com/18564404/94232121-e6483f00-ff37-11ea-916d-e434091d7e37.png)

**Comment by lilic** [comment]
@jw-s thanks, do you mind adding that bug fix in a separate PR, as we want to backport that to the release-2.0 branch, thanks!

**Comment by jw-s** [comment]
@lilic No worries, I've raised the PR

**Comment by jimmyseto** [comment]
thanks for the quick turnaround on this, @jw-s !  verified with a manual build of the latest/greatest off the release-2.0 branch, and confirmed that this is now fixed.
