### ISSUE TITLE
--labels-allow-list flag does not support wildcards

### ISSUE THREAD

**Issue by jimmyseto** [kubernetes/kube-state-metrics#1246]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug
/kind feature

**What happened**:
--labels-allow-list flag does not support wildcards.  need to specify each and every label of interest.

**What you expected to happen**:
--labels-allow-list flag to support wildcards.  should be able to configure kube-state-metrics to export labels without specifying each and every one.

for example:
--labels-allow-list=kube_pod_labels=[label_*] or --labels-allow-list=kube_pod_labels=[*]

**How to reproduce it (as minimally and precisely as possible)**:
install kube-state-metrics from https://github.com/kubernetes/kube-state-metrics/tree/master/examples/standard. enable --labels-allow-list flag using wildcard in argument.  observe invalid argument failure.  for example:

invalid argument "kube_pod_labels=[label_*]" for "--labels-allow-list" flag: invalid format, metric=[label1,label2,labeln...],metricN=[]

**Anything else we need to know?**:
there are scenarios in which users will want to export all labels for all k8s resources, in which users will want to export all labels for a particular k8s resource, in which users will want to export all labels containing a certain substring, etc, etc.  the current implementation of the flag does not allow for this unless users (1) know exactly what flags they want to export a priori and (2) specify the complete list of all flags they want for each k8s resource.

**Environment**:
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2020-10-01T19:23:04Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

- Kube-state-metrics image version
quay.io/coreos/kube-state-metrics:v2.0.0-alpha

**Comment by MMeent** [comment]
/remove-lifecycle stale
Please. Currently, labels are effectively unusable for any amount of labeled resources due to the lack of wildcards/blanket whitelisting abilities.

**Comment by mrueg** [comment]
#1403 was merged. Please let us know and feel free to reopen if this does not work as intended.

**Comment by christopherzli** [comment]
Hi, just curious on the context why we do not support regular regex on label matching here?
