### ISSUE TITLE
Kubernetes v1.19+ ingress and certificates deprecation issues

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#1249]
We get the following warning when using v1.19 kuberentes cluster:
> Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

Warning msg when running kube-state-metrics:

> W1005 14:47:25.621123   93191 warnings.go:67] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
W1005 14:47:25.706963   93191 warnings.go:67] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1005 14:47:25.757402   93191 warnings.go:67] certificates.k8s.io/v1beta1 CertificateSigningRequest is deprecated in v1.19+, unavailable in v1.22+; use certificates.k8s.io/v1 CertificateSigningRequest
W1005 14:47:25.758390   93191 warnings.go:67] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress

We should migrate to newer versions of `CertificateSigningRequest` and `Ingress`.

**Comment by tariq1890** [comment]
We should incorporate these changes into the release-2.0 branch

**Comment by lilic** [comment]
Sounds good, created a label for it.
