### ISSUE TITLE
Adding the to endpoint IPs mapping data to exposed  endpoint metrics  

### ISSUE THREAD

**Issue by shotu** [kubernetes/kube-state-metrics#1252]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 

> /kind feature

**What happened**:
Currently, In kube-state-metrics' exposed endpoint metrics, we don't have endpoints to IPs mapping data. 

**What you expected to happen**:

Expected metrics in exposition format added to endpoints metrics : 

>#HELP kube_endpoint_mapping Kubernetes endpoints data converted to Prometheus format
>#TYPE kube_endpoint_data gauge
>kube_endpoint_mapping{namespace="default",endpoint="mutateme",ips="172.17.0.5:3306,172.17.0.6:3306"} 1
>kube_endpoint_mapping{namespace="mysql",endpoint="mysql-read",ips="172.17.0.5:3306,172.17.0.6:3306"} 1

We can add multiple entries for more than one IP mapping. Also, ips can be broken down host and port.

**How to reproduce it (as minimally and precisely as possible)**:
NA

**Anything else we need to know?**:
As of now, I am a bit confused if this fits into the kube-state-metrics features. I would like to contribute to this part if it fits into the featrues. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18 
- Kube-state-metrics image version: v1.9.7

**Comment by brancz** [comment]
This doesn't strike me as a great candidate for a metric, what would be the use of this metric in let's say an alerting rule?

**Comment by shreyasHpandya** [comment]
This could be purely for the completeness of visualization of all k8 objects, also another use case is if I want to derive service to pod mapping from the KSM data.

**Comment by brancz** [comment]
The way it's proposed this metric would end every time the endpoints change, which would essentially produce extremely high unbound cardinality. As is I don't think we can accept this. We also tend to make sure there is a concrete alerting use case before adding a metric.

**Comment by shreyasHpandya** [comment]
Can you help me understand your first point? I am under the impression that it will be the same as pod metric, every time a pod changes/goes away, it will also end, or am I missing something?

**Comment by brancz** [comment]
That's correct, but the lifetime of that pod has ended then as well, while the endpoints object continues to exist, but new time-series are starting for the same endpoints object.

**Comment by shreyasHpandya** [comment]
oh ok got it, so what if we change the proposed metric to expose such that it ends when the endpoint changes and starts a new metric

**Comment by brancz** [comment]
If the endpoints object itself continues to exist, then the time-series should also, but since the unique label combination is what makes up the time-series ID essentially, this cannot be dynamic content.
