### ISSUE TITLE
Pass workflow labels down to workflow's pods

### ISSUE THREAD

**Issue by uipo78** [kubernetes/kube-state-metrics#1257]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

My use case: we have an application where it'd be useful to be able to build PromQL queries such as counting the number of pods running for a workflow with a particular set of labels.

Let me know if you all would like more information.

**Comment by lilic** [comment]
Thanks for the feature request, a few more details would be appreciated, how do you envision this to be done and what you mean by workflow here. Thanks!
