### ISSUE TITLE
Failed to create the client

### ISSUE THREAD

**Issue by lesterwang** [kubernetes/kube-state-metrics#127]
When I try to start the kube-state-metrics in Kubernetes(1.3.7), I get the following error:
```
I0425 01:13:00.524520       1 main.go:139] Using default collectors
I0425 01:13:00.525263       1 main.go:186] service account token present: true
I0425 01:13:00.525332       1 main.go:187] service host: https://10.253.0.1:443
I0425 01:13:00.526352       1 main.go:213] Testing communication with server
F0425 01:13:00.550739       1 main.go:156] Failed to create client: ERROR communicating with apiserver: the server has asked for the client to provide credentials
```
Then I delete the rc and svc to create again, the error becomes:
```
I0425 01:30:18.545484       1 main.go:139] Using default collectors
I0425 01:30:18.545707       1 main.go:186] service account token present: true
I0425 01:30:18.545721       1 main.go:187] service host: https://10.253.0.1:443
I0425 01:30:18.546196       1 main.go:213] Testing communication with server
F0425 01:30:18.547422       1 main.go:156] Failed to create client: ERROR communicating with apiserver: Get https://10.253.0.1:443/version: x509: certificate signed by unknown authority
```

The rc file is:
~~~~
apiVersion: v1
kind: ReplicationController
metadata:
  name: kube-state-metrics
  namespace: monitor
  labels:
    name: kube-state-metrics
spec:
  replicas: 1
  selector:
    name: kube-state-metrics
  template:
    metadata:
      labels:
        name: kube-state-metrics
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: kube-state-metrics
        image: gcr.io/google_containers/kube-state-metrics:v0.4.1
        ports:
        - containerPort: 8080
      nodeSelector:
        kubernetes.io/hostname: 10.22.96.10
~~~~
The svc file is:
~~~~
apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: monitor
  labels:
    name: kube-state-metrics
spec:
  type: NodePort
  ports:
  - name: main
    port: 8080
    nodePort: 30880
  selector:
    name: kube-state-metrics
~~~~
Does anyone know this? Thank you in advance

**Comment by andyxning** [comment]
@lesterwang Seems that you're using https for your apiserver with a self-signed CA which can not be handled by default golang http client.

**Comment by andyxning** [comment]
BTW, you should format your code and error log according to markdown for readability.

**Comment by brancz** [comment]
This seems to be a problem with how your cluster is handling ServiceAccounts. kube-state-metrics simply uses the in cluster client configuration which is guaranteed to work.

**Comment by lesterwang** [comment]
@andyxning @brancz when I create the kube-state-metrics pod, I use 
```kubectl -s http://{{apiserver}} create -f ...```
I don't know why kube-state-metrics still use the https, I will investigate more.
Sometime I restart the kubernetes node, the kube-state-metrics can running well, sometime not. Even it works well, I can see many log like this
~~~~
E0504 00:59:53.226610       1 reflector.go:199] k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1beta1.ReplicaSet: Get https://10.253.0.1:443/apis/extensions/v1beta1/replicasets?resourceVersion=0: x509: certificate signed by unknown authority
E0504 00:59:53.348348       1 reflector.go:199] k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1beta1.Deployment: Get https://10.253.0.1:443/apis/extensions/v1beta1/deployments?resourceVersion=0: x509: certificate signed by unknown authority
E0504 00:59:53.872967       1 reflector.go:199] k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1beta1.DaemonSet: Get https://10.253.0.1:443/apis/extensions/v1beta1/daemonsets?resourceVersion=0: x509: certificate signed by unknown authority
~~~~
I will check my kuberneter cluster configuration

**Comment by brancz** [comment]
It's highly encouraged to use https for inter cluster communication and even more so to access your cluster. It seems that you are not distributing correct certificates for your cluster components (or they might  be generating certs on the fly), which is why you are getting those errors.

kube-state-metrics expects a functioning ServiceAccount setup, which means that the Pod gets a bearer token and a ca cert mounted that it validates cluster communication certificates against.

**Comment by lesterwang** [comment]
I add the `--apiserver` args to the container, then no error happens, seems the default apiserver argument can't access the kubernetes cluster

**Comment by polinchw** [comment]
I'm having the same problem.  
`helm install --name pm --namespace pm --set alertmanager.enabled=false --set pushgateway.enabled=false --set kubeStateMetrics.args.apiserver=https://kubernetes.default.svc.cluster.local stable/prometheus` produces this error....
`root@pod-node-1:~# kubectl logs -f pm-prometheus-kube-state-metrics-7b798cf896-gpnpg -n pm
I0724 18:31:20.892478       1 main.go:85] Using default collectors
I0724 18:31:20.892765       1 main.go:93] Using all namespace
I0724 18:31:20.892784       1 main.go:129] metric white-blacklisting: blacklisting the following items: 
I0724 18:31:20.893339       1 main.go:169] Testing communication with server
F0724 18:31:20.903615       1 main.go:137] Failed to create client: ERROR communicating with apiserver: Get https://kubernetes.default.svc.cluster.local/version?timeout=32s: dial tcp 198.18.0.1:443: connect: connection refused
`

**Comment by sri-05** [comment]
@lesterwang can you share the container yaml where you added the 11apiserver arg

**Comment by lesterwang** [comment]
> @lesterwang can you share the container yaml where you added the 11apiserver arg

sorry, I can't find it.
