### ISSUE TITLE
--log_dir --log_file doesn't work

### ISSUE THREAD

**Issue by kintarowins** [kubernetes/kube-state-metrics#1271]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
Tried to use --log_dir and --log_file parameters but no log files were produced

**What you expected to happen**:
logs written to log file

**How to reproduce it (as minimally and precisely as possible)**:
add --log_dir=/var/log --log_file=ksm.log parameters to the kube-state-metrics startup command

**Anything else we need to know?**:
tried both older v1.9.5 and latest v2.0.0.alpha1
tried stderr & stdout redirection "> /var/log/ksm.log 2>&1"

**Environment**:
- Kubernetes version (use `kubectl version`): 1.17
- Kube-state-metrics image version: 2.0.0-alpha.1

**Comment by kintarowins** [comment]
to answer my own question: I needed to explicitly turn off --logtostderr and turn on --alsologtostderr then remove --log_dir as that gives a permission error
  --log_file=/var/log/ksm.log
  --alsologtostderr=true
  --logtostderr=false

maybe the cli readme could be made clearer that a combination of these switches need to be used together to make logging to file work

**Comment by lilic** [comment]
@kintarowins these flags come from klog, so best to open feature request or clarify there, thanks! :) https://github.com/kubernetes/kube-state-metrics/blob/5d56275d2b95ffcf6d15d8a6fa2b1bb02a1066ae/docs/cli-arguments.md
