### ISSUE TITLE
Add RuntimeClass metrics

### ISSUE THREAD

**Issue by tallclair** [kubernetes/kube-state-metrics#1274]
We should add RuntimeClass metrics. Maybe as an additional label on `kube_pod_info`?

/cc @egernst @SergeyKanzhelev 

/kind feature

**Comment by egernst** [comment]
Thanks @tallclair 

I think we want something similar to https://github.com/kubernetes/kube-state-metrics/pull/1053, but for runtimeclass itself.

**Comment by lilic** [comment]
@egernst @egernst can you please explain the feature request in a bit more details so we can evaluate if we want this added or not, thanks!

**Comment by egernst** [comment]
@lilic thanks.  As a user I would like to verify that a given RuntimeClass handler is being utilized.

When combined with kube_pod_status_phase, end-users can use tools like Grafana to quickly assess how pods running with various runtimeclass handlers compare. This is very similar to what was done for PodOverhead: https://github.com/kubernetes/kube-state-metrics/pull/1053

I would want to add something *like* kube_pod_runtimeclass_handler

**Comment by lilic** [comment]
Thanks @egernst sounds good to me! Are you interested in contributing this, otherwise we can mark it as help wanted. Note we are in the release 2.0 cycle so might be some delay in getting PRs merged.

**Comment by egernst** [comment]
Is there a cutoff for 2.0? I saw alpha from earlier this month (thanks!). 

In a perfect world, I would contribute this ASAP and it would be available in 2.0.  Do you think this is feasible?
