### ISSUE TITLE
How to get value of "kube_pod_container_resource_requests_cpu_cores" and node lable of "kube_pod_info" by a expression in v2.0.0

### ISSUE THREAD

**Issue by garysdevil** [kubernetes/kube-state-metrics#1277]
Kube-state-metrics image version:  latest or v2.0.0

kube_pod_container_resource_requests_cpu_cores
```
kube_pod_container_resource_requests_cpu_cores{cluster="xx",container="xx",instance="xx",job="xx",namespace="xx",pod="BB"}  0.01
```
kube_pod_info
```
kube_pod_info{cluster="xx",created_by_kind="xx",created_by_name="xx",host_ip="xx",host_network="false",instance="xx",job="xx",namespace="xx",node="AA",pod="BB",pod_ip="xx",uid="xx"}
```
It don't return lable "node" by metric "kube_pod_container_resource_requests_cpu_cores" in v2.0.0

Expected: get value of "kube_pod_container_resource_requests_cpu_cores" and node lable of  "kube_pod_info" by a expression. For example: 

kube_pod_container_resource_requests_cpu_cores{cluster="xx",container="xx",instance="xx",job="xx",namespace="xx",node="AA",pod="xx"}

**Comment by lilic** [comment]
Hey, thanks for the issue, this PR introduces node label back to the pod resource metrics, please see details there. https://github.com/kubernetes/kube-state-metrics/pull/1278

**Comment by lilic** [comment]
Closing as node label is back, let me know if you have any other issues, thanks!
