### ISSUE TITLE
Image build process is broken for arm and arm64 images

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#1288]
**What happened**:
Current images do not work on arm and arm64 arch.

**What you expected to happen**:
All the mentioned images should work for their arch. https://github.com/kubernetes/kube-state-metrics#container-image 

**How to reproduce it (as minimally and precisely as possible)**:
Try running latest arm and arm64 gcr images on those arc.

@paulfantom thanks for testing!
@mrueg FYI we found a potential problem.

**Comment by mrueg** [comment]
Which image(s) did you try to run? This one? https://console.cloud.google.com/gcr/images/k8s-staging-kube-state-metrics/GLOBAL/kube-state-metrics@sha256:aa84c31d4ab935acbd7debdc23a18e87dc344727290d8313f0d7d14b96293482/details?tab=info
