### ISSUE TITLE
Documentation of the metrics

### ISSUE THREAD

**Issue by cemo** [kubernetes/kube-state-metrics#129]
I can be considered pretty much new to monitoring land. It would be really cool to document metrics with some example usages. I know that some metrics are pretty much obvious from its name but its usage with some other metrics would be beneficial for all. I can also try my best to provide necessary information with my limited knowledge.

Another important thing is that compatibility of metrics with k8s version. Maybe something like `since` might be a good idea.

**Comment by brancz** [comment]
Example usages are a great idea. I think we should generally overhaul the whole documentation. Probably best to restructure the documentation into a docs folder and separate each group of metrics to it's own files and then have example usages in there.

**Comment by andyxning** [comment]
> Another important thing is that compatibility of metrics with k8s version. Maybe something like since might be a good idea.

This info maybe informed from the version of client-go which has a clear [compatibility matrix](https://github.com/kubernetes/client-go#compatibility-matrix) with Kubernetes. Maybe we should add some info about the version of client-go and make the users to refer to client-go compatibility matrix with the supporting Kubernetes version.
