### ISSUE TITLE
kube_pod_container_resource_[limits|requests] metrics missing in v2.0.0-alpha.2 

### ISSUE THREAD

**Issue by yli186** [kubernetes/kube-state-metrics#1292]
**What happened**:
Since we have recently upgraded our cluster to 1.18 from 1.14, so we are trying out the v2.0.0-alpha.2 version. But we were not able to get any scrape for kube_pod_container_resource_limits, while kube_pod_container_resource_requests is scraping fine for most of the pod (for some stateful pods was also missing).

**What you expected to happen**:

kube_pod_container_resource_limits and kube_pod_container_resource_requests to scrape as per documented 

**How to reproduce it (as minimally and precisely as possible)**:
Run v2.0.0-alpha.2 image pulled from quay.io as a deployment on k8s 1.18 cluster.

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: v2.0.0-alpha.2 
- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Other info:
Seems like regression from #1278 per @jimmyseto mentioned in #1245

**Comment by lilic** [comment]
Thanks for reporting! This is fixed in release-2.0 branch by @jimmyseto PR and will be included in the next pre-release sometime this week.
