### ISSUE TITLE
What's the estimate for having a GA out there on 2.0.0?

### ISSUE THREAD

**Issue by kitos9112** [kubernetes/kube-state-metrics#1295]
Hello,

I'm really interested in understanding when a fully GA (or beta) version will be available? I may understand this is still under heavy development with so many moving parts, but an estimated date in the foreseeable future would help.

Many thanks in advance!

**Comment by lilic** [comment]
@kitos9112 hey! I am working on one last bug (label allow list metrics are not showing correct labels) before we can run perf and scale testing for 2.0 alpha pre-release. There will be at least one more alpha pre-release cut and after that if no major regressions in performance we will promote it to beta. Giving actual dates would be hard to do, as the perf and scale tests depend on another SIG and any new bugs we might find. Hopefully soon, we are working hard on it. :)

As for fully GA depends on reported bugs and regressions, which you can help out by testing! 🎉 :) Hope this answers the question?

**Comment by kitos9112** [comment]
Hi @lilic! 

Thanks for your prompt and cultivated response. Yes, I perfectly understand all the commitments behind the scenes to have a beta/stable `v2` out there. Glad to see there're actual plans though 🥳 

I will give it a go with the alpha2 version down the road and report any issue/bug I may encounter :)

**Comment by lilic** [comment]
Thanks, looking forward to any reports!! Happy to leave the issue open until we ship beta to prevent other folks understand the timeline.

**Comment by mrueg** [comment]
v2.0.0 was released: https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0 :tada:
