### ISSUE TITLE
gcr.io/google_containers/kube-state-metrics image fails to run

### ISSUE THREAD

**Issue by mplzik** [kubernetes/kube-state-metrics#1296]
**What happened**:

$ docker run gcr.io/google_containers/kube-state-metrics:v1.9.5
standard_init_linux.go:219: exec user process caused: permission denied

**What you expected to happen**:

A successfully launched kube-state-metrics container (+- some errors caused by missing k8s config)

**How to reproduce it (as minimally and precisely as possible)**:

$ docker run gcr.io/google_containers/kube-state-metrics:v1.9.5
standard_init_linux.go:219: exec user process caused: permission denied

**Anything else we need to know?**:

The container in question has `kube-state-metrics` binary with following permissions:

```
-rwxr-x--- 0/0        30994432 2020-02-22 14:16 kube-state-metrics
```
This is despite of Dockerfile containing `USER nobody` stanza. This prevents any non-root user from actually launching the binary. This can be worked around in the kubernetes case by setting `fsGroup: 0`, but this increases attack surface.

When trying to build the container locally from the release-1.9 branch, the permissions were as expected (`-rwxr-xr-x`)

**Environment**:
- kube-state-metrics version: 1.9.5
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"archive", BuildDate:"2020-10-16T20:58:56Z", GoVersion:"go1.15.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: GCP/GKE
- Other info: N/A

**Comment by lilic** [comment]
Yes, this is a known issue as something went wrong when the folks built it, I don't have permission to fix it, but the quay image should work correctly or you can build it yourself and push to your own registry. The issue was fixed in newer versions of kube-state-metrics for gcr and it works correctly there and we have a build pipeline now so closing the issue, hope the info was helpful.
