### ISSUE TITLE
Pods metrics are not listed when all metrics are limited by --metric_allowlist/denylist, but listed when there is no limitation from --metric_allowlist/denylist

### ISSUE THREAD

**Issue by monikeu** [kubernetes/kube-state-metrics#1297]
**What happened**:
Deployed kube-state-metrics v 2.0.0-alpha.2, with the followng deployment configuration:
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
    app.kubernetes.io/version: 2.0.0-alpha.2
  name: kube-state-metrics
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-state-metrics
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-state-metrics
        app.kubernetes.io/version: 2.0.0-alpha.2
    spec:
      containers:
      - image: quay.io/coreos/kube-state-metrics:v2.0.0-alpha.2
        args:
          - '--telemetry-port=8081'
          **- '--metric-allowlist=pods,nodes'**
          - '--port=8080'
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          timeoutSeconds: 5
        name: kube-state-metrics
        ports:
        - containerPort: 8080
          name: http-metrics
        - containerPort: 8081
          name: telemetry
        readinessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 5
          timeoutSeconds: 5
        securityContext:
          runAsUser: 65534
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: kube-state-metrics

When looking up metrics listed by kube-state-metrics, pods metrics are missing, the ones visible are only:
\# HELP kube_poddisruptionbudget_status_expected_pods Total number of pods counted by this disruption budget
\# TYPE kube_poddisruptionbudget_status_expected_pods gauge
kube_poddisruptionbudget_status_expected_pods{namespace="kafka",poddisruptionbudget="my-cluster-zookeeper"} 1
kube_poddisruptionbudget_status_expected_pods{namespace="kafka",poddisruptionbudget="my-cluster-kafka"} 3

Looking at kube-state-metrics logs it looks like it picked up the --metrics-allowlist without problems:

[monikeu@localhost]$ kubectl logs -n kube-system kube-state-metrics-5bc957ddcd-4gprl
I1106 11:37:34.666448       1 main.go:95] Using default resources
I1106 11:37:34.666577       1 main.go:107] Using all namespace
**I1106 11:37:34.667001       1 main.go:128] metric allow-denylisting: Including the following lists that were on allowlist: pods, nodes**
W1106 11:37:34.667028       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1106 11:37:34.668149       1 main.go:234] Testing communication with server
I1106 11:37:34.673532       1 main.go:239] Running with Kubernetes cluster version: v1.18. git version: v1.18.3. git tree state: clean. commit: 2e7996e3e2712684bc73f0dec0200d64eec7fe40. platform: linux/amd64
I1106 11:37:34.673552       1 main.go:241] Communication with server successful
I1106 11:37:34.674012       1 main.go:197] Starting metrics server: 0.0.0.0:8080
I1106 11:37:34.674029       1 metrics_handler.go:96] Autosharding disabled
I1106 11:37:34.674134       1 main.go:186] Starting kube-state-metrics self metrics server: 0.0.0.0:8081
I1106 11:37:34.674563       1 builder.go:162] Active resources: certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,leases,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments

When removed - '--metric-allowlist=pods,nodes'  from deployment config of kube-state-metrics like below:
    ...
     spec:
      containers:
      - image: quay.io/coreos/kube-state-metrics:v2.0.0-alpha.2
        args:
          - '--telemetry-port=8081'
          - '--port=8080'
     ...

 pods metrics are visible: 

...
kube_pod_info{namespace="default",pod="my-cluster-kafka",host_ip="172.17.0.3",pod_ip="172.18.0.15",uid="09fac446-c1b0-4ee9-b9cc-843d06247212",node="minikube",created_by_
kind="<none>",created_by_name="<none>",priority_class="",host_network="false"} 1
kube_pod_info{namespace="kube-system",pod="kube-state-metrics-7cf5595f66-mjn4f",host_ip="172.17.0.3",pod_ip="172.18.0.5",uid="5f014eb6-aa09-4f91-a540-07e0cd5433db",node=
"minikube",created_by_kind="ReplicaSet",created_by_name="kube-state-metrics-7cf5595f66",priority_class="",host_network="false"} 1
kube_pod_info{namespace="default",pod="prometheus-prometheus-main-0",host_ip="172.17.0.3",pod_ip="172.18.0.14",uid="70b578db-2e0b-4871-ab89-82af6ab67738",node="minikube"
,created_by_kind="StatefulSet",created_by_name="prometheus-prometheus-main",priority_class="",host_network="false"} 1
kube_pod_info{namespace="kube-system",pod="kube-proxy-4m2jh",host_ip="172.17.0.3",pod_ip="172.17.0.3",uid="d86f076a-c839-4920-a758-c24406f6f866",node="minikube",created_
by_kind="DaemonSet",created_by_name="kube-proxy",priority_class="system-node-critical",host_network="true"} 1
kube_pod_info{namespace="kafka",pod="strimzi-cluster-operator-55595b6cf6-4zvbm",host_ip="172.17.0.3",pod_ip="172.18.0.6",uid="44a71f7e-aef8-4c0e-98d0-b3ff66d3acbf",node=
"minikube",created_by_kind="ReplicaSet",created_by_name="strimzi-cluster-operator-55595b6cf6",priority_class="",host_network="false"} 1
kube_pod_info{namespace="kube-system",pod="kube-controller-manager-minikube",host_ip="172.17.0.3",pod_ip="172.17.0.3",uid="702e1bc9-12d7-422f-a246-4cdb5e123a9f",node="mi
nikube",created_by_kind="Node",created_by_name="minikube",priority_class="system-cluster-critical",host_network="true"} 1
kube_pod_info{namespace="kube-system",pod="kube-scheduler-minikube",host_ip="172.17.0.3",pod_ip="172.17.0.3",uid="ee0c9f93-1680-46c6-b558-b74181b2ebe0",node="minikube",c
reated_by_kind="Node",created_by_name="minikube",priority_class="system-cluster-critical",host_network="true"} 1
kube_pod_info{namespace="kube-system",pod="storage-provisioner",host_ip="172.17.0.3",pod_ip="172.17.0.3",uid="844465d5-3b01-4b6e-8723-d0c1b1d3a58e",node="minikube",creat
ed_by_kind="<none>",created_by_name="<none>",priority_class="",host_network="true"} 1
kube_pod_info{namespace="kafka",pod="kafka-perf-consumer",host_ip="172.17.0.3",pod_ip="172.18.0.16",uid="44ad50e0-57af-405e-973a-6ef6fc59059c",node="minikube",created_by
_kind="<none>",created_by_name="<none>",priority_class="",host_network="false"} 1
kube_pod_info{namespace="kafka",pod="my-cluster-kafka-1",host_ip="172.17.0.3",pod_ip="172.18.0.10",uid="df4d5a6c-0d0c-4c5b-bb80-826b1817e390",node="minikube",created_by_
kind="StatefulSet",created_by_name="my-cluster-kafka",priority_class="",host_network="false"} 1
kube_pod_info{namespace="kafka",pod="my-cluster-entity-operator-7f4d57fd8b-qfhrk",host_ip="172.17.0.3",pod_ip="172.18.0.11",uid="bf23a279-d1e0-4836-9b65-12bc3d19844f",no
de="minikube",created_by_kind="ReplicaSet",created_by_name="my-cluster-entity-operator-7f4d57fd8b",priority_class="",host_network="false"} 1
kube_pod_info{namespace="kafka",pod="my-cluster-kafka-0",host_ip="172.17.0.3",pod_ip="172.18.0.8",uid="9ca114c2-a0a1-48e8-81d4-489df017bb31",node="minikube",created_by_k
ind="StatefulSet",created_by_name="my-cluster-kafka",priority_class="",host_network="false"} 1
kube_pod_info{namespace="kube-system",pod="etcd-minikube",host_ip="172.17.0.3",pod_ip="172.17.0.3",uid="69e3137c-2115-4a37-ac86-e37b99c353a1",node="minikube",created_by_
kind="Node",created_by_name="minikube",priority_class="system-cluster-critical",host_network="true"} 1
...

**What you expected to happen**:
Pods metrics are visible when using  '--metric-allowlist=pods,nodes'

**How to reproduce it (as minimally and precisely as possible)**:
Follow steps from above

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: v2.0.0-alpha.2
- Kubernetes version (use `kubectl version`):  (minikube)
kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration: N/A
- Other info: N/A

**Comment by lilic** [comment]
Thanks for the report! 

Did you want to see all metrics for pods and nodes resources only?

The flag says:

>       --metric-allowlist string          Comma-separated list of metrics to be exposed. This list comprises of exact metric names and/or regex patterns. The allowlist and denylist are mutually exclusive.

That flag is meant for specific metrics to be exposed and it accepts a regex pattern as well, to just do it for all resources you can just set the resources flag like this:
`--resources=pods,nodes`
