### ISSUE TITLE
Add reason label to HPA Status Condition

### ISSUE THREAD

**Issue by adammw** [kubernetes/kube-state-metrics#1299]
**What would you like to be added**:
Reason label for HPA Status Condition.

**Why is this needed**:
Current metric shows only status true/false for conditions, not their reason so you can't categorise why various HPAs are failing.

**Describe the solution you'd like**
New `reason` label key added to HPA Status Condition (and possibly other condition metrics) with the condition's reason added as the label value.

**Comment by lilic** [comment]
Hey @adammw! 👋  Are you talking about the `kube_horizontalpodautoscaler_status_condition` metric? Is there a known list of reasons of HPA? We tend to only allow a constant list of values in the reason metrics, if this exists for HPA, this feature request sgtm.

**Comment by adammw** [comment]
I don't believe a known list is documented, but the condition field is exclusively written by the HorizontalPodAutoscaler component of kube-controller-manager, which from reading the [source code](https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/podautoscaler/horizontal.go) I can see the following strings:

AbleToScale:
- FailedGetScale
- FailedUpdateScale
- ReadyForNewScale
- ScaleDownStabilized
- SucceededGetScale
- SucceededRescale

ScalingActive:
- FailedGetExternalMetric
- FailedGetObjectMetric
- FailedGetPodsMetric
- FailedGetResourceMetric
- InvalidMetricSourceType
- InvalidSelector
- ScalingDisabled
- ValidMetricFound

ScalingLimited:
- DesiredWithinRange
- ScaleDownLimit
- ScaleUpLimit
- TooFewReplicas
- TooManyReplicas

**Comment by adammw** [comment]
That being said, this is probably a generic thing that would need to be added to all resources with conditions and would not be trivial as the possible `reasons` are definitely unbounded.

**Comment by lilic** [comment]
Hey, this still sounds like a good feature request. Do you want to work on it?
