### ISSUE TITLE
Support pod guage metrics based on their statuses

### ISSUE THREAD

**Issue by aayushrangwala** [kubernetes/kube-state-metrics#1302]
**What would you like to be added**:

Need the support for a few more aggregated metrics based on the pod statuses. Like the guage metrices for evicted pods, completed pods, failed pods etc

**Why is this needed**:

It is really useful having those to be used for monitoring purposes

**Describe the solution you'd like**
We can use the same frameworks, caches and clients to just aggregate and export a few more metrics

**Comment by lilic** [comment]
Hey, thanks for the feature request, what kind of metrics specifcly did you have in mind? We already have `kube_pod_container_status_terminated_reason` which includes the reason why it was terminated and we have a list in the docs which ones we support:
> reason=<OOMKilled\|Error\|Completed\|ContainerCannotRun\|DeadlineExceeded\|Evicted>

See more metrics and docs here -> https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md

Can you describe which ones of those are missing to you, if possible we can add them!

**Comment by aayushrangwala** [comment]
@lilic  I came across a use case where I need to have the gauge metrics of evicted pods in all the namespaces, similarly, gauge metric for terminated pod, then metrics for the actual time taken between `Pending` to `Running` state, then from marked for deletion to actually deleted state. I have read the doc for pod metrics, I believe there are all good metrics but mostly not specific to a single status.

Let me know if this makes sense, I can start working on it

**Comment by lilic** [comment]
Thanks for clarifying, it might help to know what you want to achieve with those potential metrics, is it to write alerts or just have metrics for debugging, if you can clarify the use case? Thanks!

**Comment by aayushrangwala** [comment]
> Thanks for clarifying, it might help to know what you want to achieve with those potential metrics, is it to write alerts or just have metrics for debugging, if you can clarify the use case? Thanks!

Yes, I wanted to have export them to be consumed at signalfx and also to setup alerts

**Comment by brancz** [comment]
I think metrics like this make sense, but I don't think they are a great fit for kube-state-metrics, as kube-state-metrics only exposes metrics with a 1 to 1 mapping from the Kubernetes API.

Maybe we can create a new sub-project of SIG Instrumentation that fits this use-case better.

**Comment by aayushrangwala** [comment]
> I think metrics like this make sense, but I don't think they are a great fit for kube-state-metrics, as kube-state-metrics only exposes metrics with a 1 to 1 mapping from the Kubernetes API.
> 
> Maybe we can create a new sub-project of SIG Instrumentation that fits this use-case better.

Sounds Great!!! Please point me to a=move ahead if I can.

**Comment by lilic** [comment]
@brancz @aayushrangwala lets add this to the next SIG instrumentation discussion?

**Comment by brancz** [comment]
Sound good to me!

**Comment by lilic** [comment]
Added it to the agenda. @aayushrangwala if you are interested in taking part of it, here s the document https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#

**Comment by aayushrangwala** [comment]
> Added it to the agenda. @aayushrangwala if you are interested in taking part of it, here s the document https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#

Yes, I am definitely interested. Thanks
