### ISSUE TITLE
Provide alert on used api versions that are going to be deprecated

### ISSUE THREAD

**Issue by JorritSalverda** [kubernetes/kube-state-metrics#1303]
**What would you like to be added**:

A timeline serie that provides resources that use api versions that will be deprecated in a future version of Kubernetes.

**Why is this needed**:

We've been bitten many times by still using Kubernetes resources that have deprecated api versions. Even though it's already known a couple of versions before retiring the api version. Being able to alert on it before the actual upgrade happens would be very useful.

**Describe the solution you'd like**

A single timeline serie that has labels for 

- resource type
- resource api version
- resource name
- resource namespace
- version in which the api version will be deprecated

**Comment by lilic** [comment]
Hey, thanks for the feature request, but this project does not provide alerts out of the box, only metrics based on the Kubernetes APIs. I believe these metrics were added to the Kubernetes metrics recently https://kubernetes.io/blog/2020/09/03/warnings/#metrics so you can use those to create alerts, those do not originate from kube-state-metrics.

Let me know if there is something I misunderstood or if that answers your question.

**Comment by JorritSalverda** [comment]
Ah, thanks that's actually very useful, once we're on 1.19+. This is exactly what I was looking for.
