### ISSUE TITLE
kube_pod_container_resource_limits doesn't scrape

### ISSUE THREAD

**Issue by tide34** [kubernetes/kube-state-metrics#1305]
Thanks anyone for help!

**What happened**:
I'm a freshman in monitoring and I've installed kube-state-metrics container into my k8s cluster.
Also I've installed a container with seted up request/limit of resources. When i tried to scrape request/limit of the container resources i got only resource request metrics and can't got resource limit metrics. 
Request #1292 closed, but i'm still detecting this bug in my enviroument.

HELP kube_pod_container_resource_requests The number of requested request resource by a container.
TYPE kube_pod_container_resource_requests gauge
kube_pod_container_resource_requests{namespace="kube-system",pod="kube-controller-manager-emptylinux.localdomain",container="kube-controller-manager",node="emptylinux.localdomain",resource="cpu",unit="core"} 0.2
kube_pod_container_resource_requests{namespace="kube-system",pod="kube-apiserver-emptylinux.localdomain",container="kube-apiserver",node="emptylinux.localdomain",resource="cpu",unit="core"} 0.25
kube_pod_container_resource_requests{namespace="kube-system",pod="kube-scheduler-emptylinux.localdomain",container="kube-scheduler",node="emptylinux.localdomain",resource="cpu",unit="core"} 0.1
kube_pod_container_resource_requests{namespace="kube-system",pod="coredns-f9fd979d6-l7c7v",container="coredns",node="emptylinux.localdomain",resource="cpu",unit="core"} 0.1
kube_pod_container_resource_requests{namespace="kube-system",pod="coredns-f9fd979d6-l7c7v",container="coredns",node="emptylinux.localdomain",resource="memory",unit="byte"} 7.340032e+07
kube_pod_container_resource_requests{namespace="monitoring",pod="podname",container="alpine",node="emptylinux.localdomain",resource="memory",unit="byte"} 1.572864e+07
kube_pod_container_resource_requests{namespace="monitoring",pod="podname",container="alpine",node="emptylinux.localdomain",resource="cpu",unit="core"} 1
HELP kube_pod_container_resource_limits The number of requested limit resource by a container.
TYPE kube_pod_container_resource_limits gauge
HELP kube_pod_init_container_resource_requests_cpu_cores The number of CPU cores requested by an init container.
TYPE kube_pod_init_container_resource_requests_cpu_cores gauge
HELP kube_pod_init_container_resource_requests_memory_bytes Bytes of memory requested by an init container.
TYPE kube_pod_init_container_resource_requests_memory_bytes gauge
HELP kube_pod_init_container_resource_requests_storage_bytes Bytes of storage requested by an init container.
TYPE kube_pod_init_container_resource_requests_storage_bytes gauge
HELP kube_pod_init_container_resource_requests_ephemeral_storage_bytes Bytes of ephemeral-storage requested by an init container.
TYPE kube_pod_init_container_resource_requests_ephemeral_storage_bytes gauge
HELP kube_pod_init_container_resource_requests The number of requested request resource by an init container.

**What you expected to happen**:
kube_pod_container_resource_limits and kube_pod_container_resource_requests will be scraped as told documentations

**How to reproduce it (as minimally and precisely as possible)**:
1) run k8s cluster with latest version of API server; 
2) install kube-state-metrics container v2.0.0-alpha.2  version;
3) install any container with resource limit/request;
4) try to get resource request/limit metrics about this container use kube-state-metrics container.

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: v2.0.0-alpha.2 
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:09:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration:
- Other info:
 kube-apiserver: v1.19.4
 minikube version: v1.15.0

**Comment by lilic** [comment]
Hey, thanks for the issue, yes issue was closed as the PR was merged, we just have not cut the release (hopefully this week, if we merge another bug fix in time). But you can try the fix by building the image from the release-2.0 branch if you need the fix urgently. Let me know if you need any help around that.

**Comment by tide34** [comment]
Ok. I've built image with latest updates in kube-state-metrics server code and kube_pod_container_resource_limits really scraped successfully. Thank a lot for help!
