### ISSUE TITLE
Fix the high gocyclo  complexity setting

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#1306]
With the change to the podMetricFamilies and nodeMetricFamilies into a function, now our CI detected that cyclo complexity is too high, in case of the pod function it's 127. The temporary fix was that we just raised the allowed to 128 complexity.

See context in this PR https://github.com/kubernetes/kube-state-metrics/pull/1301/files#r526061712

We have a couple of options that I see:

1. Refactor the pod and node MetricFamilies functions to remove the complexity.
2. Disable testing the complexity as it might not apply to us.
3. Disable testing the complexity just for internal packages or specific files.

Other options or opinions more than welcome!

**Comment by lilic** [comment]
As discussed Damien is interested in taking this one.

/assign @dgrisonnet

**Comment by lilic** [comment]
Just to clarify, first option would be the most favorable. :) So refactoring both node and pod functions to decrease the cyclo complexity, let me know if anything is unclear!

**Comment by dgrisonnet** [comment]
:+1: it's very clear, thank you.
