### ISSUE TITLE
kube-state-metrics consuming too much cpu + memory for relatively small cluster

### ISSUE THREAD

**Issue by banDedo** [kubernetes/kube-state-metrics#1308]
**What happened**: We have currently deployed kube-state-metrics to several clusters and are seeing memory usage running relatively high (195MiB) for a single, relatively small cluster (two regions). Inspecting # of objects in cluster + numbers of metrics. Port-forwarding and inspecting metrics surfaced by this cluster reveals a response that is returned relatively quickly, with about 70,000 lines. Yesterday we redeployed v1.9.7 to both regions that were running hot and saw one region drop to memory utilization levels that look like other clusters that we have deployed to (80 MiB), but one region is still running at 195 MiB. I have attached pprof files from "good" and "bad" clusters for reference.

"GOOD":
![good pprof snapshot](https://user-images.githubusercontent.com/750729/99705883-55d63880-2a68-11eb-9e7b-62b6009d5cd6.png)
[good pprof txt](https://github.com/kubernetes/kube-state-metrics/files/5568830/expected.txt)

"BAD":
![bad pprof snapshot](https://user-images.githubusercontent.com/750729/99705874-5242b180-2a68-11eb-9145-ddf636125e5d.png)
[bad pprof txt](https://github.com/kubernetes/kube-state-metrics/files/5568828/actual.txt)

**What you expected to happen**: I would expect a small cluster like this to be running at about half memory utilization that it is.

**How to reproduce it (as minimally and precisely as possible)**: Unknown how to reproduce externally.

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: v1.9.7
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-gke.401", GitCommit:"eb94c181eea5290e9da1238db02cfef263542f5f", GitTreeState:"clean", BuildDate:"2020-09-09T00:57:35Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}`
- Cloud provider or hardware configuration: GCP (200MiB memory request + limit, 0.1 cpu request)
- Other info: -

**Comment by lilic** [comment]
Hey, thanks for the issue, but it seems like your cluster is not that small judging by the number of lines

> Port-forwarding and inspecting metrics surfaced by this cluster reveals a response that is returned relatively quickly, with about 70,000 lines.

Can you clarify what is a small cluster, two regions (not sure I understand what this is meant to be) can still have a lot of objects which can in turn produce a lot of metrics? Can you analyze instead which metric has the highest cardinality, as 70k lines of metrics seem like a lot for a small cluster.

**Comment by banDedo** [comment]
Thanks for following up on this. Even though the overall metrics count was lower than for other instances I found the issue. There was a much larger number of daemonsets for this cluster than others and lead to the higher consumption. Sorry for the false alarm. Thanks for everything that you do here - much appreciated!

**Comment by lilic** [comment]
@banDedo no problem, good to hear that! 😌  On that note don't feel hesitant to open issues in the future, even if its false alarms in the end! :)
