### ISSUE TITLE
Add feature to disable labels-allow-list

### ISSUE THREAD

**Issue by hoboroten** [kubernetes/kube-state-metrics#1309]
**What would you like to be added**:
The possibility to disable --labels-allow-list
**Why is this needed**:
There are situations, when users will want to have all the labels in metrics (even keeping in mind the cardinality issues). 
**Describe the solution you'd like**
It would be great to have something like --disable-labels-allow-list, set to "false" by default.

**Comment by lilic** [comment]
Hey! Thanks for the issue, we recently redesigned the labels-allow-list, it will be included in the next 2.0 release, see PR for more info https://github.com/kubernetes/kube-state-metrics/pull/1301

It now only affects, as it did before, the labels metrics e.g. kube_pod_labels{}. All other metrics have all labels allowed by default. The problem is not just unbound cardinality, but security as well, labels can contain sensitive information sometimes, so adding them to an allow list is a better approach than just allowing all. 

Can you explain why you cannot keep an allow list? Do you have too many labels on your resources? What are some use cases around k8s label metrics, etc. Thanks!

**Comment by hoboroten** [comment]
Thanks for the reply.

**Comment by hoboroten** [comment]
Thanks for the reply. In my case we have several different projects, located in different infrastructures (aws, eks, on-premise servers with k8s). So far, we had rather identical monitoring system thus simplifying deployment and maintenance. 
Most of monitoring filters are based on labels from kube_*_labels metrics. Such an approach gives great versatility, because:
- different environments generate different type of labels. Even k8s and software upgrades, sometimes. lead to such situation. Having all set of labels in one place (kube_*_labels metrics) allows to quickly adapt the monitoring on grafana dashboards level.
- labelling pod, nodes and other resources on the run is another useful instrument, because in most cases it's not causing restarts and do not need additional configuration of the infrastructure. 

And everything can be easily controlled and automated, because you know that all labels will be in one specific metric.
So the need to enable label list explicitly nullifies all the profits of such approach. Of course, we can try and find another metrics, which will be "stable" in different environment, having all the labels for the pod or node resource, for example. 
But in fact - it would become another "kube_*_labels@ metrics, with just different name and same cardinality and security issues.

And speaking of security issues - having the ability to give a user rights only to label resources and operate on dashboard level, IMHO, gives more control and stabilize the infrastructure, rather than having the need to configure that label list manually.
All the sensitive information in labels (is such exist) can be easily dropped on scrape/relabelling level.

**Comment by lilic** [comment]
Thanks for the use cases! Makes sense, right now we are closing in on releasing v2.0 as a stable release, so this will most likely not make it to 2.0, but we can come back to it in v2.1, just for your information.

> All the sensitive information in labels (if such exists) can be easily dropped on scrape/relabelling level.

I believe this might be trickier, as you need to know which ones they are to deny, allowing is a much easier approach from a security standpoint. But if enough users find this to be the approach for them, we can add a flag that allows all flags, which would not do that by default turned on. Maybe have a look at https://github.com/kubernetes/kube-state-metrics/issues/1246 I believe its the same feature request tehre.
