### ISSUE TITLE
Tag (`v2.0.0-alpha.3`) in examples/standard deployment image doesn't exist

### ISSUE THREAD

**Issue by benraskin92** [kubernetes/kube-state-metrics#1311]
**What happened**: When deploying kube state metrics deployment using the manifest in examples/standard, it fails because `quay.io/coreos/kube-state-metrics:v2.0.0-alpha.3` doesn't exist. However, using the tag `v2.0.0-alpha.2` works.

**What you expected to happen**: I would expect the example manifest to work.

**How to reproduce it (as minimally and precisely as possible)**: Deploy the example deployment manifest in a Kube cluster -- minikube in my case.

**Anything else we need to know?**: The tag `v2.0.0-alpha.2` exists, but not `v2.0.0-alpha.3`.

**Environment**:
- kube-state-metrics version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:

**Comment by lilic** [comment]
Oops sorry about that, will push the image today, it's a manual process for now and seems like I forgot that step during the release on Friday. Thanks for reporting!

**Comment by lilic** [comment]
@benraskin92 the image should exist now, can you double check it works for you?

**Comment by benraskin92** [comment]
Looks good! Thanks!
