### ISSUE TITLE
kube-state-metrics not serving metrics anymore but not failing

### ISSUE THREAD

**Issue by zhujik** [kubernetes/kube-state-metrics#1314]
**What happened**:
On multiple occasions, it happened that kube-state-metrics was not serving metrics anymore, but was still running and reported as ready. Prometheus reported the target as down, error message being "context deadline exceeded".
Performing a rollover of the kube-state-metrics pod fixes the issue.

The logs offered by kube-state-metrics are sparse. Here is the only log output of the pod (for reference, the pod was not serving metrics starting on 24-11-2020 1:04:00 until the rollover to the new pod):

```
> klogs prometheus-kube-state-metrics-cb76d8fbb-95425
I1124 13:24:45.554306       1 main.go:89] Using collectors certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
I1124 13:24:45.554379       1 main.go:98] Using all namespace
I1124 13:24:45.554399       1 main.go:139] metric white-blacklisting: blacklisting the following items:
W1124 13:24:45.554611       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1124 13:24:45.555810       1 main.go:184] Testing communication with server
I1124 13:24:45.563876       1 main.go:189] Running with Kubernetes cluster version: v1.18+. git version: v1.18.8-eks-7c9bda. git tree state: clean. commit: 7c9bda52c425d0d56d7b93f1377a826b4132c05c. platform: linux/amd64
I1124 13:24:45.563907       1 main.go:191] Communication with server successful
I1124 13:24:45.564129       1 main.go:225] Starting metrics server: 0.0.0.0:8080
I1124 13:24:45.564170       1 main.go:200] Starting kube-state-metrics self metrics server: 0.0.0.0:8081
I1124 13:24:45.564220       1 metrics_handler.go:96] Autosharding disabled
I1124 13:24:45.564763       1 builder.go:146] Active collectors: certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
I1125 16:53:52.068100       1 trace.go:116] Trace[2108188917]: "Reflector ListAndWatch" name:pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108 (started: 2020-11-25 16:53:39.337492631 +0000 UTC m=+98933.795472938) (total time: 12.730560538s):
Trace[2108188917]: [12.728624549s] [12.728624549s] Objects listed
E1125 17:03:43.123371       1 reflector.go:320] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to watch *v1.Pod: Get https://10.100.0.1:443/api/v1/pods?allowWatchBookmarks=true&resourceVersion=82841561&timeout=6m0s&timeoutSeconds=360&watch=true: dial tcp 10.100.0.1:443: connect: connection refused
E1125 17:03:43.123490       1 reflector.go:320] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to watch *v1beta1.CertificateSigningRequest: Get https://10.100.0.1:443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests?allowWatchBookmarks=true&resourceVersion=82841560&timeout=5m16s&timeoutSeconds=316&watch=true: dial tcp 10.100.0.1:443: connect: connection refused
E1125 17:03:43.125843       1 reflector.go:320] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to watch *v1.Service: Get https://10.100.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=82841560&timeout=6m38s&timeoutSeconds=398&watch=true: dial tcp 10.100.0.1:443: connect: connection refused
E1125 17:03:43.125974       1 reflector.go:320] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to watch *v1.Endpoints: Get https://10.100.0.1:443/api/v1/endpoints?allowWatchBookmarks=true&resourceVersion=82845071&timeout=5m16s&timeoutSeconds=316&watch=true: dial tcp 10.100.0.1:443: connect: connection refused
E1125 17:03:43.126127       1 reflector.go:320] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to watch *v1.ValidatingWebhookConfiguration: Get https://10.100.0.1:443/apis/admissionregistration.k8s.io/v1/validatingwebhookconfigurations?allowWatchBookmarks=true&resourceVersion=82841560&timeout=8m56s&timeoutSeconds=536&watch=true: dial tcp 10.100.0.1:443: connect: connection refused
E1125 17:03:43.129399       1 reflector.go:320] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to watch *v1.Namespace: Get https://10.100.0.1:443/api/v1/namespaces?allowWatchBookmarks=true&resourceVersion=82841560&timeout=6m28s&timeoutSeconds=388&watch=true: dial tcp 10.100.0.1:443: connect: connection refused
E1125 17:16:39.608304       1 reflector.go:320] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to watch *v1.Service: Get https://10.100.0.1:443/api/v1/services?allowWatchBookmarks=true&resourceVersion=82841560&timeout=5m47s&timeoutSeconds=347&watch=true: dial tcp 10.100.0.1:443: connect: connection refused
```

Grafana reports a higher than normal CPU load from that very moment on: 

![image](https://user-images.githubusercontent.com/31599908/100333088-77887000-2fd2-11eb-96b9-234f1fe9ceaf.png)

**What you expected to happen**:
If kube-state-metrics reaches a state where it cannot gather metrics anymore, we expect the readiness and liveness probe to fail and the pod to restart. At least some error messages should be shown to further debug the issue

**How to reproduce it (as minimally and precisely as possible)**:
No idea.

**Environment**:
- kube-state-metrics version: quay.io/coreos/kube-state-metrics:v1.9.7
- Kubernetes version (use `kubectl version`): v1.18.9-eks-d1db3c
- Cloud provider or hardware configuration: AWS EKS
- Other info: -

**Comment by lilic** [comment]
Thanks @zhujik for the report, have not seen this issue myself but will have a look to see what we can do. Did any of the kube-state-metrics own alerts fire https://github.com/kubernetes/kube-state-metrics/blob/master/examples/prometheus-alerting-rules/alerts.yaml?

**Comment by zhujik** [comment]
Hi @lilic,
thank you for your reply. I haven't seen those alerts yet (they are not mentioned in the readme), I will try to integrate them and see if they fire next time. However, I have trouble using the kube-state-metrics self-exposed metrics as describe in the README.md. As far as I can see, on none of our clusters the metrics described in README.md are served. I also noticed that the port that is expected to serve them (8081) is not exposed in the offical helm charts that prometheus uses to deploy kube-state-metrics (https://github.com/helm/charts/blob/master/stable/kube-state-metrics/templates/deployment.yaml). I see that in in a example kubernetes deployment yaml in this repository port 8081 is exposed. This seems to be a bug in the helm charts of kube-state-metrics provided in the helm/stable repository. As this repository is EOL since Nov 13th, I question how this can be remedied without having to deploy kube-state-metrics manually instead with Prometheus. Any advice?

**Comment by lilic** [comment]
Good point about them not being part of the README, we only mention [metrics](https://github.com/kubernetes/kube-state-metrics#kube-state-metrics-self-metrics). Would you be willing to contribute mentioning that there are alerts we recommend? No worries if not, still good idea!

Sorry, I do know much about helm chart, I don't maintain that, might be better to ask folks who are maintainers of that chart. I think @tariq1890 is/was? But agreed its a bug in the helm chart, there is a PR to add the helm chart to this repo maybe ask the folks who are adding that? https://github.com/kubernetes/kube-state-metrics/pull/1237

**Comment by philnate** [comment]
@lilic I'm seeing the same issue with one of our clusters. Should I log a new ticket or can we reopen this one?
