### ISSUE TITLE
Failed to list *v1.ReplicaSet: proto: wrong wireType = 2 for field ReadOnly

### ISSUE THREAD

**Issue by daxwang** [kubernetes/kube-state-metrics#1316]
env:
kube-state-metrics:   v.1.9.7
kubernetes: v1.18.4

error info:
reflector.go:108: Failed to list *v1.ReplicaSet: proto: wrong wireType = 2 for field ReadOnly
E1130 12:46:35.247846       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ReplicaSet: proto: wrong wireType = 2 for field ReadOnly
E1130 12:46:36.261912       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ReplicaSet: proto: wrong wireType = 2 for field ReadOnly

how fix this?

**Comment by lilic** [comment]
Hello @daxwang can you provide a bit more info on how to reproduce this, full logs and can you provide the ReplicaSet that failed to list? Also if you can provide your deployment and RBAC manifests, might be easier to reproduce, thanks! Any other info would be helpful as well! Thanks for the bug report, interesting!

**Comment by daxwang** [comment]
> Hello @daxwang can you provide a bit more info on how to reproduce this, full logs and can you provide the ReplicaSet that failed to list? Also if you can provide your deployment and RBAC manifests, might be easier to reproduce, thanks! Any other info would be helpful as well! Thanks for the bug report, interesting!

no more useful messages, here is log:
I1130 14:02:57.580191       1 main.go:86] Using default collectors
I1130 14:02:57.580235       1 main.go:98] Using all namespace
I1130 14:02:57.580245       1 main.go:139] metric white-blacklisting: blacklisting the following items:
I1130 14:02:57.581748       1 main.go:184] Testing communication with server
I1130 14:02:57.589417       1 main.go:189] Running with Kubernetes cluster version: v1.18+. git version: v1.18.4-tke.3.
git tree state: clean. commit: f8797eb035aca9c928af02ea9a74d232cfd41bc6. platform: linux/amd64
I1130 14:02:57.589436       1 main.go:191] Communication with server successful
I1130 14:02:57.589535       1 main.go:225] Starting metrics server: 0.0.0.0:8080
I1130 14:02:57.589662       1 metrics_handler.go:96] Autosharding disabled
I1130 14:02:57.590024       1 builder.go:146] Active collectors: certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
I1130 14:02:57.590224       1 main.go:200] Starting kube-state-metrics self metrics server: 0.0.0.0:8082
E1130 14:02:57.681447       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ReplicaSet: proto: wrong wireType = 2 for field ReadOnly
E1130 14:02:58.746007       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ReplicaSet: proto: wrong wireType = 2 for field ReadOnly
E1130 14:02:59.759247       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1.ReplicaSet: proto: wrong wireType = 2 for field ReadOnly

**Comment by lilic** [comment]
@daxwang thanks, this error happens straight away after deploying kube-state-metrics, can you share the deployment manifest file and the ClusterRole it has.
