### ISSUE TITLE
kube_state_metrics_list_total metrics are not exported

### ISSUE THREAD

**Issue by dbluxo** [kubernetes/kube-state-metrics#1317]
**What happened**:

Installed kube-state-metrics and the `kube_state_metrics_list_total` and `kube_state_metrics_watch_total` metrics are missing. The are needed for the predefined Prometheus alerts `KubeStateMetricsListErrors` and `KubeStateMetricsWatchErrors`.

**What you expected to happen**: Present `kube_state_metrics_list_total` and `kube_state_metrics_watch_total` metrics.

**How to reproduce it (as minimally and precisely as possible)**: Install [kube-prometheus-stack](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack) Helm Chart with default values.

**Anything else we need to know?**: kube-state-metrics runs with the following args:

```
    Args:
      --collectors=certificatesigningrequests
      --collectors=configmaps
      --collectors=cronjobs
      --collectors=daemonsets
      --collectors=deployments
      --collectors=endpoints
      --collectors=horizontalpodautoscalers
      --collectors=ingresses
      --collectors=jobs
      --collectors=limitranges
      --collectors=mutatingwebhookconfigurations
      --collectors=namespaces
      --collectors=networkpolicies
      --collectors=nodes
      --collectors=persistentvolumeclaims
      --collectors=persistentvolumes
      --collectors=poddisruptionbudgets
      --collectors=pods
      --collectors=replicasets
      --collectors=replicationcontrollers
      --collectors=resourcequotas
      --collectors=secrets
      --collectors=services
      --collectors=statefulsets
      --collectors=storageclasses
      --collectors=validatingwebhookconfigurations
      --collectors=volumeattachments
```

**Environment**:
- kube-state-metrics version: `v1.9.7`
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
`
- Cloud provider or hardware configuration: AWS

In which cases should these metrics be exported?

**Comment by underrun** [comment]
this is not just a problem with the helm chart - it's also an issue with jsonnet via kube-prometheus

**Comment by mrmartan** [comment]
Although we are not using `kube-prometheus-stack` yet the linked #1343 would solve the self-metrics problem for us. We are using the [prometheus](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus) chart.
