### ISSUE TITLE
go/src/k8s.io/kube-state-metrics/vendor/k8s.io/utils/trace/trace.go:200:119: totalTime.Milliseconds undefined (type time.Duration has no field or method Milliseconds)

### ISSUE THREAD

**Issue by arkastratuscent** [kubernetes/kube-state-metrics#1318]
sudo go get k8s.io/kube-state-metrics
# k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/errors
go/src/k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/errors/errors.go:99:10: undefined: errors.Is
# k8s.io/kube-state-metrics/vendor/sigs.k8s.io/structured-merge-diff/v4/value
go/src/k8s.io/kube-state-metrics/vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go:95:13: val.MapRange undefined (type reflect.Value has no field or method MapRange)
go/src/k8s.io/kube-state-metrics/vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go:173:14: rhs.MapRange undefined (type reflect.Value has no field or method MapRange)
go/src/k8s.io/kube-state-metrics/vendor/sigs.k8s.io/structured-merge-diff/v4/value/mapreflect.go:194:13: lhs.MapRange undefined (type reflect.Value has no field or method MapRange)
# k8s.io/kube-state-metrics/vendor/k8s.io/utils/trace
go/src/k8s.io/kube-state-metrics/vendor/k8s.io/utils/trace/trace.go:200:119: totalTime.Milliseconds undefined (type time.Duration has no field or method Milliseconds)
# k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/net
go/src/k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/net/http.go:66:5: undefined: errors.As
go/src/k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/net/http.go:83:5: undefined: errors.As
go/src/k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/net/util.go:43:5: undefined: errors.As
go/src/k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/net/util.go:52:5: undefined: errors.As

**Environment**:
- kube-state-metrics version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:
go version go1.10.4 linux/amd64

**Comment by brancz** [comment]
You are using a very old version of go. Please use the releases we publish. If you build by yourself with an outdated go version, then you're on your own.

**Comment by lilic** [comment]
As Frederic said, you need to update your version of go, if you run into problems after update feel free to open a new issue, thanks!

**Comment by arkastratuscent** [comment]
Thanks for the update guys.
