### ISSUE TITLE
Increase polling frequency for resourcequota

### ISSUE THREAD

**Issue by kamok** [kubernetes/kube-state-metrics#1319]
**What happened**:
I set up kube-state-metrics with New Relic. Time series data work for other metrics, but for resource quota specifically, reporting is very sporadic:
![image](https://user-images.githubusercontent.com/9758567/100923020-97c19e80-34ac-11eb-8f69-420f9645af92.png)

You can see in the screenshot, it updates sometimes between 1 hr, or two hr, or 3 hr. Seemingly random. 

**What you expected to happen**:
I'd like to be able to quota data every 15 minutes.

**Environment**:
- kube-state-metrics version: quay.io/coreos/kube-state-metrics:v1.9.5
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15+IKS", GitCommit:"1285edff05f9e3b46bfae11ed016c68d34662f00", GitTreeState:"clean", BuildDate:"2020-11-11T16:23:52Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: IBM Cloud
- Other info:

**Comment by lilic** [comment]
Hey @kamok, there is a newer version of kube-state-metrics out 1.9.7 you might want to consider updating.

Not familiar with new relic, but can you provide a regular dump of the /metrics endpoint, did anything change for the resource quota during that time, did kube-state-metrics not reflect that state? If you try creating a new resource quota object in your cluster does that get reflected correctly in the /metrics endpoint of kube-state-metrics?

With that being said there is no difference between the resources update or polling frequency, its the same across all resources.
