### ISSUE TITLE
Getting deployment object label in Prometheus alert rules

### ISSUE THREAD

**Issue by KR411-prog** [kubernetes/kube-state-metrics#1320]
Is there a way to show deployment object label in prometheus alert rules?

I have a deployment object label set as teamname=teamA I want to show this label in KubeDeploymentReplicasMismatch alert.

**I could do the same for pods related alerts by modifying expression with,**
```

 * on(namespace,
  pod) group_left(label_axway_com_team) kube_pod_labels
```

I am unable to do the same for deployment object related alerts..
**I have found using kube_deployment_labels help..

However the below expression is only showing the results of deployment objects that does not have the label.The same expression works for pods when I use Kube_pod_labels..**
```

(kube_deployment_spec_replicas{job="kube-state-metrics",namespace=~".*"}
  != kube_deployment_status_replicas_available{job="kube-state-metrics",namespace=~".*"})
  and (changes(kube_deployment_status_replicas_updated{job="kube-state-metrics",namespace=~".*"}[5m])
  == 0) * on (deployment,namespace) group_left(label_axway_com_team) kube_deployment_labels 
```

What is the issue with this command?

**Comment by lilic** [comment]
Hello @KR411-prog which version of kube-state-metrics are you using? What is the result of kube_deployment_labels metric directly does it contain that label to start with?

**Comment by KR411-prog** [comment]
We are using Kubernetes 1.15 EKS..yes.. kube_deployment_labels metric  contains those labels

**Comment by KR411-prog** [comment]
This has worked for me..
```
(kube_deployment_spec_replicas{job="kube-state-metrics",namespace=~".*"} * on (deployment,namespace) group_left(label_axway_com_team) kube_deployment_labels
  != kube_deployment_status_replicas_available{job="kube-state-metrics",namespace=~".*"}* on (deployment,namespace) group_left(label_axway_com_team) kube_deployment_labels)
  and (changes(kube_deployment_status_replicas_updated{job="kube-state-metrics",namespace=~".*"}[5m])
  == 0)* on (deployment,namespace) group_left(label_axway_com_team) kube_deployment_labels
```
