### ISSUE TITLE
Duplicate/useless series kube_pod_container_status_waiting_reason？

### ISSUE THREAD

**Issue by vsxen** [kubernetes/kube-state-metrics#1321]
the pod had running, but still have `kube_pod_container_status_waiting_reason` ?
```
kube_pod_container_status_running{namespace="default",pod="nginx-7b676545bc-9prql",container="nginx"} 1

kube_pod_container_status_waiting_reason{namespace="default",pod="nginx-7b676545bc-9prql",container="nginx",reason="ContainerCreating"} 0
kube_pod_container_status_waiting_reason{namespace="default",pod="nginx-7b676545bc-9prql",container="nginx",reason="CrashLoopBackOff"} 0
kube_pod_container_status_waiting_reason{namespace="default",pod="nginx-7b676545bc-9prql",container="nginx",reason="CreateContainerConfigError"} 0
kube_pod_container_status_waiting_reason{namespace="default",pod="nginx-7b676545bc-9prql",container="nginx",reason="ErrImagePull"} 0
kube_pod_container_status_waiting_reason{namespace="default",pod="nginx-7b676545bc-9prql",container="nginx",reason="ImagePullBackOff"} 0
kube_pod_container_status_waiting_reason{namespace="default",pod="nginx-7b676545bc-9prql",container="nginx",reason="CreateContainerError"} 0
kube_pod_container_status_waiting_reason{namespace="default",pod="nginx-7b676545bc-9prql",container="nginx",reason="InvalidImageName"} 0

```

**Comment by lilic** [comment]
Hey! Thanks for the issue but it seems the kube_pod_container_status_waiting_reason value is 0, not 1, so the count seems correct? Can you explain what kind of feature request you would like more in detail here, thanks!

**Comment by vsxen** [comment]
I see `kube_pod_container_status_waiting_reason`  is  `Top 10 series count by metric names` in prometheus

**Comment by vsxen** [comment]
ping @lilic

**Comment by lilic** [comment]
@vsxen busy times, thanks for reping :) 

Sorry to hear this metric is your top series count, this would be not correct approach as it means you can no longer reliably do ratios for example the following would just not return any results then:

`sum(kube_pod_container_status_waiting_reason{reason="ContainerCreating"})`

Hope that is what you meant, let me know if I misunderstood. You can always use the following flag to remove these metrics if its causing you problems:
>       --metric-denylist string            Comma-separated list of metrics not to be enabled. This list comprises of exact metric names and/or regex patterns. The allowlist and denylist are mutually exclusive.

**Comment by vsxen** [comment]
can I drop it in prometheus?
I search with google but nothing find.

**Comment by lilic** [comment]
I would suggest to use the flag provided above and this metric will not be even available to be scrapped. Otherwise, you can look at https://prometheus.io/docs/prometheus/latest/configuration/configuration/#metric_relabel_configs but just denying this metric would be better.

**Comment by vsxen** [comment]
I had used metric_relabel_configs but do not work .Thank  you I will try `--metric-denylist` .close it.

**Comment by smarterclayton** [comment]
On a moderate sized production cluster, the various "kube_pod_*_container_*_reason" metrics are roughly 200k total series (out of 2.1m, so ~10%) and only around 10k of those series are value 1 (there can be only one reason).

Reason is a fairly useful metric, but having `O(pods * reasons * containers_per_pod * states_per_pod)` cardinality is rough.  Is there a reason the 0  value is returned other than "convention"?  In practice this should change fairly infrequently once pods reach terminal state (a large contingent of the 10k are terminal pods).

**Comment by vsxen** [comment]
reopen it ?

**Comment by smarterclayton** [comment]
Lili's out - when she gets back I want to have her think through it before we re-open.  I'm fine waiting for that until she gets a chance.

**Comment by lilic** [comment]
@smarterclayton as mentioned above, we could not do ratios reliable, hence the need for the 0 values.

Yes, this could be an issue if the metric is needed. We have two options from what I can see:
1. either change the original suggestion to skip value is 0, but this would prove a problem when trying to do `sum` operations.
2. or we can as @simonpasquier suggested adding the reason as a label instead of as metric name, this could reduce the cardinality. But we have not looked if existing alerts can work this way.

We could have both options, and the user picks which ever one fits their use case, and by default exclude one. So you would have existing metric as is, as well as the 2. option.

@smarterclayton @vsxen what would be a good cardinality for this metric here, so we know what to aim for?

cc @brancz @tariq1890 for any other ideas.

**Comment by smarterclayton** [comment]
The tough issue with ratios and sums is that if we really needed them we could join on any number of other metrics or totals (count of containers, count of states) equally well (fold all of that into a pod container total).  A lot of interesting metrics today are `O(pods)`, but could be `O(failing pods)` or `O(features)`.  We seem to be increasing the number of interesting metrics quickly - if we expect that continue there may be a pattern missing beyond just "disablement" which is "exclude zero values" or "exclude uninteresting values".

Certainly for this metric being able to count by unique reasons is valuable, but there are way more reasons than just the expected list anyway (expecting there to only be 6 is dropping signal - reasons are unbounded), so I'd find `O(pods_containers_with_non_zero_reasons * unique_container_reasons)` more appealing than the current setup.  The metrics and alerts have value, but I'm not sure that it's reasonable for any component to potentially have `O(pods * metrics * interior cardinality)` series if metrics is growing and interior cardinality is growing.  Admittedly, in pathological clusters interesting series will approach this bound anyway, but that may just speak to the need for dynamic series reduction (have k-s-m work react to a budget of series generated).

**Comment by lilic** [comment]
We reworked these metrics in 2.0 which is out so closing issue, @vsxen if you have any more problems feel free to open a new issue, thank you!
