### ISSUE TITLE
error at run "helm repo add kube-state-metrics https://kubernetes.github.io/kube-state-metrics"

### ISSUE THREAD

**Issue by jingzhao-self** [kubernetes/kube-state-metrics#1331]
**What happened**: 
# helm repo add kube-state-metrics https://kubernetes.github.io/kube-state-metrics
Error: Looks like "https://kubernetes.github.io/kube-state-metrics" is not a valid chart repository or cannot be reached: Failed to fetch https://kubernetes.github.io/kube-state-metrics/index.yaml : 404 Not Found

**What you expected to happen**:
# helm repo add kube-state-metrics https://kubernetes.github.io/kube-state-metrics
"kube-state-metrics" has been added to your repositories

**How to reproduce it (as minimally and precisely as possible)**:
i guess https://kubernetes.github.io/kube-state-metrics/index.yaml is out of line.

**Anything else we need to know?**:

**Environment**: 
- helm3 version
version.BuildInfo{Version:"v3.4.0", GitCommit:"7090a89efc8a18f3d8178bf47d2462450349a004", GitTreeState:"clean", GoVersion:"go1.14.10"}

**Comment by lilic** [comment]
See this comment here for further explanation. https://github.com/kubernetes/kube-state-metrics/pull/1329#issuecomment-747843662

**Comment by Lord-Y** [comment]
Any update?

**Comment by jingzhao-self** [comment]
right now the charts/kube-state-metrics is still stick in the v1.9.7 [version](https://github.com/kubernetes/kube-state-metrics/blob/master/charts/kube-state-metrics/Chart.yaml#L10). If this version is fine for your k8s version, you could:
`
helm repo add https://charts.helm.sh/stable
helm repo update
helm search repo -l kube-state-metrics
`
BTW: the version relationship seems like this:
![image](https://user-images.githubusercontent.com/60691314/103056748-c5e05d00-45d8-11eb-9faf-edeba382b8c3.png)

**Comment by kferrone** [comment]
Why is this closed? The issue still persists . . .
