### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by matti** [kubernetes/kube-state-metrics#1340]
```
helm install prometheus prometheus-community/prometheus
```

runs `quay.io/coreos/kube-state-metrics:v1.9.7` which is not a `kubernetes.io/arch=arm64` compatible

**Comment by lilic** [comment]
Hello! We have added image support for all arch from v2.0.0 onwards, which is currently in beta, until then you need to build the images yourself for previous versions.

**Comment by oldthreefeng** [comment]
any update? 

Is there ways to build arm64 images ?

**Comment by mrueg** [comment]
As Lili had mentioned, kube-state-metrics 2.0 and later are providing multiarch and can be used on arm64.

**Comment by oldthreefeng** [comment]
https://github.com/kubernetes/kube-state-metrics/pull/1391 this seems to support mutli arch by v1.9.8 ?

**Comment by oldthreefeng** [comment]
@mrueg thanks for your reply.  is there any ways i can build arm64 local ?  or some docs?

**Comment by mrueg** [comment]
you are correct 1.9.8 got it as well. You can take a look at the Makefile, we have different container build targets there.
