### ISSUE TITLE
kube-state-metrics-helm-chart-2.9.7 - yaml: control characters are not allowed

### ISSUE THREAD

**Issue by PookiPok** [kubernetes/kube-state-metrics#1348]
when trying to use the kube-state-metrics-helm-chart-2.9.7  getting the follow error:
Error: failed to parse kube-state-metrics-2.9.7.tgz: error converting YAML to JSON: yaml: control characters are not allowed

is this a bug?
Gil

**Comment by PookiPok** [comment]
helm version Version:"v3.3.4", running on mac

**Comment by mrueg** [comment]
Thanks for reaching out.
The helm chart moved over to https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics Feel free to open an issue there if this issue still persists with the latest version.
