### ISSUE TITLE
I want to get the usage rate value of persistent volume in the numerator / denominator format.

### ISSUE THREAD

**Issue by vdi-kakui** [kubernetes/kube-state-metrics#1349]
I want to get the usage rate value of persistent volume in the numerator / denominator format.

I want to get the usage value of persistent volume in prometheus in numerator / denominator format.

How can I get the metric by writing promql?

**Comment by lilic** [comment]
Hello, these are not bugs :) there are more support questions, so please use that label next time, thanks! 🙇‍♀️ 

We have metrics around PV yes https://github.com/kubernetes/kube-state-metrics/blob/master/docs/persistentvolume-metrics.md but only around capacity, to me it sounds like you would need more detailed metrics this would be provided by the storage native metrics itself, for this best ask SIG storage team.

**Comment by brancz** [comment]
The kubelet's `/metrics` endpoint exposes volume usage metrics.

Closing, but feel free to continue to ask questions should you have any.
