### ISSUE TITLE
docker image not available for v0.5.0

### ISSUE THREAD

**Issue by jeremyd** [kubernetes/kube-state-metrics#135]
Trying to run the latest deployment.yml in kube and getting image pull errors for gcr.io/google_containers/kube-state-metrics:v0.5.0  not found.

**Comment by andyxning** [comment]
@jeremyd See #134 for more info. We just have update the version info and waiting for Google people to build and push to gcr for now. :)

**Comment by cemo** [comment]
This is pretty much interesting that still image is not published. Any problem?

**Comment by javapapo** [comment]
+1 the image is still not out :(

**Comment by brancz** [comment]
We (CoreOS) are also maintaining images of kube-state-metrics hosted on quay.io, that already has the v0.5.0 image. https://quay.io/repository/coreos/kube-state-metrics?tag=latest&tab=tags Feel free to use this mirror, we will be keeping it up to date and as we (the kube-state-metrics maintainers) don't have access to the google image registry, it may change to become the primary source of distribution, but that will have to be discussed in sig-instrumentation. I will bring it up in the next meeting.

**Comment by javapapo** [comment]
Many thanks!

**Comment by bksteiny** [comment]
Hey @brancz - do you think it would be possible to cut a new release since it's been a while since the previous one? Pulls #151 and #131 are particularly important for a project I'm working on. I could build and host on our own registry, but ideally we'd use what's available either on quay.io or gcr.io

Thanks in advance

BTW- v0.5.0 is on gcr.io now, so this issue can most likely be closed

**Comment by brancz** [comment]
Thanks for the notice @bksteiny we're actually attempting GA (aka 1.0) release of kube-state-metrics. So the release is coming up as soon as we can, but it's coming! :slightly_smiling_face:

**Comment by bksteiny** [comment]
Thanks for the info, @brancz. Do you have a rough timeline on when you think 1.0 will be available? If it won't be for at least a month, we may need to host on our own registry for the time being to meet our deadline.

**Comment by brancz** [comment]
@bksteiny I'm certain it won't happen before the end of next week. If all goes well _maybe_ Friday.
