### ISSUE TITLE
Drift between Container Running StartedAt state and Pod Ready Time

### ISSUE THREAD

**Issue by karthequian** [kubernetes/kube-state-metrics#1350]
**What happened**:
I was looking at my kube-state-metrics pod for some timing information and noticed that my Pod Ready time shown in the Status was very different from the Container Ready Time shown in the Container status.

```
            "status":{
              "conditions":[
                {
                  "lastTransitionTime":"2020-11-12T16:12:29+00:00",
                  "status":"True",
                  "type":"Initialized"
                },
                {
                  "lastTransitionTime":"2020-11-22T03:27:43+00:00",
                  "status":"True",
                  "type":"Ready"
                },
                {
                  "lastTransitionTime":"2020-11-22T03:27:43+00:00",
                  "status":"True",
                  "type":"ContainersReady"
                },
                {
                  "lastTransitionTime":"2020-11-12T16:12:29+00:00",
                  "status":"True",
                  "type":"PodScheduled"
                }
              ],
              "containerStatuses":[
                {
                  "containerID":"docker://b4f24a22a5d8cb7d6f40f32603e25a154b8da949110b7e42d39254106139c235",
                  "image":"artifactory-url/kube-state-metrics:v1.9.5",
                  "imageID":"docker-pullable://artifactory-url/kube-state-metrics@sha256:9d29333ad1cc8e14b26e40daea3739cec21b765f6077c6764546779deec3f54b",
                  "lastState":{},
                  "name":"kube-state-metrics",
                  "ready":true,
                  "restartCount":0,
                  "started":true,
                  "state":{
                    "running":{
                      "startedAt":"2020-11-12T16:12:44+00:00"
                    }
                  }
                }
              ],
```

**What you expected to happen**:
I would expect that the container status for the kube-state-metrics pod that shows `2020-11-12T16:12:44+00:00` be something close to the Pod Ready State `2020-11-22T03:27:43+00:00`. My understanding was that the container state running startedAt time was the time the container started up, and the Ready time in the conditions signified when the Pod was ready.

Does kube state metrics do something after the container is in a running state that would cause such a delay?

**How to reproduce it (as minimally and precisely as possible)**:
Run https://hub.docker.com/layers/rancher/coreos-kube-state-metrics/v1.9.5/images/sha256-9d29333ad1cc8e14b26e40daea3739cec21b765f6077c6764546779deec3f54b?context=explore in an EKS cluster (v.1.16.15 k8s on EKS)

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 1.9.5
- Kubernetes version (use `kubectl version`): 1.16.15
- Cloud provider or hardware configuration: EKS
- Other info:

**Comment by lilic** [comment]
Thanks for the issue! I have not noticed this myself but will try to reproduce. Just side note, I would reccomend to use 1.9.7 release as it included a couple of bug fixes, but don't think it would influence this.

**Comment by karthequian** [comment]
Thanks @lilic!
