### ISSUE TITLE
I want to get the memory usage rate for each pod with prometheus.

### ISSUE THREAD

**Issue by vdi-kakui** [kubernetes/kube-state-metrics#1351]
I want to get the memory usage rate for each pod with prometheus.

However, kube-state-metrics can only get the denominator for each node.

Please let me know if you know the conditional expression to get the memory usage metrics with kube-state-metrics.

**Comment by lilic** [comment]
Hello, we have pod metrics https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md that include resource metrics including memory usage. I am not sure if you seen those or if you are referring to those or not?

In Kubernetes itself, there are more detailed resource metrics, but this is currently alpha feature, but if you need more details its worth having a look. https://github.com/kubernetes/enhancements/pull/1916/files

**Comment by brancz** [comment]
Kubernetes also exposes per container metrics via cAdvisor.

I'll close this due to inactivity and two answers. Feel free to continue to comment should you have more questions!
