### ISSUE TITLE
Port the deps bumps from release-2.0 branch to master

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#1352]
I recently(ish) bumped client-go and other deps in the release-2.0 branch but did not have a chance to port these changes to master as well. I believe this is a good first issue for new contributors. 

This is the original PR that needs to be ported to master branch. https://github.com/kubernetes/kube-state-metrics/pull/1328 Note master branch does not have the vendor directory anymore.

**Comment by afrouzMashaykhi** [comment]
Happy to contribute
/assign

**Comment by mayankshah1607** [comment]
Hey, @afrouzMashaykhi 
Are you still working on this one? I'd like to take it up if not :)
Thanks

**Comment by afrouzMashaykhi** [comment]
Hey @mayankshah1607 yeah I'm working on it😅

**Comment by mrueg** [comment]
@afrouzMashaykhi thanks for working on it! Feel free to ping in #kube-state-metrics on slack, if there's anything I can assist with.

**Comment by afrouzMashaykhi** [comment]
hey @mayankshah1607 ! 
Sorry for the long pause I can't figure out the process of the issue. so could you work on it?

**Comment by mayankshah1607** [comment]
Sure, no worries @afrouzMashaykhi :)

**Comment by lilic** [comment]
@mayankshah1607 do you have any questions regarding this issue? It should be just the need to cherry-pick the patches maybe run a generate. Let me know if you have questions? Lets also not forgot to update the docs as we got issues for this https://github.com/kubernetes/kube-state-metrics/issues/1382 Thank you!

**Comment by mayankshah1607** [comment]
Hi @lilic , apologies for the delay in response. Please take a look at #1388. Thanks!

**Comment by mrueg** [comment]
This was resolved in https://github.com/kubernetes/kube-state-metrics/pull/1407
