### ISSUE TITLE
Add native TLS support

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#1353]
**What would you like to be added**:
Kube-State-Metrics does not support TLS, which recently got added to e.g. node_exporter
**Why is this needed**:
Secure and authenticated communication
**Describe the solution you'd like**
There could be an easy way to use https://github.com/prometheus/exporter-toolkit to add support.

**Comment by mayankshah1607** [comment]
Hi, I'd like to work on this if no one is :)
Thanks
