### ISSUE TITLE
More information requested in the documentation for metrics 

### ISSUE THREAD

**Issue by johmicrot** [kubernetes/kube-state-metrics#1356]
**What would you like to be added**:

It would be helpful if the metrics had a description and a unit associated to in their documentation like in the cadvisor documentation shown here https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md.  I'll specifically need it for Node Metrics, Pod Metrics, and Service Metrics.

**Why is this needed**:

To better understand the metrics themselves

**Describe the solution you'd like**

For example with looking at https://github.com/kubernetes/kube-state-metrics/blob/master/docs/node-metrics.md it would be nice if a description and base unit columns were added.

Most of the metrics don't have a base unit, but at the least a description would be very helpful.

**Comment by lilic** [comment]
Hey, that is a great idea, we use automation to generate these docs, do you want to add this change? Otherwise I will mark it as help wanted.

**Comment by johmicrot** [comment]
It would be great if you can mark it as help wanted.

**Comment by JESWINKNINAN** [comment]
@lilic Can you please assign this task to me if it is not yet assigned?

**Comment by lilic** [comment]
Thanks @JESWINKNINAN let me know if anything is not clear before you start working! :)

**Comment by JESWINKNINAN** [comment]
@lilic Thank you,  Have one question regarding the same. You have said that it should be automatically created and please let me know if you are refering a particalar flow and any clients to be used?

**Comment by lilic** [comment]
If at all possible ideally, we would not be importing new dependencies or tooling. We already generate a bunch of things in the project, so would be good to explore if those can be reused here.

You can start by looking at the `make generate` command and the `doccheck`, it just generates and also validates various markdown files. If its too hard to do it with existing tools feel free to comment on the issue and we can have a look at alternatives. :)

**Comment by JESWINKNINAN** [comment]
@lilic okay cool :)
