### ISSUE TITLE
Additional command line parameter for ksm pods deployed via helm chart (--enable-gzip-encoding)

### ISSUE THREAD

**Issue by AlexShemeshWix** [kubernetes/kube-state-metrics#1357]
**What would you like to be added**: i want to be able to add --enable-gzip-encoding command line parameter for ksm deployed with Helm chart

**Why is this needed**: We have big cluster gzip will optimize network usage a bit 

**Describe the solution you'd like**: i want extraArgs parameter in values.yaml that will be passed to ksm pod during deployment. So i can pass any parameters i want to 

**Additional context**

**Comment by lilic** [comment]
I assume this is just for helm, and nothing needs to be on kube-state-metrics itself?

**Comment by yashvardhan-kukreja** [comment]
@lilic I would like to pick this issue up. I am new to kube-state-metrics and this issue seems like a nice place to start :)
Thanks!

**Comment by lilic** [comment]
Thank you! 🎉
