### ISSUE TITLE
Add azure disk name to kube_persistentvolume_info

### ISSUE THREAD

**Issue by marcoboffi** [kubernetes/kube-state-metrics#1359]
**What would you like to be added**:
Similarly to _ebs_volume_id_ and _gce_persistent_disk_name_, it should be very userful adding azure disk volume name to kube_persistentvolume_info  

**Why is this needed**: 
Adding this attribute it's more simple match pv with corresponding azure object (and join metrics)

**Describe the solution you'd like**

**Additional context**

**Comment by lilic** [comment]
Sounds good to me, do you want to add it or do we want to mark this as help wanted?

**Comment by marcoboffi** [comment]
help wanted, please.
