### ISSUE TITLE
kube_pod_info (and many other) metrics missing

### ISSUE THREAD

**Issue by kareem613** [kubernetes/kube-state-metrics#1370]
**What happened**:
First time setting it up. Seeing metrics at the `/metrics` endpoint. 
Missing a bunch of other expected ones like `kube_pod_info` and `kube_node_status_allocatable`
No errors in the logs.

**What you expected to happen**:
All metrics from [here being logged](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md)

**How to reproduce it (as minimally and precisely as possible)**:
Apply examples/standard

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 2.0
- Kubernetes version (use `kubectl version`): v1.17.14-gke.1600
- Cloud provider or hardware configuration: GKE
- Other info:

**Comment by lilic** [comment]
Hey, thanks for the issue! 1.17 is not fully compatible with v2.0, but you should be able to see the pod metrics, can't think of those not being compatible. In my cluster, I am running kube-state-metrics v2.0.0-beta and I can see these metrics that you mention you are missing. Note I do have a cluster of k8s v1.20.1 on scaleaway.

Can you provide the following:
- exact version of kube-state-metrics you are running
- manifest you used to deploy or deployment yaml
- what metrics are you seeing

**Comment by kareem613** [comment]
release 2.0 branch. commit `2e356cdf18b1db06ef1fa9a63dde1768c53ff6c8`
manifest is the one from `examples/standard`
Here's the output from the `/metrics` endpoint. 
https://gist.github.com/kareem613/adf5f12c013a0e4519b6448cdbda091f

**Comment by lilic** [comment]
Ah, that is the self (telemetry) metrics endpoint, you need to look at the other one for the metrics. You need to scrape or view the 8080 port https://github.com/kubernetes/kube-state-metrics/blob/master/examples/standard/deployment.yaml#L30-L31 Let me know if it works for you after checking the 8080/metrics.

**Comment by kareem613** [comment]
Perfect. I see them on 8080. That clarifies things. Now to figure out how to get the grafana cloud agent to scrape those.
Thanks!

**Comment by lilic** [comment]
Hah that is more of a question for grafana folks so closing this. :)
