### ISSUE TITLE
Metric encoding is broken when using --enable-gzip-encoding flag.

### ISSUE THREAD

**Issue by AlexShemeshWix** [kubernetes/kube-state-metrics#1371]
**What happened**: Ive enabled gzip compression for kube-state-metrics using extraArgs param in helm chatr  (--enable-gzip-encoding)

**What you expected to happen**: i expect metrics to be compressed but accessible

**How to reproduce it (as minimally and precisely as possible)**: Deploy latest kube-state-metrics chart 2.11.0 with extraAgrs that contains --enable-gzip-encoding param. Wait till kube-state-metrics pod starts. Try to access metrics using any browser. It will fail with "Failed to load resource: net::ERR_CONTENT_DECODING_FAILED" message in console.

**Anything else we need to know?**:

**Environment**: 
- kube-state-metrics version: v1.9.7
- Kubernetes version (use `kubectl version`): v1.17.13
- Cloud provider or hardware configuration: AWS
- Other info:

**Comment by lou-lan** [comment]
It looks like the curl command can be accessed successfully, but the browser or Prometheus access fails

**Comment by lou-lan** [comment]
I will try to find the cause of the problem.

**Comment by AlexShemeshWix** [comment]
Any updates?

**Comment by lou-lan** [comment]
> Any updates?

Already merged into rc2 branch

**Comment by lilic** [comment]
This is fixed in master as well, thank you!
