### ISSUE TITLE
docs: Add automation for metric doc generation

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#1373]
**What would you like to be added**:

Currently, our docs are manually written, and some parts are validated as part of the CI steps. But we want to end up with a fully automated way of generating all the _metrics.md in the [docs](https://github.com/kubernetes/kube-state-metrics/tree/master/docs) dir.

**Why is this needed**:

Make our and contributor's lives easier, and end-users have better docs.

**Describe the solution you'd like**

We should have a make target called something like `make docs`, and it should generate all the markdown files with _metrics.md suffix in the [docs](https://github.com/kubernetes/kube-state-metrics/tree/master/docs). This also should include the description and unit where applicable. There is no need to keep the format if it makes it easier to change.

We also need to extend `make doccheck` to include validation for any new things we add, like description and unit. https://github.com/kubernetes/kube-state-metrics/blob/master/Makefile#L44-L55

**Additional context**

See this PR https://github.com/kubernetes/kube-state-metrics/pull/1367 and this issue https://github.com/kubernetes/kube-state-metrics/issues/1356

**Comment by lilic** [comment]
cc @JESWINKNINAN for your information opened the issue, let me know if something is not clear. Thanks again!

**Comment by lilic** [comment]
Still relevant.

**Comment by lilic** [comment]
/remove-lifecycle rotten

Still relevant!

**Comment by fpetkovski** [comment]
/remove-lifecycle stale

still relevant

**Comment by rexagod** [comment]
/remove-lifecycle stale
/assign

In addition to the ask being raised here, I'd also like to pull in a refactor around how things happen in the `doccheck` target right now (in the same PR that I raise against this).

1. Orphaned documentation IMO should be the text present in `doc_metrics` but not in `code_metrics`.
2. Right now, we call a document "orphaned" if it's not in the `doc/*.md` glob expansion. It would make more sense to remove such documents (that `grep -q` fails on) and report them as "redundant" or "irrelevant".

Just trying to keep the terminology clear.

**Comment by rexagod** [comment]
Before I dive head-first from a fresh POV into this, @lilic can you please confirm if [the requirements](https://github.com/kubernetes/kube-state-metrics/issues/1373#issue-798285472) are still the same, or need to be updated. Thanks.
