### ISSUE TITLE
Wrong namespace reported

### ISSUE THREAD

**Issue by sheerun** [kubernetes/kube-state-metrics#138]
Example metric:

kube_deployment_spec_replicas{deployment="segmenter",endpoint="http-metrics",exported_namespace="segmenter",instance="10.244.0.87:8080",job="kube-state-metrics",namespace="default",pod="kube-state-metrics-412796371-tpbv1",pod_app="kube-state-metrics",service="kube-state-metrics",svc_app="kube-state-metrics",svc_k8s_app="kube-state-metrics"}

The namespace should be "segmenter" instead. For some reason it reports "default" what breaks grafana dashboard.

**Comment by sheerun** [comment]
Hmm I'm not sure it's the reason. What exacly happens is in grafana's "Deployment" panel there's only "default" namespace to choose. If selected it shows deployments from all namespaces, even these not in "default" namespace, like segmenter.

Now, when I select segmenter deployment it shows just replicas statistics, but it's missing "CPU", "Memory" and "Network" stats. Now when I enter manually "segmenter" in namespace, it shows "CPU", "Memory" and "Network" stats but doesn't display replicas stats... Here's video:

https://v.usetapes.com/h9wvTqKzWK

Maybe the issue is with exporter exporting pod stats instead or something.

**Comment by sheerun** [comment]
Yeah, the dashboard wants to show following metric:

```
"expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",namespace=\"$deployment_namespace\"}) without (instance, pod)",
```

while I believe it should be:

```
"expr": "max(kube_deployment_spec_replicas{deployment=\"$deployment_name\",exported_namespace =\"$deployment_namespace\"}) without (instance, pod)",
```

Do you want to fix this metric (rename exported_namespace to namespace) or rather expression in grafana configuration?

**Comment by brancz** [comment]
You need to use the `honor_labels` configuration for Prometheus, then Prometheus uses the label values of the exposed metrics and does not resolve collisions with labels that would be added by the targets' labels.
