### ISSUE TITLE
Metrics about removed node still exported

### ISSUE THREAD

**Issue by aclowkey** [kubernetes/kube-state-metrics#1380]
**What happened**:
Metrics still appear after a node has been removed from the cluster.
The metric is 
`kube_node_status_condition{condition="Ready",...,node="kubeX", status="true"} 0`
Kubectl has no result for this node, and it's no even alive. 

**What you expected to happen**:
Those metrics shouldn't appear.

**How to reproduce it (as minimally and precisely as possible)**:
I haven't tried it in an isolated set up. But I think the use case is clear.

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: v1.9.7
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: on-premise
- Other info: -

**Comment by lilic** [comment]
@aclowkey but the value is 0 not 1, can you explain a bit what you expected to see? Did you mean that series should stop existing after the node goes away?

**Comment by aclowkey** [comment]
@lilic Exactly. I would expect it to stop exporting.
