### ISSUE TITLE
Can this component now support v1.20 clusters?

### ISSUE THREAD

**Issue by moweiraul** [kubernetes/kube-state-metrics#1382]
I see that the latest beta version of v2.0.0-beta only shows support to kubernetes V1.19. When will this component support kubernetes V1.20?

**Comment by lilic** [comment]
Hey, the changes for the update have not been brought into master, but you can see in the release branch we do support 1.20 k8s version. https://github.com/kubernetes/kube-state-metrics/tree/release-2.0#compatibility-matrix

**Comment by moweiraul** [comment]
Thanks for answering this question. This table should be updated recently. I remember that when I raised this issue, the latest one was only 1.19.
