### ISSUE TITLE
kube_pod_info using CreatedByAnnotation or OwnerReference

### ISSUE THREAD

**Issue by zouyee** [kubernetes/kube-state-metrics#139]
is it important to update `kube_pod_info` from `CreatedByAnnotation` to  `OwnerReference`?
@brancz

**Comment by brancz** [comment]
On a best effort basis, we should try to provide both. AFAIK the created by annotation is only informative whereas the owner reference is actually used by the GC, so they can potentially both be interesting. Therefore the owner reference should be added, but the created by label should not be removed. Also for compatibility reasons.

**Comment by zouyee** [comment]
Hi @brancz, According to the struct of [OwnerReference](https://github.com/kubernetes/contrib/blob/d519cddaa0b85d37cc912fa6cf2c0592c2b8cf74/election/vendor/k8s.io/kubernetes/pkg/api/meta/metatypes/types.go#L24)  ,I will add owner-kind、owner-name and controller labels, would you have any suggestions? thank you!

**Comment by brancz** [comment]
That sounds reasonable. Go for it! :slightly_smiling_face:

**Comment by andyxning** [comment]
@zouyee How is controller labels added? joined with comma for each `key=value` pair?

**Comment by brancz** [comment]
Yes would be good if you can clarify @zouyee, otherwise the `owner_name` and `owner_kind` labels sound good. We may actually want to split the created_by label into multiple labels of the same style as well.

**Comment by zouyee** [comment]
[#142](https://github.com/kubernetes/kube-state-metrics/pull/142)
