### ISSUE TITLE
Request for pod memory and CPU usage metrics

### ISSUE THREAD

**Issue by jpenekusu** [kubernetes/kube-state-metrics#1396]
**What would you like to be added**:
pod memory and CPU metrics 
**Why is this needed**:
It allow to gather these metrics without puting any exporter in the pod
**Describe the solution you'd like**
kube-state-metrics should get these metrics in some way from K8S
**Additional context**
In some uses cases, you don't need to install an exporter in your pods. But you need memory and CPU usage metrics

**Comment by lilic** [comment]
@jpenekusu can you explain a bit more what kind of metrics you are looking for, we already have pod resource metrics in both Kubernetes as well as in kube-state-metrics.
