### ISSUE TITLE
[helm-chart] Per namespace deployment/sts 

### ISSUE THREAD

**Issue by amuraru** [kubernetes/kube-state-metrics#1401]
**What would you like to be added**:

In environments where only namespaced resources are monitored via kube-state-metrics it would be useful to have an optional parameter in helm chart to configure whether a single or multiple Deployments/StatefulSets of ksm is deployed.
When "namespace sharding" is enabled a separate ksm deployment is created for each namespace.

**Why is this needed**:
Sharding kube-state-metrics metrics collection.

**Describe the solution you'd like**
Add a new parameter in helm chart
```
# When enabled,. namespace sharding creates one Deployment/Stateful for each scraped namespace 
# namespaceSharding:
#  enable: true
```

**Additional context**

**Comment by mrueg** [comment]
Thanks for reaching out.
The helm chart moved over to https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics Feel free to open an issue there if this feature request is still required with the latest version.
