### ISSUE TITLE
Quay image for v2.0.0-rc.0 not published yet?

### ISSUE THREAD

**Issue by dghubble** [kubernetes/kube-state-metrics#1409]
Friendly note that https://quay.io/repository/coreos/kube-state-metrics?tag=latest&tab=tags has v2.0.0-beta, but seems to be missing a v2.0.0-rc.0 image to match the [v2.0.0-rc.0](https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0-rc.0) release? cc @lilic

**Comment by lilic** [comment]
Hey @dghubble 👋  we are stopping the quay image publishing for 2.0 onwards, and only doing gcr images from now on, as really I am the only one left who has access to the quay coreos push. :) The gcr images are available [here](https://github.com/kubernetes/kube-state-metrics#container-image). 

With that said maybe I should have mentioned it more in the release notes, my bad there. Will publish the image now on quay and will include this in the next release notes. Thanks for pointing that out!

**Comment by lilic** [comment]
Okay, pushed the image, should be available on quay.io/coreos/kube-state-metrics:v2.0.0-rc.0. Let me know if you need the quay images to stay for longer and curious if you had any issues with v2.0 so far? :)

**Comment by dghubble** [comment]
Oh, I'm happy to switch to the gcr ones, I just missed the news. Thanks Lili!
