### ISSUE TITLE
`--labels-allow-list` does not work

### ISSUE THREAD

**Issue by qisikai** [kubernetes/kube-state-metrics#1411]
**What happened**:
`--labels-allow-list` does not work

I clone the master branch, then build a binary. And I run with follow params: 
```
/kube-state-metrics --host=0.0.0.0 --port=12087 --telemetry-port=12088 --skip_headers --resources=pods,nodes --labels-allow-list=kube_node_labels=[nodexx,clusterName]
```

But I got:
```
$ curl http://xxxx:12087/metrics | grep node_label
 HELP kube_node_labels Kubernetes labels converted to Prometheus labels.
# TYPE kube_node_labels gauge
kube_node_labels 1
kube_node_labels 1
kube_node_labels 1
kube_node_labels 1
kube_node_labels 1
kube_node_labels 1
```

**What you expected to happen**:
I want to get labels of nodes in k8s cluster

**How to reproduce it (as minimally and precisely as possible)**:
```
/kube-state-metrics --host=0.0.0.0 --port=12087 --telemetry-port=12088 --skip_headers --resources=pods,nodes --labels-allow-list=kube_node_labels=[nodexx,clusterName]
```

**Anything else we need to know?**:
None

**Environment**:
- kube-state-metrics version:  master. Clone at 20210312.
- Kubernetes version (use `kubectl version`): 1.14
- Cloud provider or hardware configuration: x
- Other info:
x

**Comment by lilic** [comment]
Hello 👋 The flag name changed and it's called `--labels-metric-allow-list` see the help text for it by doing `--help` on the binary, the names should also be how they appear in the Kubernetes resource originally. Let me know if that works for you!

```
      --labels-metric-allow-list string   Allows to pass a list of additional Kubernetes label keys that will be used in the resource' labels metric. By default the metric contains only name and namespace labels. To include additional labels provide a list of resource names in their plural form and Kubernetes label keys you would like to allow for them (Example: '=namespaces=[k8s-label-1,k8s-label-n,...],pods=[app],...)'
```

**Comment by Drugoy** [comment]
@lilic I can't figure if that is what I need too or if it's something else.
I don't really understand the description for said CLI argument.

> --labels-metric-allow-list string   Allows to pass a list of additional Kubernetes label keys that will be used in the resource' labels metric. By default the metric contains only name and namespace labels. To include additional labels provide a list of resource names in their plural form and Kubernetes label keys you would like to allow for them (Example: '=namespaces=[k8s-label-1,k8s-label-n,...],pods=[app],...)'

Can this be used to tell ksm to make metrics like `kube_pod_container_status_restarts_total` inherit some custom labels (`project` + `owner` for mee) set for a pod in k8s?

Or even more complex inheritance: I'd like label `project` for said metric to be inherited not from pod, but right from the namespace.

From what I've learned by searching through tickets - there is a solution (via joins to [kube_pod_labels](https://github.com/kubernetes/kube-state-metrics/issues/612#issuecomment-444477951) or [kube_pod_info](https://github.com/kubernetes/kube-state-metrics/issues/536#issuecomment-420203467)), which I don't like because the way it works in Prometheus - is that those joins seem to be prone to conflicts in the sets of metrics/subject **completely unrelated** to the ones in the query, so I'd like to avoid this as hell.

**Comment by lilic** [comment]
Good point on description, to clarify this label only enables labels on all `kube_<resource-name>_labels`, we had a security issue if we enabled all labels and annotations by default some sensitive info could be exposed by this, this allows our users to enable just the labels they want and then join. There is no inheriting on other metrics that do not end with _labels. Hope that clears it up, would be great if you could open PR to adjust the description to make it clear for other folks, thank you!

I am not sure why you do not like joins and like to avoid it, they work for many people out there including us, maybe if you can explain we can find a solution for this?

**Comment by Drugoy** [comment]
Prometheus joins are not like SQL joins. You query to join metrics A and B and get an error about conflict between metrics C and D and not being to join many-to-many.
Also, joins are never cheap.
I would very much instead prefer a similar mechanism of propagating the list of specified `<resource-name>` labels to all of its metrics.

**Comment by lilic** [comment]
Yes well aware of the differences. :) But the many-to-many errors can be solved, see examples of how we fixed them here -> https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/419/files I wonder if its just a documentation thing we are missing to suggest solutions for these errors would that be helpful? 

Yes, joins are not cheap agreed, you could use recording rules to save, but it has some tradeoffs of course.

Are you suggesting https://github.com/kubernetes/kube-state-metrics/issues/1415 ? If yes, lets rather move the discussion in that issue as this one is about the flag not working. :) If it's neither, if you could open a new issue and detail your feature request, thank you! :)

**Comment by qisikai** [comment]
@lilic @gnufied @ncdc . Thanks, but  I just want to use `--labels-metric-allow-list`, but it's missing in the latest master branch, So I try to use `--label-allow-list`, but it doesn't work.

**Comment by lilic** [comment]
@qisikai what do you mean its missing? Can you provide the output of `kube-state-metrics --help` Thank you!
