### ISSUE TITLE
ksm doesn't report any metrics at all if it lacks rights for just 1 subject namespace

### ISSUE THREAD

**Issue by Drugoy** [kubernetes/kube-state-metrics#1413]
**What happened**: ksm doesn't report any metrics at all if just 1 namespace from the list of specified ones is not available.

**What you expected to happen**: ksm should return metrics for the k8s objects from other namespaces (where it has access to).

**How to reproduce it (as minimally and precisely as possible)**: have arg '--namespaces=project1,project2' but give access only to ksm's ServiceAccount 'view' rights only in project1.
ksm will produce **NO** metrics, because its ServiceAccount lacks 'view' rights in project2, although it could return metrics from project1.

**Anything else we need to know?**: no

**Environment**:
- kube-state-metrics version: 1.9.0
- Kubernetes version (use `kubectl version`): 1.18.3+002a51f
- Cloud provider or hardware configuration: OpenShift (on premises)
- Other info: none.

**Comment by lilic** [comment]
Hello 👋  Is this the kube-state-metrics in OpenShift you are talking about or are you deploying one manually? If manually can you share the deployments manifests and which one you used? FYI the manifests in this repo are just examples so you have to customize them if you need something specific.

**Comment by Drugoy** [comment]
Hi, Lili!
Manual deploy via image quay.io/coreos/kube-state-metrics:v1.9.8 (link to it was taken from <a href="https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.9.8">here</a>).

Manifests are really irrelevant here, because they don't even specify which custom ServiceAccount to use, so the default one `default` is used.

The only part that may be relevant here is `spec.containers.[0]`:
```
- image: ...
  args:
    - "--collectors=pods"
    - "--namespace=project1,project2"
    - "--metric-whitelist=kube_pod_start_time,kube_pod_created,kube_pod_status_ready,kube_pod_container_status_running,kube_pod_container_status_restarts_total"
```

I deploy it to `namespaceA`.
I then rolebind `/view` role in namespace `project1` to serviceaccount `default` in namespace `namespaceA`.
Then the bug occurs.
If I then do a similar rolebinding for `project2` - ksm starts to return metrics for both namespaces.

**Comment by lilic** [comment]
Yes seems like a bug with the multlistwatcher, do you want to take up fixing it?

**Comment by Drugoy** [comment]
Sorry, I'm not fluent in Golang enough as to fix it.

**Comment by lilic** [comment]
No worries! I added the help wanted label, as we had folks interested in contributing more, otherwise will have a look if no one else picks it up. Thanks for reporting!

@brancz would be great to replace the custom listwatch with something else, maybe importing it from Prometheus operator what do you think?

**Comment by liangyuanpeng** [comment]
I would like to look at this problem
/remove-lifecycle stale
