### ISSUE TITLE
An option to add Kuberntes labels as Prometheus labels to metrics

### ISSUE THREAD

**Issue by aldudko** [kubernetes/kube-state-metrics#1415]
**What would you like to be added**:

To be able to add allow-listed Kubernetes labels as Prometheus labels directly to certain metrics.

**Why is this needed**:

`kube-state-metrics` exposes Kuberntes roles and labels via special metrics (`kube_node_labels`, `kube_node_role`, `kube_pod_labels`, etc) As a result, when we need to query information from a subset of nodes that that belongs role or label, we need to join the corresponding metrics with `kube_node_labels` on the client side (if the client side supports such operation) which make the query more complex and error prone.

For example,
```
kube_node_status_condition{condition="Ready", status="true"} == 0) and on (node) (kube_node_labels{label_nvidia_com_gpu_product!=""}
```

**Describe the solution you'd like**

It would be great to be able to write
```
kube_node_status_condition{condition="Ready", status="true", label_nvidia_com_gpu_product!=""} == 0
```
instead of
```
kube_node_status_condition{condition="Ready", status="true"} == 0) and on (node) (kube_node_labels{label_nvidia_com_gpu_product!=""}
```

**Additional context**

**Comment by lilic** [comment]
Hey, thanks for your feature request! 

What makes you think this is error-prone? You can use recording rules in Prometheus to avoid any errors and make queries less complex for the end-users.

Adding labels on each of the metrics produces higher cardinality metrics for users who would not need those, besides that it introduces a lot of complexity to our codebase when there exists a solution for this in Prometheus as you mentioned above.

**Comment by aldudko** [comment]
Hi Lili,

Thank you for looking into this.

Yes, in Prometheus we have a way to make joining two metrics less complex for the end-users.

I'm currently working on setting up Kubernetes monitoring in another monitoring system that doesn't have a query language similar to PromQL and doesn't allow joining metrics. I'm having a hard time getting the information I need from kube-state-metrics because Kubernetes node roles and labels are exposed via separate metrics.
That's why I created this feature request.

**Comment by Drugoy** [comment]
IMO, this is a very important ticket and I wish it got into 2.0.0 release.
With this feature introduced - it would be trivial to make pod's metrics inherit labels from the pod itself.
This way it becomes easier (without the hassle of using that non-trivial and qutie error-prone group_left() approach we discussed in another ticket's comments) to set alerts that'd be routed to a channel for specific team that develops this particular microservice.

**Comment by ronaknnathani** [comment]
Hi @lilic, 

You are right that PromQL works. However, our team doesn't use Prometheus and have a home-grown monitoring stack which doesn't support PromQL (trust me, we'd love to have prometheus but that's not gonna happen anytime soon). So, having Kubernetes labels in the metric of interest allows us to translate the Prometheus metrics into a format understood by our home grown monitoring stack.

I understand the concern for metrics cardinality. If the Kubernetes labels that will be added to the Prometheus metric is made configurable, would it help mitigate that?

**Comment by sherifabdlnaby** [comment]
What’s the status of this ? Can we revive the conversation? I’d be pleased to help developing this feature. It will make my team and I life easier.

**Comment by Drugoy** [comment]
@sherifabdlnaby
This ticket is Open, probably meaning that there wouldn't be any resistance in accepting PRs providing this feature.
If you are capable of producing PRs that'd bring this feature - please, do so.

If you need any help (from Lili or from other maintainers) - you need to be specific about what you need help with.

**Comment by sherifabdlnaby** [comment]
@Drugoy Great, Thanks 🙏🏻

I was not sure if it was a strict design decision was taken previously to not support such metric labels and so I was bumping this issue to ask.

**Comment by sherifabdlnaby** [comment]
@lilic Hello, I tried looking up Github Issues trying to find if maintainers have a concrete/explicit opinion about exporting Kubernetes resources labels to metric labels, I want to implement the feature, it will greatly help me, yet I won't be able to run a fork of kube-state-metrics at where I actually want to use the feature :D

**Comment by sherifabdlnaby** [comment]
I created #1689 to address this feature request.
@ronaknnathani @Drugoy @lilic Would like to know your opinion, and possibly re-open this ticket 😄
