### ISSUE TITLE
Kube state metrics as executable

### ISSUE THREAD

**Issue by sakthiraam** [kubernetes/kube-state-metrics#1416]
**What would you like to be added**:
Option to generate a kube state metrics executable.

**Why is this needed**:
We need this because our environment is cut off from internet and we need to run our containers with specific base image hence if we have a executable tar ball like prometheus we can use it and build our custom image.

**Describe the solution you'd like**
If the executable is released as part of every new release it would be great solution or please provide support for offline executable generation

If it's already supported please do update. Thank You

**Additional context**

**Comment by lilic** [comment]
Hey 👋 you can build your executable yourself right now by running `make build` target, it is what we use to build the image in the end. Would that be enough for you?

**Comment by sakthiraam** [comment]
Hi @lilic , Thanks for your quick reply. make build-local target actually helped. Will close this request. Have a nice day ahead.
