### ISSUE TITLE
Missing container image for v2.0.0-rc.1

### ISSUE THREAD

**Issue by dghubble** [kubernetes/kube-state-metrics#1430]
Trying the new [v2.0.0-rc.1](https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.0.0-rc.1) release, I don't find an image available from the new authoritative registry. We've already switched away from Quay to `k8s.gcr.io` in https://github.com/kubernetes/kube-state-metrics/issues/1409

Is there a time lag between release and image publishing internally? I usually update with some automation involvement, so it'd be good to know if I should factor in a lag.

```
skopeo inspect docker://k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0-rc.0
{
    "Name": "k8s.gcr.io/kube-state-metrics/kube-state-metrics",
    "Digest": "sha256:ed886c793c35596c64e45d0bf34dd345bf42caaf246a7e55e160be36bf70c085",
    "RepoTags": [
        "2.0.0-alpha",
        "2.0.0-alpha.1",
        "2.0.0-alpha.2",
        "v1.9.8",
        "v2.0.0-alpha.2",
        "v2.0.0-alpha.3",
        "v2.0.0-beta",
        "v2.0.0-rc.0"
    ],
    "Created": "2021-03-04T13:29:29.075821949Z",
    "DockerVersion": "19.03.8",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:9e4425256ce4503b2a009683be02372ee51d411e9cc3547919e064fee4970eab",
        "sha256:a759dddd612c6a710f71a8e4eecdb2fe4f967352a5bcb84eea1a6bbcb6209b5d"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt"
    ]
}
```

**Comment by dghubble** [comment]
cc @mrueg

**Comment by mrueg** [comment]
It is available but in staging waiting for promotion. https://github.com/kubernetes/k8s.io/pull/1837

If you want to try it, feel free to test with: https://console.cloud.google.com/gcr/images/k8s-staging-kube-state-metrics/GLOBAL/kube-state-metrics@sha256:95e06a9e1eb075873adefcf1b3646997e4800fee2653a1514fa35531245a5aeb/details?tab=info

**Comment by lilic** [comment]
@dghubble hey 👋 there is usually a slight delay always as we need to open a promotion PR and wait for images to be built. What triggers your automation is it tag or release?

**Comment by lilic** [comment]
We promoted the images, should be good to go. We will try to maybe next time do a pre-release until the images are not ready or promoted, would that work for you @dghubble ?

```
 docker run -it k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0-rc.1 --version
Unable to find image 'k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0-rc.1' locally
v2.0.0-rc.1: Pulling from kube-state-metrics/kube-state-metrics
60775238382e: Pull complete
e3030d04a6a4: Pull complete
Digest: sha256:95e06a9e1eb075873adefcf1b3646997e4800fee2653a1514fa35531245a5aeb
Status: Downloaded newer image for k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0-rc.1
version.Version{GitCommit:"", BuildDate:"2021-03-26T22:44:10Z", Release:"v2.0.0-rc.1", GoVersion:"go1.16.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by dghubble** [comment]
Ok, I can just factor in a few days or a week delay from release before bumping. I don't think I'll be consuming the staging ones @mrueg though I appreciate the link, there are just far too many projects to keep track of to get into that level of detail.

Looks like v2.0.0-rc.1 is present now. Thanks!
