### ISSUE TITLE
kube_pod_info metrics occasionally missing pod_ip label for some pods

### ISSUE THREAD

**Issue by mikonse** [kubernetes/kube-state-metrics#1432]
**What happened**:
In our OKD 4.6 cluster we currently have the problem of the `kube_pod_info` metric is appearing with a different set of labels for the same pod. More concretely sometimes the `kube_pod_info` metric is missing the `pod_ip` label, so e.g. for pod xyz we would get these two distinct time series:

```
kube_pod_info{container="kube-rbac-proxy-main",created_by_kind="Job",created_by_name="xyz",endpoint="https-main",host_ip="10.0.38.53",instance="100.122.4.162:8443",job="kube-state-metrics",namespace="namespace",node="node1",pod="xyz",prometheus="openshift-monitoring/k8s",service="kube-state-metrics",tenant_id="default-tenant"}
kube_pod_info{container="kube-rbac-proxy-main",created_by_kind="Job",created_by_name="xyz",endpoint="https-main",host_ip="10.0.38.53",instance="100.122.4.162:8443",job="kube-state-metrics",namespace="namespace",node="node1",pod="xyz",pod_ip="100.122.4.252",prometheus="openshift-monitoring/k8s",service="kube-state-metrics",tenant_id="default-tenant"}
```

Important to note here is that the time series do not appear at the same time but after one another, as far as I have seen the one without the `pod_ip` label before the one with.

This messes with some of our grafana dashboards as some queries do joins on the `kube_pod_info` through the tuple of `(namespace, node)` and throw duplicate time series errors if a pod has two `kube_pod_info` time series one with the `pod_info` label and one without. The obvious quick fix is to adjust the queries to be able to deal with this behaviour but I'm just curious if this is a bug or intended behaviour (if it is a note in the documentation would be quite nice).

**What you expected to happen**:
As documented the `pod_ip` label is always present for the`kube_pod_info` metric.

**Environment**:
- kube-state-metrics version: 1.9.5
- Kubernetes version (use `kubectl version`): 1.19.2 (okd 4.6.0-0.okd-2021-02-14-205305)

**Comment by lilic** [comment]
@mikonse thanks for the issue! Interesting one, can you provide the pod object as seen via kubectl?

**Comment by mikonse** [comment]
It's somewhat difficult to get a hold of this problem since it only happens sporadically. But in one case I've found that a pod was missing the `pod_ip` label when it was stuck in the ContainerCreating state.

The pod object looked as follows:
```
Name:           <pod-name>
Namespace:      <namespace>
Priority:       0
Node:           <node>
Start Time:     Tue, 30 Mar 2021 13:28:00 +0000
Labels:         app=v2
                pod-template-hash=5d959cdffc
Annotations:    k8s.ovn.org/pod-networks:
                  {"default":{"ip_addresses":["100.122.14.16/24"],"mac_address":"<mac>","gateway_ips":["100.122.14.1"],"ip_address":"100.122.14....
                openshift.io/scc: restricted
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/<replicaset>
Containers:
  v2:
    Container ID:
    Image:          docker.rsint.net/docker.io/nginxinc/nginx-unprivileged:latest
    Image ID:
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     20m
      memory:  20Mi
    Requests:
      cpu:        15m
      memory:     15Mi
    Liveness:     http-get http://:8080/ delay=30s timeout=30s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /usr/share/nginx/html from www-v2 (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-t7s84 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  www-v2:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      www-v2
    Optional:  false
  default-token-t7s84:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-t7s84
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason       Age                    From                          Message
  ----     ------       ----                   ----                          -------
  Warning  FailedMount  29m (x1247 over 42h)   kubelet, <node>  MountVolume.SetUp failed for volume "www-v2" : configmap "www-v2" not found
  Warning  FailedMount  9m7s (x970 over 42h)   kubelet, <node>  Unable to attach or mount volumes: unmounted volumes=[www-v2], unattached volumes=[www-v2 default-token-t7s84]: timed out waiting for the condition
  Warning  FailedMount  2m57s (x267 over 42h)  kubelet, <node>  Unable to attach or mount volumes: unmounted volumes=[www-v2], unattached volumes=[default-token-t7s84 www-v2]: timed out waiting for the condition
```
To me this looks like when a pod is stuck in the ContainerCreating state but has not fully started yet kube-state-metrics does not provide the `kube_pod_info` metric with the pod_ip if the pod does not show an IP in the k8s API. I'm guessing since the k8s API ist probably the point where kube-state-metrics gets that info from.

**Comment by mikonse** [comment]
Any update whether this is intended behavior or actually a bug?

**Comment by fpetkovski** [comment]
Pods do not get an IP until they get scheduled on a node. If a pod is in a Pending state when a scrape happens, the `pod_ip` label value will be empty. This might be something you are running into and also a reason why you see time series with and without the pod ip.
