### ISSUE TITLE
Adding resourceVersion to CronJob metrics?

### ISSUE THREAD

**Issue by JensErat** [kubernetes/kube-state-metrics#1433]
**What would you like to be added**:

For deployments we already have a generation metric, which helps to see whether a deployment changed. We do not have such a metric for CronJobs -- they don't have such metadata at all. We could export the resourceVersion metadata as label though, similar to what ConfigMaps, Secrets and Ingress resources have.

**Why is this needed**:

#500 was closed due to being inactive, but is still an issue. We have an alert that notifies us whenever the calculated CronJob start date passed. Something like `and changes(kube_cronjob_metadata_resource_version[24h])` would help to mitigate the issue.

**Describe the solution you'd like**

Mostly copy-paste the solution from configmaps.

**Additional context**

I'm fine with providing the code, if we have agreement on this being a good thing to have.

<sup>Jens Erat <jens.erat@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by lilic** [comment]
Exporting resource version sounds good to me as we have it for other resources anyways. There is also `kube_cronjob_status_active`, but have not had a chance to see if that would possibly work?

cc @brancz as you commented on the last issue referenced here.
