### ISSUE TITLE
example in each metric doc

### ISSUE THREAD

**Issue by zouyee** [kubernetes/kube-state-metrics#144]
is it suitable to add a column for  example？@andyxning @brancz 
# Pod Metrics

| Metric name| Metric type | Labels/tags | Examples   |
| ---------- | ----------- | ----------- |----------- |
| kube_pod_info | Gauge | `pod`=&lt;pod-name&gt; <br> `namespace`=&lt;pod-namespace&gt; <br> `host_ip`=&lt;host-ip&gt; <br> `pod_ip`=&lt;pod-ip&gt; <br> `start_time`=&lt;date-time since kubelet acknowledged pod&gt; <br> `node`=&lt;node-name&gt;<br> `created_by`=&lt;created_by&gt;  |kube_pod_info{host_ip="10.142.21.158",namespace="kube-system",pod="nginx-ingress-controller-49379976-bsw1p",pod_ip="10.142.21.158"} 1|

**Comment by brancz** [comment]
I don't think examples in this format make a whole lot of sense, the most sense I could see involving examples are example queries.

I'm not against having example queries but there are a few things to consider:

* having an examples section like that is a huge maintenance effort, which might be worth it, but it requires some commitment
* there are multiple systems consuming the Prometheus exposition format and this seems to be especially true for kube-state-metrics as we've had more than one issue filed for users using google stackdriver

So what I'd take from that is that we shouldn't put it in a column, also for readability reasons, but when adding examples we should have a "PromQL examples" section. I'd expect most of these to come from the community and frankly the queries are probably not going to be optimal, but that's not a huge problem as I'd expect this to be a low barrier contribution if anyone can optimize an existing example.

**Comment by andyxning** [comment]
I agree with @brancz .

Recording and updating the metrics and labels is already a maintenance burden. Since we have already record all the labels for a metric, it is easy enough for users to find the actual metric examples. :)

> but when adding examples we should have a "PromQL examples" section.

Maybe we should firstly resolve #123.

**Comment by brancz** [comment]
That's probably a good idea @andyxning , as it has a more explicit use and people would actually notice if something is wrong if they are loading the dashboards into their grafana instances, so I agree that that's probably a better point to start.
