### ISSUE TITLE
Add option to configure scrape interval for kube-state-metrics helm chart

### ISSUE THREAD

**Issue by tustyianovych** [kubernetes/kube-state-metrics#1446]
**What would you like to be added**: a property in values.yaml to change the scrape interval. By default it is 15s.

**Why is this needed**: To reduce memory and CPU utilization as well as the amount of data ingested. 

**It will be great to have a property like serviceMonitor.interval or whatever to change the scrape interval for KSM.**

**If this option is already available for KSM helm charts, please let me know**

**Comment by mrueg** [comment]
Thanks for reaching out.
The helm chart moved over to https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics Feel free to open an issue there if this feature request is still required with the latest version.
