### ISSUE TITLE
[helm-chart] Role resource can't be created

### ISSUE THREAD

**Issue by moltamas93** [kubernetes/kube-state-metrics#1452]
**What happened**:
I want to create namespaced Role instead of ClusterRole by kube-state-metrics helm chart, but got a template error.
Helm error log:
```
Error: YAML parse error on kube-state-metrics/templates/role.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context
helm.go:81: [debug] error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context
YAML parse error on kube-state-metrics/templates/role.yaml
```
[Range action](https://github.com/kubernetes/kube-state-metrics/blob/master/charts/kube-state-metrics/templates/role.yaml#L3) not working properly in role.yaml. The range scope is reset after [{{ end }}](https://github.com/kubernetes/kube-state-metrics/blob/master/charts/kube-state-metrics/templates/role.yaml#L4).

**What you expected to happen**:
Create Role resource in specified namespaces (`.Values.namespaces`)

**How to reproduce it (as minimally and precisely as possible)**:
Command: `helm upgrade --install --namespace test kube-state-metrics kube-state-metrics --values values.yaml`

values.yaml
```
namespace: test
podSecurityPolicy:
  enabled: false
rbac:
  useClusterRole: false
```
**Environment**:
- kube-state-metrics version: 2.13.2
- Helm version: v3.5.3 (Same with: v2.17.0)

**Comment by StepanKuksenko** [comment]
also faced with this issue.

**Comment by StepanKuksenko** [comment]
@moltamas93 do you have some workaround for this issue ? Could you share...

**Comment by moltamas93** [comment]
@StepanKuksenko Sorry for the late answer. I created the Role manually. So I use existingRole.
This is my kube-state-metrics config now:
 ```  
  namespace: "{{ .Release.Namespace }}"
  podSecurityPolicy:
    enabled: false
  rbac:
    useExistingRole: kube-state-metrics
    useClusterRole: false```

**Comment by mrueg** [comment]
Thanks for reaching out.
The helm chart moved over to https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-state-metrics Feel free to open an issue there if this request is still required with the latest version.
