### ISSUE TITLE
Bump kubernetes dependencies to v1.21 version  

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#1454]
Couple of things to do:

* In master branch, we want to bump client-go & co to `v0.21` -> https://github.com/kubernetes/kube-state-metrics/blob/master/go.mod#L41-L43

* We also need to test against Kubernetes v1.21, for that we should change this to v1.21 https://github.com/kubernetes/kube-state-metrics/blob/7fd83751066b39d6f80fd31ee190d1cd2cd6352a/tests/e2e.sh#L27 maybe even adding the ability to test against both v1.20 and v1.21. cc @mrueg what do you think?

* Document compatibility in the README file.

**Comment by mrueg** [comment]
Sounds interesting to test against multiple versions, will need to see how long it will extend CI time (assuming the spin up of the kind clusters is where we spent most time on)

**Comment by lilic** [comment]
We do this in kube-prometheus,  https://github.com/prometheus-operator/kube-prometheus/blob/main/.github/workflows/ci.yaml#L55-L56 You can see how it is in this PR https://github.com/prometheus-operator/kube-prometheus/pull/1094 for example:
> ci / E2E tests (kindest/node:v1.19.0) (pull_request) Successful in 6m
> ci / E2E tests (kindest/node:v1.20.0) (pull_request) Successful in 6m

**Comment by dgrisonnet** [comment]
I can take care of the Kubernetes dependencies bump.

**Comment by lilic** [comment]
Thank you both! 🎉
