### ISSUE TITLE
Install  kube-state-metrics v2 in kubernetes 1.17 fails with error "unknown flag: --collectors"

### ISSUE THREAD

**Issue by vukasin-nikodijevic** [kubernetes/kube-state-metrics#1456]
**What happened**:
Updated image tag to:
```
-         image: "k8s.gcr.io/kube-state-metrics/kube-state-metrics:v1.9.8"
+         image: "k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.0.0-rc.1"
```

**What you expected to happen**:
kube-state-metrics pod start without any issue

**How to reproduce it (as minimally and precisely as possible)**:
Just update image tag to v2.0.0-rc.1

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version:  v2.0.0-rc.1
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-22T19:05:30Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.16", GitCommit:"d88fadbd65c5e8bde22630d251766a634c7613b0", GitTreeState:"clean", BuildDate:"2020-12-18T15:59:27Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- Cloud provider or hardware configuration: Azure AKS
- Other info:

After installed, the ksm pod will go into CrashLoopBackOff state with following error log:
```
╰─➤  k logs kube-state-metrics-58c6d8d7b8-88b8r
unknown flag: --collectors
Usage of /kube-state-metrics:
unknown flag: --collectors
      --add_dir_header                   If true, adds the file directory to the header of the log messages
      --alsologtostderr                  log to standard error as well as files
.
.
.
.
```

If you check master branch `--collectors` option is still present without any conditioning based on the image version tag:
https://github.com/kubernetes/kube-state-metrics/blob/master/charts/kube-state-metrics/templates/deployment.yaml#L71

**Comment by lilic** [comment]
Thanks for your report, I assume this is done via helm? I don't know if helm chart is v2.0 ready, but this flag was renamed to `--resources`? cc @mrueg @tariq1890

**Comment by mrueg** [comment]
The helm chart is not upgraded yet and we will once we're migrated to the new repository.
Please track https://github.com/prometheus-community/helm-charts/issues/839 and https://github.com/kubernetes/kube-state-metrics/pull/1448  for further information.

**Comment by vukasin-nikodijevic** [comment]
@mrueg - any eta because this is real blocker for having KSM in Kubernetes v1.17+, in or without combination with `kube-prometheus-stack`.

Plz, be aware that 1.17 is pretty low version of kubernetes now days.
