### ISSUE TITLE
Add NodeAffinity in podStatusReasons for kube_pod_status_reason metrics

### ISSUE THREAD

**Issue by pkbhowmick** [kubernetes/kube-state-metrics#1460]
Now kube-state-metrics collects kube_pod_status_reason metrics for "NodeLost", "Evicted" and "UnexpectedAdmissionError". But it doesn't collect metrics for reason "NodeAffinity".

I personally feel the necessity of this metrics to know which pods are failed to schedule for node affinity.

**Comment by pkbhowmick** [comment]
kind/feature

**Comment by thdesous** [comment]
Hi @pkbhowmick
I agree with you. How do you identify through the metrics the status 'NodeAffinity' today?
