### ISSUE TITLE
Support kube_pod_ready_time metric

### ISSUE THREAD

**Issue by sgrzemski** [kubernetes/kube-state-metrics#1465]
**What would you like to be added**:

Hello kube-state-metrics team!
I am a happy user of your metrics software. I would like the kube-state-metrics to report also the time, when pod became ready (passing readiness probe). According to [docs](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md), there are already a couple of gauges in seconds: `kube_pod_start_time`, `kube_pod_container_state_started`, etc. 

**Why is this needed**:

I would like to be able to measure the time needed for the container to become fully operational and healthy. I already have the created and start timestamp, so a simple delta query in prometheus would do the trick if a metric reporting the ready time would be implemented. 

**Describe the solution you'd like**

Query the Kubernetes API to get the ready timestamp.

**Additional context**

**Comment by lilic** [comment]
Hey 👋 Can you explain where this API is at? If k8s API reports this, it sounds good to me. 

Note that `ContainerState` is the only thing that reports `StartedAt`. I haven't looked into `StartTime` if that can be used somehow.

**Comment by sgrzemski** [comment]
Pardon my delay, I was off for some time.
I took a look at the code and it looks like kube-state-metrics uses [Pod objects](https://pkg.go.dev/k8s.io/api/core/v1#Pod), `Pod.Status.StartTime` specifically,  to create the `kube_pod_start_time` metric. However, according to [Pod Lifecycle](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions) docs, [PodStatus](https://pkg.go.dev/k8s.io/api/core/v1#PodStatus) should have an array of [PodConditions](https://pkg.go.dev/k8s.io/api/core/v1#PodCondition), containing the following information:
- PodScheduled: the Pod has been scheduled to a node.
- ContainersReady: all containers in the Pod are ready.
- Initialized: all init containers have started successfully.
- **Ready: the Pod is able to serve requests and should be added to the load balancing pools of all matching Services.** 

Those come with two useful properties called:
- lastProbeTime: Timestamp of when the Pod condition was last probed.
- **lastTransitionTime: Timestamp for when the Pod last transitioned from one status to another.**

This information should be enough to form a metric called `kube_pod_ready_time` and with a simple PromQL get the time needed for the pod to start.

**Comment by szymon-grzemski** [comment]
I've patched v1.9.8 release with some additional code to report both ContainersReady and Ready timestamps and the transition between states can happen multiple times (e.g. pod stopped passing readiness probes). Quoting Pod Lifecycle docs:
```
Pod is evaluated to be ready only when both the following statements apply:

All containers in the Pod are ready.
All conditions specified in readinessGates are True.
```
I will change those metrics to report latest timestamp and match with your current convention: `kube_pod_status_ready_time` and `kube_pod_containers_status_ready_time` and prepare a PR.

**Comment by sgrzemski** [comment]
I've patched v1.9.8 release with some additional code to report both ContainersReady and Ready timestamps and the transition between states can happen multiple times (e.g. pod stopped passing readiness probes). Quoting Pod Lifecycle docs:
```
Pod is evaluated to be ready only when both the following statements apply:

All containers in the Pod are ready.
All conditions specified in readinessGates are True.
```
I will change those metrics to report latest timestamp and match with your current convention: `kube_pod_status_ready_time` and `kube_pod_containers_status_ready_time` and prepare a PR.

**Comment by brancz** [comment]
I'm pretty sure the kubelet exposes metrics about the readiness probes. I think it's the kubelet's responsibility to expose this.

**Comment by szymon-grzemski** [comment]
> I'm pretty sure the kubelet exposes metrics about the readiness probes. I think it's the kubelet's responsibility to expose this.

I am running 1.19+ and I am seeing `kubelet_pod_start_duration_seconds_bucket, _sum and _count` in Prometheus, but they are node level, not per specific pods.

**Comment by slamdev** [comment]
@lilic @brancz any plans to merge this? looking forward to use this metric

**Comment by kevinwubert** [comment]
I was looking for something just like this! Was there something blocking this from getting merged into kube state metrics 2?

**Comment by SpectralHiss** [comment]
:+1: This is useful for doing accurate total pod start time calculation, (instead of trying to infer from ready count or something), in my particular case trying to benchmark the effect of some Istio sidecar settings on startup time.
any updates @sgrzemski ?

**Comment by stat-johan** [comment]
This would be really nice to have, @sgrzemski

**Comment by qingguee** [comment]
Looking forward for this PR be merged, because I find that the "kube_pod_status_ready" has 2s delay to show ready status which compare with  Ready timestamp from pod condition.  I have reported a Issue, but no response yet.
https://github.com/kubernetes/kube-state-metrics/issues/1830

So, we can't rely on "kube_pod_status_ready". If we want to calculate POD startup time, that's an issue. 
It's always an issue by using metrics to calculate time, so we need a metrics can return ready timestamp which can get from pod conditions.

**Comment by sumanthkumarc** [comment]
This would be a really great metric to have. Helps us to understand the time taken for services to come up in cluster.

**Comment by max-rocket-internet** [comment]
The metric would be incredibly valuable! For example to know:

- Seconds until pod is scheduled
- Seconds until pod is `Ready`

**Comment by coleary-hyperscience** [comment]
I'm still pretty new to Prometheus, but I'm using this query to collect an almost equivalent metric. Please let me know if you find this useful or foresee any issues with it: `sort_desc(max(sum_over_time(kube_pod_status_phase{namespace=~"$namespace", phase="Pending"}[$__range])/4) by (pod))`
This returns the approximate (30 sec accuracy) time (in min) for each pod in the pending state.

**Comment by vijaynidhi85** [comment]
> I'm still pretty new to Prometheus, but I'm using this query to collect an almost equivalent metric. Please let me know if you find this useful or foresee any issues with it: `sort_desc(max(sum_over_time(kube_pod_status_phase{namespace=~"$namespace", phase="Pending"}[$__range])/4) by (pod))` This returns the approximate (30 sec accuracy) time (in min) for each pod in the pending state.

Could I know why the /4 is required?

**Comment by jkdihenkar** [comment]
Hi @sgrzemski - can you share us the export of the dashboard that you've plotted based on these metrics?
