### ISSUE TITLE
add exitcode to labels of kube_pod_init_container_status_terminated_reason

### ISSUE THREAD

**Issue by dafenko** [kubernetes/kube-state-metrics#1481]
**What would you like to be added**:
Add exitcode to labels of kube_pod_init_container_status_terminated_reason

**Why is this needed**:
Our application has defined exit codes. We would like to be alerted when app ends up with a specified error code.

**Describe the solution you'd like**
We would like to define alert that uses kube_pod_init_container_status_terminated_reason metric and be alerted when container exists with certain exit code. 

**Additional context**
We are using node.js. Node.js has limit for memory allocation. (see NODE_OPTIONS --max-old-space-size=) 
We intentionally keep limit for node.js a few percent less then K8S resource limit.
In that way node.js has possibility to handle OOM (e.g. create dump file).
POD gets then signal SIGABRT 6 (exit code 128+6 = 134).
We would like to be alerted when such situation happens.

**Comment by slashpai** [comment]
I would like to work on this. I will review and update back

/assign

**Comment by dannylee-** [comment]
Would it be better to create a new metric with the exit code?  Or else we would introduce a label with a large cardinality (256 possible values)

**Comment by prashantv** [comment]
/reopen

Having exit code would be useful for monitoring different types of container exits.

**Comment by fgiannetti** [comment]
> I would like to work on this. I will review and update back
> 
> /assign

Hey @slashpai 
Have some news about this? It would be really useful to have this feature ;)
Or maybe this message will reopen this issue...
Thank you!!
