### ISSUE TITLE
Pod ephemeral storage resources wanted

### ISSUE THREAD

**Issue by dbazhal** [kubernetes/kube-state-metrics#1488]
**What would you like to be added**:

kube_pod_container_resource_requests_ephemeral_storage_bytes
kube_pod_container_resource_limits_ephemeral_storage_bytes

**Why is this needed**:

I have metric kube_node_status_allocatable and i want to deduct sum of all running containers requests from this metric to get "how much free ephemeral storage each node has" to see if node soon comes to unschedulable state.

**Describe the solution you'd like**

I don't know how this could be done, i just see there is 

kube_pod_init_container_resource_requests_ephemeral_storage_bytes
kube_pod_init_container_resource_limits_ephemeral_storage_bytes

and it is strange to me that there is such metric for init container, but no metric for main container in pod.

**Additional context**

None.

**Comment by fpetkovski** [comment]
Hi @dbazhal, since no one has picked up the issue yet, would you be interested in contributing the enhancement to KSM?
