### ISSUE TITLE
image for v2.1.0 not found

### ISSUE THREAD

**Issue by Sund3** [kubernetes/kube-state-metrics#1498]
What happened: failed to pull k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.1.0 when deploying

Failed to pull image "k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.1.0": rpc error: code = Unknown desc = Error response from daemon: manifest for k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.1.0 not found: manifest unknown: Failed to fetch "v2.1.0" from request "/v2/kube-state-metrics/kube-state-metrics/manifests/v2.1.0".

What you expected to happen: image to be pulled

How to reproduce it (as minimally and precisely as possible): apply yaml with k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.1.0 as image 

**Environment**:
- kube-state-metrics version: 2.1.0
- Kubernetes version (use `kubectl version`): 1.19
- Cloud provider or hardware configuration: aws
- Other info:

**Comment by mrueg** [comment]
Thanks for reporting. You are right, it looks like not all images got promoted. This should fix it: https://github.com/kubernetes/k8s.io/pull/2139

**Comment by mrueg** [comment]
@Sund3 they should be in place now. Feel free to reopen if the issue is still not fixed for you.
