### ISSUE TITLE
Kube-state-metrics compatability

### ISSUE THREAD

**Issue by vignesh-v-nutanix** [kubernetes/kube-state-metrics#1500]
**What happened**:
Cluster related metrics are not working

**What you expected to happen**:
I have kubernetes 1.18 and kube state metrics is of 2.0.0. I dont see any cluster related items in the dashboard

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version:  2.0.0
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: aws
- Other info: kops cluster

I want to know if kube-state-metrics deprecated any of the things or how to get the cluster metrics up and running

**Comment by elcomtik** [comment]
please read the release notes for 2.0.0, there is info about metrics that were deprecated and replaced by new ones.
