### ISSUE TITLE
Some questions about Perc50

### ISSUE THREAD

**Issue by sivanWu0222** [kubernetes/kube-state-metrics#1502]
I have some questions about the content of [article](https://github.com/kubernetes/kube-state-metrics#latency)

**What would you like to be added**:
Three Questions：
1.  More scaling test samples in latency time
2. What do the Perc50, Perc90 and Perc99 mean?
3. How to calc the time of Perc50?

**Why is this needed**:

**Describe the solution you'd like**

**Additional context**

**Comment by lilic** [comment]
Hey, These were the results of our scaling tests and the latency numbers, It's the 50th [percentile](https://en.wikipedia.org/wiki/Percentile). Its meant to be used for scaling purposes as a benchmark of some sorts. Hope that answers the questions?

**Comment by sivanWu0222** [comment]
3KS, And i want to know **how to get the latency number in scaling tests**.

**Comment by lilic** [comment]
Are you having an issue that you need to get the latency number? This was done as part of 2.0 release by k8s perf team and us maintainers, often you wouldn't need to know. But if you do there are KSM own metrics to check https://github.com/kubernetes/kube-state-metrics#kube-state-metrics-self-metrics the `http_request_duration_seconds_bucket ` where you can calculate.
