### ISSUE TITLE
Expose annotations and labels on configmaps

### ISSUE THREAD

**Issue by aecay** [kubernetes/kube-state-metrics#1503]
**What would you like to be added**:

Configmap metrics only export info, created, and resource_version ([docs](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/configmap-metrics.md)).  It would be useful to see labels and annotations as well.

**Why is this needed**:

In my usecase, it's possible to use the labels/annotations applied to pods to track the rollout of versions of an application across different clusters (each with its own prometheus instance, aggregated in a single grafana dashboard -- the labels are applied by our deployment automation).  Some of the "applications" have static (or rarely changing) code, and changes in behavior are instead driven by config map updates.  It would be good to have a similar ability to track those rollouts via metrics, which requires exposing the labels and annotations to prometheus.

(In the above writeup I've referred to "labels and annotations".  But perhaps it makes sense to prioritize one or the other -- that would probably work as well.  Our tooling at the moment uses annotations but could probably be adjusted to use labels instead.)

**Describe the solution you'd like**

Exposure of `kube_configmap_annotations` and `kube_configmap_labels` -- exactly parallel to `kube_namespace_annotations` `kube_pod_labels` etc.

**Additional context**

**Comment by grzesuav** [comment]
Hmm as far as I am aware in annotation there are some special fields (like `lastAppliedConfiguration`, `generation` etc) which should not be exposed (because of cardinality and sensitive information exposure)

**Comment by fpetkovski** [comment]
There are two open PRs for exposing annotations for all resources, so it might be worth tracking those:
* https://github.com/kubernetes/kube-state-metrics/pull/1495
* https://github.com/kubernetes/kube-state-metrics/pull/1468
