### ISSUE TITLE
Add important missing metrics for Pods and Deployments

### ISSUE THREAD

**Issue by rahulbandariSensei** [kubernetes/kube-state-metrics#1508]
We are not getting important metrics:
"privileged","readinessprobe","livenessprobe" for Pods from kube-state-metrics.

I have checked the [pods](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md) doc page and found that the above important metrics are missing.

Also, We need the metric "kube_deployment_status_replicas_ready", which is not supported as of now as per [deployment docs](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/deployment-metrics.md) 

We need the above information for monitoring the k8s cluster using Kube-state-metrics.

**Comment by rahulbandariSensei** [comment]
Hi @lilic and @mrueg, Can you please prioritize it and assign it to me. I have context and I will like to contribute.
Thanks

**Comment by brancz** [comment]
Privileged doesn't need to be a separate metric, it can just be added to the container info metric and health and readiness probes metrics are already available from the Kubelet (even as more useful counters).
