### ISSUE TITLE
Support returning cached results from api server (resourceVersion=0)

### ISSUE THREAD

**Issue by jpdstan** [kubernetes/kube-state-metrics#1518]
**What would you like to be added**:

The ability to specify whether or not to use the k8s api server by setting the `resourceVersion` parameter ([docs](https://kubernetes.io/docs/reference/using-api/api-concepts/#the-resourceversion-parameter)). 

**Why is this needed**:

This would be immensely helpful for us as we run this application at quite a large scale (about 8mil total timeseries, 37k pods / cluster).

We constantly get these errors, which we presume is the cause for many of our metrics to not reflect reality (e.g. terminated pods that still exist as `Running` in metrics):

```
W0630 18:02:48.644785       1 reflector.go:302] k8s.io/kube-state-metrics/internal/store/builder.go:314: watch of *v1.ConfigMap ended with: too old resource version: 2066904261 (2099124935)
```

(not just with `ConfigMaps` but every resource type)

We don't need to be so strongly consistent, thus it would be nice to allow expose this option.

**Describe the solution you'd like**

Allow for a CLI arg `--use-api-server-cache` that will explicitly input `resourceVersion=0` to the api server calls.

**Additional context**

Example of a client that does this: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/commit/3e11f395e5539156bec990d9b71683f0b4fe7c75

**Comment by liangyuanpeng** [comment]
I want to work for it and it's will be great if someone can get me some novice tips.

**Comment by fpetkovski** [comment]
Hi @liangyuanpeng, thanks for taking the initiative and you're more than welcome to work on this. 

To start with, maybe try to run KSM locally and verify you can access metrics on localhost:8080/metrics. Then investigate the codebase a bit and see how you can implement this feature. We have a #kube-state-metrics channel in the Kubernetes slack where you can ask concrete questions if you get stuck.

**Comment by liangyuanpeng** [comment]
> Hi @liangyuanpeng, thanks for taking the initiative and you're more than welcome to work on this.
> 
> To start with, maybe try to run KSM locally and verify you can access metrics on localhost:8080/metrics. Then investigate the codebase a bit and see how you can implement this feature. We have a #kube-state-metrics channel in the Kubernetes slack where you can ask concrete questions if you get stuck.

Thanks for your patience! I have completed the feature, i think... and i  am checking my code.  

/assign
