### ISSUE TITLE
Get metrics only for one namespace

### ISSUE THREAD

**Issue by zenman94** [kubernetes/kube-state-metrics#152]
Dear all,

I try to deploy monitoring on a CaaS. I'm limited to one namespace on a Kubernetes cluster and I try to monitor deployments, replicas, respawn in this namespace.
When I try to deploy kube-state-metrics I have a lot of error because it list all cluster objects : 
_User *** cannot list all pods in the cluster_

Is it possible to limit listing activity only for one or some namespace depit of all cluster?

Regards

**Comment by brancz** [comment]
It is currently not possible, but can be implemented. Do you want to give it a shot?

**Comment by zouyee** [comment]
some resource are unscoped with namespace,such as node,etc.

**Comment by brancz** [comment]
That's absolutely correct @zouyee, I would say that we still include all objects of those kinds, and then a user has to disable those collectors if they are not wanted.

**Comment by andyxning** [comment]
Working on this recently. :)

**Comment by andyxning** [comment]
@zenman94 @zouyee I have proposed a PR to add this functionality to kube-state-metrics in #201 . PTAL.

As for resources, i.e. nodes, which do not binding with a namespace, you should disable them with `collectors` command line argument like @brancz advised. :)
