### ISSUE TITLE
Support KSM 2.0

### ISSUE THREAD

**Issue by invidian** [kubernetes/kube-state-metrics#1526]
Right now, when running with KSM 2.0, Horizontal Pod Autoscaler (HPA) metrics are not available, as they has been renamed: https://github.com/kubernetes/kube-state-metrics/pull/1003

**Comment by lilic** [comment]
Hey, not sure I understand what this means? To support kube-state-metrics 2.0, can you explain?

**Comment by invidian** [comment]
Aha! I remembered I opened this issue, but turns out in the wrong repository! :smile: Sorry for the noise!
