### ISSUE TITLE
metric are not geting scraped after updating it to 2.0.0 from 1.9.8

### ISSUE THREAD

**Issue by ashdon4u** [kubernetes/kube-state-metrics#1527]
**What happened**:
after I upgrade to 2.0.0 version below metrics are not getting scraped 

        kube_hpa_status_desired_replicas
	kube_hpa_spec_min_replicas
	kube_hpa_spec_max_replicas

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
older chart (kube-prometheus-stack-15.2.3)  and value file (atm.yaml attached)

new chat(kube-prometheus-stack-16.12.1) and values file (only changed the image tag )

helm upgrade --install prom-operator kube-prometheus-stack-16.12.1.tgz  --values=atm.yaml --namespace=monitoring --set nameOverride=prometheus-operator

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 2.0.0 from 1.9.8
- Kubernetes version (use `kubectl version`):1.17
- Cloud provider or hardware configuration:AWS
- Other info:

**Comment by fpetkovski** [comment]
Per [CHANGELOG](https://github.com/kubernetes/kube-state-metrics/blob/master/CHANGELOG.md)
```
[CHANGE] v2: Rename hpa metrics to use full horizontalpodautoscaler #1003 All metrics with prefix of kube_hpa_ were renamed to kube_horizontalpodautoscaler_
```
