### ISSUE TITLE
Allowlist problem

### ISSUE THREAD

**Issue by mrmassis** [kubernetes/kube-state-metrics#1538]
**What happened**:
When I configure --metric-allowlist to export a set of metrics, two metrics that I didn't configure appear.

**What you expected to happen**:
Only exporte the metrics that are in the whitelist!

**How to reproduce it (as minimally and precisely as possible)**:
I configure my kube-state-metrics with the configuration below:
```
        - --resources=cronjobs
        - --resources=daemonsets
        - --resources=deployments
        - --resources=nodes
        - --resources=pods
        - --resources=statefulsets
        - --metric-allowlist=kube_pod_info,kube_cronjob_status_active,kube_node_status_capacity,kube_pod_container_status_restarts_total,kube_deployment_status_replicas_available,kube_deployment_status_replicas,kube_deployment_metadata_generation,kube_pod_container_status_last_terminated_reason,kube_pod_container_status_waiting_reason,kube_pod_container_info,kube_statefulset_status_replicas_current
```

The total metrics that I allow is  11 metrics. However, when I do a curl in /metrics I receive the metrics bellow:
```
kube_cronjob_status_active
kube_deployment_status_replicas
kube_deployment_status_replicas_available
kube_deployment_status_replicas_unavailable
kube_deployment_status_replicas_updated
kube_deployment_metadata_generation
kube_node_status_capacity
kube_pod_container_info
kube_pod_container_status_last_terminated_reason
kube_pod_container_status_restarts_total
kube_pod_container_status_waiting_reason
kube_pod_info
kube_statefulset_status_replicas_current
```

Look, the metrics  `kube_deployment_status_replicas_updated` and  `kube_deployment_status_replicas_unavailable` were'nt configured to be exported. 

**Environment**:
- kube-state-metrics version: kube-state-metrics:2.1.0-debian-10-r23

**Comment by fpetkovski** [comment]
Hi @mrmassis, the allowlist value is a regular expression. The reason why `kube_deployment_status_replicas_updated` shows up is because you have `kube_deployment_status_replicas` in the allowlist. The following should resolve the problem 

Adding `$` at the end of `kube_deployment_status_replicas` should resolve the problem.

**Comment by mrmassis** [comment]
Tkz so much by support.
I will do it.
