### ISSUE TITLE
Documentation on Sharding Features / Status of experimental AutoSharding Feature

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#1546]
**What would you like to be added**:
As @SuperQ made me aware of, the documentation around Sharding is lacking some information on which to use when.
https://github.com/kubernetes/kube-state-metrics/blob/master/README.md#horizontal-scaling-sharding
**Why is this needed**:
Improve User Experience
**Describe the solution you'd like**
Document:
* Auto Sharding is marked as experimental since 2019 - is it still?
* Explain when to use AutoSharding vs. fixed argument driven sharding
* Make it clear what is the preferred / supported method.
 
**Additional context**
I believe autosharding is useful when your workloads change a lot in scale (so you can scale the statefulset instead of a redeploy), but comes with the complexity of a statefulset compared to a regular Kubernetes deployment.

**Comment by SuperQ** [comment]
I think there also needs to be some more documentation around sharding in the tooling used to deploy this. For example, there is [some of this mentioned in the helm chart](https://github.com/prometheus-community/helm-charts/blob/0b0956ec3fb3f2af1a61f652d9c0e0a350cf988e/charts/kube-state-metrics/values.yaml#L11-L18). But it seems like it only supports AutoSharding. Which I was just told is not recommended.
