### ISSUE TITLE
missing cAdvisor mertics issue

### ISSUE THREAD

**Issue by rkydybets** [kubernetes/kube-state-metrics#1547]
kube-state-metrics is installed from https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack
some metrics `container_memory_working_set_bytes` and `container_spec_memory_limit_bytes` and other

why i have no idea, i have restarted the kube-state-mertics but not succes working for monitoring them
and increase the resources to kube-state-mertics

and one remark, i have 6 environments with the same configuration, on 5 of the it is not reproduce, and only in the the biggest cluster with 40 nodes it appears 

**Environment**:
- kube-state-metrics version:  2.1.0
- Kubernetes version (use `kubectl version`): 1.21.2
- Cloud provider or hardware configuration:
- Other info:

**Comment by fpetkovski** [comment]
Hello :wave: , KSM is not related in any way to cAdvisor and does not export `container_memory_working_set_bytes` and `container_spec_memory_limit_bytes`. Are you saying that you expect to see them but you don't?
