### ISSUE TITLE
"regex" does not work for daemonset

### ISSUE THREAD

**Issue by felipeek** [kubernetes/kube-state-metrics#1572]
**What happened**:

My alert is not triggered when I use a regex in the alert expression

**What you expected to happen**:

My alert should have been triggered

**How to reproduce it (as minimally and precisely as possible)**:

My expression is:
```
      expr: |
        kube_daemonset_status_number_ready{daemonset="hdl-files-volume-csi-*"}
          /
        kube_daemonset_status_desired_number_scheduled{daemonset="hdl-files-volume-csi-*"} < 1.00
```

The daemonset name is:
```
daemonset="hdl-files-volume-csi-016fbce91d7848a8048b9d6e10b6a357a065d4284f85a0a119f97c1639deab01"
```

This alert does not get triggered.

If I change my expressions to:
```
      expr: |
        kube_daemonset_status_number_ready{daemonset="hdl-files-volume-csi-016fbce91d7848a8048b9d6e10b6a357a065d4284f85a0a119f97c1639deab01"}
          /
        kube_daemonset_status_desired_number_scheduled{daemonset="hdl-files-volume-csi-016fbce91d7848a8048b9d6e10b6a357a065d4284f85a0a119f97c1639deab01"} < 1.00
```

Then the alert is triggered.

**Anything else we need to know?**:

I suspect this was supposed to work, but this behavior is not documented, so idk.

**Environment**:
- kube-state-metrics version: 1.9.3
- Kubernetes version (use `kubectl version`): 1.20
- Cloud provider or hardware configuration:
- Other info:

**Comment by fpetkovski** [comment]
Hi @felipeek, this is not really a kube-state-metrics issue.

Looking at your query, I noticed that the regular expression you are using is not correct. Selecting label values using a regular expression is done with the `=~` operator, so in your example it would be:
```
kube_daemonset_status_number_ready{daemonset=~"hdl-files-volume-csi-.+"}
```

For information on how to use PromQL, you should refer to the Prometheus documentation: https://prometheus.io/docs/prometheus/latest/querying/basics/#instant-vector-selectors

**Comment by felipeek** [comment]
@fpetkovski thank you so much! I will give it a shot. The strange part is that I was doing this exact same query with `pod=` instead of `daemonset=` and it was working fine, this is why I didn't suspect that the error was in the query.
