### ISSUE TITLE
Some pod status reasons missing in podStatusReasons var and kube_pod_status_reason metric

### ISSUE THREAD

**Issue by idsvandermolen** [kubernetes/kube-state-metrics#1573]
**What happened**:
We are trying to monitor pods in `Failed` phase with reasons `Shutdown` or `NodeAffinity`. However, the `kube_pod_status_reason` metric only exposes `NodeLost`, `Evicted` and `UnexpectedAdmissionError` reasons (see [pod-metrics.md](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md) and [pod.go](https://github.com/kubernetes/kube-state-metrics/blob/master/internal/store/pod.go#L37))

Here's an example of the status part of a pod we saw (used `kubectl get po <pod name> -o yaml`)
```
status:
  message: Pod Predicate NodeAffinity failed
  phase: Failed
  reason: NodeAffinity
  startTime: "2021-09-09T07:23:22Z"
```
And [here](https://stackoverflow.com/questions/68727863/pods-are-getting-stuck-in-shutdown-status) you can find an example of Failed pods with `Shutdown` reason

**What you expected to happen**:
pod status reasons `Shutdown`, `NodeAffinity` and possibly others should be added to `kube_pod_status_reason` metric

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
See also https://github.com/kubernetes/kube-state-metrics/issues/1389#issuecomment-867945016
We checked the [v1.22 API docs](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#podstatus-v1-core), but couldn't find a predefined list of possible values for `reason`.
`Shutdown` reason was introduced in 1.20 (https://kubernetes.io/docs/concepts/architecture/nodes/#graceful-node-shutdown)

**Environment**:
- kube-state-metrics version: `v2.2.0`
- Kubernetes version (use `kubectl version`): `v1.18.20` for `NodeAffinity` and `v1.20.8` for `Shutdown`
- Cloud provider or hardware configuration: GKE
- Other info:

**Comment by fpetkovski** [comment]
Hi @idsvandermolen, thanks for reporting this issue. The rationale behind limiting the metric to just a handful of reasons was to control the cardinality. 

Since you already looked into the codebase, would you be interested in adding `Shutdown` or `NodeAffinity` as exported reasons as well?

**Comment by idsvandermolen** [comment]
> Hi @idsvandermolen, thanks for reporting this issue. The rationale behind limiting the metric to just a handful of reasons was to control the cardinality.
> 
> Since you already looked into the codebase, would you be interested in adding `Shutdown` or `NodeAffinity` as exported reasons as well?

We already suspected it was because of cardinality issues. I can have a look at the code, do you happen to know if there's a authoritative source for possible pod status reasons like `NodeAffinity` or `Shutdown`

**Comment by fpetkovski** [comment]
That's a good question, I am not sure if there is such an authoritative source. For now we can add the two new reasons that you needed and we can think about how to scale the approach if more use cases come up
