### ISSUE TITLE
Implement a mechanism for opt-in metrics

### ISSUE THREAD

**Issue by fpetkovski** [kubernetes/kube-state-metrics#1574]
**What would you like to be added**:
A way to enable potentially risky metrics through an opt-in command line argument.

**Why is this needed**:
New metrics are regularly added to kube-state-metrics and KSM versions automatically expose these new metrics on the `/metrics` endpoint. Because of this, we have to be very careful when deciding which metrics KSM should include in order to not break users when they upgrade to a new version.

**Describe the solution you'd like**
One possible solution would be to add an additional command line argument through which additional metrics can be enabled. Ideally, users should be able to opt-into each of those metrics individually by specifying them as values to the arg. Examples of metrics which would require an explicit opt-in are those that can potentially have high cardinality. This will allow the community to contribute metrics which enable deeper visibility into their cluster and users can enable those metrics explicitly for themselves. Users which run KSM with the default settings will not be affected by such changes.

**Additional context**
Issues that were closed in the past due to a lack of such mechanism:
* https://github.com/kubernetes/kube-state-metrics/issues/348
* https://github.com/kubernetes/kube-state-metrics/issues/167
* https://github.com/kubernetes/kube-state-metrics/issues/1394

**Comment by Serializator** [comment]
@fpetkovski, I'm thinking about working on this but whilst scrolling through the code I noticed `metric-allowlist` and `metric-denylist`, in what way do these defer from the proposed solution?

https://github.com/kubernetes/kube-state-metrics/blob/7fd83751066b39d6f80fd31ee190d1cd2cd6352a/pkg/options/options.go#L91

**Comment by fpetkovski** [comment]
Hey @Serializator, thanks for looking into this. The idea was to have metrics that are not exported by default and can be added through an explicit opt-in mechanism. I don't specifically know if we could reuse the `metric-allowlist` flag, but it might be an option worth exploring. Alternatively we could also add a new flag along the lines of `--additional-metrics` which is going to allow toggling these additional metrics by name or regex.

**Comment by Serializator** [comment]
Thank you for clarifying @fpetkovski, using `--metric-allowlist` and `--metric-denylist` wouldn't support an opt-in kind of approach as they are exclusive and are more of an absolute "what metrics I want or not want" rather than "what metrics do I want **additionally** to those that are already enabled by default",  I understand now.

I would suggest using `--opt-in-metrics` as I think the term "opt-in" better represents what it is actually doing, though I don't really know how to explain "why" I think it better represents it so using `--additional-metrics` is fine by me too.

Will see if I have the time to work on this and if so I will assign it to myself once I begin working on it!

**Comment by Serializator** [comment]
I created a PR (https://github.com/kubernetes/kube-state-metrics/pull/1632) related to this issue with the purpose of refactoring some of the code to allow for easier extensibility (e.g. to add an opt-in metric family filter).

**Comment by Serializator** [comment]
#1632 is merged and I will continue working on the opt-in functionality this weekend or maybe somewhere in the evening in the next few days.
