### ISSUE TITLE
Kube-State-metrics 2.2.0 not resolving PodDisruptionBudget percentages

### ISSUE THREAD

**Issue by dbarranco** [kubernetes/kube-state-metrics#1579]
Hello, team!

**What happened**:

I have recently upgraded the kube-state-metrics version I'm running in my Kubernetes cluster form the 1.9.7 version to the 2.2.0 one (latest release compatible with Kube 1.19).

After this upgrade some Prometheus alerts that were based on the `kube_deployment_spec_strategy_rollingupdate_max_unavailable` metrics started firing. Specifically, this is the Prometheus alert:

```
sum by(deployment) (kube_deployment_status_replicas_unavailable{namespace="prod-namespace"}) >= sum by(deployment) (kube_deployment_spec_strategy_rollingupdate_max_unavailable{namespace="prod-namespace"})
```

Just to alert us if there are more replicas unavailable than it should. 
Digging a bit in the metrics, it seems that in the `1.9.7` version Kube-state-metrics is able to compute the PodDisruptionBudgets that are based on percentages, in example:

```
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
```

But not in the `2.2.0` version. It seems now it is mandatory to base the PodDisruptionBudgets in: 

```
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 1
```

**What you expected to happen**:

I would have expected kube-state-metrics to be able to resolve the different percentage values.

**How to reproduce it (as minimally and precisely as possible)**:

Run Kube-state-metrics 1.9.7 and 2.2.0 in a Kubernetes cluster and take a look at the metrics.

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version:  1.9.7 && 2.2.0
- Kubernetes version (use `kubectl version`): v1.19.10
- Cloud provider or hardware configuration: AWS EC2 instances
- Other info:

**Comment by fpetkovski** [comment]
Hi @dbarranco, thanks for this report.

I tested this metrics with a deployment of 10 replicas and a maxUnavailable of 25%. KSM reports the following series:
```
kube_deployment_spec_strategy_rollingupdate_max_unavailable{namespace="default",deployment="nginx"} 2
```

To me looks like the correct behavior. Were you expecting to see something else?

**Comment by dbarranco** [comment]
Hey @fpetkovski 
Thanks for the information.

In my example, I was running a 3-replicas deployment and the difference I saw from old versions to this one is that:

* In the 1.9.7 version, a `maxUnavailability` of the 25% of pods would be rounded up to 1 replica.
* In the 2.2.x version, a `maxUnavailability` of the 25% of pods would be rounded up to 0 replicas.

Configuring higher percentages (40% so in a 3-replicas deployment the max.Unavailability is >1) works:

![Screenshot_2021-10-06_at_11_36_36](https://user-images.githubusercontent.com/9199512/136178602-44b76206-938d-4a22-bef3-55e70c24fbbb.png)

Is this a desired change?
