### ISSUE TITLE
Failed to pull image "k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.0":

### ISSUE THREAD

**Issue by jonasmulticloudiac** [kubernetes/kube-state-metrics#1588]
I tried to install kube-prometheus-stack- but I have this  errors on pod kube-state-metrics.

  Warning  Failed     4s (x3 over 39s)   kubelet            Failed to pull image "k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.0": rpc error: code = Unknown desc = failed to pull and unpack image "k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.0": failed to resolve reference "k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.0": failed to do request: Head https://k8s.gcr.io/v2/kube-state-metrics/kube-state-metrics/manifests/v2.2.0: dial tcp 172.217.192.82:443: connect: no route to host

kubernetes v19.11

**Comment by fpetkovski** [comment]
`docker pull k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.0` seems to work for me so it could have been an intermittent issue. Are you still able to reproduce it?
