### ISSUE TITLE
No replicaset kube state metrics in Prometheus

### ISSUE THREAD

**Issue by ercindemir** [kubernetes/kube-state-metrics#1590]
I'm trying to set some alarms based on [replica set metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/replicaset-metrics.md) but Prometheus cannot find replicaset kube state metrics while browsing expressions. What would be the problem with that? On Prometheus dashboard, I can see lots of metrics, which is in kube state metrics repo, but replica sets. Is it kube-metric-state causing this issue?

Kube state metrics version: v1.9.7
K8s: 1.18

For example, I can see most of [deployment metrics ](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/deployment-metrics.md)on the dashboard, but no metrics for replica sets.
![Screen Shot 2021-09-27 at 12 33 13 PM](https://user-images.githubusercontent.com/85083642/134960509-ecc58ead-cd52-485c-94ac-568431da9264.png)

**Comment by fpetkovski** [comment]
Replicaset metrics should be available in 1.9: https://github.com/kubernetes/kube-state-metrics/blob/release-1.9/docs/replicaset-metrics.md

**Comment by ercindemir** [comment]
@fpetkovski yes, I checked that, too. But I can't fix any metrics whereas I can find daemon sets or stateful sets.

**Comment by fpetkovski** [comment]
Have you checked the logs of KSM to see whether there are any warnings or errors? Also, could you provide the deployment yaml you're using to run KSM?

**Comment by ercindemir** [comment]
thanks @fpetkovski! The service account had some missing privileges. Now, it's working as expected. I'm closing the issue.
