### ISSUE TITLE
Phase metrics are not following enumeration semantics.

### ISSUE THREAD

**Issue by fabxc** [kubernetes/kube-state-metrics#161]
For pod conditions we introduced enumerations (true, false, unknown). For each possible state, an object exposes a time series. The series for the condition the pod is currently is set to 1, the others to 0.

Now we have new metrics like the pod phase, which broke with that pattern and just expose a single series by flipping the label value to whatever phase we are currently in.
This breaks various handy computations and is inconsistent in general.

In general, we should just add it back. What's making me hesitant still is the series blow up for a relatively small piece of information. Possible phases are: Pending, Running, Succeeded, Failed, Unknown.

@brian-brazil

**Comment by brian-brazil** [comment]
There's generally 3 options:

1) have it as a single enum time series. Hard to use.

2) Have one time series per potential state. Easy to use, but creates many time series.

3) Have one or more bools that capture the states the user really cares about, e.g. `is_finished` would cover succeeded and failed. This depends on use cases.

You could combine 1) and 3), I don't think anyone is doing 3) anywhere currently.

@superq

**Comment by brancz** [comment]
We should figure this out before GA, right now we're still able to break, but once we go GA it will be harder/not possible.

**Comment by brancz** [comment]
cc @discordianfish
