### ISSUE TITLE
Kube_job_owner missing owner_kind and owner_name

### ISSUE THREAD

**Issue by zarrarrana** [kubernetes/kube-state-metrics#1612]
**What happened**:

In kube_job_owner metrics 'owner_kind' and 'owner_name' are none for cronjob owned  jobs.
owner_kind="\<none\>"
owner_name="\<none\>"

**What you expected to happen**:

Expecting owner_kind and owner_name to be populated. 

**How to reproduce it (as minimally and precisely as possible)**:
Run a cronjob and see the metrics in prometheus.

**Environment**:
- kube-state-metrics version: v2.2.0
- Kubernetes version (use `kubectl version`): 1.21
- Cloud provider or hardware configuration: EKS

**Comment by pawcykca** [comment]
Hi @dgrisonnet,

I have similar problem for jobs that doesn't have `metadata.ownerReferences` field.
For example, jobs created by Ingress Nginx Controller:
```
kube_job_owner{namespace="ingress-nginx",job_name="ingress-nginx-admission-patch",owner_kind="<none>",owner_name="<none>",owner_is_controller="<none>"} 1
kube_job_owner{namespace="ingress-nginx",job_name="ingress-nginx-admission-create",owner_kind="<none>",owner_name="<none>",owner_is_controller="<none>"} 1
```
Why in such a case `kube-state-metrics` does not return just "" as a value instead of the current "<none>" value?
