### ISSUE TITLE
Decrease number of labels for some metrics

### ISSUE THREAD

**Issue by loburm** [kubernetes/kube-state-metrics#162]
I'm working on integration of kube-state-metrics with prometheus-to-sd. Recently have met one really big issue related to the metric kube_pod_labels. As I have understood this metric in theory can have unlimited number of labels attached to it:

https://github.com/kubernetes/kube-state-metrics/blob/3bf74507e082607d9ce6d5c935efe6459d67099d/collectors/pod.go#L220

Unfortunately we can't create metrics in the Stackdriver that have more than 10 labels (and I assume that other systems also can't handle big number of labels). Is it a known issue and is there any plans of fixing such behavior?

/c @piosz

**Comment by matthiasr** [comment]
If someone attaches more than 10 labels to their Kubernetes pod, how should that be represented in StackDriver?

**Comment by fabxc** [comment]
What would you suggest to do? The only viable solution seems to be to truncate the list of labels at a certain point or to split it up into `kube_pod_labels_{1,...,N}`.
I think any modifications to the model kube-state-metrics exposes is the wrong place to work around limitations of the ingesting system. The next system can only hold 8 labels – what do we do then?

The labels metric is indeed a special case, though various `*_info` metrics may also grow beyond 10 labels, even though rarely.
Maybe the easiest solution for you is simply to not ingest those and pull such meta information from elsewhere if needed.

**Comment by piosz** [comment]
@fabxc my understanding was that we want to have a limited cardinality of metrics, while by simple 1:1 mapping of Kubernetes labels to Prometheus labels we can't control this at all. I think having >10 labels is fine as far as it's a limited set. Am I wrong?

**Comment by matthiasr** [comment]
the total cardinality of this metric is still limited to 1 per pod in the cluster. that's as limited as we can reasonably get it :)

Prometheus & its data model do not impose a limit on the number of labels, and neither does Kubernetes. There is already a precedent for downstream systems having issues with this, OpenTSDB is limited to 8 labels (by default?). I agree with @fabxc that the exporter is not the right place to impose a downstream limitation. Either limit how many labels GKE users are allowed to attach to pods in their clusters, or handle the overflow when ingesting into systems that cannot handle them.

**Comment by fabxc** [comment]
> There is already a precedent for downstream systems having issues with this, OpenTSDB is limited to 8 labels (by default?) 

I think they worked on getting rid of that a while ago.

@piosz right, we care about metric cardinality being within estimate-able bounds. That's typically violated if we have an unknown number of values for different labels and those labels occurring in arbitrary combinations with each other.
Here we have a lot of labels – but the set is generally fixed for the pod.

**Comment by andyxning** [comment]
> I agree with @fabxc that the exporter is not the right place to impose a downstream limitation. Either limit how many labels GKE users are allowed to attach to pods in their clusters, or handle the overflow when ingesting into systems that cannot handle them.

I agree that limitation should be done in the tsdb storage instead of the upstream. And also, tsdb storage should make the result consistentand predicatable across multiple write when the lable number exceeds the limitation. Fox example, if we choose to drop some labels, we tsdb storage may first sort the labels and then cut at the first acceptable number. This makes the storaged labels predicatable.

**Comment by piosz** [comment]
Thanks for the clarification. If the cardinality of O(#pods) is fine let's close the issue then.

**Comment by loburm** [comment]
Thanks guys. That makes sense.
