### ISSUE TITLE
kube_endpoint_address_available and kube_endpoint_address_not_ready get computed by kube-state-metrics

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes/kube-state-metrics#1624]
**What would you like to be added**:

`kube_endpoint_address_available` and `kube_endpoint_address_not_ready` should be marked as deprecated and replaced in the future by an other metric which only export these information and calculation could be done afterwards.

**Why is this needed**:

> Yes, kube-state-metrics shouldn't be responsible for the computation. As an exporter, its only goal is to expose kubernetes objects data as metrics. Any computation such as getting the total number of ports should be done in promQL.

xref: https://github.com/kubernetes/kube-state-metrics/pull/1571#issuecomment-936327316

**Describe the solution you'd like**

* [ ] `kube_endpoint_address_available` and `kube_endpoint_address_not_ready` should be marked as deprecated
* [ ] new metrics is implemented
* [ ] `kube_endpoint_address_available` and `kube_endpoint_address_not_ready` will be removed

**Additional context**

Similar implementation got rejected in https://github.com/kubernetes/kube-state-metrics/pull/1571 and was reimplemented to do the computation via promQL later on.

**Comment by bavarianbidi** [comment]
#1549 is also doing some changes on this topic

**Comment by bavarianbidi** [comment]
> @dgrisonnet if #1761 got merged, what's the process to mark `kube_endpoint_address_available` and `kube_endpoint_address_not_ready` as deprecated?

+ @fpetkovski :point_up:

**Comment by mangkoran** [comment]
Apologize for the necrobump. The new `kube_endpoint_address` would have cardinality of all IPs in the endpoint subset. This seems to be a major cost compromise if we have service with a lot of endpoints and only want to count the available addresses and readiness of these addresses. Whereas `kube_endpoint_address_available` and `kube_endpoint_address_not_ready` should always have one series per endpoint.

**Comment by receperdogan** [comment]
> Apologize for the necrobump. The new `kube_endpoint_address` would have cardinality of all IPs in the endpoint subset. This seems to be a major cost compromise if we have service with a lot of endpoints and only want to have the number of available addresses and readiness of these addresses. Whereas `kube_endpoint_address_available` and `kube_endpoint_address_not_ready` should always have one series per endpoint. In our case we would like to check for service readiness and `kube_endpoint_address_available` and `kube_endpoint_address_not_ready`seems the better option to keep our cost down.

I agree with @mangkoran. for this reason, we downgraded the version.
