### ISSUE TITLE
kube_pod_info{start_time=...} documented, but unimplemented

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/kube-state-metrics#163]
See https://stackoverflow.com/a/44862179/717998.

**Comment by fabxc** [comment]
I noticed this yesterday myself and was quite happy it wasn't actually there in the form it is documented.
It's generally a classical example for something that can be captured as a number and thereby be used for alerts and more. As a string it has very limited value.

If there's a valid use case, I'm happy to review a pull request adding it as a metric with the Unix timestamp as a value.
