### ISSUE TITLE
Extend kube-state-metrics to support Custom Resource metrics

### ISSUE THREAD

**Issue by Garrybest** [kubernetes/kube-state-metrics#1640]
**What would you like to be added**:
Since the CRD has been widely used nowadays, is there any chance for `kube-state-metrics` to support Custom Resource metrics extension, a little bit like `kube-scheduler`. The repo [scheduler-plugin](https://github.com/kubernetes-sigs/scheduler-plugins) is based on the out-of-tree scheduler plugins framework. 

I suppose we could make small changes to make users define their own out-of-tree metrics stores so they could easily depend this project to add the Custom Resource metrics.

**Why is this needed**:
Now users should copy this repo and modify the source codes to support their own Custom Resource metrics because the `availableStores` is hard-code [here](https://github.com/kubernetes/kube-state-metrics/blob/0c9580d09c6ac8b35630813afbcc0fe217ce1874/internal/store/builder.go#L222-L253). I hope this could be more flexible so that users just only have to depend this repo in their own project, add their plugin registry and finally build the project to get a new customized `kube-state-metrics`.

**Describe the solution you'd like**
A simple solution is add a new func in `builder.go` and handle some details in `main.go`. Here is the new function.
```go
func RegisterOutOfTreeStores(
	name string,
	metricFamilies []generator.FamilyGenerator,
	expectedType interface{},
	listWatchFunc func(kubeClient clientset.Interface, ns string, fieldSelector string) cache.ListerWatcher,
) {
	availableStores[name] = func(b *Builder) []cache.Store {
		return b.buildStoresFunc(metricFamilies, expectedType, listWatchFunc, b.useAPIServerCache)
	}
}
```
The out-of-tree metrics store could be added into the `availableStores` to prevent hard-code. 

**Additional context**

**Comment by fpetkovski** [comment]
I think this is a really cool idea. There's also the alternative to enable dynamic configuration of exporters through a config file, but I think that's more complicated than what you're suggesting. 

Since you already have an idea of what needs to be done, would you be willing to make this contribution?

**Comment by Garrybest** [comment]
Hi @fpetkovski, thanks for your reply. That's great! I'm willing to make a contribution.

**Comment by dgrisonnet** [comment]
For what it's worth, a similar effort was tracked in https://github.com/kubernetes/kube-state-metrics/pull/1644.

**Comment by Garrybest** [comment]
> For what it's worth, a similar effort was tracked in #1210.

Hi @dgrisonnet, this issue is very helpful. I think it focuses on CRD itself rather than CR. IMO, both are important. 

#1644 has given a revision that helps `ksm` to add any out-of-tree CR metrics. As a result, the extension of `ksm` will be improved and the whole framework of `ksm` could benefit for CR metrics. Users could define their own metrics or override the built-in metrics just registering their own metrics factories. 

How do you think? 😉
