### ISSUE TITLE
prometheus didn't find it

### ISSUE THREAD

**Issue by 1998729** [kubernetes/kube-state-metrics#1641]
hi ～ I tried to deploy kube-state-metrics in version 1.22 of kubernetes, and deploy the manifest file in the stand of the example directory, but why is there no comment of prometheus auto-discovery service in the service, and how should he let prometheus discover it by itself?

**Comment by 1998729** [comment]
![image](https://user-images.githubusercontent.com/88186802/143242422-fee03e7d-24b3-4c93-9095-b83e8d8db7e4.png)
![image](https://user-images.githubusercontent.com/88186802/143242450-3c71123a-3723-4334-bc1c-461d3f392811.png)

**Comment by 1998729** [comment]
![image](https://user-images.githubusercontent.com/88186802/143242503-da2375ee-86c6-40e1-b395-ace9e0d10124.png)

**Comment by fpetkovski** [comment]
Hi @1998729, did you use kube-prometheus for your setup?
