### ISSUE TITLE
kube_service_info only showing kube-state-metrics as pod, job and container, not the actual pods that the services point to

### ISSUE THREAD

**Issue by doktormerlin** [kubernetes/kube-state-metrics#1642]
**What happened**:
When using `kube_service_info` all services listed only have the kube-state-metrics pod as the pod in `pod` field

**What you expected to happen**:
The `pod` field should be populated with the pods that the service points to

**How to reproduce it (as minimally and precisely as possible)**:
Use `kube_service_info` in your query

**Anything else we need to know?**:
None

**Environment**:
- kube-state-metrics version: 2.24.0
- Kubernetes version (use `kubectl version`): 1.20.0
- Cloud provider or hardware configuration: AWS EKS
- Other info:

**Comment by fpetkovski** [comment]
Hi @doktormerlin, I don't think this is a bug. 
KSM is intended to export metrics about the resources themselves with direct one-to-one mapping. 
So the `kube_service_info` metric should contain information about services and should not be aware of other resources in the cluster. Everything else should be calculated with PromQL instead.

In addition, the `pod` label that you're seeing is very likely coming from a Prometheus relabel config. As you can see in the docs[1], KSM does not export a `pod` label for the `kube_service_info` metric.

https://github.com/kubernetes/kube-state-metrics/blob/master/docs/service-metrics.md#service-metrics

**Comment by branttaylor** [comment]
Sorry @fpetkovski meant to tag you on the above message.

**Comment by fpetkovski** [comment]
We've had a similar issue before, but it seems it went stale along with the associated PR:
* https://github.com/kubernetes/kube-state-metrics/issues/1473
* https://github.com/kubernetes/kube-state-metrics/pull/1525

If you are interested, you maybe pick up from where the previous contributor left? We already have a mechanism no for explicit opt-in.

**Comment by ZoeQ** [comment]
I have the same question. Is there any solution such as  label_place in promql or relabel in service monitor or something like that to figure out the service of a pod belongs to?
