### ISSUE TITLE
docs: readme says 'go get' then 'make', but there's no makefile

### ISSUE THREAD

**Issue by drewp** [kubernetes/kube-state-metrics#1647]
Following https://github.com/kubernetes/kube-state-metrics#setup

```
go get k8s.io/kube-state-metrics
```

makes this
```
% ls *
bin:
kube-state-metrics

pkg:
mod  sumdb
```

Maybe the 1st command was meant to be a `git clone`?

**Comment by dgrisonnet** [comment]
Yeah, I think the README should be updated to use `git clone` instead of `go get` since its behavior changed a lot over time. Would you mind raising a PR @drewp?
