### ISSUE TITLE
pod_labels does not exists in kube_pod_labels metrics

### ISSUE THREAD

**Issue by rameshmishra777** [kubernetes/kube-state-metrics#1655]
Can i know what will be the workaround for this - we are using the below query to expect the pod/namespace for the cpu metrics and use the kube_pod_labels to get the pod name based on labels.

But somehow the `kube_pod_labels` prom metric doesn’t have the `pod labels`

```
max(kube_pod_labels{label_workflow_instance_id="$workflow_instance_id", label_workflow_vertex_id=~"$workflow_vertex_id", pod=~".+"} * on(pod) group_left sum by(pod) (label_replace(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace="pipeline-worker", container_name!="POD"},"pod", "$1", "pod_name", "(.+)")) * on(pod) group_left kube_pod_status_phase{phase="Running"}) by(label_workflow_vertex_id)
```

Able to see empty query result for this. we are having out cluster over EKS(attached the grafana UI screenshot)
![Grafana](https://user-images.githubusercontent.com/54392456/146801939-a981ee62-dafc-4bc3-bc5a-ff7c0e80a68b.png)

Any help here would be highly associated ( like what i am doing wrong here )

we are using the KSM 2.2.0 for the one above.

i even tried using this -> `--metric-labels-allowlist=pods=[*],deployments=[*]` but no luck still getting a blank query output with the above mentioned PromQL used.

**Comment by fpetkovski** [comment]
Can you confirm that KSM is exporting a `kube_pod_labels` metric on the /metrics endpoint?

**Comment by rameshmishra777** [comment]
@fpetkovski yes i can see the KSM is exporting the `kube_pod_labels` metric on the /metrics endpoint.
Below is the output for that - 

# HELP kube_pod_labels Kubernetes labels converted to Prometheus labels.
> # TYPE kube_pod_labels gauge

`kube_pod_labels{namespace="services",pod="horse-2-water-ais-postprocess-v2-1-1640055600-45hx6",uid="6daf2b55-d442-4d26-8d96-7ebf226ec3d5",label_controller_uid="96ae98e2-58ac-4d88-9fe1-e9d315045af8",label_job_name="horse-2-water-ais-postprocess-v2-1-1640055600"} 1
`

`kube_pod_labels{namespace="services",pod="nexus-iq-nexus-iq-server-76f46d65d-jn2rj",uid="7f1322dd-0d10-4342-8287-3d043c19655e",label_app_kubernetes_io_instance="nexus-iq",label_app_kubernetes_io_name="nexus-iq-server",label_pod_template_hash="76f46d65d"} 1`

`kube_pod_labels{namespace="services",pod="result-init-db-wsw7hvhoei-4fsbh",uid="4077e1ce-04f7-4662-b3c0-0f078d14cc66",label_app="result",label_controller_uid="eb7ffc35-6095-4b43-b157-76fda62f8925",label_job_name="result-init-db-wsw7hvhoei",label_orbitalinsight_com_values_repo_sha="d01a699",label_release="result"} 1
`

`kube_pod_labels{namespace="kube-system",pod="kube-proxy-7466p",uid="0d0d02f1-d00a-4726-88e7-363d6007a2e7",label_controller_revision_hash="676d7f9765",label_k8s_app="kube-proxy",label_pod_template_generation="1"} 1
`

`kube_pod_labels{namespace="nats-io",pod="nats-2",uid="ddb48713-fcd6-4f89-8557-dc2fc169873d",label_app="nats",label_app_kubernetes_io_instance="nats",label_app_kubernetes_io_name="nats",label_controller_revision_hash="nats-5f74c8944f",label_release="nats",label_statefulset_kubernetes_io_pod_name="nats-2"} 1`

**Comment by fpetkovski** [comment]
I don't see a workflow_instance_id, are you sure it exists on the pods?

**Comment by rameshmishra777** [comment]
i can see these labels on one for the pod for the respective **`streamy`** namespace - 

```
k get pod -n streamy streamy-frontend-995948784-w5hz6 -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
    orbitalinsight.com/logging.output: output-disk,output-es
    orbitalinsight.com/logging.parser: oi-service,oi-api,oi-middlewares
  creationTimestamp: "2021-12-03T20:17:50Z"
  generateName: streamy-frontend-995948784-
  labels:
    app: streamy
    orbitalinsight.com/values_repo_sha: 8e201f8
    pod-template-hash: "995948784"
    release: streamy
    service: frontend
  managedFields:
```

**Comment by fpetkovski** [comment]
Right, and those labels are exported as far ask I can see. However, your query is filtering kube_pod_labels by `label_workflow_instance_id="$workflow_instance_id"` and that labels does not exist on the pod.

**Comment by rameshmishra777** [comment]
What i am doing is - not the right way i should go ahead with ? any suggestion here what needs to be done for that now?

**Comment by fpetkovski** [comment]
Ok, but I also see a selector `label_workflow_vertex_id` in the query, but no vertex_id label on the pod

**Comment by rameshmishra777** [comment]
its because we dont have much pods running under that NS and i guess as of now we have just the one pod which i mentioned on the top with the kubectl describe.
