### ISSUE TITLE
k8s.io/kube-state-metrics/collectors not found

### ISSUE THREAD

**Issue by camilocot** [kubernetes/kube-state-metrics#166]
I'm tryng to download project dependencies but I get the following error for `k8s.io/kube-state-metrics/collectors` package:

```
go get k8s.io/kube-state-metrics/collectors
package k8s.io/kube-state-metrics/collectors: unrecognized import path "k8s.io/kube-state-metrics/collectors" (parse https://k8s.io/kube-state-metrics/collectors?go-get=1: no go-import meta tags)
```

**Comment by brancz** [comment]
not sure why it's not go get-able (I don't have any influence or knowledge of how the k8s.io stuff is handled), but if you clone the github repo into that source, it's builds properly for me

**Comment by camilocot** [comment]
Thanks. It's working properly.

**Comment by brancz** [comment]
happy to help

**Comment by ixdy** [comment]
`go get k8s.io/kube-state-metrics/collectors` should work now. thanks to @samuelmanzer for the fix.

**Comment by mvmn** [comment]
Doesn't work for me
