### ISSUE TITLE
Pod label rewriting policy is inconsistent with Prometheus operator's policy

### ISSUE THREAD

**Issue by franck102** [kubernetes/kube-state-metrics#1662]
**What happened**:
I created a pod with a "com.acme/fooBar" label.
The label was rewritten to **com_acme_foo_bar** (https://github.com/kubernetes/kube-state-metrics/issues/1162 )
The pod reports metrics, which are scraped by Prometheus thanks to a Prometheus Operator ServiceMonitor on the pod's service. The service monitor specifies
```
podTargetLabels:
    - com.acme/fooBar
```
In the scraped metrics the label is rewritten as **com_acme_fooBar**

**What you expected to happen**:

I expected Prometheus Operator and Kubestate to follow the same policy when ingesting pod labels.
At least a configuration switch should allow adopting the Prometheus Operator approach (which was kubestate's approach too before #1162 was merged)

**How to reproduce it (as minimally and precisely as possible)**:
Create a pod and a service selecting it, both with the same CamelCase label - e.g. fooBar.
Create a serviceMonitor for the service, with fooBar included in podTargetLabels.
kube_pod_labels metrics will have a foo_bar label, pod metrics will have a fooBar label.

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.2.4
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-0389ca3", GitCommit:"8a4e27b9d88142bbdd21b997b532eb6d493df6d2", GitTreeState:"clean", BuildDate:"2021-07-31T01:34:46Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Cloud provider or hardware configuration: AWS
- Prometheus Operator version: quay.io/prometheus-operator/prometheus-operator:v0.52.0
-

**Comment by fpetkovski** [comment]
The Prometheus Operator and KSM are independent projects. The reason for rewriting the label in KSM is well described in the issue that you linked. If you would like to see the same change in Prometheus Operator, then this issue is more suitable for that project.

**Comment by franck102** [comment]
> The Prometheus Operator and KSM are independent projects. The reason for rewriting the label in KSM is well described in the issue that you linked. If you would like to see the same change in Prometheus Operator, then this issue is more suitable for that project.

This is a disappointing stance. What I would like is for kubestate to not introduce breaking changes without at least providing a backward compatible setting/switch; especially when those changes conflict with other popular components of the ecosystem you rely on - even if they are independent projects.

**Comment by fpetkovski** [comment]
As described in the changelog, this was a breaking change introduced in a major version: https://github.com/kubernetes/kube-state-metrics/blob/master/CHANGELOG.md#v200-alpha--2020-09-16

My previous comment tried to explain that we cannot make changes just so that we align with other open source projects. In the long term that would mean complying with lots of different projects.

However, adding a command line option to _disable label rewriting_ would be a possible solution for your case.

**Comment by franck102** [comment]
Thanks, a switch to rewrite labels as they were rewritten before 1162 would be perfect.

I do understand your rationale for the change, and yes I could file a request with the Prometheus operator project to adopt your new policy… but I’ll presumably get a similar response.

**Comment by shotnaka** [comment]
Hi! I'm new to open source, and I'd like to try this good-first-issue first.

@slashpai I reassign myself. If you're still working on this issue and want an assignment, please leave a comment.

**Comment by slashpai** [comment]
@shotnaka no problem you can have this one
/unassign

**Comment by dgrisonnet** [comment]
I don't really see the point of adding this CLI flag.

> What I would like is for kubestate to not introduce breaking changes without at least providing a backward compatible setting/switch; especially when those changes conflict with other popular components of the ecosystem you rely on - even if they are independent projects.

There was no breaking change that was introduced by #1162 to KSM, the support for label metrics was added in 2.0 at the same time as the label rewriting feature. So we never broke the API. Also, the metrics were introduced as EXPERIMENTAL so there was no guarantee about them in the first place.

Even though kube-state-metrics and prometheus-operator are often used together, these projects are independents and are not tied together, so I don't understand your point. The only guarantees that kube-state-metrics offer with regard to compatibility with other projects is that it will follow Kubernetes skew policy and be compatible with its latest versions as well as follow the Prometheus best practices. Disabling label metrics relabeling would break the latter.
