### ISSUE TITLE
kube_statefulset_labels  cannot be queried

### ISSUE THREAD

**Issue by my1990** [kubernetes/kube-state-metrics#1664]
There are two labels in Minio / Minio cluster,
![image](https://user-images.githubusercontent.com/16768690/148916961-4da4ece6-6969-4720-9098-3321358e489d.png)

I set kube-state-metrics/values.yaml
metricLabelsAllowlist:
  - namespaces=[minio]
  - pods=[*]
![image](https://user-images.githubusercontent.com/16768690/148917869-25a00b09-71e5-4891-a953-4f089894a010.png)

![image](https://user-images.githubusercontent.com/16768690/148917238-82b23267-3bdc-4d72-9706-cdc11b91b550.png)

But why can't you find the label when querying the kube_statefulset_labels?

![image](https://user-images.githubusercontent.com/16768690/148917028-08248597-c771-4d99-bef2-d710bc09130c.png)

**Comment by fpetkovski** [comment]
You've only enabled labels for pods, but not for statefulsets. Can you try adding `statefulsets=[*]` as well?
