### ISSUE TITLE
kube_pod(_container)?_status_*, Add label for reason

### ISSUE THREAD

**Issue by SleepyBrett** [kubernetes/kube-state-metrics#167]
Right  now we're running into some issues that are hard to find with the current kube_pod_status_* and kube_container_status_* metrics.

On the pod_status side there are only four possible states (that I have seen) Running, Pending, Succeeded, Failed. One problem is that it's really hard to detect what kubernetes calls CrashLoopBackOff.

It might be nice to expose metrics more in line with what kubectl shows for pods and containers in the Status column of it's display which means digging into the  status.containerStatuses.state.*.reason field. Perhaps exposing this in a reason label.

Thoughts?

**Comment by fabxc** [comment]
AFAIK the "reason" is not a known enumeration but possibly an arbitrary field. That makes it not directly suitable for putting into a metric label.

Can you elaborate your use case a bit? In which cases is knowing "Failed" not enough for the stage where one would look at a metric?

**Comment by SleepyBrett** [comment]
For instance, I have to go through a lot of contortions to find if a pod is in crashloop backoff ( my current unsatisfactory solution is `(increase(kube_pod_container_status_restarts{namespace="kube-system"}[10m]) > 1)` but man would `kube_pod_status_phase{namespace="kube-system",reason="CrashLoopBackOff"}` be nicer.

Another case is due to a bug in docker, but it's been a bug for a long time and I'm not seeing any progress on resolving it. Occasionally a node's docker daemon will just become stuck. The way we notice it generally is a high number of pods stuck in Pending/Terminating on any given node. Unfortunately there are other reasons for pending state that create a high number of false positives in alerts like: `sum( max(kube_pod_status_phase{phase="Pending"}) by (pod,namespace) * on (pod,namespace)  GROUP_RIGHT(phase) kube_pod_info{}) by(node,phase) > 8` and I think I could improve the ham/spam ratio by having that reason field.

I do know what you mean about Reason not being a strict enum, but perhaps we could start by creating a list of common states and then just an "other" bucket.

**Comment by brancz** [comment]
I misunderstood this the first time I read it. I think this is more something that should be done once we as operators troubleshoot. This is indeed a completely free form value therefore this is likely to cause problems in terms of time-series churn.

**Comment by richerve** [comment]
There's a reason, for example I want to track the Eviction rate of Pods given that I'm implementing kube-reserved and system-reserved settings in kubelet, so I want to have graphs and alerts on Pod evictions. Aren't there well-known reasons to at least write an Enum with those? For example "Eviction" is even documented in the official API docs
