### ISSUE TITLE
kube_ingress_* metrics should contain IngressClass name

### ISSUE THREAD

**Issue by tzaspel-finatix** [kubernetes/kube-state-metrics#1672]
**What would you like to be added**:
Since Kubernetes 1.18 added the IngressClass resource, the kube_ingress_* metrics should include which Ingress has which IngressClass.

**Why is this needed**:
This is important because it provides the ability to filter the ingresses based on their IngressClass. Furthermore you can create alters based on the IngressClass or even if someone forgot to assign the correct IngressClass. Currently no [kube_ingress_*](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/ingress-metrics.md) metric has a label/tag which contains IngressClass. 

**Describe the solution you'd like**
Simply add to every kube_ingress_* metric a Label/Tag with the IngressClass in it.

**Additional context**

**Comment by Serializator** [comment]
There is an `ingressclass` label for the `kube_ingress_info` metric but this relies on the `kubernetes.io/ingress.class` annotation rather than the `ingressClassName` in the specification of the ingress.

**Comment by tzaspel-finatix** [comment]
Thanks for your response. 
You are right. There is a `ingressclass` label in `kube_ingress_info`. 
But when I use Cortex and query `kube_ingress_info` it doesn't provide a label with the Ingressclass.

![image](https://user-images.githubusercontent.com/90749078/151496167-829ac6c8-8d13-4991-a206-98d657f4d20d.png)

Maybe I explain it not correctly.

**Comment by fpetkovski** [comment]
Looks like the ingress class was added after the latest release. We'll cut a new release next week and you can upgrade to get that label.

**Comment by tzaspel-finatix** [comment]
Thanks, I greatly appreciate your prompt responses!
