### ISSUE TITLE
What is the correct readiness probe port?

### ISSUE THREAD

**Issue by dudicoco** [kubernetes/kube-state-metrics#1678]
Hi,

In https://github.com/kubernetes/kube-state-metrics/pull/858 @MIBc added `readinessProbe` on port `8080` within the example deployment manifest.
This was later changed in https://github.com/kubernetes/kube-state-metrics/pull/908 by @brancz to port `8081`.

Within the official helm chart the port is still configured as `8080`: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-state-metrics/templates/deployment.yaml#L113-L118

Which port is the correct one for readiness probe and why?

**Comment by dudicoco** [comment]
Thanks @fpetkovski.

In the end, everything is up for me to decide :)
However, I believe there should be an official recommendation, and currently it isn't consistent between the deployment manifest and the helm chart.

**Comment by fpetkovski** [comment]
I agree, we should at least document the options somewhere to avoid confusion.
