### ISSUE TITLE
0.6 release?

### ISSUE THREAD

**Issue by alamaison** [kubernetes/kube-state-metrics#168]
Is it a good time for a 0.6 release?  We use the public docker images and would like to take advantage of the recent StatefulSet support.

**Comment by bksteiny** [comment]
@alamaison there's some discussion about that here https://github.com/kubernetes/kube-state-metrics/issues/135

Unless something has changed, @brancz is targeting 1.0 (GA) for the next release.

**Comment by brancz** [comment]
I was on vacation for two weeks. First GA we still have to perform some scalability tests, but after that we should be good if nothing big comes up.

I have some other things that are higher priority for me right now, but after that I'll get right to this.

**Comment by andyxning** [comment]
@alamaison @bksteiny 1.0-rc1 has been released. 👏 .

@brancz should we close this issue?
