### ISSUE TITLE
	server returned HTTP status 403 Forbidden

### ISSUE THREAD

**Issue by ymwfish** [kubernetes/kube-state-metrics#1684]
Endpoint:
https://172.16.80.154:6443/api/v1/namespaces/kube-system/pods/http:kube-state-metrics-77879b89ff-rhw9b:8080/proxy/metrics

**Comment by ymwfish** [comment]
Is there a problem with my agent address? Or do you need some other authorization?

**Comment by ymwfish** [comment]
Prometheus is deployed on a single server and is not in the Kubernetes cluster

**Comment by fpetkovski** [comment]
Prometheus needs to be able to reach the IP address of kube-state-metrics. If it is running outside of the cluster, you might need to set up an ingress to expose it outside of kubernetes,

**Comment by ymwfish** [comment]
I currently use ingress as a static resource for access, thank you!

**Comment by tanzhenlong** [comment]
I also encountered the same problem, the browser can be accessed normally, but the prometheus interface reports a 403 error. how did you solve it

**Comment by ymwfish** [comment]
I currently use ingress as a static resource for access, thank you!
