### ISSUE TITLE
Record deployment labels

### ISSUE THREAD

**Issue by alamaison** [kubernetes/kube-state-metrics#169]
How can we filter the deployment metrics such as `kube_deployment_status_replicas_available` by labels we define in the deployment

We label each deployment/service/etc with the project it belongs to.  Each project has its own prometheus, and alerts are defined there.  We would like to be able to alert on replica unavailability, but without the project label being included in the metric, each project would end up alerting on all other projects too.  Is there a way to do this?

**Comment by matthiasr** [comment]
Generally, the idea is to "join" with a `kube_XXX_labels` metrics, but that metric does seem to be missing for deployments. Would you mind sending a PR? See [how it's done for services](https://github.com/kubernetes/kube-state-metrics/blob/be6842aa31d0ec421d27c33e4754f7f6a6cc16e0/collectors/service.go#L115-L116) for inspiration.

**Comment by brancz** [comment]
I'll be happy to review any PRs for this! :slightly_smiling_face:

**Comment by alamaison** [comment]
I've PRed #175 but I'm not a Go programmer so its a bit of a cargo-cult job.  I added statefulsets as well.

**Comment by andyxning** [comment]
@alamaison Maybe we could close this issue since #175 has been merged.

**Comment by brancz** [comment]
Agreed with @andyxning . Closing here. Thanks a lot for your effort @alamaison !
