### ISSUE TITLE
kube_namespace_status_phase overcounts when namespaces are specified

### ISSUE THREAD

**Issue by tyen-brex** [kubernetes/kube-state-metrics#1695]
**What happened**:

Updated flags to specific `--namespaces=a,b,c`. When fetching metrics from the kube-state-pod, there are duplicate `kube_namespace_status_phase` metrics

```
$ curl localhost:8080 | grep kube_namespace_status_phase | sort | uniq -c | grep Active
   3 kube_namespace_status_phase{namespace="a",phase="Active"} 1
   3 kube_namespace_status_phase{namespace="b",phase="Active"} 1
   3 kube_namespace_status_phase{namespace="c",phase="Active"} 1
```

**What you expected to happen**:

There are no duplicate `kube_namespace_status_phase` metrics for each namespace when using the `--namespaces` flags

**How to reproduce it (as minimally and precisely as possible)**:

1. Run kube-state-metrics with `--namespaces` flag
2. Fetch metrics and filter by `kube_namespace_status_phase`

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 2.3.0
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:

**Comment by liangyuanpeng** [comment]
I have reproduce it , let me check it.

/assign

**Comment by liangyuanpeng** [comment]
@tyen-brex 
After i check the history, you should get the metrics from `curl http://localhost:8080/metrics?namespace=kube-system&namespace=kube-public` when you run KSM for `--namespaces=kube-system,kube-public`.

Some issue and PR:
- https://github.com/kubernetes/kube-state-metrics/issues/368
- https://github.com/kubernetes/kube-state-metrics/pull/395
- https://github.com/kubernetes/kube-state-metrics/pull/1098
