### ISSUE TITLE
Tag 2.4.1 does not contain the version changes

### ISSUE THREAD

**Issue by mruoss** [kubernetes/kube-state-metrics#1698]
Hey there

Is it possible to force push the tag [v2.4.1](https://github.com/kubernetes/kube-state-metrics/releases/tag/v2.4.1) and re-create the Release to include this commit e52d8ace?

Background: Our update mechanism uses the files in the example folder of the tag as base. Now the examples on tag v2.4.1 still point to a non-existing docker image tag (2.4.0).

Also the assets on the Release contain examples that point to image 2.4.0.

**Comment by fpetkovski** [comment]
Ouch, sorry about that. We had issues with building the images for v2.4.0 so we published a new tag, but forgot the bump the version.

We can't overwrite tags, but we can publish 2.4.2. Do you have a workaround until then?

**Comment by fpetkovski** [comment]
We release patch versions only when there is explicit demand for it, but I think this would be a good case for it. I'll try to do it within the next few days.

**Comment by Duologic** [comment]
:wave: We just hit this too. I'll :+1: the main post and so should others hitting this issue so we can have a quick count of impact.
