### ISSUE TITLE
Ancestors name references in kube_pod_infos labels

### ISSUE THREAD

**Issue by sylr** [kubernetes/kube-state-metrics#1703]
**What would you like to be added**:

I'd like that `kube_pod_infos` be added labels corresponding of the names of their "ancestors" (`deployment`, `replicaset`, `daemonset`, `statefulset`, `job`, `cronjob`), e.g.:

```
kube_pod_info{namespace="monitoring",pod="kube-state-metrics-7c8d9fb9c4-xwd2l",deployment="kube-state-metrics",replicaset="kube-state-metrics-7c8d9fb9c4"}
kube_pod_info{namespace="monitoring",pod="prometheus-node-exporter-f6txq",daemonset="prometheus-node-exporter"}
kube_pod_info{namespace="monitoring",pod="some-cronjob-27439620-ljhqh",cronjob="some-cronjob",job="some-cronjob-27439620"}
kube_pod_info{namespace="monitoring",pod="some-job-ljhqh",job="some-cronjob-27439620"}
```

**Why is this needed**:

I believe this is needed so that it is possible to easily write queries with joins between pods and their ancestors, which is not possible with `created_by_kind` and `created_by_name` labels.

**Describe the solution you'd like**

Add `deployment`, `replicaset`, `daemonset`, `statefulset`, `job`, `cronjob` labels to `kube_pod_infos`.

Maybe remove `created_by_kind` & `created_by_name` as they would become redundant.

**Additional context**

**Comment by fpetkovski** [comment]
```
I believe this is needed so that it is possible to easily write queries with 
joins between pods and their ancestors
```
Is that because you currently need to know which ancestor metric to join with?

**Comment by sylr** [comment]
I want this so I can join `kube_pod_info` with its ancestor to allow advanced filtering in my grafana dashboard, e.g:

```
kube_deployment_created{namespace=~"$namespace",deployment=~"$deployment"}
* on (namespace, deployment)
kube_pod_info
* on (namespace, pod)
count(kube_pod_container_status_ready) without (container)
```

**Comment by fpetkovski** [comment]
Can you use `label_replace` to inject the desired label? e.g.
```
label_replace(kube_pod_info{created_by_kind="ReplicaSet"}, "deployment", "$1", "created_by_name", "(.+)-.+")
```
