### ISSUE TITLE
Add node name to Pod Metrics

### ISSUE THREAD

**Issue by bsamsom** [kubernetes/kube-state-metrics#1707]
**What would you like to be added**:
I would like for more of the metrics from kube-state-metrics to include the "node" label. 
**Why is this needed**:
Knowing which node the pod is running on is valuable information for triaging problems, and linking them to root causes. If for example you know node x is being worked on, being able to see this pod on on that node would let you know that the issue is likily expected while the work is happening.
**Describe the solution you'd like**
[pod metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/pod-metrics.md) like: kube_pod_status_phase and others would return an additonal label for what node the pod is running on.

**Additional context**
I have tried manaully adding this with:
      - source_labels: [__meta_kubernetes_pod_node_name]. 
        action: replace. 
        target_label: kubernetes_node. 

but unfortunalty that doent work, it pulls in name of the node the kube-state-metrics pod is running on and not the name of the node the pod in the metric is alerting on.

This looks to be a similar closed issue:
https://github.com/kubernetes/kube-state-metrics/issues/540

**Comment by fpetkovski** [comment]
You can always join multiple metrics. In your example, you can use the following query to get what you need:
```
kube_pod_status_phase * on(pod) group_left(node) kube_pod_info
```

KSM tries to control cardinality as much as possible and offload most calculations to PromQL.

**Comment by bsamsom** [comment]
While that works on an individual metric, im trying to get all of our KSM metric based alerts to include the node label so i dont have to edit/rewrite all of our kuberentes alerts just to see what node the pod is running on.


I dont suppsoe you know a way to do that without editing all of our alerts via a source label remap or something simialar that would actually pull the pods node and not the kube-state-metric pods node

**Comment by fpetkovski** [comment]
I see, in this case there's no simple way to add the label to all alerts. Unless @mrueg and @dgrisonnet have a reason why this can be problematic, I think it should be fine to add the node label to more pod metrics since there is a 1 to 1 mapping from pod to node.

**Comment by dgrisonnet** [comment]
Theoretically, it is fine to add the node name to the metrics as it doesn't increase the cardinality and it is useful information. However, since most of the pod metrics are marked as stable, I don't think we should add new dimensions to them.

**Comment by bsamsom** [comment]
@fpetkovski  @dgrisonnet Just following up to see if there has been an agreed upon descission on this as its been about a month since the last reply.

**Comment by dgrisonnet** [comment]
I would personally be against this change since it would break stable metrics for non-essential purposes. As mentioned by Filip before, this information can already be aggregated from other metrics.

**Comment by fpetkovski** [comment]
Since we don't have a consensus, I also wouldn't want to change the metric. 

Currently, our only way to evolve metrics beyond stable is to change them in a new major release.

**Comment by aspyker** [comment]
@bsamsom did you ever try taking this forward to kube-prometheus-stack folks? Would love to know if you found a solution as we are looking to rewrite many of their rules to deal with the same issue.

Specifically KubePod*/KubeDaemonset*/etc... from: 

https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack/templates/prometheus/rules-1.14

**Comment by bsamsom** [comment]
@aspyker I did not, we don't use the stack helm chart and decided to just live with the issue.

**Comment by mossad-zika** [comment]
@aspyker hello, could you please share if you eventually did it ?
