### ISSUE TITLE
autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by arajkumar** [kubernetes/kube-state-metrics#1711]
**What happened**:
The following warning is seen when you run KSM on k8s v1.23+ cluster,

```
warning "autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler"
```

**What you expected to happen**:
No warnings

**How to reproduce it (as minimally and precisely as possible)**:
 Run KSM on k8s v1.23+ cluster

**Anything else we need to know?**:

IIUC, KSM supports up to (latest - 3) k8s versions. Probably KSM can start use `autoscaling/v2 HorizontalPodAutoscaler` once k8s v1.25 goes GA.

**Environment**:
- kube-state-metrics version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:

Reference: https://bugzilla.redhat.com/show_bug.cgi?id=2069543

**Comment by liangyuanpeng** [comment]
k8s v1.25 have release and i think we can begin work for `autoscaling/v2 HorizontalPodAutoscaler`.

/assign

**Comment by JoaoBraveCoding** [comment]
Hello @liangyuanpeng do you plan to open a PR on this soon? If not I wouldn't mind help contributing for this issue :)
