### ISSUE TITLE
Allow wildcard or regex to whitelist labels (kube_pod_labels ...)

### ISSUE THREAD

**Issue by finkr** [kubernetes/kube-state-metrics#1715]
We use labels and taints to reserve and/or restrict some nodes for some software with licenced based on CPU or vCPU.
We have standardised the name of those taints and labels (like `lic_vendorname_productname`).

Therefore we wish we could whitelist all labels prefixed with `lic_*`

**Comment by fpetkovski** [comment]
As an alternative solution, could you drop unwanted labels at scrape time with metric relabel configs?
