### ISSUE TITLE
Deployment Time Metrics

### ISSUE THREAD

**Issue by caatclaudia** [kubernetes/kube-state-metrics#1719]
## Proposal

In a Cluster with more than one application, the deployment time of all the applications is an important metric:

- To calculate the time that is necessary if the deployment of an application needs to be restarted;
-  To find out if the time is acceptable (e.g.: in certain Clusters, it may be necessary that the deployment time is less than 1min).

So, the Deployment time of the pods on a specific namespace should be available in Prometheus metrics.

**Comment by fpetkovski** [comment]
Hello 👋, could you use the `kube_pod_created` metric?

**Comment by fpetkovski** [comment]
KSM exports `kube_pod_status_ready` which will be 1 as soon as the pod has become ready. Can you use that one?

**Comment by caatclaudia** [comment]
But the pod become Ready is different than Service that the pod provides become accessible, or not?

**Comment by fpetkovski** [comment]
To solve this, you can [define a readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes) on the pod to tell Kubernetes when it should consider the pod ready. For example, your service can expose an HTTP endpoint indicating whether it is ready or not. Once it becomes ready, the pod containing it will also become ready and the `kube_pod_status_ready` metric will go from 0 to 1.

**Comment by caatclaudia** [comment]
Ok, let me see if I understand. What you saying is to define a readiness probe (I agree) and after, I verify with metric `kube_pod_status_ready` when the value is 1, right? With the definition of readiness probe, this metric reports 1 when the probe becomes ready, is this?

I already tried to use the `prober_probe_total` metric but this metric takes come time to be reported and, in some cases, the first time that is reported, shows 3 probes with Successful (for example), and not just one as I wish.

**Comment by fpetkovski** [comment]
Yes, that would be the idea. 

Keep in mind that the metric is binary, so it will show 1 once the pod becomes ready, but it will not report the exact time when it became ready. The time can be inferred from the timestamp when KSM was scraped.
