### ISSUE TITLE
PV/PVC creation timestamp metrics

### ISSUE THREAD

**Issue by aidan-og** [kubernetes/kube-state-metrics#1724]
**What would you like to be added**:
Addition of 'created' metric on PV/PVC metrics, using `creationTimestamp` field, similar to existing metrics for other components.

**Why is this needed**:
We have Prometheus alerts which alert if a PV is predicted to fill up in X days. However, disk usage is variable during creation which causes quite a few false positives each time a PV is provisioned for a new resource. 

We want to suppress these alerts until the PVC is >N seconds old. In order to do this, we want to know the creation time of the resource.

**Describe the solution you'd like**
Add `*_created` metric to PVC metrics, similar to other resources.

**Additional context**

**Comment by dgrisonnet** [comment]
@aidan-og this sounds like a good idea, would you be interested in contributing these new metrics?

**Comment by aidan-og** [comment]
@dgrisonnet sure, I'll tackle it!

**Comment by bavarianbidi** [comment]
As #1741 got merged, this issue could be closed i guess?
