### ISSUE TITLE
duplicated metrics using ksm statefulset

### ISSUE THREAD

**Issue by youpai** [kubernetes/kube-state-metrics#1736]
### 1. versions
- k8s, v1.23.5
- kube-state-metrics, 2.4.2

### 2. problem(I'm not sure if it's a problem)
When I search the metrics by using prometheus ui, I get the result

![image](https://user-images.githubusercontent.com/29447211/169488699-7897ef34-69c5-4a91-8420-b16bd6377be5.png)

and other is similar

![image](https://user-images.githubusercontent.com/29447211/169489200-53775dfb-5274-4f63-a217-61b665ddf69f.png)

I want to know if it's a problem and why

**Comment by liangyuanpeng** [comment]
It have not duplicated , they value is different.

**Comment by youpai** [comment]
yeah，I misdescribed it，I want to know why they have different values

**Comment by fpetkovski** [comment]
I think this is fine, it might be caused by staleness from transitioning from one state to another in the CR. Are you seeing this consistently?

**Comment by youpai** [comment]
yeah，I think it occured at one time，but I always see it at any time. So how can I ensure it is fine

**Comment by fpetkovski** [comment]
It should be fine, you can add `== 1` at the end of your PromQL query to remove duplicates.

**Comment by youpai** [comment]
ok，thanks~
