### ISSUE TITLE
Release v2.5

### ISSUE THREAD

**Issue by splitice** [kubernetes/kube-state-metrics#1739]
Not exactly an issue, sorrry.

Is there any blockers to cutting a new release?

**Comment by fpetkovski** [comment]
Yes, we need to do this soon :) 

If you need something urgent until then, you can use the latest image from main: https://console.cloud.google.com/gcr/images/k8s-staging-kube-state-metrics/global/kube-state-metrics

**Comment by splitice** [comment]
Woot
