### ISSUE TITLE
Error when building from master

### ISSUE THREAD

**Issue by shiranp** [kubernetes/kube-state-metrics#174]
I don't have much experience with go so maybe i'm missing something.
I needed the StatefulSet collector so I am building from master in a docker image using the following Dockerfile:

    FROM golang:1.7-alpine
    
    ENV GOOS=linux GOARCH=amd64 CGO_ENABLED=0
    
    # Get Software
    RUN apk update \
     && apk add ca-certificates wget git\
     && update-ca-certificates
    RUN wget https://github.com/kubernetes/kube-state-metrics/archive/master.zip
    RUN unzip master.zip
    
    WORKDIR ./kube-state-metrics-master/
    
    # Build binary
    RUN cp -r ./vendor/* /go/src/
    RUN mkdir -p /go/src/k8s.io/kube-state-metrics/collectors/
    RUN cp -r ./collectors/* /go/src/k8s.io/kube-state-metrics/collectors/
    RUN go build -o /kube-state-metrics
    
    # Cleanup
    WORKDIR /
    RUN apk del --purge -f wget git
    
    ENTRYPOINT ["/kube-state-metrics", "--port=8080"]
    
* NOTE: I had some trouble with the dependencies so i just copied the contents of vendor directory to $GOPATH/src.

When i run the container and have my prometheus server scrape it (through nodePort service) I get the following error:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x547000]
    goroutine 187 [running]:
    panic(0x13341e0, 0xc420016060)
            /usr/local/go/src/runtime/panic.go:500 +0x1a1
    k8s.io/kube-state-metrics/collectors.(*statefulSetCollector).collectStatefulSet(0xc4203b6830, 0xc420340780, 0x0, 0x0, 0x0, 0x0, 0xc420275e94, 0x5, 0x0, 0x0, ...)
            /go/src/k8s.io/kube-state-metrics/collectors/statefulset.go:95 +0xa0
    k8s.io/kube-state-metrics/collectors.(*statefulSetCollector).Collect(0xc4203b6830, 0xc420340780)
            /go/src/k8s.io/kube-state-metrics/collectors/statefulset.go:85 +0x10c
    github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc4202f5470, 0xc420340780, 0x1be0000, 0xc4203b6830)
            /go/src/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x63
    created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
            /go/src/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x2b6

Any Suggestions?
Thanks.

**Comment by brancz** [comment]
What is your kubernetes version?

**Comment by shiranp** [comment]
@brancz I am running the api-server in a container with this image: gcr.io/google-containers/hyperkube-amd64:v1.5.2

**Comment by shiranp** [comment]
@brancz The Prometheus server is external by the way.

**Comment by shiranp** [comment]
I forgot to mention: i have no problems when i run the v0.5.0 image from gcr with the same setup.

**Comment by brancz** [comment]
My suspicion is that there are fields different in Kubernetes 1.6 (which is the version of the used version of client-go is based off of). Could you just start kube-state-metrics with the statefulset collector disabled? Also an example yaml of a statefulset that you are running in your cluster would also help (including the status object).

**Comment by andyxning** [comment]
Currently, client-go 2.0 is the dependency. According to the docs, it is compatible with Kubernetes 1.5.

**Comment by shiranp** [comment]
The all reason I'm building from master is because i need the statefulset collector.

    kubectl get statefulsets/elastic-data --namespace=some-app -o=yaml
    apiVersion: apps/v1beta1
    kind: StatefulSet
    metadata:
      annotations:
        pod.alpha.kubernetes.io/initialized: "false"
      creationTimestamp: 2017-07-10T10:46:40Z
      generation: 1
      labels:
        role: data
        service: elasticsearch
      name: elastic-data
      namespace: some-app
      resourceVersion: "6340525"
      selfLink: /apis/apps/v1beta1/namespaces/some-app/statefulsets/elastic-data
      uid: 0e7b6d7e-655d-11e7-a8d7-005056997206
    spec:
      replicas: 3
      selector:
        matchLabels:
          role: data
          service: elasticsearch
      serviceName: elastic-api
      template:
        metadata:
          annotations:
            pod.alpha.kubernetes.io/initialized: "true"
          creationTimestamp: null
          labels:
            role: data
            service: elasticsearch
        spec:
          containers:
          - args:
            - --cluster.name=some-app
            - --node.data=true
            - --node.master=false
            - --discovery.zen.ping.unicast.hosts=elastic-discovery
            - --index.number_of_shards=2
            - --index.number_of_replicas=1
            - --indices.store.throttle.max_bytes_per_sec=150mb
            env:
            - name: ES_HEAP_SIZE
              value: 4g
            image: elasticsearch:2.4.4
            imagePullPolicy: IfNotPresent
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /
                port: 9200
                scheme: HTTP
              initialDelaySeconds: 300
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 30
            name: elastic-data
            ports:
            - containerPort: 9200
              protocol: TCP
            - containerPort: 9300
              protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elastic-data-pvc
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          securityContext: {}
          terminationGracePeriodSeconds: 0
      volumeClaimTemplates:
      - metadata:
          annotations:
            volume.beta.kubernetes.io/storage-class: nfs
          creationTimestamp: null
          name: elastic-data-pvc
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 33Gi
          selector:
            matchLabels:
              app: some-app
              service: elasticsearch
        status:
          phase: Pending
    status:
      replicas: 3

**Comment by shiranp** [comment]
@brancz @andyxning Just tested with apiserver v1.6.2 and the error still occurs

**Comment by andyxning** [comment]
I have downloaded the 1.5.2 release and tested the compiled binary with it. I can successfully get the  `/metrics`.

**Comment by andyxning** [comment]
@shiranp 

can you please edit the source code file `/go/src/k8s.io/kube-state-metrics/collectors/statefulset.go`. Add some debug log about the value of the variables before line 95.

```golang
glog.Infof("%#v", *statefulSet.Status)
```

**Comment by shiranp** [comment]
@andyxning 
After adding the line:

    93:        }
    94:        glog.Infof("%#v", *statefulSet.Status)
    95:        addGauge(descStatefulSetStatusReplicas, float64(statefulSet.Status.Replicas))
    96:        addGauge(descStatefulSetStatusObservedGeneration, float64(*statefulSet.Status.ObservedGeneration))

I get this error at build:

    # k8s.io/kube-state-metrics/collectors
    ../src/k8s.io/kube-state-metrics/collectors/statefulset.go:94: invalid indirect of statefulSet.Status (type 
    "k8s.io/client-go/pkg/apis/apps/v1beta1".StatefulSetStatus)

**Comment by andyxning** [comment]
Sorry @shiranp. I have updated the comment with the correct syntax.

glog.Infof("%#v", statefulSet.Status)

**Comment by andyxning** [comment]
@shiranp @brancz I have make a PR to fix this panic in #176.

**Comment by shiranp** [comment]
Hi, @andyxning @brancz 

The last error is indeed fixed but I am now getting the same error for job collector:

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x53e794]
    goroutine 123 [running]:
    panic(0x13364c0, 0xc420016060)
            /usr/local/go/src/runtime/panic.go:500 +0x1a1
    k8s.io/kube-state-metrics/collectors.(*jobCollector).collectJob(0xc420476380, 0xc4201ad260, 0x0, 0x0, 0x0, 0x0, 0xc42020f000, 0x16, 0x0, 0x0, ...)
            /go/src/k8s.io/kube-state-metrics/collectors/job.go:157 +0x134
    k8s.io/kube-state-metrics/collectors.(*jobCollector).Collect(0xc420476380, 0xc4201ad260)
            /go/src/k8s.io/kube-state-metrics/collectors/job.go:141 +0x133
    github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func2(0xc42041c980, 0xc4201ad260, 0x1be2e40, 0xc420476380)
            /go/src/github.com/prometheus/client_golang/prometheus/registry.go:433 +0x63
    created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
            /go/src/github.com/prometheus/client_golang/prometheus/registry.go:434 +0x2b6

I will appreciate your assistance.
Thanks.

**Comment by andyxning** [comment]
@shiranp 

Seems like a similar problem. I will take a look at this later today. However, i am wondering why some of the collector will not work properly in your env. 

Could you please add some version info about Kubernetes and does any special changes you make to your env.

**Comment by andyxning** [comment]
@shiranp I have make a PR about fix this panic. please take a look at #187

**Comment by shiranp** [comment]
Hi @andyxning,
First of all thanks for all your help, everything seems to work properly now.
Here is some version and setup info, if there is anything else you want to know, ask:

    uname -a
    Linux Server-name 3.10.0-514.16.1.el7.x86_64 #1 SMP Wed Apr 12 15:04:24 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    
    cat /etc/os-release
    NAME="CentOS Linux"
    VERSION="7.20170428 (Core)"
    
    docker info
    Server Version: 1.12.6
    Storage Driver: devicemapper
     
    prometheus   --version
    prometheus, version 1.7.1 (branch: master, revision: 3afb3fffa3a29c3de865e1172fb740442e9d0133)
      build user:       root@0aa1b7fc430d
      build date:       20170612-11:44:05
      go version:       go1.8.3
    
    apiserver:
      image: gcr.io/google-containers/hyperkube-amd64:v1.5.2
    
      options:
      --etcd-servers=https://master-server:2379,https://node1:2379,https://node2:2379,https://node3:2379,
      --etcd-cafile=/path/to/etcd/ca.pem,
      --etcd-certfile=/path/to/etcd/client.pem,
      --etcd-keyfile=/path/to/etcd/client-key.pem,
      --admission-control=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,ResourceQuota,
      --service-cluster-ip-range=10.0.0.0/16,
      --client-ca-file=/path/to/ca.crt,
      --tls-cert-file=/path/to/master-server.crt,
      --tls-private-key-file=/path/to/tmaster-server.key,
      --basic-auth-file=/etc/kubernetes/basic-auth.csv,
      --secure-port=443,
      --allow-privileged,
      --storage-backend=etcd2,
      --runtime-config=batch/v2alpha1=true,
      --v=4

My api server is running as a pod through kubelet manifest directory. 
kube-state-metrics is running behind a nodPort service and scraped by an external prometheus server.
All components communicate through ssl.
