### ISSUE TITLE
Add starts with capability

### ISSUE THREAD

**Issue by dedishari** [kubernetes/kube-state-metrics#1771]
Currently all the parameter in kube_pod_info has "equal to" operator. Can we add a capability of "starts with"? This will help to group a group of replicaset under a particular deployment in turn giving us the capability of viewing info of all pods started by a particular deployment.

**Comment by fpetkovski** [comment]
I think it's best if we delegate this operation to PromQL instead.

**Comment by dedishari** [comment]
achieved this by creating custom variable and adding the regex there
