### ISSUE TITLE
Allow monitoring of CRs only

### ISSUE THREAD

**Issue by bavarianbidi** [kubernetes/kube-state-metrics#1778]
**What would you like to be added**:

As i'm only interested in monitoring CRs i would have an additional flag e.g. `--resources-crds-only` to not list every CR in the `resources` argument

**Why is this needed**:

I'm currently setting up a second `KSM` instance which is only responsible for CRDs.

Any given GVK in my `helm template` will extend the `ClusterRole` with the required permissions to monitor these objects.
In the current implementation i have to extend the GVK list with a `plural` field to generate and concat the values for the `--resources` flag.

**Describe the solution you'd like**

A boolean called `resourcesCrdsOnly` which is `false` per default/if not set and can be set to `true` to only monitor CRs.

logic in `pgk/app/server.go` could look like:

```diff
	var resources []string
-	if len(opts.Resources) == 0 {
+	if len(opts.Resources) == 0 && resourcesCrdsOnly == false {
		klog.Info("Using default resources")
		resources = options.DefaultResources.AsSlice()
		// enable custom resource
		for _, factory := range factories {
			resources = append(resources, factory.Name())
		}
+	} else if resourcesCrdsOnly { 
+		// enable custom resource
+		for _, factory := range factories {
+			resources = append(resources, factory.Name())
+		}
	} else {
		klog.Infof("Using resources %s", opts.Resources.String())
		resources = opts.Resources.AsSlice()
	}
```

**Additional context**

**Comment by dgrisonnet** [comment]
I like the idea behind this feature, we should definitely make it possible to run a CRD version of ksm separately.

/assign @bavarianbidi

**Comment by bavarianbidi** [comment]
> I like the idea behind this feature, we should definitely make it possible to run a CRD version of ksm separately.
> 
> /assign @bavarianbidi 

Nice, will implement/continue in that
