### ISSUE TITLE
Streamline Metrics

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#1793]
Define standards and look through all metrics and check if the dimensions match certain standards (e.g. all plural / singular)

**Comment by grzesuav** [comment]
Maybe test like `promtool check metrics` [link](https://manpages.debian.org/testing/prometheus/promtool.1.en.html#check_metrics) or https://github.com/prometheus/client_golang/blob/main/prometheus/testutil/promlint/promlint.go can be used in CI to validate the metrics exposition format ?

**Comment by dgrisonnet** [comment]
We already have an e2e test verifying that metrics are conform with Prometheus standards: https://github.com/kubernetes/kube-state-metrics/blob/master/tests/e2e/main_test.go#L78-L95
