### ISSUE TITLE
 The deployment resource is add label , but the one queried by Prometheus has no label. and my  Kube state metrics is configured to allow all resources.   What else do I need to do? 

### ISSUE THREAD

**Issue by easonboy** [kubernetes/kube-state-metrics#1794]
kube-state-metrics  config :

     - args:
        - --metric-labels-allowlist=pods=[*],node=[*],namespaces=[*],deployment=[*],endpoint=[*]
        - --host=127.0.0.1
        - --port=8081
        - --telemetry-host=127.0.0.1
        - --telemetry-port=8082
        image: cnych/kube-state-metrics:v2.0.0
        imagePullPolicy: IfNotPresent
        name: kube-state-metrics

deployment.yaml:

kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deloy
  namespace: infra
  labels:
    project: mid
	app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        project: mid
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 0
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 7
  progressDeadlineSeconds: 600

kubernets version: v1.20.9
kube-state-metrics: v2.0.0

prometheus query result:

kube_deployment_labels{container="kube-rbac-proxy-main", deployment="nginx-deloy", endpoint="https-main", instance="10.0.168.208:8443", job="kube-state-metrics", namespace="monitoring", pod="kube-state-metrics-6bfd8855d7-6tnwq", service="kube-state-metrics"}

 you can find that there are no project and app label.
 
The query result I want is:

kube_deployment_labels{container="kube-rbac-proxy-main", deployment="nginx-deloy", endpoint="https-main", instance="10.0.168.208:8443", job="kube-state-metrics", namespace="monitoring", pod="kube-state-metrics-6bfd8855d7-6tnwq", service="kube-state-metrics",project=mid,app=nginx}

thanks~~

**Comment by osipovdaniil** [comment]
@easonboy How did you resolve this problem?

**Comment by easonboy** [comment]
this way:

 - args:
    - --metric-labels-allowlist=pods=[*],nodes=[*],namespaces=[*],deployments=[*],endpoints=[*]
    - --host=127.0.0.1
    - --port=8081
    - --telemetry-host=127.0.0.1
    - --telemetry-port=8082
    image: cnych/kube-state-metrics:v2.0.0
    imagePullPolicy: IfNotPresent
    name: kube-state-metrics

**Comment by easonboy** [comment]
> this way:
> 
> * args:
>   
>   * --metric-labels-allowlist=pods=[_],nodes=[_],namespaces=[_],deployments=[_],endpoints=[*]
>   * --host=127.0.0.1
>   * --port=8081
>   * --telemetry-host=127.0.0.1
>   * --telemetry-port=8082
>     image: cnych/kube-state-metrics:v2.0.0
>     imagePullPolicy: IfNotPresent
>     name: kube-state-metrics

**Comment by osipovdaniil** [comment]
Yes, thank you, i resolved too
I did so `--metric-labels-allowlist=horizontalpodautoscaler=[*]` instead `--metric-labels-allowlist=horizontalpodautoscalers=[*]`

**Comment by easonboy** [comment]
good job

**Comment by nskumz** [comment]
thats fine. so in my case i want to pass this argument from values.yaml file of kube-prometheus-stack helm chart. so where did i need to edit the values.
kube-state-metrics:
  namespaceOverride: ""
  rbac:
    create: true
  releaseLabel: true
  prometheus:
    monitor:
      enabled: true

      ## Scrape interval. If not set, the Prometheus default scrape interval is used.
      ##
      interval: ""

      ## SampleLimit defines per-scrape limit on number of scraped samples that will be accepted.
      ##
      sampleLimit: 0

      ## TargetLimit defines a limit on the number of scraped targets that will be accepted.
      ##
      targetLimit: 0

      ## Per-scrape limit on number of labels that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
      ##
      labelLimit: 0

      ## Per-scrape limit on length of labels name that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
      ##
      labelNameLengthLimit: 0

      ## Per-scrape limit on length of labels value that will be accepted for a sample. Only valid in Prometheus versions 2.27.0 and newer.
      ##
      labelValueLengthLimit: 0

      ## Scrape Timeout. If not set, the Prometheus default scrape timeout is used.
      ##
      scrapeTimeout: ""

      ## proxyUrl: URL of a proxy that should be used for scraping.
      ##
      proxyUrl: ""

      # Keep labels from scraped data, overriding server-side labels
      ##
      honorLabels: true

      ## MetricRelabelConfigs to apply to samples after scraping, but before ingestion.
      ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
      ##
      metricRelabelings: []
      # - action: keep
      #   regex: 'kube_(daemonset|deployment|pod|namespace|node|statefulset).+'
      #   sourceLabels: [__name__]

      ## RelabelConfigs to apply to samples before scraping
      ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#relabelconfig
      ##
      relabelings: []
      # - sourceLabels: [__meta_kubernetes_pod_node_name]
      #   separator: ;
      #   regex: ^(.*)$
      #   targetLabel: nodename
      #   replacement: $1
      #   action: replace

  selfMonitor:
    enabled: false


so , where do i need to edit the above values to pass the argument. thanks
