### ISSUE TITLE
getting an imagepullbackoff error

### ISSUE THREAD

**Issue by jjduverge** [kubernetes/kube-state-metrics#1795]
As I am applying the the files in kube-state-metrics/examples/standard, i am getting a 'imagepullbackoff' error for the kube-state-metrics pod. Is anyone else encountering this issue?

**Comment by jjduverge** [comment]
attempted to pull image from docker and am getting the following error:
<details>
<summary>Error from docker</summary>
```
$ docker pull kube-state-metrics:v2.5.0
Error response from daemon: pull access denied for kube-state-metrics, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
</details>

**Comment by mrueg** [comment]
that image references a different registry: https://github.com/kubernetes/kube-state-metrics/blob/master/examples/standard/deployment.yaml#L24 
Do you modify the deployment somehow?

**Comment by jjduverge** [comment]
No I didn't make any changes at all. Should I have? 

I currently already have a daemonset running the Datadog agents. Any recommendations would be greatly appreciated.

**Comment by rexagod** [comment]
@jjduverge Is this still the case for you?

**Comment by mrueg** [comment]
no response, feel free to reopen if this is still an issue.
