### ISSUE TITLE
Metrics kube_pod_container_status_last_terminated_reason does not report the pod terminated situation

### ISSUE THREAD

**Issue by amber-yan** [kubernetes/kube-state-metrics#1805]
I did a test, I updated the deployment(by kubectl edit deployment), I observed and I found the old pod is terminated, and a new pod is created.

I checked and I found kube_pod_container_status_last_terminated_reason did not report this.

**Comment by fpetkovski** [comment]
Was the pod deleted from the API server?

**Comment by amber-yan** [comment]
Hi @fpetkovski 
How to check if the pod is deleted from the API server? I use the command `kubectl get pods` to check, the pod is missing in the result. 

amber

**Comment by fpetkovski** [comment]
KSM can only report data for resources that exist in Kubernetes. If `get pods` does not show the pod, it means that it was removed from the API server and KSM has no way of knowing about it.

**Comment by amber-yan** [comment]
If that is the case, Is there any way to get the metrics to know the pod is removed

**Comment by fpetkovski** [comment]
You can check the `kube_pod_info` metric and see when the pod disappeared.

**Comment by amber-yan** [comment]
If I would like to get the all crash events, can I ignore the situation that the pod is removed? If the application crashes, the K8s will keep the pod and restart the container or terminate the existing pod and create a new one?

**Comment by fpetkovski** [comment]
It will recreate the crashed container and keep the existing pod

**Comment by amber-yan** [comment]
Is there any way to get the terminated time from the metric kube_pod_container_status_last_terminated_reason?
Thanks

**Comment by fpetkovski** [comment]
If you are scraping KSM, you will know when the pod went away by looking at when `kube_pod_info` for the pod stops being reported.

**Comment by amber-yan** [comment]
Sorry, I don't describe my question clearly. 
I would like to get the crash situation, so I need to use the KSM kube_pod_container_status_last_terminated_reason to get the container termination reason and time. 
I tried the KSM  kube_pod_container_status_last_terminated_reason, from that, I can only get the pod, container, hana-tooling etc information, and the value seems the termination conut. But the termination timestamp is not contained.

**Comment by fpetkovski** [comment]
Having the termination timestamp as a label would create extremely high cardinality, which is why it is not added to any of the metrics. 

For this we would need a new metric `kube_pod_container_status_last_terminated_timestamp` that has the timestamp as a value, but I would make that a new issue that we can discuss separately.

**Comment by tetianakravchenko** [comment]
hey @fpetkovski I am also trying to achieve the same as described above:

> I would like to get the crash situation, so I need to use the KSM kube_pod_container_status_last_terminated_reason to get the container termination reason and time.

And would be interested in metric as `kube_pod_container_status_last_terminated_timestamp` as you mentioned:
> For this we would need a new metric kube_pod_container_status_last_terminated_timestamp that has the timestamp as a value, but I would make that a new issue that we can discuss separately.

should I first open an issue for that? or there was any similar discussion regarding that?
