### ISSUE TITLE
All kubectl logs are shown as 'stderr'  

### ISSUE THREAD

**Issue by bhaskarpalani** [kubernetes/kube-state-metrics#1806]
All kubectl logs are shown as 'stderr' logs.
We tried to use the available option as in the documentation, such as enabling stdout,
one_output, but the logs display as stderr logs only.

kube-state-metrics version: 2.5.0

**Comment by rexagod** [comment]
Hello @bhaskarpalani. If it's alright, could you please post the logs as well, just so I could get a better idea around this?

**Comment by bhaskarpalani** [comment]
Hi @rexagod . Thank you for the reply, for few reasons, We can't attach the logs. 

      --logtostderr                           log to standard error instead of files (default true)

I suspect all the logs displayed as stderror logs, is this because they are enabled default to true.
