### ISSUE TITLE
Promote experimental metric kube_pod_container_status_waiting_reason to stable

### ISSUE THREAD

**Issue by CatherineF-dev** [kubernetes/kube-state-metrics#1811]
**What would you like to be added**:
Promote this metric from experimental to stable

**Why is this needed**:

- kube_pod_container_status_waiting_reason and kube_deployment_status_replicas_ready are very useful metrics. If they're stable, then down-streams can use it with less risk of deprecation
- https://github.com/kubernetes/kube-state-metrics/issues/1792

**Describe the solution you'd like**

Promote this metric from experimental to stable

**Additional context**

**Comment by dgrisonnet** [comment]
Promoting these metrics sounds reasonable to me since they've been in kube-state-metrics for a while now.

@CatherineF-dev feel free to open a PR to promote them.

**Comment by rexagod** [comment]
@CatherineF-dev If it's alright, I can take this up, it'd be a good starting issue for me I think.
