### ISSUE TITLE
Update client-go to support Kubernetes 1.7

### ISSUE THREAD

**Issue by andyxning** [kubernetes/kube-state-metrics#183]
I think we should update client-go to `4.0.beta.0` to support Kubernetes 1.7 since it has been released.

This should be done before 1.0 GA.

/cc @brancz @fabxc

**Comment by brancz** [comment]
I'm afraid of the effects this could have on the recently performed scalability tests, but given that the kubernetes components themselves use these components and they are more regulargly load/scale tested, this should generally be safe.
