### ISSUE TITLE
Add network policy pod selector gauge metric 

### ISSUE THREAD

**Issue by laurivosandi** [kubernetes/kube-state-metrics#1840]
Current `kube_networkpolicy_*` metrics don't seem very useful.

I was hoping to find gauge (how many pods are matched) for network policy pod selector so I could add an alert for dangling/mismatching network policies

**Comment by fpetkovski** [comment]
KSM aims to expose metrics from single Kubernetes resources in a one-to-one manner. Adding functionality that spans multiple resources has never been in scope. If some controller can update the status (or metadata) of network policies with the needed information, then that information can be exposed by KSM.
