### ISSUE TITLE
Deprecate pod resource request and limit metrics

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes/kube-state-metrics#1846]
We should look into whether we should deprecate the container-level `kube_pod_container_resource_limits` and `kube_pod_container_resource_requests` metrics in favor of pod-level resource request and limit metrics exposed by the kube-scheduler. The scheduler metrics were introduced by https://github.com/kubernetes/enhancements/tree/master/keps/sig-instrumentation/1748-pod-resource-metrics in 1.21, as a replacement for the metrics exposed by kube-state-metrics. The goal is to improve accuracy when doing capacity planning.

The k8s effort is currently in beta phase, but we will be looking into graduating it to stable for 1.27. As such, to avoid having duplicate metrics in the ecosystem, it would be better to deprecate the ksm metrics in favor of the ones exposed by the scheduler.

One thing we need to consider is that these metrics are exposed on a separate endpoint so we should make sure that if we do the transition, we leave some time for the kube-state-metrics users to start scraping the /metrics/resources endpoint.

**Comment by fpetkovski** [comment]
I am not sure if we can do this easily. Since the scheduler is a control plane component, not everyone has access to it, especially in managed kubernetes environments. I also like the fact that KSM has all data-plane metrics exposed in one place, and they all follow the same naming convention.

**Comment by rexagod** [comment]
I agree, however, do we want to allow duplicates in KSM? To frame it better, in an instance where there is an overlap between the metrics exposed by KSM and the ones exposed elsewhere, do we just remove them from KSM? Should that be the approach going forward?

**Comment by fpetkovski** [comment]
In my view, the goal of KSM should be to expose metrics about the state of Kubernetes objects. I am pretty sure there already are overlaps with many different exporters that have different goals, but I would expect KSM to be a standalone project that can fulfil its own goal independently. 

I also don't see why duplicates are problematic. It's easier to drop a duplicate than to run a different exporter for just a handful of metrics. Also as mentioned above, such duplicates can often exist in exporters that are not easily accessible to users that use managed environments.

**Comment by dgrisonnet** [comment]
> Since the scheduler is a control plane component, not everyone has access to it, especially in managed kubernetes environments.

This is a very fair point.

> In my view, the goal of KSM should be to expose metrics about the state of Kubernetes objects. I am pretty sure there already are overlaps with many different exporters that have different goals, but I would expect KSM to be a standalone project that can fulfil its own goal independently.

As much as I agree with that, kube-state-metrics is dependent on the Kubernetes project. KSM will never run outside of a Kubernetes environment, and I don't think anyone is running Kubernetes without kube-scheduler. So I think that we should consider the global picture and drive kube-state-metrics as a tool covering gaps in k8s API monitoring that were intentionally left for cardinality reasons.

> I also don't see why duplicates are problematic. It's easier to drop a duplicate than to run a different exporter for just a handful of metrics. Also as mentioned above, such duplicates can often exist in exporters that are not easily accessible to users that use managed environments.

The thing that I personally find problematic is that by keeping the ksm metrics around, we won't be helping the transition to the new more precise metrics from the kube-scheduler. Although users may not think they need it, every improvement is still worth taking.

That said, considering that the new metrics weren't added to the default kube-scheduler endpoint, they should be treated as being optional in a Kubernetes environment. As such considering my logic above there is a gap for us to fill and as such it would make sense to keep the metrics around. What we may want to do though to help with the transition to the new metrics is to update the description of the existing metrics and comment that new more precise metrics are exposed by the kube-scheduler.
