### ISSUE TITLE
We should be able to watch all CRDs in a given APIGroup

### ISSUE THREAD

**Issue by logicalhan** [kubernetes/kube-state-metrics#1848]
**What would you like to be added**:

Currently the implementation of CRD metrics allows us to allowlist a CRD of a known variety. What would be great is if we could watch all CRDs in a known apiGroup instead. 

**Why is this needed**:

This makes configuration much simpler and is considerably more powerful since we can subscribe to an apiGroup instead of known CRDs. 

**Additional context**

https://github.com/kubernetes/kube-state-metrics/blob/master/docs/customresourcestate-metrics.md

**Comment by dgrisonnet** [comment]
Sounds like a great addition to improve the user experience. In general, we could make both the kind and version part of the gvk config optional as it would allow defining custom metrics for:
- a specific API version
- all the API versions of a resource
- all the APIs part of an API group

Compared to what we have today where we can only add custom metrics for one specific API version at a time.

**Comment by rexagod** [comment]
Just adding to Damien's comment above, this means that we'd keep the `group` fixed, while:

```
    - a specific API version: `version` is fixed, `kind` varies.
    - all the API versions of a resource: `version` varies, `kind` is fixed.
    - all the APIs part of an API group: `version` varies, `kind` varies.

```
