### ISSUE TITLE
Metrics kube_statefulset_annotations and kube_statefulset_labels don't work as expected

### ISSUE THREAD

**Issue by Aracki** [kubernetes/kube-state-metrics#1852]
Both metrics do not show custom labels/annotations I've added to my StatefulSets.

I am getting only default ones, as `container`, `instance`, `job`,...

**Environment**:
- kube-state-metrics version: `v2.5.0`
- Kubernetes version: `v1.22.8`

https://github.com/kubernetes/kube-state-metrics/issues/1852#tasklist-block-734ed8f2-d80b-4fd2-9c28-58f7651bf90c

**Comment by ju4nmg** [comment]
+1 i have the same problem with kube-state-metrics `v2.6.0` in kubernetes `v1.23.8`

**Comment by fpetkovski** [comment]
Are you setting `--metric-labels-allowlist`? https://github.com/kubernetes/kube-state-metrics/blob/master/docs/cli-arguments.md#available-options
