### ISSUE TITLE
Typo in docs of custom resources after PR #1777

### ISSUE THREAD

**Issue by gadisn** [kubernetes/kube-state-metrics#1855]
**What happened**:
The new 'type' field for custom metrics, as added in https://github.com/kubernetes/kube-state-metrics/pull/1777, should be under 'each', see:

https://github.com/kubernetes/kube-state-metrics/blob/master/pkg/customresourcestate/registry_factory.go#L65
https://github.com/kubernetes/kube-state-metrics/blob/master/pkg/customresourcestate/registry_factory.go#L136

The problem is in line 46 in https://github.com/kubernetes/kube-state-metrics/edit/master/docs/customresourcestate-metrics.md

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:

**Comment by gadisn** [comment]
@chrischdi FYI

**Comment by chrischdi** [comment]
Thanks for reporting @gadisn 😄 👍  I opened a PR to fix the document
