### ISSUE TITLE
Want to add a new node condition metric(KernelDeadlock)

### ISSUE THREAD

**Issue by WIZARD-CXY** [kubernetes/kube-state-metrics#186]
Hi~
     I am using node-problem-detector (https://github.com/kubernetes/node-problem-detector) for detecting any kernel and docker problems on my node. I notice there already has some node metrics(https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/node-metrics.md). I want to add more conditions like KernelDeadlock node condition into kube-state-metrics. After  a quick code searching, I found it is easy to add it to the existing system. I can mimic node ready condition https://github.com/kubernetes/kube-state-metrics/blob/master/collectors/node.go#L60 to finish the job.For the future, I think it is nice to have more node condition type. Because it is not a default node condition in k8s, I wonder is it ok for me to add this to the kube-state-metrics?

**Comment by andyxning** [comment]
@WIZARD-CXY We have discussed about adding `KernelDeadlock` condition to Kubernetes api and it is closed for the reason that npd is a side-car component for Kubernetes and npd has not any enforcement about the condition name which you ref as `KernelDeadlock`.

For more info about this discussion, [go to Kubernetes #44099](https://github.com/kubernetes/kubernetes/pull/44099)

**Comment by WIZARD-CXY** [comment]
@andyxning thx
