### ISSUE TITLE
Failed to run e2e tests locally

### ISSUE THREAD

**Issue by CatherineF-dev** [kubernetes/kube-state-metrics#1877]
**What happened**:
In following https://github.com/kubernetes/kube-state-metrics/blob/master/tests/README.md to run e2e test locally, but 
```
➜  kube-state-metrics git: bash tests/e2e.sh

+ set -e
+ set -o pipefail
+ case $(uname -m) in
++ uname -m
+ ARCH=amd64
+ NODE_IMAGE_NAME=docker.io/kindest/node
+ KUBERNETES_VERSION=v1.24.0
+ KUBE_STATE_METRICS_LOG_DIR=./log
+ KUBE_STATE_METRICS_CURRENT_IMAGE_NAME=registry.k8s.io/kube-state-metrics/kube-state-metrics
+ KUBE_STATE_METRICS_IMAGE_NAME=registry.k8s.io/kube-state-metrics/kube-state-metrics-amd64
+ E2E_SETUP_KIND=
+ E2E_SETUP_KUBECTL=
+ KIND_VERSION=v0.14.0
+ SUDO=
++ uname -s
++ awk '{print tolower($0)}'
+ OS=linux
+ OS=linux
+ [[ -n '' ]]
+ kind version
kind v0.17.0 go1.19.2 linux/amd64
+ kind create cluster --name test-1 --image=docker.io/kindest/node:v1.24.0 --config ~/username/.kube/kind-3nodes-config.yaml
Creating cluster "test-1" ...
 ✓ Ensuring node image (docker.io/kindest/node:v1.24.0) 🖼
 ✗ Preparing nodes 📦 📦 📦
ERROR: failed to create cluster: could not find a log line that matches "Reached target .*Multi-User System.*|detected cgroup v1"
```

**What you expected to happen**:
kind created a k8s cluster successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. download this repo
2. run `bash test/e2e.sh`

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: latest
- Kubernetes version (use `kubectl version`): v1.22.0
- Cloud provider or hardware configuration:
- Other info: 
 
Has anyone else encountered with this issue? Or only me.

**Comment by rexagod** [comment]
Seems to be working fine for the latest commit (as of this moment).

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/33557095/199664706-493da96b-1e39-41be-b34b-bf7e3b603592.png)

</details>

**Comment by CatherineF-dev** [comment]
What's your `kind` version? cc @rexagod

**Comment by rexagod** [comment]
`kind v0.16.0 go1.19.1 linux/amd64`

**Comment by rexagod** [comment]
@CatherineF-dev If this is resolved, can we close this?

**Comment by CatherineF-dev** [comment]
No, haven't 😂

**Comment by CatherineF-dev** [comment]
It seems stuck in this step. In waiting

Creating cluster "kind" ...
 ✓ Ensuring node image (docker.io/kindest/node:v1.24.0) 🖼
⢎⡠ Preparing nodes 📦 📦 📦

**Comment by logicalhan** [comment]
If kind isn't coming up, it's probably not a ksm issue...

**Comment by logicalhan** [comment]
/close

(this isn't a KSM issue)
