### ISSUE TITLE
Enable discussions

### ISSUE THREAD

**Issue by rexagod** [kubernetes/kube-state-metrics#1884]
Hello maintainers! 👋🏼 

Can we enable discussions on this repository? That would save us a lot of noise that ends up turned into issues that aren't bugs, and should pave the way for general doubts that are more suited towards a forum than on a tracker.

WDYT?

**Comment by rexagod** [comment]
cc @dgrisonnet @logicalhan @mrueg @fpetkovski

**Comment by dgrisonnet** [comment]
I should have enabled them

**Comment by mrueg** [comment]
I'm not sure if there's an org-wide guidance to enable/disable them?
I have a slight preference for regular issues, as there's a lifecycle available.

**Comment by dgrisonnet** [comment]
I don't think there is any guidance.

For me, it depends on the scenarios. I think discussions are better than issues for answering and tracking support questions as well as for discussing technical designs and ideas and keeping a record of them that is easier to browse than normal issues.

**Comment by dgrisonnet** [comment]
Reopening to have a consensus.

**Comment by logicalhan** [comment]
I don't see the harm in enabling discussions. Since kube-state-metrics is a subproject and therefore does not have a dedicated google group, I see the argument for enabling a forum for community discussion.

**Comment by mrueg** [comment]
I'm not against enabling discussions for ksm, simply wanted to raise awareness for additional moderation and support required there to provide a good user experience (as there's e.g. a missing lifecycle).

**Comment by logicalhan** [comment]
> I'm not against enabling discussions for ksm, simply wanted to raise awareness for additional moderation and support required there to provide a good user experience (as there's e.g. a missing lifecycle).

For sure, we are actually actively working in SIG instrumentation for staffing sub-projects more aggressively. Moderating discussions could be a welcome contribution for new contributors.

> Maybe we can test it out for a couple of months and then re-evaluate?

Yeah that sounds reasonable to me. I suspect we may not even use it that much.

**Comment by rexagod** [comment]
Closing this now. Feel free to reopen.
