### ISSUE TITLE
Add support for hot-reloading on CRS config changes

### ISSUE THREAD

**Issue by rexagod** [kubernetes/kube-state-metrics#1892]
**What would you like to be added**: Hot-reloading when CRS config changes are detected.

**Why is this needed**: Allow users to make changes to their config and have KSM pick up on that automatically.

**Describe the solution you'd like**: Extend https://github.com/kubernetes/kube-state-metrics/pull/1827 for CRS config.

**Comment by mrueg** [comment]
/assign @mrueg 

@rexagod I had some spare time to start working on an implementation here
