### ISSUE TITLE
Can Grafana Dashbord json file be appended to the project?

### ISSUE THREAD

**Issue by xinsir88** [kubernetes/kube-state-metrics#1897]
Can Grafana Dashbord json file be appended to the project?

**Comment by rexagod** [comment]
IIUC right now we have alerts, but not dashboard in our [mixins](https://github.com/kubernetes/kube-state-metrics/tree/master/jsonnet). Is this a request to add the same?

**Comment by rexagod** [comment]
https://github.com/kubernetes/kube-state-metrics/issues/123#issuecomment-543838164 makes sense, would having a dashboard in KSM be extraneous, given that K8s mixins already incorporates KSM functionality to a great degree?

**Comment by mrueg** [comment]
We could add a link https://github.com/prometheus-operator/kube-prometheus in the README.
Dashboards for KSM are usually really specific and I don't think there's a good universal view.

**Comment by dgrisonnet** [comment]
If the dashboard is exposing SLIs about kube-state-metrics I am fine with having it in this repository, but if we are talking about dashboards related to Kubernetes clusters in general, https://github.com/kubernetes-monitoring/kubernetes-mixin/ would be better suited.

**Comment by rexagod** [comment]
I'd like to establish the layout of the dashboard before actually starting work on it. @xinsir88 @trallnag Do you have a set of panels in mind that you think would be suited specific to the repository? Keep in mind that we already have KSM-specific panels in [k/k-mixin]() so we'd need to come up with a set of requirements that we can put down as panels which that lacks and would make sense to keep specific to the repository.

I guess my question would be, why https://github.com/kubernetes/kube-state-metrics/issues/1897#issue-1449532692 but not using the KSM panels in the aforementioned repository in the first place?

**Comment by rexagod** [comment]
/unassign
/needs-triage
Removing assignment till further triage.

**Comment by dgrisonnet** [comment]
Since there is no need for this at the moment, I will close the issue.
