### ISSUE TITLE
Difference between node_status_capacity_memory and node_status_allocateable_memory

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/kube-state-metrics#19]
Hello,

With 0.2.0 release, it seems that kube_node_status_allocateable_memory_bytes and kube_node_status_capacity_memory_bytes report same values for nodes (with pod scheduled with required memory).

I'm looking to get available or reserved memory per node. Am'I missing something ?

**Comment by brancz** [comment]
Interesting, in the code we seem to [use the correct values](https://github.com/kubernetes/kube-state-metrics/blob/8bf322a88712726762d16d5abadc7c9a4ac8a3da/node.go#L156-L168) and the values from the status struct should reflect the [state you are looking for](https://github.com/kubernetes/client-go/blob/93fcd402979cfad8a7151f96e016416947c6a3cb/1.4/pkg/api/v1/types.go#L2492-L2497). I believe these numbers come from cAdvisor through the apiserver. I believe we have seen that behaviour from cAdvisor before, right @fabxc?

**Comment by brancz** [comment]
Actually, looking further into it there are quite a few more constants that [describe memory resources](https://github.com/kubernetes/client-go/blob/93fcd402979cfad8a7151f96e016416947c6a3cb/1.4/pkg/api/v1/types.go#L3161-L3170). We should figure out which ones are applicable for the purpose you described. At least from our current naming I would expect the same numbers/behavior as you do @rvrignaud .

**Comment by brancz** [comment]
Looking at my local dev cluster it looks like the resources we take should be correct, but I get the same numbers for capacity/allocatable.

```
{
  "capacity": {
    "alpha.kubernetes.io/nvidia-gpu": "0",
    "cpu": "1",
    "memory": "1021160Ki",
    "pods": "110"
  },
  "allocatable": {
    "alpha.kubernetes.io/nvidia-gpu": "0",
    "cpu": "1",
    "memory": "1021160Ki",
    "pods": "110"
  },
  ...
}
```

**Comment by fabxc** [comment]
I recall seeing this issue before and it being an issue in cAdvisor.

Found something similar at least: https://github.com/google/cadvisor/issues/1404

**Comment by ahakanbaba** [comment]
Would this code help to understand the difference between capacity and allocatable ? 

```
 // Set Allocatable.
 node.Status.Allocatable = make(api.ResourceList)
 for k, v := range node.Status.Capacity {
    value := *(v.Copy())
    if kl.reservation.System != nil {
       value.Sub(kl.reservation.System[k])
    }
    if kl.reservation.Kubernetes != nil {
       value.Sub(kl.reservation.Kubernetes[k])
    }
    if value.Sign() < 0 {
       // Negative Allocatable resources don't make sense.
       value.Set(0)
    }
    node.Status.Allocatable[k] = value
 }
```

This is from here https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_node_status.go#L459 

Reservation is defined here 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet.go#L974

```

 // reservation specifies resources which are reserved for non-pod usage, including kubernetes and
 // non-kubernetes system processes.
 reservation kubetypes.Reservation

```

**Comment by therc** [comment]
Yes, by default capacity and allocatable are the same, but a good administrator will reserve some resources from the node for system processes (systemd, journald, sshd and in many cases kubelet/kube-proxy).

**Comment by nvartolomei** [comment]
I get different values for allocatable in kube-state-metrics and in influxdb via heapster. fyi

**Comment by andyxning** [comment]
@rvrignaud @brancz Kubelet now supports two command line arguments: `--kube-reserved` and `--system-reserved`. By setting any of both, node allocatable and capacity should be different. Just as what has been mentioned in [comment 264933854](https://github.com/kubernetes/kube-state-metrics/issues/19#issuecomment-264933854).

**Comment by rvrignaud** [comment]
Closing it
