### ISSUE TITLE
Document scale testing process

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes/kube-state-metrics#1901]
In https://github.com/kubernetes/kube-state-metrics/issues/1341 kube-state-metrics scale testing was introduced, but the process to run them was never documentation, we should remediate to that.

**Comment by dgrisonnet** [comment]
@mrueg I wasn't implicated in the original effort but saw that you were, do you perhaps know how to run the tests? Otherwise I can take the item and try to figure out how to run them.

**Comment by mrueg** [comment]
I haven't run them, but was able to find the PRs created at that time. 

https://github.com/kubernetes/perf-tests/pull/1684
https://github.com/kubernetes/perf-tests/pull/1761
https://github.com/kubernetes/perf-tests/pull/1773
https://github.com/kubernetes/perf-tests/pull/1774 (this was a successful run via CI on a GCE based cluster)

**Comment by dgrisonnet** [comment]
Ah, I see, thank you for linking the PRs, I somehow missed the one that added the test to the list of presubmits.

So I guess what we should do is add an action item to the release process to update https://github.com/kubernetes/perf-tests/blob/master/clusterloader2/pkg/prometheus/manifests/exporters/kube-state-metrics/deployment.yaml. Maybe what we should do is set the image of ksm to the staging one that is expected to be promoted and then take actions based on the scalability results?

**Comment by mrueg** [comment]
I believe they were only ran once via CI in that PR and are not running them continuously right now. 
We could probably have a test PR that we trigger before the release?

**Comment by dgrisonnet** [comment]
Yes, that could be easy, not sure how we could hook into that, but it is worth investigating. Let's try to look into that for the next release
