### ISSUE TITLE
Cleanup documentation directory structure

### ISSUE THREAD

**Issue by dgrisonnet** [kubernetes/kube-state-metrics#1903]
Over time the docs directory became very messy and it has become very hard to find information in it since it doesn't have any structure. It would be great to improve that by separating related content into dedicated directories.

**Comment by sarahjanenewnham** [comment]
@dgrisonnet I could group them into directories that roughly align with the [categories listed in the Kubernetes API docs](https://kubernetes.io/docs/reference/kubernetes-api/)? i.e. "workload", "service", "config and storage", etc.
