### ISSUE TITLE
Merge labels in metric labels allowlist when resource glob is used

### ISSUE THREAD

**Issue by fkrestan** [kubernetes/kube-state-metrics#1907]
**What would you like to be added**:

I'd like to change the resource glob (`*=[...],`) behavior in `--metric-labels-allowlist` cli option to merging instead of overriding all allowed labels of explicitly listed resources.

Example for Deployment:

 `--metric-labels-allowlist=*=[foo],deployments=[bar]`

- Current behavior is that `kube_deployment_labels` would have only `foo` label allowed.
- Proposed new behavior would result in Deployments having both `foo` and `bar` labels allowed.

Both behaviors result in `foo` label being allowed in all enabled Kubernetes API resources.

**Why is this needed**:

My use case is  that I have a common labels on most Kubernetes API resources (e.g. https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/), but there are labels that I'd like to allow only on specific resources in addition to the common labels (e.g. topology labels on `Nodes` and `PersistentVolumes`, vendor specific labels).

Our current workaround is to generate the `--metric-labels-allowlist`, but the result is 1511 characters long argument and that is just for most common resources. This also means maintaining the list of API resources used for generating the argument which is not ideal as new resource types are added relatively often.

The current behavior is also not obvious from the help string and I believe that merging behavior would be more intuitive.

**Describe the solution you'd like**

From the looks of it, only https://github.com/kubernetes/kube-state-metrics/blob/master/internal/store/builder.go#L213 needs to be changed to allow this behavior.

As of KSM v2.6.0 the resource glob in label whitelist is still an unreleased feature so this should not be a breaking change.

**Comment by fpetkovski** [comment]
Hm this would be a breaking change, which means it can break existing users if we release such a change. Do you have a way to solve this with better configuration management on your side?

**Comment by fkrestan** [comment]
Oh, the v2.7.0 has been released already. That's unfortunate. 

While it ads complexity, I can resolve this with configuration management.

**Comment by carlpett** [comment]
Sorry to revive an old thread, but just so I'm not missing something trivial: given a naive configuration like this `--metric-labels-allowlist=nodes=[cloud.google.com/gke-nodepool],*=[app,component,owner]`, the "better configuration management" path would be expanding `*` with all possible types?
