### ISSUE TITLE
Improve UX for Config File syntax

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#1917]
**What would you like to be added**:

The config file syntax could be improved to provide a better UX.

**Why is this needed**:
Currently resources and namespaces use the types ResourceSet (map[string]struct{}), which works on the CLI like this:

`--resources=endpoints,services`

in the config file, it needs to be:
```
resources: 
  endpoints: {}
  services: {}
```
which is rather not intuitive.

**Describe the solution you'd like**

Ideally the config would look similar to this:
```
resources: 
- endpoints
- services
```

**Additional Context**

The same UX improvement can be applied to MetricAllowlist, MetricDenylist, MetricOptInList, LabelsAllowList, AnnotationsAllowList.

**Comment by rexagod** [comment]
@mrueg @CatherineF-dev  How about allowing folks to switch between YAML and JSON? We can add more decoders as well in the future.

Changing the unmarshalling behavior for specific flags will have to be followed-up by some documentation that specifies the format these should be in, diverging from the format that one would assume by looking at the types, which may lead to issues requesting the current behavior, or interchangeability between older and newer formats.
