### ISSUE TITLE
The ability to query for when a pod is stuck in a "ContainerCreating" status

### ISSUE THREAD

**Issue by tyl1024** [kubernetes/kube-state-metrics#1935]
I would like the ability to query for when a kubernetes pod is stuck in a certain status:

**Why is this needed**: This would be helpful for monitoring when pods are in a certain status and will help teams check status's on their pods.

**Describe the solution you'd like**
Currently, I am under the impression that you can query for when pods are stuck in given phase by using:
kube_pod_status_phase{phase=~<insert phase>})

The phases that I see available are: Failed, Pending, Running, Succeeded, Unknown

Is there a way to check a pod status for phase=~ ContainerCreating.

I am attempting to check if a pod is stuck in this phase for more than 5 minutes but I do not believe ContainerCreating is an option.

My current attempt is as follows:
min_over_time(sum by(namespace,pod)(kube_pod_status_phase{phase =~ "ContainerCreating"}) [5m]) > 0

Is what I am attempting possible currently?

**Comment by olivierlemasle** [comment]
If I'm not wrong, `ContainerCreating` is a status _reason_ for a pod _container_.

It should then be reported in `kube_pod_container_status_waiting_reason`.

**Comment by dgrisonnet** [comment]
Closing since an answer was provided in https://github.com/kubernetes/kube-state-metrics/issues/1935#issuecomment-1369848816.

Feel free to reopen if that didn't solve your probleme completely.
