### ISSUE TITLE
Expose APIService status

### ISSUE THREAD

**Issue by carlpett** [kubernetes/kube-state-metrics#1937]
**What would you like to be added**:
`APIService` is, from what I can tell, not exposed in any way today. We'd like to be able to write alerts against what would probably be `kube_apiservice_status_condition`(?).
Say `kube_apiservice_status_condition{type="Available",status="true"} == 0`

**Why is this needed**:
To be able to monitor availability of apiservices.

**Describe the solution you'd like**
Adding `kube_apiservice_status_condition`.

**Additional context**
Nope!

**Comment by dgrisonnet** [comment]
Kubernetes already expose this information in metrics, you can look for apiservice in https://kubernetes.io/docs/reference/instrumentation/metrics/

**Comment by carlpett** [comment]
Oh, was not aware of that. Thanks!
For reference, the metric name is `aggregator_unavailable_apiservice`.
