### ISSUE TITLE
Truncating values of kube-state-metrics when trying to get different units

### ISSUE THREAD

**Issue by raijenki** [kubernetes/kube-state-metrics#1949]
Hi! I am not sure if this is exactly a bug or a feature request (as I saw that there were some previous discussions regarding precision).
I am attempting to have the kube_pod_* metrics in milliseconds instead of seconds. The reasons don't really matter for this post.

At least in my head, the natural way of obtaining such metrics is changing the calls on `pod.go`, for example, `float64((p.Status.StartTime).Unix())` to `float64((p.Status.StartTime).UnixMilli())`. I did it, built a new image, and then deployed. However, when querying Prometheus, the results (originally in seconds) get ceiled to seconds, so I always get numbers like 1673368813000, 1673450550000 and 1673368826000, always with three zeros at the end, always with three zeros at the end but with milliseconds-precision. Same happens if I try nanoseconds or microseconds, the number of zeros at the end just increase.

I've been reading a lot of documentation and I don't think neither Prometheus nor K8s have an issue with the precision, so it must be something with kube-state-metrics. 

Feature Request / Bug: The kube-state-metrics writer is apparently rounding values to second precision. Would it be possible to let it write in whatever precision the user requests from the metrics? (I tried to solve it myself checking the Metric package but it's not clear to me)

My environment:
kube-state-metrics 2.7.0, Prometheus Operator v0.61, deployed with kube-prometheus. K3d 5.4.6 with Kubectl v1.24.4 (server).

**Comment by rexagod** [comment]
I've been digging around logic for the metric values, and I'm positive that we are not _rounding_ anything. However, I was half-expected to see the `float64` value being `Sprintf`-ed by a `%v` modifier, instead of `%f`, causing the roundoff (`1.<10 digits>ex`) to happen by casting the value into the exponent notation.

Is it possible for metrics with `float64` values to have a `%f`-like visualization (even before being scraped)? I doubt this maybe happening in one of the package we are using for exposing these.

**Comment by raijenki** [comment]
I also dug the code during last week and came to the same conclusion related to rounding. If the problem is the exposition of %v vs %f, maybe we can include a initialization flag for high precision metrics or create an alternative family structure for it?

**Comment by rexagod** [comment]
Not sure that'll work if the underlying handlers are explicity setting the `float64` value to `%v`-like representation.

**Comment by raijenki** [comment]
@rexagod Let me know if you need any sort of testing or help (although my Go skills aren't really the best). I still didn't manage to track the problem after few modifications in the code.
