### ISSUE TITLE
Allow aggregation of pod metrics by service

### ISSUE THREAD

**Issue by rndstr** [kubernetes/kube-state-metrics#195]
Similar to #70 I'm looking for a way to gather all the pods, but belonging to a service. Since one pod can be selected by multiple services it could be something like `kube_pod_services{pod=…, service=…}`.

Would there be interest for this in `kube-state-metrics`?

**Comment by matthiasr** [comment]
How would you determine the service(s) connected to a pod?

Services and pods are not the only things with a relation in Kubernetes, and the relations are always governed by label selectors. If we do this for pod/service, should we do it for other relations too? Which ones?

You can get _basically_ this by using `kube_pod_labels{…reproduce the label selector from the service…}`. I wonder if it would be possible to expose the service _label selector_, and then cleverly combine this with `kube_pod_labels` to find the pods. This would however result in quite a long join chain.

**Comment by brancz** [comment]
Prometheus has endpoints discovery, which gives you meta labels for of the endpoints/service object that particular pod is selected by, that's the way we relabel the that information onto the target, instead of going over additional information.

What use case are you looking to use that for?

**Comment by rndstr** [comment]
@brancz one use case is to get the cpu usage of a service by its name (=sum of all pods selected by this service). Currently, we make assumptions about the way that a pod is selected but we would like to make this more robust for all possible selector combinations.

Thanks for the hint, but it seems the [prometheus meta labels](https://github.com/prometheus/docs/blob/master/content/docs/operating/configuration.md#kubernetes_sd_config) are not providing selectors but just all the labels of the selected pod.

@matthiasr

> How would you determine the service(s) connected to a pod?

See whether a service's label selectors match a pod. From an implementation perspective, the pod collector would need to have access to the services somehow.

> If we do this for pod/service, should we do it for other relations too? Which ones?

My understanding is that only services (and the [discouraged](https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller/) replicationcontrollers) use label selectors while other controlling sets spawn and name pods by following a rule, thus already allowing label filters such as `pod=~"^daemonSet-[^-]+$"`

> You can get basically this by using kube_pod_labels{…reproduce the label selector from the service…}

That is a good idea and aligns with what Frederic seems to be suggesting.
