### ISSUE TITLE
ResourceQuota labels

### ISSUE THREAD

**Issue by oniram88** [kubernetes/kube-state-metrics#1951]
**What would you like to be added**:
Enable to get custom labels from ResourceQuota object with the 
`--metric-labels-allowlist` command.

**Comment by dgrisonnet** [comment]
/triage accepted
/help wanted

Hi @oniram88, would you be interested in contributing this feature to the project?

**Comment by oniram88** [comment]
I'd like to but I can't write code in go. :-(

**Comment by A-Hilaly** [comment]
@dgrisonnet @oniram88 any guidance/examples to know what's needed to support this? i'd like to give it a shot

**Comment by opeco17** [comment]
I've created PR (https://github.com/kubernetes/kube-state-metrics/pull/2175) to implement this feature.
