### ISSUE TITLE
kube_pod_info to include status/phase. 

### ISSUE THREAD

**Issue by andrew-pickin-epi** [kubernetes/kube-state-metrics#1954]
`kube_pod_info` to include `status`. Specifically `Running` and `Completed`.

Consider the following. Some nodes might have system resource limitations over and above cpu, ram or disk. I my case some AWS hosts only have a limited number of IP. The capacity in the case is `kube_node_status_allocatable{resource="pods"}`.

I would like to monitor and alert on this usage. `kube_pod_info` is best (only?) metric to use for node utilization.  

I'm currently counting the number of pods on a node thus (let's ignore how much headroom I require for now).

```
(sum by (node) (kube_node_status_allocatable{resource="pods"})) - (sum by (node) (kube_pod_info))
```
However this include a number of cron tasks already completed, and makes significant difference to the result.
Compare theses two real-world queries;
```
$ kubectl get pod --no-headers  --field-selector=status.phase==Running -n production | wc -l
16
$ kubectl get pod --no-headers  -n production | wc -l
22
```
The difference is the complete tasks:
```
$ kubectl get pod  --field-selector=status.phase!=Running -n production
NAME                                  READY   STATUS      RESTARTS   AGE
podium-backup-27897420-hgjmm          0/1     Completed   0          11h
podium-redis-pruning-27875760-4sg74   0/1     Completed   0          15d
telemetry-ingest-27898071-ztwbb       0/1     Completed   0          12m
telemetry-purge-27897060-sr899        0/1     Completed   0          17h
telemetry-s3-purge-27897000-fjqwg     0/1     Completed   0          18h
wiski-ingest-27897000-qn2qk           0/1     Completed   0          18h

```

There are a number of workaround available such as filtering by `created_by_kind` to discount these tasks, but these would also discount long-running cron tasks that might overlap. This only true fix is to include `status`.

**Describe the solution you'd like**

I would like each `kube_pod_info` metric to include an additional label (`status` or `phase`, don't really care about the name) to allow for filtering pods that are using resources.

**Additional context**

My metric/alert would hence become 
```
(sum by (node) (kube_node_status_allocatable{resource="pods")) - (sum by (node) (kube_pod_info{status="Running"}))
```

**Comment by CatherineF-dev** [comment]
Is it feasible to join two metrics `kube_pod_info` and `kube_pod_status_phase`? 

Because metric `kube_pod_info` is STABLE, it can't add new labels.

**Comment by CatherineF-dev** [comment]
For ready pods, another metric is `kube_pod_status_ready` whose cardinality should be smaller than `kube_pod_status_phase`.

You can find all possible pod metrics [here](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md).

**Comment by andrew-pickin-epi** [comment]
Suggest `kube_pod_status_scheduled` might be preferable for this case as the pod may will use the resource before pod is ready.

**Comment by CatherineF-dev** [comment]
Maybe you can contribute this alert into https://github.com/kubernetes/kube-state-metrics/tree/main/examples/prometheus-alerting-rules, if you have time:
- rename alerts.yaml to self-alerts.yaml
- add this alerting into k8s-alerts.yaml

**Comment by andrew-pickin-epi** [comment]
I think this more suitable for prometheus-community as they already have alerts on `kube_node_status_allocatable{resource="x"}`.
I'll look to see what's involved.

**Comment by dgrisonnet** [comment]
If the alert only involves kube-state-metrics metrics, it would be better to have it in https://github.com/kubernetes/kube-state-metrics/tree/main/examples/prometheus-alerting-rules as @CatherineF-dev suggested.

But generally to answer your original ask, it is not a good idea to add new dimensions to `kube_pod_info` since it would just make it confusing. An info metric should just give you minimal info about the object, nothing more. If you need additional info there are other metrics for that and Prometheus is optimized in a way that makes joining metrics super efficient.
