### ISSUE TITLE
Add volumeMode to PersistentVolume metrics

### ISSUE THREAD

**Issue by cospotato** [kubernetes/kube-state-metrics#1966]
**What would you like to be added**:

Add `volumeMode` to `kube_persistentvolume_info`

**Why is this needed**:

`volumeMode` is an important information of a PersistentVolume.

**Describe the solution you'd like**

Add `volumemode` to `kube_persistentvolume_info` metrics

**Additional context**

**Comment by dgrisonnet** [comment]
I am fine with adding a new metrics for the `volumeMode`, but that would have to go in its own metrics rather than being added to `kube_persistentvolume_info`.

Something like: `kube_persistentvolume_volume_mode`.

**Comment by cospotato** [comment]
@dgrisonnet PTAL

**Comment by dashpole** [comment]
This needs someone to implement the feature.  Marking as help-wanted

/unassign @dgrisonnet 
/triage accepted

**Comment by ricardoapl** [comment]
@cospotato is this something you would like to work on, or can I assign it to me?
