### ISSUE TITLE
Watch multiple versions of a custom resource

### ISSUE THREAD

**Issue by branden** [kubernetes/kube-state-metrics#1975]
**What would you like to be added**:

I'd like to be able to define metrics for multiple versions of a custom resource in custom resource state config, such as the following:

```
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: helm.crossplane.io
        version: v1alpha1
        kind: Release
      metrics:
        - name: uid
          help: "The UID of a helm.crossplane.io/v1alpha1 Release."
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]
    - groupVersionKind:
        group: helm.crossplane.io
        version: v1beta1
        kind: Release
      metrics:
        - name: uid
          help: "The UID of a helm.crossplane.io/v1beta1 Release."
          each:
            type: Info
            info:
              labelsFromPath:
                uid: [metadata, uid]

```

Running kube-state-metrics with the above config results in this error: `"Parsing from Custom Resource State Metrics file failed" err="found multiple custom resource configurations for the same resource releases"`

**Why is this needed**:

Not being able to watch multiple versions of a custom resource is a significant limitation. I must either ignore resources or run an instance of kube-state-metrics for each version.

**Describe the solution you'd like**

Support the above config and emit metrics accordingly. Custom resource state metrics already include a label for the API version, which can be used to differentiate versions in queries.

**Additional context**

https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md

**Comment by logicalhan** [comment]
/triage accepted

This is actually in progress.

/assign @dgrisonnet

**Comment by dgrisonnet** [comment]
As Han mentioned, this is a work in progress that you can track via https://github.com/kubernetes/kube-state-metrics/issues/1848. This other effort has a bigger scope which includes watching multiple versions of the same resource.

Closing as a duplicate.

/close
