### ISSUE TITLE
I see certificatesigningrequests interface is deprecated?

### ISSUE THREAD

**Issue by MagicStarTrace** [kubernetes/kube-state-metrics#1979]
![image](https://user-images.githubusercontent.com/15685376/217195220-9a08d654-f5ea-4249-9f6c-0c4c8fa511bd.png)

I see in the kube-state-metrics related yaml configuration that there is an api that uses certificatesigningrequests, so let's see if the deprecated api will affect the proper functioning of kube-state-metrics?

![image](https://user-images.githubusercontent.com/15685376/217195336-2a46fbc8-5e66-4a8c-8305-83698ed84c61.png)

kube-rbac-proxy Seeing that there are 2 of them, what is the difference between these 2?
What are they responsible for?
Thanks!

**Comment by dashpole** [comment]
Sorry we didn't get to this.  If this is still affecting you, feel free to reopen.
