### ISSUE TITLE
Add an option to allow adding Kubernetes Labels as Prometheus Metric Labels per metric-series

### ISSUE THREAD

**Issue by kostz** [kubernetes/kube-state-metrics#1980]
**What would you like to be added**:
Add an option to tag metrics with kubernetes labels

**Why is this needed**:
The case I'm working on involves otel-collector scraping prometheus metrics from KSM and exporting them into the commercial backend. The thing is that commercial backend charges for metric cardinality, so reporting metrics with such labels as pod_name and then do joins would cost a lot.

One of the possibility to avoid this excessive costs is to shrink cardinality by aggregating before exporting metrics (well, with acceptable loosing of visibility of keeping data for each pod) and it looks very promising to have this labelling on KSM and then remove extra labels (like pod_name, uid, etc) on otel-collector's processor.

**Describe the solution you'd like**
Have a feature toggle similar to `metric-allowlist` which will not add labels to `kube-pod-labels` metrics, but add labels for related metric timeseries, like `kube_pod_container_resource_requests`

**Additional context**
Follow up for https://github.com/kubernetes/kube-state-metrics/issues/1758

**Comment by dgrisonnet** [comment]
My concerns from https://github.com/kubernetes/kube-state-metrics/issues/1758#issuecomment-1192710597 still applies.

You could today remove labels via the otel-collector relabeling config but more complex aggregation similar to what Prometheus has with recording rules is not possible: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/receiver/prometheusreceiver/README.md#unsupported-features. Maybe there is a way to do post-processing in Otel, but that is out of kube-state-metrics' scope.

**Comment by dgrisonnet** [comment]
This is what you are most likely looking for: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/4968

**Comment by kostz** [comment]
@dgrisonnet , sorry, my bad of using the 'aggregation' term, that may lead to confusion about caching something and doing a real aggregation in KSM, that's not I'm asking for, I'm asking just about having an option to tag time series points with tags taking them from pod specs.

Honestly I didn't get a point about enormous memory footprint you're projecting for this feature, KSM will still deliver metrics almost 1:1, but adding additional (limited) tags taking them from pod specs

Also this feature may affect not the whole set of metrics, but just some of them (well, we're using less then 10% IIRC)

**Comment by kostz** [comment]
Also I would like to say that `cadvisor` already has this feature out of the box to bypass container labels to time series with CLI argument `whitelisted_container_labels`, and that works pretty well - https://github.com/google/cadvisor/blob/master/cmd/cadvisor.go#L66

So @dgrisonnet, why not to have the same in KSM?

**Comment by dgrisonnet** [comment]
> Honestly I didn't get a point about enormous memory footprint you're projecting for this feature, KSM will still deliver metrics almost 1:1, but adding additional (limited) tags taking them from pod specs

All these new label will have to be stored in both ksm cache and Prometheus timeserie database. When you have 100 timeseries it is not that much, but when you have millions it is a lot of memory you are wasting for an ease of use.

> Also I would like to say that cadvisor already has this feature out of the box to bypass container labels to time series with CLI argument whitelisted_container_labels, and that works pretty well - https://github.com/google/cadvisor/blob/master/cmd/cadvisor.go#L66

It could make sense for cAdvisor since it doesn't have dedicated `_labels` metrics like ksm, but I don't think that is the wisest choice. For sure it might be the most convenient but it is definitely not the most efficient. Metrics should be as minimal as possible and serve only one purpose.

@mrueg do you have any thought on that?

**Comment by framegrace** [comment]
I have urgent need of this feature.
I think an arbitrary way to categorize the metrics will be very useful, so they appears on prometheus queries.

 It allows to split metrics by internal classifications, other than cluster. (To send alerts to correct teams, split metrics in multi-tenant clusters ....). I really think it's a must feature. 

I understand the implications of adding labels to the metrics, but I maybe adding just one extra optional label on each metric  would be acceptable.
The label can be called  "classifier" or something similar, which can be assigned to an arbitrary label of the resource and it can be made optional, so current installs are not affected.

But well, at the end, either need that or a way yo have multiple kube-state-metric processes handling different resources selected by label so I can process this situation later on prometheus rules. 

My current situation is that I need to split metrics by "project_id" to thanos, so each customer can see it's own metrics without seeing the ones for the rest. And I'm currently out on the water trying to implement this with current options.

**Comment by dgrisonnet** [comment]
> It allows to split metrics by internal classifications, other than cluster. (To send alerts to correct teams, split metrics in multi-tenant clusters ....). I really think it's a must feature.

This can already be achieve by doing joins on `kube_*_labels` metrics to surface the labels that you wish to see in your alerts.

> My current situation is that I need to split metrics by "project_id" to thanos, so each customer can see it's own metrics without seeing the ones for the rest. And I'm currently out on the water trying to implement this with current options.

To achieve this kind of tenancy, we personally use https://github.com/prometheus-community/prom-label-proxy in OpenShift and it does the work pretty well.

**Comment by mrueg** [comment]
I agree with your points @dgrisonnet this request seems outside of ksm's scope and I'm fine with rejecting the feature request at this point.

For the initial request, it might make sense to run prometheus with recording rules and then remote-write it to your commercial backend (what @dgrisonnet described as a middleware).

For the second request, if your cluster supports multi tenancy, you might want to consider running a single ksm per tenant. 

An alternative could be customstatemetrics or if we ever get to this: https://github.com/kubernetes/kube-state-metrics/issues/2165

**Comment by framegrace** [comment]
This is pretty condescendent guys... why not let have an opinion on how to waste our resources?
This feature would solve a lot of problems and wasted time to a lot of people.
Specially if seems SOOOOO hard to implement....

**Comment by awoimbee** [comment]
> This can already be achieve by doing joins on kube_*_labels metrics to surface the labels that you wish to see in your alerts.

So easy:
```promql
sum by (label_app_kubernetes_io_component, label_node_kubernetes_io_instance_type) (
    # Get sheduled pods
    kube_pod_status_phase{phase="Running"}
    # Get pod labels
    * on(uid) group_left(label_app_kubernetes_io_component) max by (uid, label_app_kubernetes_io_component) (kube_pod_labels{label_app_kubernetes_io_component!=""})
    # Get node sheduled on
    * on (uid) group_left(node) max by (uid, node) (kube_pod_info{node!=""})
    # Get node labels
    * on (node) group_left(label_node_kubernetes_io_instance_type) max by (node, label_node_kubernetes_io_instance_type) (kube_node_labels{label_node_kubernetes_io_instance_type!=""})
    # When e.g. 2 pods are on one node, return .5 instead of 1 for each
    / on (node) group_left() count by (node) (
        max by (uid, label_app_kubernetes_io_component) (kube_pod_labels{label_app_kubernetes_io_component!=""})
        * on (uid) group_left(node) max by (uid, node) (kube_pod_info{node!=""})
    )
)
```

**Comment by maran-maran** [comment]
> This can already be achieve by doing joins on kube_*_labels metrics to surface the labels that you wish to see in your alerts.

But not in case when you need to use those labels in `metric_relabel_configs` ☝️
e.g., to drop all POD metric labeled with "{drop_me="true"}"

**Comment by rexagod** [comment]
I'll bring this up in the call next week.

**Comment by kostz** [comment]
Thanks for a great discussion here!

For me this feature request doesn't make sense any longer since I solved my problem with a special opentelemetry collector processor which adds needed labels to KSM (and cadvisor or any other) metrics taking them from  KSM's `kube_pod_labels` having `pod_name` as key.

I think we'll publish that opentelemetry collector component in some point.
