### ISSUE TITLE
KSM does not return labels with filter metric-labels-allowlist=nodes[label1,lable2,...]

### ISSUE THREAD

**Issue by poligraph** [kubernetes/kube-state-metrics#1984]
**What happened**:

KSM ignores allowed metrics list provided by
`--metric-labels-allowlist=nodes=[label1, label2]`

and returns only metrics like:
`kube_node_labels{node="node123"}`

**What you expected to happen**:
I expect to get metrics like:
`kube_node_labels{node="node123", label1="324", label2="456"}`

**How to reproduce it (as minimally and precisely as possible)**:
add argument to KSM
`--metric-labels-allowlist=nodes=[label1, label2]`

or to helm values

```
metricLabelsAllowlist:
  - nodes=[label1, label2]
```

**Anything else we need to know?**:

if I specify 
`--metric-labels-allowlist=nodes=[*]`
it returns metric `kube_node_labels{}` with all labels assigned to node

**Environment**:
- kube-state-metrics version: 2.7.0
- Kubernetes version (use `kubectl version`): v1.25.2
- Cloud provider or hardware configuration: GKE 1.24.8-gke.401
- Other info:

**Comment by Richabanker** [comment]
Hi @poligraph 

I tried to reproduce the reported issue but could not.

One thing to note is that the GKE version you reported in the issue `v1.24.8-gke.401` is [no longer available](https://cloud.google.com/kubernetes-engine/docs/release-notes) 
![Screenshot 2023-03-03 at 3 44 33 PM](https://user-images.githubusercontent.com/26771552/222856023-440add3b-c455-4ced-8958-6c8e8f3278f9.png)

While trying to reproduce the issue, I followed these steps:

1. I created a Kind cluster and also a GKE v1.24.8-gke.2000 cluster
2. Ran  kube-state-metrics v2.7.0 against both with the argument ` --metric-labels-allowlist="nodes=[kubernetes.io/hostname]" `
3. I was able to see the following entry in the /metrics endpoint: 
    ``` 
    kube_node_labels{node="gke-ossdebug-default-pool-101c74f4-dk90",label_kubernetes_io_hostname="gke-ossdebug-default-pool-101c74f4-dk90"} 1 
    ```

**Comment by poligraph** [comment]
Dear @Richabanker 

Thanks for your answer, seems like I read documentation wrong or it was unclear for me https://github.com/kubernetes/kube-state-metrics/blob/main/docs/cli-arguments.md

I used exact label names and it worked for me.

Maybe label example should be added to documentation for better understanding?

Thanks a lot.

**Comment by Richabanker** [comment]
@poligraph  Could you provide more details about what label value you had tried before (which didn't work) and after (which did work) ? 
@dgrisonnet do you think usage examples for the cli flags is a good thing to have in the docs?

**Comment by dgrisonnet** [comment]
Some of the CLI flags are pretty complex, so I think it would be great to document them :+1:

**Comment by poligraph** [comment]
@Richabanker sorry for late reply, I used allowed list like
```
- nodes=[label_service, label_cloud_google_com*]
```
but worked these one
```
- nodes=[service, cloud.google.com/gke-nodepool]
```

**Comment by Richabanker** [comment]
Got it thanks @dgrisonnet  @poligraph 
Lets close this issue, I have opened another one to track the documentation of usage examples here https://github.com/kubernetes/kube-state-metrics/issues/2043
