### ISSUE TITLE
We should be able to watch CRDs with a different group and same kind

### ISSUE THREAD

**Issue by aslafy-z** [kubernetes/kube-state-metrics#1997]
**What would you like to be added**:
As seen in https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md?plain=1#L19, the collector list should be updated with the plural form of the watched kind. Allow referencing GK or GKV instead.

**Why is this needed**:
The current behavior is ambiguous when using multiple CRDs with the same Kind.

**Comment by mrueg** [comment]
Is this a possible duplicate of https://github.com/kubernetes/kube-state-metrics/issues/1848 ?

**Comment by aslafy-z** [comment]
@mrueg Depending on how #1848 implementation is done, it may or may not fix this issue.

**Comment by logicalhan** [comment]
/triage accepted

This is a duplicate.
/close
