### ISSUE TITLE
KSM Pod Metrics Label Miss Node Label

### ISSUE THREAD

**Issue by tripitakav** [kubernetes/kube-state-metrics#2009]
k8s version: v1.20.15
kube-state-metrics: v2.6.0
![image](https://user-images.githubusercontent.com/73687556/220947942-a03e4050-a57b-4349-a886-d5e178d75091.png)
some pod metrics such as kube_pod_container_resource_requests how to carry node labels？

**Comment by dashpole** [comment]
Sorry we weren't able to get to this.  Please reopen if this is still impacting you.
