### ISSUE TITLE
A way for all the pod metrics to automatically include labels from kube_pod_labels?

### ISSUE THREAD

**Issue by Aracki** [kubernetes/kube-state-metrics#2016]
I've added custom labels for kube-state-metrics by adding:

`--metric-labels-allowlist=deployments=[team],pods=[team]`
which means I can see the "label_team" label within _kube_pod_labels_ and _kube_deployment_labels_ metrics.

Now, if I'd like to use "label_team" within alerts, I'd need to group metrics in each expression like explained in [this answer](https://stackoverflow.com/a/53151782/2884309).

Is there a way to include these custom labels in all the metrics automatically?

Somehow to tell kube-state-metrics to inject custom labels into all pod/deployment metrics...? I was thinking if it's possible with "relabelings" or "metricRelabelings" options within kube-state-metric's ServiceMonitor.

**Comment by Richabanker** [comment]
Injecting labels into existing metrics by default, especially stable metrics will not comply with [metrics stability guarantees](https://kubernetes.io/blog/2021/04/23/kubernetes-release-1.21-metrics-stability-ga/#what-are-the-stability-levels-for-metrics), though can perhaps have an optional flag to propagate the labels to metrics if specified so.. but there could be cardinality issues depending on the label being added. To me this change could be too much of a high-risk to have.

**Comment by Richabanker** [comment]
Also, refer to the discussion on this [pre-existing issue](https://github.com/kubernetes/kube-state-metrics/issues/1980) for opinions.

**Comment by logicalhan** [comment]
/close 

(in favor of the original issue https://github.com/kubernetes/kube-state-metrics/issues/1980)
