### ISSUE TITLE
Its regarding version flag

### ISSUE THREAD

**Issue by padmeshgit** [kubernetes/kube-state-metrics#2026]
I have created docker image using kube-state-metrics v2.8.1 but I am getting below error whenever I am running "version", I am wandering from where this "--port" flag is coming from.

_Command which I am running: docker run --rm <image_name> version_

**Error: unknown flag: --port
Usage:
  kube-state-metrics version [flags]

Flags:
  -h, --help   help for version**

**Comment by CatherineF-dev** [comment]
I could reproduce this issue.

```
$ docker run -t --rm registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.1  version
Error: unknown flag: --port
Usage:
  kube-state-metrics version [flags]

Flags:
  -h, --help   help for version
```

**Comment by padmeshgit** [comment]
I can see the same error in v2.8.0 as well, can this be looked/triaged please?

**Comment by mrueg** [comment]
If you're running ksm via docker, you have to overwrite the entry point first.

**Comment by padmeshgit** [comment]
@mrueg Can you please show me how to overwrite? Moreover, how come it is working with v2.6.0, this version is also having the same Dockerfile (entrypoint) as other version?

I tried with "--entrypoint" to override, but failed.

`$ docker run -t --rm --entrypoint version registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.7.0
Error: container_linux.go:380: starting container process caused: exec: "version": executable file not found in $PATH: OCI runtime attempted to invoke a command that was not found
 $`

**Comment by padmeshgit** [comment]
@mrueg @CatherineF-dev I think I got the answer, this is the correct command to get the version info.

`$ docker run -t --rm --entrypoint /kube-state-metrics registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.1  version
kube-state-metrics, version v2.8.1 (branch: , revision: unknown)
  build user:       root@83f32
  build date:       2023-02-22T14:25:21Z
  go version:       go1.19.6
  platform:         linux/amd64
~ $
`
Thanks for the help!
