### ISSUE TITLE
HPA & EPS compatibility mess

### ISSUE THREAD

**Issue by rbjorklin** [kubernetes/kube-state-metrics#2028]
**What happened**: `kube_horizontalpodautoscaler*` metrics stopped being available.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
We recently upgraded to KSM 2.8.1 to get access to the EndpointSlice metrics introduced in #1910 (required k8s version: 1.22)
Unfortunately HPA's were moved to v2 in #1906 which graduated to GA in k8s 1.23.

What this means is if you are on k8s 1.22 or earlier you cannot have both HPA metrics and EPS metrics at the same time. If this is intended it would be great if this information could be made more apparent in the README.

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 2.8.1
- Kubernetes version (use `kubectl version`): 1.22.11
- Cloud provider or hardware configuration:
- Other info:

**Comment by dgrisonnet** [comment]
Please refer to our compatibility matrix: https://github.com/kubernetes/kube-state-metrics#compatibility-matrix.

kube-state-metrics v2.8.1 is not meant to be compatible with k8s 1.22. The only compatible version that is still supported would be v2.4.2.

/triage accepted
