### ISSUE TITLE
Export HPA Event details as metrics

### ISSUE THREAD

**Issue by rustycl0ck** [kubernetes/kube-state-metrics#2039]
**What would you like to be added**:
Just like there is [`kube_horizontalpodautoscaler_status_condition`](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/horizontalpodautoscaler-metrics.md), it would be good to have `kube_horizontalpodautoscaler_status_event` too (which should include `Type` and `Reason` as labels) to get information about various events reported for the HPA.

**Why is this needed**:
 This information can be helpful in detecting when an HPA (or a group of HPAs) is failing to gather metrics or malfunctioning for any other reason. For example, events like `FailedGetResourceMetric`, `FailedGetScale`, `FailedGetExternalMetric`, `FailedComputeMetricsReplicas` etc, can be useful of alerting and detecting issues in the infrastructure.

**Describe the solution you'd like**
As mentioned above, having event metrics for HPA would be helpful.

**Additional context**
This information is available in the HPA description, but not available as metrics anywhere yet:
```console
$ kubectl describe hpa echo-server
Name:                                                  echo-server
Namespace:                                             echo-server
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Thu, 30 Mar 2023 11:51:54 +0900
Reference:                                             Deployment/echo-server
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 20%
Min replicas:                                          1
Max replicas:                                          10
Deployment pods:                                       1 current / 0 desired
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
Events:
  Type     Reason                        Age                  From                       Message
  ----     ------                        ----                 ----                       -------
  Warning  FailedComputeMetricsReplicas  58m (x12 over 61m)   horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get cpu resource metric value: failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
  Warning  FailedGetResourceMetric       58s (x241 over 61m)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
```

**Comment by CatherineF-dev** [comment]
I think it's a good idea to convert some suspicious events into metrics.

**Comment by CatherineF-dev** [comment]
Discussed with @dgrisonnet  and @mrueg,  haven't planned to add these metrics.

`One reason for not adding metrics based on events is cardinality since the event reason is unbounded and it is not something you can safely rely on since it has zero guarantees. `

**Comment by dgrisonnet** [comment]
Generally I think that the right way to progress when needing metrics about Events is to create new metrics at the place where the events are produces. That's the only way to have something accurate and granular. So in this particular case, I would encourage you to fill out an issue in Kubernetes and ask if these metrics can be added to the HPA controller.

**Comment by dgrisonnet** [comment]
As mentioned in the previous comments, we are rejecting this feature request.
