### ISSUE TITLE
Compatibility of kubernates and jump updates

### ISSUE THREAD

**Issue by Lark-super** [kubernetes/kube-state-metrics#2040]
https://github.com/kubernetes/kube-state-metrics#compatibility-matrix
Regarding the above, if we update to v2.8.1, is the version of kubernates compatible with v1.26 or less?
Is there any problem if the version of kubernates is v1.24 or v1.25?

Also, the current version of kube-state-metrics is v2.0.0-beta, is it safe to update to the latest version?

**Comment by waterserver** [comment]
triage/accepted

**Comment by Lark-super** [comment]
hi @logicalhan 
How about this one?
