### ISSUE TITLE
Decouple custom resource config with kube-state-metrics deployment

### ISSUE THREAD

**Issue by CatherineF-dev** [kubernetes/kube-state-metrics#2050]
**What would you like to be added**:

**Why is this needed**:
Add a custom resource metric requires changing KSM deployment.
In a company with platform monitoring team and application team, it means application team needs to change codes managed by platform monitoring team.

**Describe the solution you'd like**
#2049

**Additional context**

**Comment by mrueg** [comment]
Thanks for coming up with a possible solution here @CatherineF-dev @chrischdi  
Some thoughts on this approach and the design:

I feel like this approach definitely improves the situation, coming with a drawback of added complexity to kube-state-metrics which might make it more difficult to maintain though.

I would prefer a solution that mimics a similar design as prometheus and prometheus-operator. This will reduce complexity and simplify things, as well as follow the unix philosphy "Make each program do one thing well".

kube-state-metrics-operator could support two CRDs:

* CustomResourceMonitor, which matches your design
* KubeStateMetrics, which sets up new instances of kube-state-metrics

A couple of use cases:
* Large fleet of nodes and you need to separate kube-state-metrics out into multiple deployments (e.g. one is a daemonset collecting pod metrics, while the other one is a deployment collecting api resource info, while the third one is dealing with custom-resources) 
* Multi-tenancy and you want to have one kube-state-metrics deployment per namespace
* The operator further could support an AdmissionWebhook  to make sure no invalid CustomResourceMonitor gets added and takes kube-state-metrics down


What do you think?

**Comment by mrueg** [comment]
Could you elaborate why you think kube-state-metrics-operator is a breaking change to kube-state-metrics?

I would have assumed the operator is maintained in a separate repository, similar to https://github.com/prometheus-operator/prometheus-operator and https://github.com/prometheus/prometheus - completely decoupled.

This would allow to work independently on it, be on different release cycles.

**Comment by nathanperkins** [comment]
Some perspectives I hope are helpful in deciding where to put this feature.

- Configuring components through a (potentially giant) yaml blob in a config file that is mounted via a config map is not really friendly UX. I don't get any help from my IDE on linting or auto-completion; it's just a big blob of text.
- CRDs are so much more friendly and the natural UX that Kubernetes engineers are familiar with.
- CRDs are easier to deal with when you are providing metrics configs for API types coming from multiple components / projects / repos.
- CRD generation and validation is easier to automate.
  - FR: CustomResourceMonitor CRs could be generated from go type definitions using comment tags (this would be awesome)!

For these reasons, CRDs should be the first class API for configuring custom resource monitoring. I wouldn't want to have to deploy an entire separate operator pod (wasting resources) just to get a friendly UX.

**Comment by dgrisonnet** [comment]
This will be covered as part of https://github.com/kubernetes/enhancements/issues/4785.
