### ISSUE TITLE
container label missing in kube_pod_status_container_ready_time

### ISSUE THREAD

**Issue by bharathvenkatrajan** [kubernetes/kube-state-metrics#2053]
**What would you like to be added**: `kube_pod_status_container_ready_time` should have the container label and be able to filter on a container level

https://github.com/kubernetes/kube-state-metrics/blob/main/docs/pod-metrics.md

**Why is this needed**: The metric `kube_pod_status_container_ready_time` is supposed to show the ready time for each container 

**Describe the solution you'd like**
Need to add the `container` label to the metric `kube_pod_status_container_ready_time`
Adding a `container` label here? - https://github.com/kubernetes/kube-state-metrics/blob/main/internal/store/pod.go#L1339-L1364

**Comment by CatherineF-dev** [comment]
The metric name should be kube_pod_container_ready_time.

You can add this new metric @bharathvenkatrajan with container label.

**Comment by dgrisonnet** [comment]
cc @Henrywu573

**Comment by Henrywu573** [comment]
@bharathvenkatrajan Would the kube_pod_container_state_started metric documented at [this link](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/workload/pod-metrics.md) meet your requirements?

**Comment by bharathvenkatrajan** [comment]
@Henrywu573 Yes, that’s perfect. Thank you!

**Comment by richabanker** [comment]
/close
Thanks @Henrywu573 for seeing through this issue!
