### ISSUE TITLE
Need Multi Architecture Image for KSM

### ISSUE THREAD

**Issue by padmeshgit** [kubernetes/kube-state-metrics#2069]
I need a multi-architecture docker image for KSM so that I can use it on different architectures like amd/arm64 etc simultaneously. Please help me in downloading the multi-architecture image using "docker pull".

**Comment by CatherineF-dev** [comment]
You can find multi-arch here k8s.gcr.io/k8s-artifacts-prod/kube-state-metrics.

I also find `k8s.gcr.io Redirect to registry.k8s.io`, but I haven't figured out why  registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.8.1 is 404.
