### ISSUE TITLE
Container image not found registry.k8s.io

### ISSUE THREAD

**Issue by lakhansamani** [kubernetes/kube-state-metrics#2086]
**What happened**:
The container image is not found in the registry for version > 2.9.x
https://explore.ggcr.dev/?repo=registry.k8s.io%2Fkube-state-metrics%2Fkube-state-metrics

**What you expected to happen**:

Expected following image to be present:
`registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.9.2`

**How to reproduce it (as minimally and precisely as possible)**:
I tried pulling this image using docker image
```
docker pull registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.9.2
```

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: >= 2.9.0
- Kubernetes version (use `kubectl version`): 1.25
- Cloud provider or hardware configuration:
- Other info:

**Comment by amiga23** [comment]
Any update on this? Image is still not available:
Back-off pulling image "k8s.gcr.io/kube-state-metrics/kube-state-metrics:v2.9.2"
Latest version available is 2.8.2:
https://k8s.gcr.io/kube-state-metrics/kube-state-metrics
