### ISSUE TITLE
Sidecar container for kube state metrics deployment using helm chart values file

### ISSUE THREAD

**Issue by iamshinto** [kubernetes/kube-state-metrics#2091]
**What would you like to be added**:
Possibility to add a sidecar container on the kube state metrics deployment using the helm chart values.yaml

**Why is this needed**:
We want to generate custom resource monitoring config from configmaps automatically after combining several CRD resources metrics configmaps for KSM.  We want to use a [sidecar container](https://github.com/kiwigrid/k8s-sidecar) that will perform this.
Additionally a shared volume will be used between the ksm container and the sidecar to utilise the combined configmap for exposing custom resource state metrics.

**Describe the solution you'd like**
Modify the deployment to include extra containers and volume mounts from values file.

**Additional context**
The kube state metrics [helm chart](https://github.com/bitnami/charts/tree/main/bitnami/kube-state-metrics) by bitnami supports having extra containers and volume mounts but they doesn't support monitoring custom resources.

**Comment by mrueg** [comment]
This repository does not provide any support around helm. Please reach out to the provider of the helm chart.
