### ISSUE TITLE
Support for 3rd party pluggable metrics providers, including eBPF / BPF ones

### ISSUE THREAD

**Issue by yuriy-yarosh** [kubernetes/kube-state-metrics#2094]
**What would you like to be added**: Support for third party metrics providers to reduce and optimize resource consumption on per node basis. There are various eBPF enabled tools already, which could be reused as a kube-state-metrics data providers.

**Why is this needed**: To consolidate observability approach, enhance the existing metrics with more granular data - there's really no reason to measure twice, if eBPF tools, like [Pixie](https://px.dev/), already provide lower latency and resource consuption (it's C/C++ most of the time, so there's no GC Pressure etc).

**Describe the solution you'd like**

A GRPC API to propagate node/namespace metrics from a third party agent.
Optional [Apache Arrow](https://pkg.go.dev/github.com/apache/arrow/go/arrow) support would've been also nise.

**Additional context**

If we're gathering metrics each 10 seconds, it's important to get local min/max for that 10 seconds, - measure in Japanese Candle Charts instead of Common Hystograms. There's just too much Observability Data lost in between, and is unaccounted for, which actually hurts all potential autoscaling effort. By integrating with eBPF we can get a lot more data, without much throughput and latency degradation - there's no reason why anything should've been measured twice, especially if it's eBPF with a dedicated `DaemonSet`.

I'd also like to extend the existing ClusterAutoscaler / HPA / VPA API's and OTel to be able to work with Candle Charts and min/max data, or adapted approximations, instead of common Histograms. e.g. epbf can accumulate local min/max without much added mem/computational  overhead.

**Comment by dgrisonnet** [comment]
We don't have enough resources right now to look into this.

**Comment by dgrisonnet** [comment]
Nevermind, wrong repo. We definitely should look into this.
/reopen

**Comment by dgrisonnet** [comment]
@yuriy-yarosh I am not sure I fully understand you request. Kube-state-metrics' purpose is to expose Kubernetes API data as metrics. Any update to a Kubernetes resource is watched by kube-state-metrics and immediately reflected. The accuracy of the information then just depends on the scrape interval chosen by the users, but it is hard to get it down by a lot considering the amount of timeseries.

You mentioned that we are measuring twice, but I don't understand how that is the case, could you please explain? Also you mentioned that you'd want to turn Histograms into Candle sticks, but kube-state-metrics only exposes Gauges and I am not sure how candle sticks could help improve visualization in that case.

**Comment by dgrisonnet** [comment]
closing, feel free to reopen
