### ISSUE TITLE
UID for all the components in KSM

### ISSUE THREAD

**Issue by Gopinath-Selvam** [kubernetes/kube-state-metrics#2115]
**Request Kind**: 

Feature request

**What would you like to be added**: 

Recently while working with KSM, I've came across a particular use case where UID's are needed for all the components for which metrics are exposed in KSM. So, would love it if there's ever a chance where UID for all the components are exposed along with their metrics.

**Why is this needed**:

This has been previously addressed here(Ref. [here](https://github.com/kubernetes/kube-state-metrics/issues/1259)). This same use case applies to most of the components as well.

**Comment by Gopinath-Selvam** [comment]
Would love to contribute for this as well if the Community/Maintainers find the above request useful!

**Comment by Gopinath-Selvam** [comment]
> **Request Kind**:
> 
> Feature request
> 
> **What would you like to be added**:
> 
> Recently while working with KSM, I've came across a particular use case where UID's are needed for all the components for which metrics are exposed in KSM. So, would love it if there's ever a chance where UID for all the components are exposed along with their metrics.
> 
> **Why is this needed**:
> 
> This has been previously addressed here(Ref. [here](https://github.com/kubernetes/kube-state-metrics/issues/1259)). This same use case applies to most of the components as well.

Anybody checked this?

**Comment by mrueg** [comment]
What are the implications on cardinality?

**Comment by logicalhan** [comment]
This isn't going to work, there would be a cardinality explosion. 

/close 

(as unfeasible)
