### ISSUE TITLE
Alpha features should not be used by default

### ISSUE THREAD

**Issue by unguiculus** [kubernetes/kube-state-metrics#212]
v1.0.0-rc.1 uses alpha features which may not be available for every one. At least, they are not in our case on GKE. It doesn't seem to be do harm, but the log is flooded with this:

```
E0808 12:43:47.637347       1 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource
E0808 12:43:48.739642       1 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource
E0808 12:43:49.742757       1 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource
E0808 12:43:50.745885       1 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource
E0808 12:43:51.749028       1 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource
E0808 12:43:52.752262       1 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource
E0808 12:43:53.755323       1 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource
E0808 12:43:54.839768       1 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource
E0808 12:43:55.939709       1 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource
E0808 12:43:56.943320       1 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource
```

Please make the use of alpha feature configurable. Ideally they should be turned off by default.

**Comment by brancz** [comment]
As we don't version along with the Kubernetes version, this question is not as easy to be answered. While a feature might be in alpha in one version it can be beta in the next version, do we then change this and essentially break for old clusters.

I discussed this with @fabxc and there is no non-breaking path of us deciding on these things meaning this boils down to being a decision of the cluster administrator (who ideally has knowledge of whether a particular collector is compatible with the cluster in the first place).

To improve the experience, what we could do is write a discovery mechanism, to discover which APIs are available and enable the collectors for those. An additional difficulty though even when discovering the APIs is that RBAC roles have to be setup properly in the first place according to the state of that particular API. Being this close to the 1.0 release though I'd prefer to implement such a feature for an upcoming release.

Today the answer is, you need to be aware of what your cluster configuration and enable only those collectors compatible with it. I'm leaving this issue open though, as I agree that the experience can be better than what we offer right now.

**Comment by brancz** [comment]
Not sure if my answer was clear enough on this, but there is already the possibility to enable only certain collectors (`--collectors=...` flag), so a cluster administrator can setup these according to the RBAC roles, that have to be setup anyways as well.

**Comment by andyxning** [comment]
Agreed with @brancz with `the experience can be better than what we offer right now.`

**Comment by matthiasr** [comment]
What if we simply swallow the error / return from the collector without producing any metrics if the error is "not found" and the resource is alpha?

This is similar to the way many (not all) collectors behave in [node exporter](https://github.com/prometheus/node_exporter) – collectors that are default-on for optional kernel features will simply return without an error if the feature isn't enabled.

**Comment by brancz** [comment]
@matthiasr that's also one of the ideas @fabxc and I came up with, regarding the 1.0 release that would cause significant changes, that I'd like to avoid while already being in RC phase, and this seems like something we can still improve in the future. For the record the "errors" in the logs are still caught gracefully, so functionality wise these wouldn't differ, just the errors log lines would disappear, which I'd consider a non-breaking change.

**Comment by matthiasr** [comment]
agree!

**Comment by unguiculus** [comment]
@brancz Thanks, I was looking for something like the `--collectors` flag. Digging through the code I managed to get it working.

**Comment by brancz** [comment]
Feel free to open a PR to add it to the "usage" part of the readme :)

**Comment by unguiculus** [comment]
Here we go: #214

**Comment by zouyee** [comment]
you can use`kubectl api-versions` to check out batch version, and could enabled `batch/v2alpha1`feture gate with kubelet

**Comment by brancz** [comment]
@zouyee nice. That sounds like something we may be able to use, when I enable logging I get this:

```
I0809 09:08:24.549408   16328 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.7.0 (linux/amd64) kubernetes/d3ada01" https://<dns-name>:443/api    
I0809 09:08:25.060053   16328 round_trippers.go:405] GET https://<dns-name>:443/api 200 OK in 510 milliseconds
```

So sounds like we can discover which APIs are enabled with this.

**Comment by andyxning** [comment]
> and could enabled batch/v2alpha1feture gate with kubelet

@zouyee I can not understand this. Could you please detail it. :)

**Comment by zouyee** [comment]
related code [feature_gate](https://github.com/kubernetes/kubernetes/blob/7593a9f55548af7ea51d14e356e7cbbd4b86bf43/staging/src/k8s.io/apiserver/pkg/util/feature/feature_gate.go#L32),for example, if we want to enable hpa custom metrics feature， kubelet must be configured with `--feature-gates autoscaling/v2alpha1` which described feature gates for alpha/experimental features.

**Comment by brancz** [comment]
Yep that makes sense, that is essentially equivalent to the `--collectors` flag that we have today. However, the idea is that the apiserver already has this information so we should be able to discover those and automatically use all available collectors compatible with the apiserver. The problem remains, that the RBAC roles have to be setup correctly for each API, unless you give it cluster admin roles (which is not recommended __at all__).

**Comment by andyxning** [comment]
If we add all available collector resources RBAC config to the apiserver and apiserver does not support some of resources. Will apiserver failed to authenticate for all or just log the none supported ones  and let the supported resources work properly. If apiserver is kindly enough to this and let the supported resources work properly, We can just add all to RBAC. Or otherwise, we should only give it cluster admin roles as @brancz described.

**Comment by andyxning** [comment]
@zouyee 

> kubelet must be configured with --feature-gates autoscaling/v2alpha1 which described feature gates for alpha/experimental features.

Will this be reflected in the apiserver `api-versions` api response?

**Comment by andyxning** [comment]
Seems we can query this info through `Discovery` method of a kube client.

**Comment by zouyee** [comment]
@andyxning  yes, Discovery method would given version info.

**Comment by jpza** [comment]
Bump for this feature. Specifying collectors in a deployment manually fixed the problem for me however before that point a massive amount of errors was generated based on GCP's lack of Kube CronJob support

**Comment by atombender** [comment]
This is currently affecting Kubernetes 1.8, where `CronJob` has transitioned from `batch/v2alpha1` to `batch/v1beta1`, and now we don't get any cronjob metrics, and also the log is filling up with errors (`Failed to list *v2alpha1.CronJob`).

**Comment by zouyee** [comment]
when upgrade kubernetes to 1.8, you must enable v2alpha1.CronJob when config api-server in `--feature-gates`

**Comment by atombender** [comment]
That's not possible on Google Container Engine. And why would you want to do that when 1.8 has CronJob enabled under the beta API?

**Comment by zouyee** [comment]
@brancz

**Comment by zouyee** [comment]
It has been explained.
/close

**Comment by white-cloud** [comment]
@zouyee  Hello please how to configure  config api-server in --feature-gates???

**Comment by zouyee** [comment]
`--runtime-config=batch/v2alpha1=true`
