### ISSUE TITLE
Reload kube-state-metrics when kubeconfig changes. 

### ISSUE THREAD

**Issue by valayDave** [kubernetes/kube-state-metrics#2120]
**What would you like to be added**:
The `kube-state-metrics` server takes the `--kubeconfig` argument. This argument allows passing a path to the kube-config file. When the kubeconfig file changes, the server doesn't automatically reload and we need to reload the server manually (or with hacky reload logic which we have to maintain downstream). If there were a way for the server to listen to a change in the kube-config file, then we wouldn't have to write any custom reload logic. 

**Why is this needed**:
As good security measure, kubeconfig files should be short-lived and renewed periodically. Since kube-state-metrics takes a custom configuration file options, it would be really great if kube-state-metrics updates when the kube-config file changes.

**Describe the solution you'd like**
 I have noticed that KSM already has a watcher for the `--config` file option (where it is trying to listen to the change in the file), Can a similar pattern be implemented for a `--kubeconfig` option ?

**Additional context**

**Comment by dashpole** [comment]
Might need change in k8s client go
/assign @dgrisonnet 
/triage accepted

**Comment by dgrisonnet** [comment]
Sounds like something that could be beneficial to the project. I looked again in client-go and couldn't find any existing helper that we could reuse, so we will have to implement the watcher ourselves.

/help

**Comment by opeco17** [comment]
I created PR (https://github.com/kubernetes/kube-state-metrics/pull/2144) to implement the feature.
I'm using the same logic as the hot reload of `--config` .
