### ISSUE TITLE
Custom resources spam `Info metric %s does not have _info suffix`

### ISSUE THREAD

**Issue by chrischdi** [kubernetes/kube-state-metrics#2155]
**What happened**:

I configured a custom resource metric with the following configuration:

```
kind: CustomResourceStateMetrics
spec:
  resources:
  - groupVersionKind:
      group: cluster.x-k8s.io
      kind: Machine
      version: v1beta1
    - name: owner
      help: Owner references.
      each:
        info:
          labelsFromPath:
            owner_is_controller:
            - controller
            owner_kind:
            - kind
            owner_name:
            - name
            owner_uid:
            - uid
          path:
          - metadata
          - ownerReferences
        type: Info
```

KSM spams the following message on every CR creation:

```
I0818 16:54:32.105070   71540 generator.go:79] "Info metric %s does not have _info suffix" capi_machine_owner="(MISSING)"
```

This is caused here:

https://github.com/kubernetes/kube-state-metrics/blob/64c05aebc8d9cad9a4988fbd4fb4e7e39fe340f0/pkg/metric_generator/generator.go#L79

**What you expected to happen**:

* The message only getting printed out a single time on startup instead of on every CR creation
* The message either using `Infof` or properly using `InfoS`, e.g. `klog.InfoS("Info metric does not have _info suffix", "family.Name", family.Name)`

**How to reproduce it (as minimally and precisely as possible)**:

Use the above configuration and adjust to any kind of custom resource (because all provide the `.metadata.ownerReferences` property)

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: main
- Kubernetes version (use `kubectl version`): v1.27.3
- Cloud provider or hardware configuration: kind
- Other info:

**Comment by mrueg** [comment]
/triage accepted

`klog.InfoS("Info metric does not have _info suffix", "family.Name", family.Name)` sounds like a good approach.

**Comment by chrischdi** [comment]
We could move the name validation and log output somewhere into `registry_factory` instead, e.g. when doing `compileFamily` or `newCompiledMetric`:

https://github.com/kubernetes/kube-state-metrics/blob/64c05aebc8d9cad9a4988fbd4fb4e7e39fe340f0/pkg/customresourcestate/registry_factory.go#L72-L97
