### ISSUE TITLE
[feature] add pod gpu resource limit and request monitoring

### ISSUE THREAD

**Issue by WIZARD-CXY** [kubernetes/kube-state-metrics#216]
Hi~
   Our team use gpu for ml task and we think it is nice to have gpu resource monitoring in kube-state-metrics, Now I find the doc, only to find it doesn't have yet。I'm happy to submit a pr to add this feature

**Comment by matthiasr** [comment]
I think this makes sense. They are very similar to CPU resources, right?

**Comment by brancz** [comment]
Yes this is perfectly reasonable to add, as @matthiasr already mentioned, it's essentially the same as memory and cpu metrics we have today.

**Comment by WIZARD-CXY** [comment]
ok I will submit a pr now stay tuned
