### ISSUE TITLE
 customresource metrics is still experimental

### ISSUE THREAD

**Issue by sunglim** [kubernetes/kube-state-metrics#2167]
**What happened**: 

Looking at the document - https://github.com/kubernetes/kube-state-metrics/blob/main/docs/README.md
custome resource state metric is still experimental. 

> [Custom Resource State Metrics](customresourcestate-metrics.md) for experimental support for custom resources

**What you expected to happen**:
it's been more than 1 year since it was implemented.  Please consider removing *experimental*.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
N/A

**Environment**:
- kube-state-metrics version: 
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Other info:

**Comment by mengjiao-liu** [comment]
Looks like this is not a bug but a feature enhancement.

/remove-kind bug
/kind feature

**Comment by sunglim** [comment]
@mengjiao-liu Thank you for triaging.

**Comment by mrueg** [comment]
The reason why it is still experimental is, that we're still improving the configuration syntax and working on other areas around customresourcestate.

Experimental means mainly that we cannot provide any interface guarantees right now and we might change things in a follow up release.
This does not mean that you cannot use it, you should use it with caution in any production environments though.

**Comment by sunglim** [comment]
> we're still improving the configuration syntax and working on other areas around customresourcestate.

Thanks. That's a fair reason. I hope I can help you if I can find chances.  
I'll close this issue then.

**Comment by mrueg** [comment]
> > we're still improving the configuration syntax and working on other areas around customresourcestate.
> 
> Thanks. That's a fair reason. I hope I can help you if I can find chances. I'll close this issue then.

definitely, testing it out, providing feedback on usability and missing features is appreciated!
