### ISSUE TITLE
data_stream.dataset: kubernetes.pod has not status field

### ISSUE THREAD

**Issue by ozlembalat** [kubernetes/kube-state-metrics#2177]
**What happened**: some fields are missing in state_ message

**What you expected to happen**: all graphics have to be run successfully and messages must include all needed fields and values.

**How to reproduce it (as minimally and precisely as possible)**: install kube-state-metrics and kubernetes integration for ECK

**Anything else we need to know?**:

Hi, I have installed ECK and kube-state-metrics. Then checked dashboards, recognized some graphics are not working because of some fields are missing in metric messages.

For example, in [Metrics Kubernetes] Pods dashboard, status graphic is not working:

<img width="951" alt="2023-08-29 150857" src="https://github.com/kubernetes/kube-state-metrics/assets/93054432/63cbd04e-b3f8-444f-9b94-27e4516e3e7b">

When I checked `data_stream.dataset: kubernetes.pod` logs, there was no status field really:

![image](https://github.com/kubernetes/kube-state-metrics/assets/93054432/5b116459-ab3d-4458-84b7-22b3c6c9f06b)

But as official API guide, there must be **status** field to get status values.

https://docs.elastic.co/en/integrations/kubernetes/kube-state-metrics#state_pod

What's wrong for this situation? Thanks for now

**Environment**:
- kube-state-metrics version: 1.43.1
- Kubernetes version (use `kubectl version`): 1.27.2
- Cloud provider or hardware configuration: Vultr
- Other info:

**Comment by dgrisonnet** [comment]
Please reach out to elastic directly with regards to problem with their platform.
