### ISSUE TITLE
docs state that kube_job_created is a gauge, but seems to be unix timestamp

### ISSUE THREAD

**Issue by rfsburger** [kubernetes/kube-state-metrics#2179]
**What happened**:

https://github.com/kubernetes/kube-state-metrics/blob/main/docs/job-metrics.md states that kube_job_created is a gauge, but when querying the metrics in prometheus, it seems to be a unix timestamp. I am not sure if the docs is incorrect or the metrics is incorrect at this point.

**What you expected to happen**:

The docs to accurately represent the truth. 

**How to reproduce it (as minimally and precisely as possible)**:

check the kube_job_created metric

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: v2.8.2
- Kubernetes version (use `kubectl version`): 1.25
- Cloud provider or hardware configuration: GCP
- Other info:

**Comment by mrueg** [comment]
Could you provide an example metric?

**Comment by Serializator** [comment]
`kube_job_created` is expected to be a unix timestamp. There are more metrics like this in KMS.
https://github.com/kubernetes/kube-state-metrics/blob/dbd456831b5adfc8642d5c7793c6cdad59c2e975/internal/store/job.go#L118

A gauge is only a particular type of metric, one which can go up or down. The value can be anything you'd want. Including a unix timestamp. The description which mentions the value of the metric to be a unix timestamp is missing and should added to the documentation for clarity.

**Example (`kube_persistentvolumeclaim_`)**
https://github.com/kubernetes/kube-state-metrics/blob/dbd456831b5adfc8642d5c7793c6cdad59c2e975/docs/persistentvolumeclaim-metrics.md?plain=1#L12-L13

I hope this clears up any confusion around this particular metric @rfsburger, please say so if it doesn't 😉

**Comment by rfsburger** [comment]
Yeah, that makes sense. Thanks for the quick reply. I'll close this issue and make a quick PR for adding the description
