### ISSUE TITLE
kube_pod_container_status_ready How do I display the correct node ip

### ISSUE THREAD

**Issue by golangav** [kubernetes/kube-state-metrics#2230]
kube_pod_container_status_ready How do I display the correct node ip

**Comment by dgrisonnet** [comment]
@golangav could you be explicit about what you mean with node IP? Are you referring to the instance label from Prometheus? https://prometheus.io/docs/concepts/jobs_instances/

**Comment by CatherineF-dev** [comment]
cc @golangav https://github.com/kubernetes/kube-state-metrics/issues/2230#issuecomment-1802353970

**Comment by mrueg** [comment]
No response since a year. Closing then.
