### ISSUE TITLE
Memory and CPU usage metrics

### ISSUE THREAD

**Issue by sengaya** [kubernetes/kube-state-metrics#2235]
**What would you like to be added**:
Metrics for memory and CPU usage for each pod/container

**Why is this needed**:
For optimizing memory and CPU request/limit settings it is helpful to have metrics about the actual usage.

**Describe the solution you'd like**
Additional metrics for each pod/container for memory and CPU usage. The metrics of interest can be retrieved by `kubectl top pod --containers` or direct calls to the kubernetes API: `/apis/metrics.k8s.io/v1beta1/pods`

**Additional context**
There are two similar issues, #1351 and #1396. The answers on these tickets mention existing metrics for memory/cpu usage. But these metrics seem to be no longer available in the current version.

**Comment by CatherineF-dev** [comment]
cAdvisor  / summary API endpoint have these data.

**Comment by dashpole** [comment]
+1 I would recommend using other metric providers (cadvisor, summary api, or kubelet resource metrics)

**Comment by sengaya** [comment]
Many thanks for the suggestions. I was not aware that cadvisor is built-in and could be used right away. In case someone is looking for the API path and metrics: `/api/v1/nodes/${node_name}/proxy/metrics/cadvisor`
- `container_memory_working_set_bytes` is the equivalent to `kubectl top pod --containers`
- `container_cpu_usage_seconds_total` can be used to calculate the CPU usage. The comments at https://github.com/google/cadvisor/issues/2026 are quite helpful.
