### ISSUE TITLE
Twistlock PRISMA-2022-0227

### ISSUE THREAD

**Issue by dpericaxon** [kubernetes/kube-state-metrics#2253]
As discussed in this issue: https://github.com/kubernetes/kube-state-metrics/issues/1999#issuecomment-1652439596

Description of CVE: github.com/emicklei/go-restful/v3 module prior to v3.10.0 is vulnerable to Authentication Bypass by Primary Weakness. There is an inconsistency in how go-restful parses URL paths. This inconsistency could lead to several security check bypass in a complex system.

I think its still appearing because of this line: https://github.com/kubernetes/kube-state-metrics/blob/main/go.mod#L35

Is it possibly a false positive then?

**Comment by CatherineF-dev** [comment]
I can help fix this https://github.com/kubernetes/kube-state-metrics/pull/2254

**Comment by mrueg** [comment]
This should be resolved with https://github.com/kubernetes/kube-state-metrics/commit/0cb296564ba94269f7cb17d383fc49e9e076af57
