### ISSUE TITLE
Pod ready time

### ISSUE THREAD

**Issue by Dark002** [kubernetes/kube-state-metrics#2283]
I have a deployment with two pods: pod1 and pod2 for the same deployment. I want to get median pod ready time for the deployment. First I was using the difference between _**kube_pod_status_ready_time**_ and _**kube_pod_start_time**_ to calculate ready time for pod. But in case, due to some error the pod restarts, the restart time will also be included. So, I started using _**kube_pod_status_container_ready_time**_ and _**kube_pod_container_state_started**_ to calculate ready time.
Now, suppose the autoscaler creates one more pod, say pod3. The running times for pods are:
pod1 -> 12 days
pod2 -> 12 days
pod3 -> entered ready state just now
The actual ready time for each pod is around 4 mins. But I am getting the times as:
pod1 -> 12 days
pod2 -> 10 days
pod3 -> 4 mins
Can somebody tell me where I am wrong?

**Comment by rexagod** [comment]
I'd suggest posting this along with your PromQL expression in one of the relative support channels. Closing since this isn't related to this repository.
