### ISSUE TITLE
Why do kube-state-metrics clusterrole need access to list,watch all secrets at cluster scope?

### ISSUE THREAD

**Issue by dsai1** [kubernetes/kube-state-metrics#2315]
An issue was raised by our security team saying the existing kube-state-metrics cluster role has access to all secrets.

Below is the AVD-KSV-0041, which is blocking our pipeline as part of trivy checks.

Can we restrict access to specified secrets?

**Comment by CatherineF-dev** [comment]
It collects secret metrics.

> Can we restrict access to specified secrets?

You can remove this permission if don't need secret metrics.

**Comment by CatherineF-dev** [comment]
1. drop secret related metrics using allowlist/denylist https://github.com/kubernetes/kube-state-metrics/blob/main/docs/cli-arguments.md

2. remove secret permission


Do you have other questions? If not, will close
