### ISSUE TITLE
What is kube-state-metrics status on Kubernetes 1.29?

### ISSUE THREAD

**Issue by benoit74** [kubernetes/kube-state-metrics#2323]
Kubernetes 1.29 is still not mentioned in https://github.com/kubernetes/kube-state-metrics#compatibility-matrix

Is there any known issues on 1.29? Is there any plan to do a real release supporting 1.28 / 1.29?

**Comment by CatherineF-dev** [comment]
Hi, 1.29 will be released soon..

- https://github.com/kubernetes/kube-state-metrics/pull/2327
- https://github.com/kubernetes/kube-state-metrics/pull/2331

**Comment by McDonald755** [comment]
I need him, too. Please release it as soon as possible

**Comment by liangyuanpeng** [comment]
Working at:
- https://github.com/kubernetes/kube-state-metrics/pull/2335

**Comment by mrueg** [comment]
Main branch is now at k8s 1.29 https://github.com/kubernetes/kube-state-metrics/commit/0cb296564ba94269f7cb17d383fc49e9e076af57 

Let us know if there's any urgency behind it. Usually Kubernetes provides great compatibility between multiple a couple of minor releases.
