### ISSUE TITLE
[WIP]go fmt error

### ISSUE THREAD

**Issue by zouyee** [kubernetes/kube-state-metrics#233]
After [that commit](https://github.com/kubernetes/kube-state-metrics/pull/210) merged, now PRs could not passed `Go fmt` TEST!

https://github.com/kubernetes/kube-state-metrics/pull/232<img width="423" alt="2017-08-21 2 26 47" src="https://user-images.githubusercontent.com/5785605/29506151-cc3b640c-867c-11e7-930b-bce1cee2c610.png">

<img width="588" alt="2017-08-21 2 28 32" src="https://user-images.githubusercontent.com/5785605/29506340-c22bc8e8-867d-11e7-81da-d0a02f848ff8.png">

**Comment by chlunde** [comment]
@brancz I think this issue should be closed.

**Comment by brancz** [comment]
Yes @chlunde you're absolutely right! Thanks for the ping.
