### ISSUE TITLE
Chart missing for v2.11.0

### ISSUE THREAD

**Issue by grigoni** [kubernetes/kube-state-metrics#2346]
Hello Folks 
Chart for latest released KSM has Not yet published 

any ETA?

**Anything else we need to know?**:

**Environment**: all

* kube-state-metrics version: v2.11.0
* Kubernetes version (use `kubectl version`): 1.28.x
* Cloud provider or hardware configuration: any
* Other info:

**Comment by mrueg** [comment]
The chart is not maintained in this repository. See: https://github.com/kubernetes/kube-state-metrics?tab=readme-ov-file#helm-chart

**Comment by grigoni** [comment]
Thx
I had wrong impression ksm releases would trigger coordination with chart project
