### ISSUE TITLE
sharding with a deployment with '--resources=pods' and '--node=""' does not fetch pending pods

### ISSUE THREAD

**Issue by carlosrmendes** [kubernetes/kube-state-metrics#2353]
**What happened**: a deployment with `--resources=pods` and `--node=""` does not fetch pending pods

**What you expected to happen**: pending pods be fetched by ksm

**How to reproduce it (as minimally and precisely as possible)**:
- create a ksm deploy with `--resources=pods` and `--node=""` and `-v=10`
- force another pod to be in a pending state
- check the logs for the api request like `https://<kubernetes_api_ip>:443/api/v1/pods?allowWatchBookmarks=true&fieldSelector=spec.nodeName%3D%22%22&resourceVersion=3998681&timeout=5m23s&timeoutSeconds=323&watch=true`
- 'kubect proxy' and try to make the same request
- make the same request without the `&fieldSelector=spec.nodeName%3D%22%22` and confirm that on the response, the pending pods does not have any `nodeSelectot` key with an empty value

* kube-state-metrics version: v2.10.1
* Kubernetes version (use `kubectl version`): k3s v1.24.10

**Comment by CatherineF-dev** [comment]
Thanks for reporting this. 

Could you help paste your pending pod yaml, if it's available? Want to see nodeName value on the yaml

**Comment by CatherineF-dev** [comment]
Wondering whether apiserver fieldSelector supports `-nodeName` which means nodeName doesn't exist

**Comment by CatherineF-dev** [comment]
From https://kubernetes.io/docs/concepts/overview/working-with-objects/field-selectors,

one solution might be 
1. Daemonset: status.phase=Running && nodeName = x
2. Deployment: status.phase!=Running

**Comment by CatherineF-dev** [comment]
I tried again and verified `--field-selector spec.nodeName=` can get unscheduled pods.

--node="" is translated into `spec.nodeName=`

1. nothing: get all pods
2. --node="A":  `--field-selector spec.nodeName=A ` get pods on node A
3. --node="": `--field-selector spec.nodeName= ` get pods with no node assigned
```
kubectl get pods --field-selector spec.nodeName= -A

NAMESPACE   NAME                          READY   STATUS    RESTARTS   AGE
default     helloworld-7f5cd44b59-zhgzj   0/1     Pending   0          87s
```

```
kube_pod_status_scheduled{namespace="default",pod="helloworld-7f5cd44b59-zhgzj",uid="26018553-ceb6-427f-be1a-088032edac7a",condition="false"} 1
```

**Comment by CatherineF-dev** [comment]
@carlosrmendes does it mean we need to fix this for KSM?  Or just your local query doesn't work.

**Comment by CatherineF-dev** [comment]
I can reproduce it that `--node=""` doesn't work as expected.

```bash
/usr/lib/go-1.22/bin/go  run main.go  --resources=pods --node=  --kubeconfig ~/.kube/config

curl localhost:8080/metrics | grep kube_pod_status
```
