### ISSUE TITLE
Cut 2.12.1

### ISSUE THREAD

**Issue by CatherineF-dev** [kubernetes/kube-state-metrics#2375]
**What would you like to be added**:  https://github.com/kubernetes/kube-state-metrics/pull/2388

**Why is this needed**:

**Describe the solution you'd like**

**Additional context**

**Comment by LaikaN57** [comment]
Just a bit of self-advocation here 😅, we are interested in getting the following 2 issues/PR resolved in this next release:
- https://github.com/kubernetes/kube-state-metrics/pull/2347
- https://github.com/kubernetes/kube-state-metrics/pull/2373

**Comment by feym78** [comment]
Hi.
Also interested in new release asap to bump GO version to 1.21.9+

**Comment by CatherineF-dev** [comment]
Also to include https://github.com/kubernetes/kube-state-metrics/issues/2393

**Comment by feym78** [comment]
@LaikaN57 Hi!
Do you have any predictions for the next release?

**Comment by LaikaN57** [comment]
@feym78 I am not a repo maintainer unfortunately.

**Comment by feym78** [comment]
> @feym78 I am not a repo maintainer unfortunately.

Oh, sorry. Got confused.
If anyone know right person to tag please do. Thx.

**Comment by nikhil-bhat** [comment]
hi @CatherineF-dev  do you know when this release will be created

**Comment by CatherineF-dev** [comment]
https://github.com/kubernetes/kube-state-metrics/pull/2419
