### ISSUE TITLE
`kube_job_failed` should have `reason` label

### ISSUE THREAD

**Issue by keisku** [kubernetes/kube-state-metrics#2382]
**What would you like to be added**:

Add `reason` label here other than `condition`.

https://github.com/kubernetes/kube-state-metrics/blob/9e6e70d328c5d750a0df84cc044c38124b271538/internal/store/job.go#L292-L316

**Why is this needed**:

Enable to monitor why a job fails.

**Describe the solution you'd like**

```diff
-- 					metric.LabelKeys = []string{"condition"}
++ 					metric.LabelKeys = []string{"condition", "reason"}
```

**Additional context**

I would like to know why the current implementation doesn't allow adding `reason` label. Any concerns?

**Comment by ricardoapl** [comment]
> I would like to know why the current implementation doesn't allow adding reason label. Any concerns?

I don't know, but wouldn't using `kube_job_status_failed` instead of `kube_job_failed` solve your issue?

**Comment by CatherineF-dev** [comment]
Yes, kube_job_status_failed has reason.
https://github.com/kubernetes/kube-state-metrics/blob/9e6e70d328c5d750a0df84cc044c38124b271538/internal/store/job_test.go#L207
