### ISSUE TITLE
failed to list *v2.HorizontalPodAutoscaler: the server could not find the requested resource

### ISSUE THREAD

**Issue by wang007** [kubernetes/kube-state-metrics#2392]
**What happened**:
E0517 08:27:54.618278       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.5/tools/cache/reflector.go:231: Failed to watch *v2.HorizontalPodAutoscaler: failed to list *v2.HorizontalPodAutoscaler: the server could not find the requested resource

**What you expected to happen**:
list and watch hpa.

kube-state-metrics uses v2 hpa, but api-server does not support v2 hpa. Is it compatible?

**Environment**:
Client Version: v1.29.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.22.13

**Comment by CatherineF-dev** [comment]
Not compatible. https://github.com/kubernetes/kube-state-metrics?tab=readme-ov-file#compatibility-matrix

**Comment by wang007** [comment]
ok. thx
