### ISSUE TITLE
When is the next release scheduled? Will it be based on "Debian GNU/Linux 12 (Bookworm)"?

### ISSUE THREAD

**Issue by TechBRSavvy** [kubernetes/kube-state-metrics#2406]
Hi Team,

It seems the last released v2.12.0 is built based on "Debian GNU/Linux 11 (bullseye)" which is going end of life in 2 months (31 Jul 2024) (Ref: https://endoflife.date/debian).

I am assuming next release will be based on the "Debian GNU/Linux 12 (Bookworm)". So the question is when is the next release planned and is it safe assumption that it will be based on "Debian GNU/Linux 12 (Bookworm)"?

Thanks in advance

**Comment by mrueg** [comment]
I don't know how bitnami builds their distribution of kube-state-metrics, it's not supported by this repository.

We're using distroless/static:latest in our Dockerfile, I assume distroless upstream will switch the tags over at some point. If this is a concern for you, please raise an issue upstream. https://github.com/GoogleContainerTools/distroless/

**Comment by TechBRSavvy** [comment]
@mrueg 

Thats fine. I will wait for the next release of 2.13.0 to be done. I am assuming that will be based on the "Debian GNU/Linux 12 (Bookworm)".

**Comment by mrueg** [comment]
It looks like debian 11 builds are gone in https://github.com/GoogleContainerTools/distroless/commit/1533e54a73805ec13fe0cc68218fc7a215a0a6f7 so v2.14.0 should be using bookworm.
