### ISSUE TITLE
Support metrics for Sidecar containers

### ISSUE THREAD

**Issue by Stono** [kubernetes/kube-state-metrics#2436]
**What would you like to be added**:

`kube_pod_container_resource_requests` should support Sidecar containers (those with `restartPolicy: Always`).  

**Why is this needed**:

We've recently migrated a bunch of workloads from `containers` to `initContainers`, such as `istio-proxy`, `cloudsql-proxy` etc.  We use to use `kube_pod_container_resource_requests{container="istio-proxy"}` to generate alerts when the cpu usage of that container > the request.

**Describe the solution you'd like**

As `sidecar` containers are really just like any other running container, it would be good for them to just be included in `kube_pod_container_resource_requests` regardless of if they're in `containers` or `initContainers` with `restartPolicy: Always`.

**Additional context**

**Comment by Stono** [comment]
Ah, there is `kube_pod_init_container_resource_requests`.  Shall close this off and think about how we migrate across.

**Comment by joebowbeer** [comment]
See https://github.com/kubernetes/kube-state-metrics/issues/2729 for missing native sidecar memory limit
