### ISSUE TITLE
Need help to troubleshoot/understand issue with KSM pods

### ISSUE THREAD

**Issue by beingashwin** [kubernetes/kube-state-metrics#2440]
Hi,

We are getting a crashloopbackoff error on ama agent KSM pod

we tried to increase node rss but it does not seem to be the issue.in the logs it is complaining about annotations
logs below
![image](https://github.com/kubernetes/kube-state-metrics/assets/50450773/f22b87ff-01de-4ec2-ae90-2c08c0f8830b)
cluster info below
![image](https://github.com/kubernetes/kube-state-metrics/assets/50450773/84b53456-d8d1-4465-b917-8a33bae9544d)

what can be done here?

**Comment by dgrisonnet** [comment]
@beingashwin as said in the log message, `monitoring` is not a kube-state-metrics resource. This flag only work for resources for which kube-state-metrics exposes metrics by default. These metrics are documented in https://github.com/kubernetes/kube-state-metrics/tree/main/docs/metrics.

If you want to add annotation metrics for your Prometheus CRD, then I'd recommend looking into https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/extend/customresourcestate-metrics.md, which explains how to add your own metrics for your CRDs.
