### ISSUE TITLE
Version is not applied to the container release binary 

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#2455]
**What happened**:
https://github.com/kubernetes/kube-state-metrics/pull/2361/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R5 requires gomplate to be installed to read the version.

The Dockerfile currently does not run make install-tools to install gomplate
**What you expected to happen**:
We should install them during the build process in the Dockerfile to ensure that the version is correctly read.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
See: https://kubernetes.slack.com/archives/CJJ529RUY/p1721936633731669
**Environment**:

* kube-state-metrics version: v2.12.0+
* Kubernetes version (use `kubectl version`):
* Cloud provider or hardware configuration:
* Other info:

CC: @Pokom

**Comment by Pokom** [comment]
Thanks for filing the issue @mrueg! Do you need any helping on crafting a fix?
