### ISSUE TITLE
Version info missing in v2.13.0

### ISSUE THREAD

**Issue by SuperQ** [kubernetes/kube-state-metrics#2459]
**What happened**:

The official container image is missing build info:
```
kube_state_metrics_build_info{branch="",goarch="amd64",goos="linux",goversion="go1.22.5",revision="unknown",tags="unknown",version="v"} 1
```

**What you expected to happen**:
```
kube_state_metrics_build_info{branch="main",goarch="amd64",goos="linux",goversion="go1.22.5",revision="...",tags="...",version="v2.13.0"} 1
```

**Anything else we need to know?**:

**Environment**:

* kube-state-metrics version: v2.13.0

**Comment by mrueg** [comment]
Thanks! We're already aware and have fixed it in the main branch. See: https://github.com/kubernetes/kube-state-metrics/issues/2455
