### ISSUE TITLE
kube-state-metrics jsonnet format wrong

### ISSUE THREAD

**Issue by wangjc0216** [kubernetes/kube-state-metrics#2460]
**What happened**:

I can't build correct kube-state-metrics yaml  in  [ kube-prometheus customizing](https://github.com/prometheus-operator/kube-prometheus/blob/v0.13.0/docs/customizing.md) 

**What you expected to happen**:

I found the spelling mistake in this project , I want to fix it

**How to reproduce it (as minimally and precisely as possible)**:

Just replay in the [docs](https://github.com/prometheus-operator/kube-prometheus/blob/v0.13.0/docs/customizing.md)

```
$ mkdir my-kube-prometheus; cd my-kube-prometheus
$ jb init  # Creates the initial/empty `jsonnetfile.json`
# Install the kube-prometheus dependency
$ jb install github.com/prometheus-operator/kube-prometheus/jsonnet/kube-prometheus@main # Creates `vendor/` & `jsonnetfile.lock.json`, and fills in `jsonnetfile.json`

$ wget https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/example.jsonnet -O example.jsonnet
$ wget https://raw.githubusercontent.com/prometheus-operator/kube-prometheus/main/build.sh -O build.sh
$ chmod +x build.sh

$ ./build.sh 
# print error 
RUNTIME ERROR: vendor/github.com/kubernetes/kube-state-metrics/jsonnet/kube-state-metrics/kube-state-metrics.libsonnet:392:21-22 Expected token OPERATOR but got "{"
	vendor/kube-prometheus/components/kube-state-metrics.libsonnet:51:19-124	function <anonymous>
	vendor/kube-prometheus/main.libsonnet:136:21-64	object <anonymous>
	vendor/kube-prometheus/platforms/platforms.libsonnet:37:22-40	+:
	example.jsonnet:33:90-109	thunk from <$>
	<std>:1539:24-25	thunk from <function <anonymous>>
	<std>:1539:5-33	function <anonymous>
	example.jsonnet:33:73-110	$
	example.jsonnet:33:1-112	
	example.jsonnet:33:1-112	
	During evaluation	


```

**Anything else we need to know?**:

**Environment**:  a pc with golang env

**Comment by TimothySutton81** [comment]
It appears this check in has several bugs to the format https://github.com/kubernetes/kube-state-metrics/commit/b45913db5963958c0008cb5f8a608402f3b74c1c follow up, I tried adding single quotes where it looked like they were missing as well still no dice. I am unfortunately not familiar enough with what is expected here to fix it myself.

**Comment by wangjc0216** [comment]
seems like  #2454 already fix it
