### ISSUE TITLE
Feature request: Create a new `kube_${entity}_annotations` set of metrics

### ISSUE THREAD

**Issue by andrewhowdencom** [kubernetes/kube-state-metrics#250]
The use case for this is to append annotations to metrics, such that new slices of the data can be created for review. For example, adding a `sitewards.com/project: "SITEWARDS"` to a pod would allow querying of the sum of CPU used by the Sitewards project.

This is possible now, but not so elegant. Currently, there are two metrics that expose metadata about a pod:

kube_pod_info
kube_pod_labels

This is useful in combination with the `group` feature of Prometheus to append additional metadata to the metrics. This is demonstrated more fully in the following post:

https://www.weave.works/blog/aggregating-pod-resource-cpu-memory-usage-arbitrary-labels-prometheus/

Kubernetes has two mechanisms that are capable of storing arbitrary key/value data:

- labels
- annotations

Labels are load bearing, in the sense that the core API uses them to make decisions around which traffic should be routed to what application, or how many of a given application should exist. It is perhaps thus not a good idea to overload these labels simply to add arbitrary key / value data, only useful when viewing data exported from the cluster.

Thus, I propose a new metric is created for each monitored entity that exports the annotations associated with a pod.

Annotations are problematic in a couple of ways:

1. They can contain large blogs of data. `kubernetes.io/created-by=${JSON}` includes a large json blob. I would thus suggest they are truncated at some point.
2. The data they store can be unique, and thus create lots of time-series. Programs may store backup information there, or last modified, or a number of other properties. To resolve this, I would suggest adding a CLI argument that limited the annotations filtered by CSV. This may further help with 1.
3. They are arbitrary, and have no character limitations. I would suggest simply running a replace with the invalid characters to `_`.

Such a patch is likely behind my skills as a golang developer.. But this is a problem that I'm facing, and I'm thus documenting it here in case someone is inspired, and would look to implement this.

**Comment by matthiasr** [comment]
I think 3. is not such a big issue, since the label names already need to be treated this way, and label _values_ are pretty freeform in Prometheus too.

**Comment by matthiasr** [comment]
Do I understand your suggestion in 2. correctly that this should be *exclusively* whitelist based? I can get behind that.

**Comment by andrewhowdencom** [comment]
I would probably run it something like default disabled, encourage a whitelist approach where it's something akin to `--allowed-annotations=sitewards.com/project,foo.com/bar` but allow `--allowed-annotations=*`. 

I can't envision a use case for the last one, and it will quicklly spam Prometheus full of crap (thus default disabled) however I also can't think of why annotations are somehow different from labels, in the verbosity of their data.

People use them differently, and I would provide hints that this is the case -- but there's nothing about their construction, as far as I can see, that means they must be different and thus might need a different user interface.
