### ISSUE TITLE
Release branch cut requested to implement Go version update

### ISSUE THREAD

**Issue by martidelviscovo** [kubernetes/kube-state-metrics#2523]
As a fix to 3 CVEs, we requested an upgrade of the go language in https://github.com/kubernetes/kube-state-metrics/issues/2512. This was merged in https://github.com/kubernetes/kube-state-metrics/pull/2493/files. However, we need a new release branch to be cut to test and update the version of kube-state-metrics we import.

**Comment by CatherineF-dev** [comment]
@martidelviscovo, we are planning the next release now.

**Comment by CatherineF-dev** [comment]
See https://github.com/kubernetes/kube-state-metrics/milestone/7

**Comment by martidelviscovo** [comment]
Hello! I see the issue is at 100% now. Can we cut a release?

**Comment by CatherineF-dev** [comment]
https://github.com/kubernetes/kube-state-metrics/pull/2538
