### ISSUE TITLE
Support for JobSet metrics

### ISSUE THREAD

**Issue by chelseychen** [kubernetes/kube-state-metrics#2560]
**What would you like to be added**:

Expose metrics about JobSet resource: https://jobset.sigs.k8s.io/docs/reference/jobset.v1alpha2/

**Why is this needed**:

For better monitoring of AI training job status.

**Describe the solution you'd like**

Following docs/developer/guide.md to add a new JobSet resource with a few metrics reporting the status of the JobSet.

**Additional context**

**Comment by mrueg** [comment]
closing this one as we won't be able to support non-native resources in ksm at this moment.
