### ISSUE TITLE
List/watch store shouldn't be created for non-existing CRD

### ISSUE THREAD

**Issue by chelseychen** [kubernetes/kube-state-metrics#2566]
**What happened**:

I was tring to use CRS to collect my CR metrics and was looking into the codes, and found something that might be a bug.

IIUC everytime there's a new Add/Delete event in CRDiscoverer, it will [re-build the CR stores and restart all available stores](https://github.com/kubernetes/kube-state-metrics/blob/main/internal/discovery/discovery.go#L254-L256). `factoryGenerator` is where it recreates CR store builders using CRS config and discovery cache, which points to [here](https://github.com/kubernetes/kube-state-metrics/blob/main/pkg/customresourcestate/config.go#L186-L217). For every Custom Resource that is defined in CRS config, `ResolveGVKToGVKPs` function is used for finding the matching CR in the discovery cache, and only those having matched entries in the cache map will be returned. However, for the case where both version and kind is specified, it will [always return GVK no matter whether it exists in the cache or not](https://github.com/kubernetes/kube-state-metrics/blob/release-2.14/internal/discovery/discovery.go#L129-L147). This is causing the following issue:

For example, in CRS config I define my resource with GVK all specified:

```
kind: CustomResourceStateMetrics
spec:
  resources:
    - groupVersionKind:
        group: jobset.x-k8s.io
        kind: "JobSet"
        version: "v1alpha2"
```

Even if JobSet CRD is **not** registered, KSM will still bring up a store to list and watch my JobSet resource which causes spamming list/watch error logs `failed to list`.

Is this intended?

**What you expected to happen**:

From what I understand, for the above case, it shouldn't create a list/watch store for JobSet when it's not registered in API server.

Basically in `ResolveGVKToGVKPs`, the logic should be:

```
	if hasVersion && hasKind {
		for _, el := range r.Map[g][v] {
			if el.Kind == k {
				return []groupVersionKindPlural{
						{
							GroupVersionKind: schema.GroupVersionKind{
								Group:   g,
								Version: v,
								Kind:    k,
							},
							Plural: el.Plural,
						},
				}, nil
			}
		}
	}
```

**How to reproduce it (as minimally and precisely as possible)**:

```bash
# An example: https://github.com/kubernetes/kube-state-metrics/issues/2223#issuecomment-1792850276
minikube start
...
go run main.go --custom-resource-state-only --custom-resource-state-config-file ksm-2223/custom-resource-config-file.yaml --kubeconfig ~/.kube/config
```

**Anything else we need to know?**:

**Environment**:

* kube-state-metrics version:
* Kubernetes version (use `kubectl version`):
* Cloud provider or hardware configuration:
* Other info:

**Comment by rexagod** [comment]
FYI We rebuild stores at CRD events currently to maintain metrics for different versions, since otherwise, the APIServer tends to resolve them to the latest one, which could break backwards compatibility for us. https://github.com/kubernetes/enhancements/pull/4811 improves on this by relying on APIServer's version (see https://github.com/kubernetes/client-go/issues/1251 for more info).

**Comment by chelseychen** [comment]
> To provide some context, we rebuild stores at CRD events currently to maintain metrics for different versions, since otherwise, the APIServer tends to resolve them to the latest one, which could break backwards compatibility for us. [kubernetes/enhancements#4811](https://github.com/kubernetes/enhancements/pull/4811) improves on this by relying on APIServer's version (see [kubernetes/client-go#1251](https://github.com/kubernetes/client-go/issues/1251) for more info).

Got it, thanks for providing this information!
