### ISSUE TITLE
Content-Type header for Prometheus 3.0.0

### ISSUE THREAD

**Issue by jcpunk** [kubernetes/kube-state-metrics#2568]
### Is your feature request related to a problem? Please describe.

Prometheus 3.0.0 has the option (by default) to be far more strict about what content it scrapes. This can cause unexpected scrape failures for the prometheus exporter.

### Describe the solution you'd like

Set the header "to the correct value". 

### Describe alternatives you've considered

If a scrape target is not providing the correct Content-Type header the fallback protocol can be specified using the fallback_scrape_protocol parameter. 

### Additional context

From : https://prometheus.io/docs/prometheus/3.0/migration/
> Prometheus v3 is more strict concerning the Content-Type header received when scraping. Prometheus v2 would default to the standard Prometheus text protocol if the target being scraped did not specify a Content-Type header or if the header was unparsable or unrecognised. This could lead to incorrect data being parsed in the scrape. Prometheus v3 will now fail the scrape in such cases.

**Comment by dgrisonnet** [comment]
Kube-state-metrics sets the content-type explicitly: https://github.com/kubernetes/kube-state-metrics/blob/fb28420d3c8648aa06c95eadc03afa3ef47f23c4/pkg/metricshandler/metrics_handler.go#L207
