### ISSUE TITLE
cannot find pod's network monitoring

### ISSUE THREAD

**Issue by txg1550759** [kubernetes/kube-state-metrics#258]
cannot find pod's network monitoring metrics,What happened? how fix bug?

**Comment by andyxning** [comment]
@txg1550759 Actually we have not collect any network related metrics for now.

What metrics do you want to collect as for pod network?

**Comment by brancz** [comment]
kube-state-metrics only collects metrics off of the information available in Kubernetes API objects, so I'm wondering what kind of metrics you are looking for.

**Comment by r4j4h** [comment]
He may be referring to the removed `kube_node_status_network_unavailable` metric. It's brethren were all moved to `kube_node_status_condition` but since network unavailable isn't a classic/official condition it seems to have been dropped.

All conditions listed by `kubectl describe no` seem present though.

**Comment by r4j4h** [comment]
Ugh I forgot /reopen, re-posting so bot sees it. Re-including message incase someone has some summary tool that only shows this comment.

/reopen

1.0.0-rc1 collapsed several metrics including kube_node_status_network_unavailable into kube_node_status_condition and NodeNetworkUnavailable still exists in this project's tests so I don't think this issue should be closed until an official word is put on the matter as it really seems like the kube_node_status_condition started a regression and it was intended for this to be present through the new metric.

(sorry for spam/double-post, tried editing first but bot didn't seem to notice)

**Comment by brancz** [comment]
This issue is about _pod_ metrics, whereas you're describing node metrics. If as you describe those metrics with the respective condition label are not present, then that's indeed a regression.
