### ISSUE TITLE
Difference between a restart=Never and restart=Always is very important for pod states

### ISSUE THREAD

**Issue by smarterclayton** [kubernetes/kube-state-metrics#263]
Currently pod metrics don't distinguish well between restart Never and Always pods.  Since the two workloads are very, very different, it doesn't seem unreasonable to distinguish them.

`kube_pod_created` really lacks the equivalent in `kube_pod_terminated` - once a pod is terminated, the majority of its function on the cluster is complete.  None of the existing pod metrics represent that in any way.

Example queries that are difficult / impossible:

1. number of pods that would fall under the terminating quota at this time
2. sum of pod resource limits in the terminating quota
3. average runtime of pods per namespace
4. average runtime of pods by resource request

**Comment by brancz** [comment]
I'm open for suggestions on how to fix the described problems.

**Comment by smarterclayton** [comment]
/reopen

I think the simplest possible option here is that pods that are RestartAlways and RestartNever are completely different, and there should be a metric that reports that so we can identify the difference in usage between batch and long running.  One example could be:

```
kube_pod_restart_policy{name="RestartAlways"} 1
```

Another option is

```
kube_pod_restart_always{...} 1 // restarts always
kube_pod_restart_always{...} 0 // restarts never
```

**Comment by brancz** [comment]
Yeah I think this is a classic enum type metric that we have all over the place, which would be the second option.

**Comment by smarterclayton** [comment]
the key distinction is "run to completion" vs "run forever", (even though we have the RestartOnFailure and RestartNever, in practice they are lumped together by almost every part of the system)
