### ISSUE TITLE
multi-version resource metrics supported

### ISSUE THREAD

**Issue by zouyee** [kubernetes/kube-state-metrics#265]
Is it suitable to change the arch of collectors like [typed](https://github.com/kubernetes/client-go/tree/release-5.0/kubernetes/typed),according to the comments of the [PR](https://github.com/kubernetes/kube-state-metrics/pull/220/)
![2017-09-25 9 53 41](https://user-images.githubusercontent.com/5785605/30789475-619afe38-a1d8-11e7-8744-9acb70317597.png)
@andyxning @brancz

**Comment by brancz** [comment]
Our compatibility guarantees revolve around the client-go version so as APIs get deprecated we move to the new APIs. I feel that is going to be a better experience for the user, then breaking all metrics available, as API changes are generally small throughout the evolution of an object.

**Comment by andyxning** [comment]
This is a good question. What if there are two available group versions for a resource object. As for now, we hard code the specific group version for a resource version.

I am not quite sure that whether there are chances more than one group versions are available.

Aside from the above concerns, what if a reource graduate from beta to GA, which version should kube-state-metrics supports. 

BTW, log the currently used resource version for a resource should be user friendly for debugging.

**Comment by andyxning** [comment]
This will definitely make kube-state-metrics more easy to avolve and maintain. I agree with this approach. I suggest we add a statement about the resource version behavior in readme to make this clear to end users.  @brancz WDYT.

**Comment by andyxning** [comment]
Sorry for the press wrong button. :(

**Comment by brancz** [comment]
No worries, clicking the wrong button happens :slightly_smiling_face: . A note in the readme sounds good. Probably most suitable in the upcoming compatibility matrix section.

**Comment by andyxning** [comment]
yep. Kubernebtes resource group version compatibility. @zouyee since you are the contributor to the kunernetes compatibility pr, could you please update the pr by adding the new resource group version compatibility.

**Comment by vincevaghalsen** [comment]
Only if the client generates programmatic IDs to exclude redundant metrics. Prometheus should always be initiated with a multilevel manifest in the cluster.
