### ISSUE TITLE
v1.0.1 not gathering data, repeated CronJob error

### ISSUE THREAD

**Issue by sgmiller** [kubernetes/kube-state-metrics#275]
Kubernetes v1.7.4, only this in the logs for kube-state-metrics:

E1013 15:02:43.602589       7 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource

**Comment by brancz** [comment]
I believe your cluster has alpha features disabled, that would explain this error.

**Comment by sgmiller** [comment]
No, I believe CronJob is no longer alpha.

**Comment by brancz** [comment]
It was only promoted to beta in 1.8, your cluster is 1.7.4, which is where it was still in alpha, and the code if definitely using the alpha API.

https://github.com/kubernetes/kube-state-metrics/blob/64428b457722fe8bbd4e877dd689fab7f8fd86f9/collectors/cronjob.go#L80

**Comment by andyxning** [comment]
@sgmiller 

In order to diagnose the problem. Could you please help us to provide the following info
* please check the `http://API_SERVER:8080/apis/batch` and post the response here.
* if there is an item of `batch/v2alpha1` in above response, please check the `http://10.3.23.159:8080/apis/batch/v2alpha1` endpoints and post the response here.

**Comment by sgmiller** [comment]
I wound up enabling that api to get around the problem.  As long as ksm is still reporting all other metrics while erroring out on that call I don't consider this a problem.  If it derails the collection then it is.

**Comment by brancz** [comment]
> As long as ksm is still reporting all other metrics while erroring out on that call I don't consider this a problem.

That's exactly how it works :slightly_smiling_face: . Even if an individual collector errors out on any action, the functioning collectors will continue as usual.

**Comment by andyxning** [comment]
Since it has been resolved. We should close this. :)
