### ISSUE TITLE
Expose more labels on services

### ISSUE THREAD

**Issue by felixPG** [kubernetes/kube-state-metrics#293]
Hi:

Currently **kube_service_info** metrics only expose information about a service name, instance, etc. but what about the name of pods that this service could access?

**Comment by brancz** [comment]
If at all that would be part of a set of metrics extracted from `Endpoints` objects.

**Comment by felixPG** [comment]
Is possible to include, request access count, response time, request size for a service, like whatever http/s service metrics?

**Comment by brancz** [comment]
No that would be the responsibility of your application and or ingress as well as kube-proxy (or kube-proxy alternative) to expose. kube-state-metrics only purpose is to create metrics from API objects in Kubernetes.
