### ISSUE TITLE
Space used in persistvolumeclaim

### ISSUE THREAD

**Issue by yeplaa** [kubernetes/kube-state-metrics#304]
Hello,

My environment is kube-state-metrics 1.1, Prometheus 1.7.1, K8S 1.7.5.
With kube-state-metrics, I would like to retrieve the stats about used persistentvolumeclaim space.
Actually, it seems only the metrics "kube_persistentvolumeclaim_resource_requests_storage_bytes" is available with kube-state-metrics.  Are there any other metrics available for my need on k8s 1.6/1.7? 
On K8s 1.8, kubelet exposes the metrics kubelet_volume_stats_available_bytes, kubelet_volume_stats_used_bytes that could meet the need.  
Is it expected that kube-state-metrics can recover it?

Thank's
Loïc

**Comment by brancz** [comment]
kube-state-metrics is intended to _only_ expose information available to it via Kubernetes API objects. So if the `PersistentVolumeClaim` object were to implement this, it could be something we could implement this. However I highly recommend to scrape the information from the real life origin, meaning the kubelet is the process that actually knows about this, if this information came from the Kubernetes API object, this would be an additional indirection.

**Comment by yeplaa** [comment]
Thank's for your reply brancz
