### ISSUE TITLE
Unable to enable HPA collector/no hpa metrics

### ISSUE THREAD

**Issue by tmegow** [kubernetes/kube-state-metrics#306]
I'm running the latest v1.1.0 release and I am unable to see hpa metrics
```
# curl -s 10.77.77.177:8003/metrics | grep kube_hpa
#
```

Looking at the help output I see this informative message: `--collectors string                Comma-separated list of collectors to be enabled. Defaults to "cronjobs,daemonsets,deployments,jobs,limitranges,namespaces,nodes,persistentvolumeclaims,pods,replicasets,replicationcontrollers,resourcequotas,services,statefulsets"`

If I try specifically enabling that collector with `--collectors="cronjobs,daemonsets,deployments,jobs,limitranges,namespaces,nodes,persistentvolumeclaims,pods,replicasets,replicationcontrollers,resourcequotas,services,statefulsets,horizontalpodautoscalers"` I get:
`F1121 17:50:38.057655       1 main.go:98] Collector "horizontalpodautoscalers" does not exist`

How can I see the hpa metrics? Where am I going wrong?

**Comment by brancz** [comment]
The HPA metrics have not been released yet. The documentation on the master branch potentially contains unreleased features, we recommend looking at the documentation at the commit of the git release tag.
