### ISSUE TITLE
deploy error

### ISSUE THREAD

**Issue by beatlejuse** [kubernetes/kube-state-metrics#308]
i have a problem with deploy ClusterRole, ClusterRoleBinding, Role and RoleBinding.
here are my .yaml:
https://gist.github.com/beatlejuse/8ed9ac9db38c5b58c07cdf7e1d8d3fb3
and here are my logs:
Error from server (Forbidden): error when creating "./k8s/monitoring/exporters/kubernetes/kube-state-metrics-role.yml": clusterroles.rbac.authorization.k8s.io "kube-state-metrics" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["resourcequotas"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["resourcequotas"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["replicationcontrollers"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["replicationcontrollers"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["limitranges"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["limitranges"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["daemonsets"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["daemonsets"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["replicasets"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["replicasets"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["list"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["watch"]}] user=&{kube-admin  [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
Error from server (Forbidden): error when creating "./k8s/monitoring/exporters/kubernetes/kube-state-metrics-role.yml": roles.rbac.authorization.k8s.io "kube-state-metrics-resizer" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]}] user=&{kube-admin  [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
error validating "./k8s/monitoring/exporters/kubernetes/kube-state-metrics-role.yml": error validating data: found invalid field namespace for v1.ServiceAccount; if you choose to ignore these errors, turn validation off with --validate=false

I use k8s v1.8.1 and have full admin rights in k8s.

**Comment by brancz** [comment]
Is this on GKE?

**Comment by beatlejuse** [comment]
@brancz  yes, this is on CoreOS 1520.8.0, docker 1.12.6 and k8s 1.8.1

**Comment by nuriel77** [comment]
I am having the same problem:
```sh
# kubectl create -f kubernetes
clusterrolebinding "kube-state-metrics" created
deployment "kube-state-metrics" created
rolebinding "kube-state-metrics" created
serviceaccount "kube-state-metrics" created
service "kube-state-metrics" created
Error from server (Forbidden): error when creating "kubernetes/kube-state-metrics-cluster-role.yaml": clusterroles.rbac.authorization.k8s.io "kube-state-metrics" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["resourcequotas"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["resourcequotas"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["replicationcontrollers"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["replicationcontrollers"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["limitranges"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["limitranges"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["daemonsets"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["daemonsets"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["replicasets"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["replicasets"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["list"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["watch"]} PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["list"]} PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["watch"]} PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["list"]} PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["watch"]}] user=&{admin admin [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
Error from server (Forbidden): error when creating "kubernetes/kube-state-metrics-role.yaml": roles.rbac.authorization.k8s.io "kube-state-metrics-resizer" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["deployments"], ResourceNames:["kube-state-metrics"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["deployments"], ResourceNames:["kube-state-metrics"], APIGroups:["extensions"], Verbs:["update"]}] user=&{admin admin [system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[]
```

```sh
# kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-26T13:03:52Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
(Centos Atomic)

**Comment by brancz** [comment]
The errors say, that you are trying to grant higher privileges to an application that you have yourself. Please check that you do have these roles, and if it still holds true, then this is rather an issue on upstream Kubernetes than here.

**Comment by beatlejuse** [comment]
@brancz i have a full admin privileges.
this problem in your  kube-state-metrics-cluster-role.yaml and kube-state-metrics-role.yaml files - they don't correct or incompatible with kubernetes 1.8.1

**Comment by beatlejuse** [comment]
here is an example working configuration ClusterRole:
https://github.com/rook/rook/blob/master/cluster/examples/kubernetes/rook-operator.yaml
it works I have now on kubernetes 1.8.1 and worked on kubernetes 1.6.1

**Comment by beatlejuse** [comment]
yes, i fix it!
https://gist.github.com/beatlejuse/b795f2dcf1c2bbd674cff66190660818
this is right kube-state-metrics-cluster-role.yaml 
it's work for me

**Comment by brancz** [comment]
Feel free to update it, and open a PR :slightly_smiling_face:

**Comment by nuriel77** [comment]
Didn't work for me :(
Still getting the same forbidden error.
I have no roles, role/bindings or clusterrolebindings whatsoever configured in kubernetes.
