### ISSUE TITLE
Missing deployment metric metadata.generation 

### ISSUE THREAD

**Issue by lymichaels** [kubernetes/kube-state-metrics#32]
I'm trying to use the metrics provided by this project but it's missing the metadata.generation metric to check for status of a deployment. It would be great if that could be added in!

Below is from the kubernetes docs about deployments. I'm using that as a guideline to check if deployments fail or not and then send out an alert if it does fail.
> 
After creating or updating a Deployment, you would want to confirm whether it succeeded or not. The simplest way to do this is through kubectl rollout status.

> 
This verifies the Deployment’s **.status.observedGeneration >= .metadata.generation**, and its up-to-date replicas (**.status.updatedReplicas**) matches the desired replicas (**.spec.replicas**) to determine if the rollout succeeded. If the rollout is still in progress, it watches for Deployment status changes and prints related messages.
Note that it’s impossible to know whether a Deployment will ever succeed, so if the above command doesn’t return success, you’ll need to timeout and give up at some point.
Additionally, if you set **.spec.minReadySeconds**, you would also want to check if the available replicas (**.status.availableReplicas**) matches the desired replicas too.

**Comment by shamil** [comment]
Submitted PR that adds the `metadata.generaation` metric
