### ISSUE TITLE
Release docker image for latest

### ISSUE THREAD

**Issue by AndreaGiardini** [kubernetes/kube-state-metrics#320]
Hello everyone

I noticed that the `latest` tag for the docker image corresponds to the latest release that has been published. Could we change this behavior in order to have `latest` = latest commit on master?

**Comment by brancz** [comment]
In that case I would prefer creating an actual `master` tag. The `latest` tag pointing at the latest release is a common (and in my opinion good) practice. Happy to introduce the `master` tag though and happy about PRs for it :slightly_smiling_face: .

**Comment by andyxning** [comment]
This definitely needs some automation for pulling master branch, building the image  and pushing image.

**Comment by zouyee** [comment]
It has been released.

**Comment by AndreaGiardini** [comment]
@zouyee I do not see any `master` tag at quay.io/coreos/kube-state-metrics

**Comment by zouyee** [comment]
`quay.io/coreos/kube-state-metrics:v1.2.0-rc.0 ` is the newest image.

**Comment by AndreaGiardini** [comment]
Yeah... but my ticket was about having a `master` tag. In order to have a docker image with all the latest commits

**Comment by brancz** [comment]
yes this is still to be done

**Comment by Jukie** [comment]
What's required to make this work? Would it be as simple as adding a new target in the Makefile similar to https://github.com/kubernetes/kube-state-metrics/blob/master/Makefile#L97? If that was done, I imagine there would also need to be some extra steps on the ci side to trigger a build on every commit to master or PR merge.
