### ISSUE TITLE
Not able to get HPA metrics

### ISSUE THREAD

**Issue by utsav2307** [kubernetes/kube-state-metrics#321]
I have deployed kube-state-metrics in my cluster, now when i do a curl on /metrics for the container endpoint, I am able to get Replication Controller and Deployments metrics, but there are no metrics for Horizontal Pod Autoscaler. Any idea what can be the issue?

**Comment by brancz** [comment]
HPA metrics are only on master, they have not been released yet.

**Comment by utsav2307** [comment]
Oh ok. Is there any plan for a release with hpa in near future?

**Comment by brancz** [comment]
I believe we have worked on the majority of features that we wanted for the next minor release, so I think we should be able to release rather sooner than later.

**Comment by utsav2307** [comment]
Oh great! Hoping this will happen in next couple of weeks(fingers crossed). Thanks for the update.

**Comment by brancz** [comment]
I can't promise anything, but I imagine somewhere mid January as everyone is on vacation over the holidays until the 3rd or so of January.

**Comment by andyxning** [comment]
Before releasing a new version, i think we can also update `client-go` to `v6.0.0`. :)

**Comment by zouyee** [comment]
I will complete it after updated client-go version.

**Comment by andyxning** [comment]
@utsav2307 v1.2.0-rc.0 has been released last day. Could you please upgrade and help us test it?

**Comment by utsav2307** [comment]
sure, will chk if it solves my purpose

**Comment by andyxning** [comment]
Thanks @utsav2307. Hope you give v1.2.0-rc.0 a try and give us some feedback about how it is working. :)

For now, i will close this issue as hpa metrics is available in v1.2.0-rc.0. Feel free to re-open it if you still have some problems in using kube-state-metrics for hpa metrics. :)

**Comment by utsav2307** [comment]
Metrics seem to be fine, but it's difficult to get the alerts from prometheus whenever HPA is triggered. 
I tried using kube_hpa_status_current_replicas != kube_hpa_status_desired_replicas but this gets resolved instantly coz of which alerts don't get triggered

**Comment by brancz** [comment]
@utsav2307 have you tried the `for` clause in Prometheus alerting rules? It's expected that the HPA reconciles the current replicas to the desired replicas, that's the nature of a level trigger as Kubernetes implements it virtually everywhere. Using the `for` clause you can make sure, that a condition has been in the triggering state for at least X seconds/minutes/hours.
