### ISSUE TITLE
Question about the default Kubernetes Pod Metrics dashboard 

### ISSUE THREAD

**Issue by ahrtr** [kubernetes/kube-state-metrics#329]
I downloaded the default kubernetes Pod Metrics dashboard as below,
https://grafana.com/dashboards/747 

But I found that some metrics as below used in the dashboard do not exist in prometheus. What did I miss?
container_memory_working_set_bytes
container_cpu_usage_seconds_total
container_network_receive_bytes_total

Or can someone please provide some guide how to update the dashboard?

Some related information is as below,
prometheus version: v2.0.0
grafana version: v4.6.2
kube-state-metrics: quay.io/coreos/kube-state-metrics:v1.1.0
addon-resizer: gcr.io/google_containers/addon-resizer:1.0
OS: Oracle Linux 7.3

**Comment by zouyee** [comment]
these metrics were generated by cadvisor not ksm.

**Comment by ahrtr** [comment]
Thanks for the info.
