### ISSUE TITLE
Feature Request: Add a new metric for currently used resources in nodes. 

### ISSUE THREAD

**Issue by ahakanbaba** [kubernetes/kube-state-metrics#33]
Hi All,
We would like to propose a new metric addition that describes the used resources by pods in every node. 
Its name could be 
kube_node_current_pod_cpu_requests,
kube_node_requested_cpu_resources,
kube_node_allocated_cpu_resources. 

The names extend naturally for _memory_ 

Or something else suggested by you we are open to suggestions for names. 

As the desired semantics, we propose this metric to contain the sum of requested resources of all the currently running pods in that node.

The same computation is done every time one executes `kubectl describe node`. 
The resources table is computed every time from scratch. 
For example

```
 Namespace          Name                        CPU Requests    CPU Limits  Memory Requests Memory Limits
  ---------         ----                        ------------    ----------  --------------- -------------
  default           k8s-master-127.0.0.1                0 (0%)      0 (0%)      0 (0%)      0 (0%)
  default           k8s-proxy-127.0.0.1             0 (0%)      0 (0%)      0 (0%)      0 (0%)
  hello-world-hbaba-build   hello-world-hbaba-989929512-6jiaf       800m (20%)  20 (500%)   100Mi (2%)  100Mi (2%)
  hello-world-hbaba-build   hello-world-hbaba-989929512-8hq9v       800m (20%)  20 (500%)   100Mi (2%)  100Mi (2%)
  hello-world-hbaba-build   hello-world-hbaba-989929512-jjd5n       800m (20%)  20 (500%)   100Mi (2%)  100Mi (2%)
  hello-world-hbaba-build   hello-world-hbaba-989929512-n00t2       800m (20%)  20 (500%)   100Mi (2%)  100Mi (2%)
  kube-system           kube-dns-v10-z4ics              310m (7%)   310m (7%)   170Mi (4%)  170Mi (4%)
Allocated resources:
  (Total limits may be over 100%, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests  CPU Limits  Memory Requests Memory Limits
  ------------  ----------  --------------- -------------
  3510m (87%)   80310m (2007%)  570Mi (14%) 570Mi (14%)
````

The code for that table is in `kubernetes/pkg/kubectl/describe.go` file in `describeNodeResource` function. It iterates over a collection that is accessed like this : 
`nodeNonTerminatedPodsList, err := d.Core().Pods(namespace).List(api.ListOptions{FieldSelector: fieldSelector})`

For the above example the printed metrics would be 

```
kube_node_current_pod_cpu_requests{node="compute-node01"} 3510
kube_node_current_pod_memory_requests{node="compute-node01"} 80310
```

Our use case for this metric is the following: 
We would like to understand the "utilization" of the nodes and we would like to understand how much resources have been allocated to running pods and how much is left. 
We are interested in this "currentPodRequests" information at the node level as well as at the global cluster level. 

We have created this issue to get any reactions to this suggestion. Has there been any similar discussions before? Would a PR adding this metric welcomed ? 

Another alternative would be to extend the NodeStatus type and add a "currentPodRequests" field in the NodeStatus type in the kubernetes API. 

We have also created an [issue](https://github.com/kubernetes/kubernetes/issues/34073) about that approach in the kubernetes repo. Since that is an API change we cannot anticipate the reaction it is going to get .

We propose that it is valuable to add such a currentPodRequests metric for nodes into kube-state-metrics. 

Thanks

**Comment by matthiasr** [comment]
In principle you can get this data through the cAdvisor container metrics embedded in the kubelet. The problem there is that cAdvisor exposes kernel-level metrics (like CPU shares), and you need to reverse engineer how they were set by the kubelet (e.g. 1024 shares = 1.0 core requests).

**Comment by ahakanbaba** [comment]
Hi @matthiasr, thanks for your comment.

Is this an implementation suggestion? 
I was planning to use the same approach as the `kubectl describe node` implementation. 

As far as I can tell, it lists the nodes, then lists the pods, filters the pods according to the nodes and does some accumulation on them. 

Do you see obvious problems with implementing something similar to that in kube-state-metrics. 
PS: I have not proved to myself that this is possible. So I would appreciate any feedback or suggestions. 

Thanks

**Comment by matthiasr** [comment]
I just meant this as a workaround with what's there today. I agree that exposing the _logical_ values from the API is correct and within the scope of kube-state-metrics.

I'm not 100% sure (and would appreciate more opinions) on doing the addition beforehand (in kube-state-metrics) especially if it's _just_ a sum. At least for Prometheus, this is kind of what it does.

**Comment by fabxc** [comment]
Exporting metrics should expose the raw data necessary to do further computation (especially aggregation) in the ingesting system.

I know that this is not necessarily true as is, as we are collecting metrics from the API that may also be produced by pre-computation. However, kube-state-metrics should not add to this by becoming an aggregator itself. 

There are many possible aggregations of various raw metrics, accumulating to hundreds of possible aggregates. Eventually, we'll be implementing them all, when a consuming system can provide the same, more efficiently and more dynamically. Especially when this goes as far as performing joins, which at some degree might require query planning to scale (actually the comment in #34 already asks for it).

As @matthiasr, I'm also in favor of exposing more base metrics to allow for the general use case.
We also want to add some missing labels that allow us to match/join metrics more easily. For example, we should probably have a `node` label in pod info additionally to `host_ip`.

Just using base metrics, your computation could then look like this in Prometheus:

```
sum by(node) (
    kube_container_requested_cpu * on(pod) group_left(node) kube_pod_info
)
```
_This matches both metrics on the `pod` label and adds the `node` label from the `kube_pod_info` to the result. The `*` is a noop as the info metrics are set to `1`. We can then sum the result by the `node` label._

This is a pretty simple query once familiar with the query language. It's a lot simpler and more flexible than the code shown here and benefits from the capabilities and future improvements of an underlying TSDB.
Similar approaches can be taken by many other systems that handle time series data.

The result can also be recorded (think materialized view in SQL) and then accessed by users via the simple `node:requests_cpu:sum` metric name.

```
node:requested_cpu:sum = sum by(node) (
    kube_container_requested_cpu * on(pod) group_left(node) kube_pod_info
)
```

**Comment by ahakanbaba** [comment]
Hi Fabian, 
thanks for your comments. 
I see your point about base metrics, a more purist approach to the kube-state-metrics. 
Keeping it simple is always appealing. 

Thanks for your suggestion to do this calculation more downstream in the TSDB level or similar. 
That suggestion agrees with our system as well. It is easily implementable too. 

So I will close this issue and follow up with a pull request where pod > container > requests are written out as metrics. 
Without any accumulation nor any special purpose calculation. 
Thanks

**Comment by htlhenry** [comment]
> Exporting metrics should expose the raw data necessary to do further computation (especially aggregation) in the ingesting system.
> 
> I know that this is not necessarily true as is, as we are collecting metrics from the API that may also be produced by pre-computation. However, kube-state-metrics should not add to this by becoming an aggregator itself.
> 
> There are many possible aggregations of various raw metrics, accumulating to hundreds of possible aggregates. Eventually, we'll be implementing them all, when a consuming system can provide the same, more efficiently and more dynamically. Especially when this goes as far as performing joins, which at some degree might require query planning to scale (actually the comment in #34 already asks for it).
> 
> As @matthiasr, I'm also in favor of exposing more base metrics to allow for the general use case.
> We also want to add some missing labels that allow us to match/join metrics more easily. For example, we should probably have a `node` label in pod info additionally to `host_ip`.
> 
> Just using base metrics, your computation could then look like this in Prometheus:
> 
> ```
> sum by(node) (
>     kube_pod_container_requested_cpu * on(pod) group_left(node) kube_pod_info
> )
> ```
> _This matches both metrics on the `pod` label and adds the `node` label from the `kube_pod_info` to the result. The `*` is a noop as the info metrics are set to `1`. We can then sum the result by the `node` label._
> 
> This is a pretty simple query once familiar with the query language. It's a lot simpler and more flexible than the code shown here and benefits from the capabilities and future improvements of an underlying TSDB.
> Similar approaches can be taken by many other systems that handle time series data.
> 
> The result can also be recorded (think materialized view in SQL) and then accessed by users via the simple `node:requested_cpu:sum` metric name.
> 
> ```
> node:requested_cpu:sum = sum by(node) (
>     kube_pod_container_requested_cpu * on(pod) group_left(node) kube_pod_info
> )
> ```
very clear
