### ISSUE TITLE
Adding more labels to kube_pod_status_phase

### ISSUE THREAD

**Issue by rajatjindal** [kubernetes/kube-state-metrics#332]
we had a situation where # of failed pod counts increased dramatically, and we were wondering what happened. 

on debugging we found 2 nodes were having docker issues and most of the failed nodes were being scheduled on those problematic nodes.

i think it will be useful to add more labels to kube_pod_status_phase, so that we can run query like all failed pods count group by node.

![screen shot 2018-01-04 at 10 23 43 am](https://user-images.githubusercontent.com/612092/34578331-6771b03a-f139-11e7-8516-daa6f4394fc5.png)

**Comment by rajatjindal** [comment]
I will be more than happy to open a PR if we agree that this is a reasonable ask.

**Comment by brancz** [comment]
That can be done at query time. Prometheus supports joins, so you can join pod info on the phase to figure out the node.

**Comment by andyxning** [comment]
Close this via @brancz's comments.

In case you have not used the join syntax of Prometheus, there is an example in the [#137 comment](https://github.com/kubernetes/kube-state-metrics/issues/137#issuecomment-299837471) with some query like:
```
sum by(node)(avg(kube_pod_info{}) by(node,pod,namespace)* on(pod, namespace) group_right(node) kube_pod_status_phase{phase="Failed"})
```

**Comment by rajatjindal** [comment]
thank you very much guys. I will try this out tonight
