### ISSUE TITLE
ksm v1.2.0-rc.0 on K8s 1.5.3 - Failed to list *v1beta1.CronJob

### ISSUE THREAD

**Issue by dannyk81** [kubernetes/kube-state-metrics#337]
Hey!

Was eager to try the new RC, however I'm getting the following errors when it tries to collect CronJobs:
```
E0105 16:13:29.620093       1 reflector.go:205] k8s.io/kube-state-metrics/collectors/cronjob.go:103: Failed to list *v1beta1.CronJob: the server could not find the requested resource
```

We are running Kubernetes 1.5.3, the following Api Versions are supported:
```
$ kubectl api-versions
apps/v1beta1
authentication.k8s.io/v1beta1
authorization.k8s.io/v1beta1
autoscaling/v1
batch/v1
batch/v2alpha1
certificates.k8s.io/v1alpha1
extensions/v1beta1
policy/v1beta1
rbac.authorization.k8s.io/v1alpha1
storage.k8s.io/v1beta1
v1
```

I believe the issue is that Batch API version in K8s 1.5.3 is still `batch/v2alpha1` and server doesn't support `batch/v1beta1`.

`batch/v1beta1` is available with Kubernetes 1.8 onwards (according to [this](https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/))

WDYT?

**Comment by dannyk81** [comment]
Ok, so I just saw https://github.com/kubernetes/kube-state-metrics/issues/295 🤦‍♂️ 

It seems that by switching the API version in 1.2.0 to `batch/v1beta1` it made it incompatible with K8s <1.8

Is there any way to support both? based on K8s api server version perhaps?

**Comment by andyxning** [comment]
Actually we have talked about using different resource group version according to different Kubernetes versions in #256 and #220 . But we have not make an conclusion about how to do this. :(

Will think about this later and hope to make it before v1.2.0 GA release.

**Comment by brancz** [comment]
> Will think about this later and hope to make it before v1.2.0 GA release.

I would prefer not to introduce any features between the v1.2.0 rc.0 and GA. We are not bound to the Kubernetes release cycle, so it's perfectly legit to do a v1.3.0 release once we figure out the discovery of availble APIs.

**Comment by dannyk81** [comment]
Sounds resaonble, so anyone using K8s <1.8 should stick to v1.1.0 until this is resolved? unless the CronJob metrics are not relevant I guess.

**Comment by andyxning** [comment]
@dannyk81 I am afraid that is true. We will try to fix it asap.

**Comment by brancz** [comment]
> Sounds resaonble, so anyone using K8s <1.8 should stick to v1.1.0 until this is resolved? unless the CronJob metrics are not relevant I guess.

There are no known bugs in `v1.1.0`, so for the time being you'll be ok. Obviously you should upgrade your kubernetes cluster regularly :slightly_smiling_face: .

**Comment by dannyk81** [comment]
Thanks @brancz, indeed we have no issue with v1.1.0 and will stick to it for now.

My main incentive for testing this RC was to get the new `kube_cronjob_labels` & `kube_job_labels` metrics.

Indeed, we are due for an upgrade, hope that we can get 1.8 deployed soon.

**Comment by spheromak** [comment]
how bout just letting us disable cronjob collection for clusters < 1.8 ?

**Comment by dannyk81** [comment]
@spheromak I believe you can do this by passing the `--collectors=` cli arg with the list of all collectors except cronjob.

The list can be found here: https://github.com/kubernetes/kube-state-metrics/blob/00bd666ccea53c89f978415ea3675722d89ccaaf/main.go#L70-L87
