### ISSUE TITLE
job label in kube_job_* metrics conflicts with the job label defined by scrape_config in Prometheus

### ISSUE THREAD

**Issue by dannyk81** [kubernetes/kube-state-metrics#338]
All the `kube_job_*` metrics have a `job` label with the name of the Job, however this label is conflicting with the `job` label assigned by Prometheus per what is defined in the `job_name` of the `scrape_config`

Prometheus keeps the original value of the label `job` in a new label called `exported_job`, but this is a bit confusing.

I think it would be better to rename the `job` label in the `kube_job_*` metrics to `job_name`

**Comment by brancz** [comment]
Does this also happen is `honor_labels` is set to `true`? Technically the kube-state-metrics target still has the job label, and the unique combination of labels still uniquely identify the metrics.

Nonetheless I think I agree, there are scenarios where this could become a problem.

**Comment by dannyk81** [comment]
It seems that `job` label is a special case in Prometheus, so if the source metric has a `job` label it is renamed to `exported_job`.

As you said, uniquness of the metrics is prserved, but I would rather we use a different label name and not `job`.

`job_name` sounds reasonable to me, but I'm not married to it :)

**Comment by dannyk81** [comment]
ping @brancz 😄

**Comment by brancz** [comment]
/remove-lifecycle stale

I'm not really happy with any of the solutions, I'll have to discuss more with the other prometheus devs to see if they have any better ideas.

**Comment by Renol7** [comment]
As a Prometheus user, for me it makes sense to use "job_name" as the label of source metric and "job" as the label of Prometheus job to do it consistently.

**Comment by brancz** [comment]
Agreed, let's change the label here to `job_name`.

**Comment by brancz** [comment]
As far as I know this has not been implemented yet, so re-opening this.
