### ISSUE TITLE
Empty reply from server

### ISSUE THREAD

**Issue by r0fls** [kubernetes/kube-state-metrics#350]
When I hit the metrics endpoint for the kube-state-metrics service I get an empty reply from the server:

```
$ curl kube-state-metrics:8080/metrics
curl: (52) Empty reply from server
```

It returns the correct response for `/`:

```
$ curl kube-state-metrics:8080/
<html>
             <head><title>Kube Metrics Server</title></head>
             <body>
             <h1>Kube Metrics</h1>
                         <ul>
             <li><a href='/metrics'>metrics</a></li>
             <li><a href='/healthz'>healthz</a></li>
                         </ul>
             </body>
             </html>
```

The kube-state-metrics logs don't show any errors or debug information. I'm raising this issue in hopes of suggestions to debug this, but also because I'm going to create a corresponding PR that adds logging to the prom handler.

**Comment by andyxning** [comment]
@r0fls Have you ever patch the kube-state-metrics with #351 and found the root reason about this?

**Comment by andyxning** [comment]
@r0fls Any clue in the kube-state-metrics log?

**Comment by andyxning** [comment]
@r0fls Any clue in the kube-state-metrics log?

**Comment by r0fls** [comment]
Ya, after uploading the image with logging enabled, it looks like it's an issue with the service account abilities 👍   I'll investigate that further, and close this out.

**Comment by r0fls** [comment]
Thanks for the help @andyxning!
