### ISSUE TITLE
additional status in kube_pod_container_status_waiting_reason

### ISSUE THREAD

**Issue by utsav2307** [kubernetes/kube-state-metrics#356]
currently only two types of status are available in kube_pod_container_status_waiting_reason metrics (ContainerCreating,ErrImagePull). 
Can this be modified to have "Pending"  as well, when the pods dont have enough resources to run?

**Comment by mheggeseth** [comment]
Also include `ImagePullBackOff` and `CrashLoopBackOff` as a potential waiting reasons.

`ImagePullBackOff` is the most prevalent waiting reason I see (k8s server version v1.7.7) in the case of a failed image pull. `ErrImagePull` is quite brief and will most likely be missed by a Prom scrape.

Ditto for `CrashLoopBackOff`. Crash-looping pods have a _current_ state of `terminated` very briefly and then go into `waiting` with a reason of `CrashLoopBackOff`.

More broadly, it's unclear why this service is so restrictive about potential label values. It makes the collectors ignore useful data.

**Comment by brancz** [comment]
@mheggeseth the reasoning is because every unique label combination creates a new time-series. Which inevitably puts higher load on the time-series database when we have unbound number of time-series. This is why we whilelist label names. If you wish to add more possible values I invite you to add them.

**Comment by mheggeseth** [comment]
@brancz you might be able to re-evaluate that guideline given the drastic database performance improvements of Prometheus 2.

**Comment by brancz** [comment]
While the new Prometheus storage is a lot better, the problem is just pushed down the road. More data will always mean more churn. In general kube-state-metrics is already extremely liberal in the amount of metrics it exposes.

**Comment by jtslear** [comment]
Hopefully the above PR addresses some concerns in this issue.  The `Pending` status is stored at the Pod level already.  So I feel it would be repetitive in here.  `ImagePull` and `CrashLoop` back offs I think are valuable.

**Comment by andyxning** [comment]
close via #359
