### ISSUE TITLE
Proposal for supporting different group versions for a single resource.

### ISSUE THREAD

**Issue by andyxning** [kubernetes/kube-state-metrics#357]
This Proposal is used to demonstrating the problem how to support different group version for a single resource.

docs: https://docs.google.com/document/d/1f7Q_FVODNNc5IytBYbLbLLIWSlefuk4d9YYbIsj99Ec/edit#

/cc @brancz 
/ping @zouyee  as you have proposed a similar PR for attempting to support this functionality.

We need to make a conclusion about this in this week and implement it later as this has been delayed for a long time and we definitely need this feature.

**Comment by zouyee** [comment]
https://github.com/kubernetes/kube-state-metrics/issues/265

**Comment by andyxning** [comment]
Ping @brancz @zouyee 

Personally, i am in favor of Typed scheme. It is easy to understand and straightfroward.

**Comment by andyxning** [comment]
Ping @brancz @zouyee 

Personally, i am in favor of Typed scheme. It is easy to understand and straightfroward.

**Comment by brancz** [comment]
Sorry I'm currently swamped with work on Prometheus and can't currently get to this. I trust that you make the right call, and move forward with what you believe makes sense. We can always release a beta and see if it turns out working or not and revert if it doesn't.

**Comment by brancz** [comment]
Personally I think this is not as necessary anymore as objects are not being added/changed/removed as much as in the past anymore so I don't think we should take on the additional complexity this brings with it.
