### ISSUE TITLE
prometheus targets kubernetes-service-endpoints state is Down

### ISSUE THREAD

**Issue by marsty** [kubernetes/kube-state-metrics#358]
Error server returned HTTP status 404 Not Found  why?

**Comment by r0fls** [comment]
What is the path shown from the prometheus targets page? It should be `/metrics`.

Have you tried querying the metrics from another pod in the cluster? `curl <KUBE_STATE_METRICS_SERVICE_NAME>` or `curl <KUBE_STATE_METRICS_SERVICE_NAME>/metrics`

**Comment by andyxning** [comment]
@marsty As @r0fls said above, seems that you config the wrong target endpoint for kube-state-metrics. Please check it first.

**Comment by andyxning** [comment]
Since there are no further useful clues for us to diagnose the problem, close this issue for now. @marsty Feel free to reopen it if you still has some questions.

**Comment by LiliC** [comment]
@sri-05  Its your Prometheus scrape config that is the problem, sounds like kube-state-metrics works correctly.

**Comment by sri-05** [comment]
@LiliC Thanks for the reply.
It seems like a network issue. I will re-configure pod network and keep you posted on the same.
