### ISSUE TITLE
Clarify k8s version compatibility

### ISSUE THREAD

**Issue by vmranh** [kubernetes/kube-state-metrics#363]
I found the [compatibility ](https://github.com/kubernetes/kube-state-metrics#compatibility-matrix)matrix very useful but a bit confusing, I read it as 1.2/master is compatible with k8s 1.7.

When I applied the configurations (from master) I got the following error: 
`"no kind "ClusterRoleBinding" is registered for version "rbac.authorization.k8s.io/v1"`

I realize that the container itself is backward compatible, but the rest of the k8s deployment objects (ClusterRoleBinding, ClusterRole, Deployment, RoleBinding) were not compatible with 1.7, maybe its worth adding a note about it.

Thanks !

**Comment by brancz** [comment]
Would you like to create a PR to add this note? :slightly_smiling_face:

**Comment by vmranh** [comment]
yes, I will prepare one.

**Comment by brancz** [comment]
#364 is merged, so closing here. Thanks a lot for adding this!
