### ISSUE TITLE
kube_job_status_failed metric not fluctuating

### ISSUE THREAD

**Issue by noah-mercado** [kubernetes/kube-state-metrics#367]
The documentation for kube_job_status_failed claims that this metric is a gauge and therefore should fluctuate. When using this metric and summing by the job name to get the number of times each job has failed, the numbers are consistent and there is no fluctuation for weeks on end which is hard to believe.

Here's the query I'm using in grafana to display the each job that has failed:

sum(kube_job_status_failed) by (exported_job) > 0

Is this an issue with the documentation? Or am I calculating the metric wrong?  Thanks!

**Comment by brancz** [comment]
The implementation seems correct at first glance:

https://github.com/kubernetes/kube-state-metrics/blob/507a2f8ce67c35d01a13504b4cc60a171d0cf8ba/collectors/job.go#L208:31

It's really just the `failed` field of the Job's status. Could you try to have Jobs fail artificially, and try to see what it says when you do `kubectl get job <job-name> -oyaml` and then check the metric?

**Comment by andyxning** [comment]
@noah-mercado 

What is the output of `sum(kube_job_status_failed) by (exported_job) > 0` query. Does it always be zero or any constant. A graph is preferred if it is available. 

And btw do you indeed have some jobs running for weeks?

**Comment by povilasv** [comment]
I'm seeing a similiar issue with Kubernetes 1.14.6:

The status of the job is:

```
status:
  completionTime: "2019-08-27T05:31:06Z"
  conditions:
  - lastProbeTime: "2019-08-27T05:31:06Z"
    lastTransitionTime: "2019-08-27T05:31:06Z"
    status: "True"
    type: Complete
  failed: 3
  startTime: "2019-08-27T05:29:00Z"
  succeeded: 1
```

**Comment by povilasv** [comment]
hmm I think I might be wrong here, so the metric `kube_job_status_failed` is actually correct, the job failed 3x times, so I think I should be using `kube_job_failed`, which will show me the current status of job. 

https://github.com/kubernetes/kube-state-metrics/blob/507a2f8ce67c35d01a13504b4cc60a171d0cf8ba/collectors/job.go#L224

**Comment by povilasv** [comment]
I think we can close this issue.
