### ISSUE TITLE
Add optional GET arguments to /metrics

### ISSUE THREAD

**Issue by dohnto** [kubernetes/kube-state-metrics#368]
# Current situation

Our company have on-premise kubernetes cluster for several teams. One team use several namespaces. We want to run single kube-state-metrics as a deployment inside kubernetes and we want to allow teams to run their own prometheus and scrape kube-state-metrics deployment.

However, every team has to have their special relabel configuration and drop other namespaces otherwise dataseries count would rise significantly. Also most of the time series are transferred through networked and they are just dropped by prometheus.

# Proposed solution

Would it be possible to add optional GET arguments to metricsPath? I could imagine something like:
```
/metrics?namespace=team1-staging&namespace=team1-production
/metrics?collectors=deployments&namespace=team1-staging
```

Although I am not sure whether this is compatible with gRPC. I am willing to do the implementation but first I would like to discuss it with maintainers.

Thank you for any ideas or tips how to solve our issue.

**Comment by brancz** [comment]
Generally I like all that you're proposing and I think it would make sense to add these filters by parameters. However you are inevitably going to run into a scalability problem, where the sheer amount of objects is too much for a single kube-state-metrics deployment, at which point you have to deploy a kube-state-metrics instance per namespace and or collector anyways, which is already possible today. The latter also makes a lot of sense from a security/access control view, as kube-state-metrics then really only has access to what it must view, instead of what it could view.

**Comment by dohnto** [comment]
@brancz thank you for quick response.

Ok I understand. It is probable, that we will end up running several kube-state-metrics instances (per namespace). But it would be awesome, if we could run kube-state-metrics per team (but one team owns few namespaces).

I appreciate that you implemented `--namespace` argument but it would be awesome, if this argument could be passed multiple times. Would you accept such extension? Or another way how to express that we want are interested not in single but multiple namespaces.

Or is it possible to achieve this using Roles, Rolebindings and ServiceAccounts? To limit the scope of what kube-state-metrics is able to see?

**Comment by dohnto** [comment]
For a consistency, wouldn't it be better to add extra arguments 
```--namespaces=test,stage``` (note the plural, same as `--collectors`) and after deprecate the ```--namespace```?

Or can anyone help me with the interface the upstream prefers?

**Comment by brancz** [comment]
for compatibility reasons, I'd prefer not to change the name of the flag, but extend the usage to accept lists as you suggested

**Comment by andyxning** [comment]
@brancz @dohnto 
> However, every team has to have their special relabel configuration and drop other namespaces otherwise dataseries count would rise significantly. Also most of the time series are transferred through networked and they are just dropped by prometheus.

IIUC, the relabel config for Prometheus happens before scrape. So, it should have no network overhead. As the useless metrics have been dropped from the target. Am i right? @brancz 

> As I said, even the first thing you proposed is something I think is useful (although rather complicated to implement I think with the standard go client).

Seems Prometheus client and server do not support query parameter?

**Comment by brancz** [comment]
> IIUC, the relabel config for Prometheus happens before scrape. So, it should have no network overhead. As the useless metrics have been dropped from the target. Am i right? @brancz

I believe what @dohnto was talking about was "metric relabeling" which does happen at scrape time, not discovery.

> Seems Prometheus client and server do not support query parameter?

The prometheus server supports it all, but the golang client is rather spartan on this end.

**Comment by dohnto** [comment]
Please see #395 for my naive solution.
