### ISSUE TITLE
Is there any metrics about configmaps and secrets ?

### ISSUE THREAD

**Issue by younid** [kubernetes/kube-state-metrics#370]
Hello,

I'm looking for the way to monitoring configmaps and secrets changes. Is there any thing like this in kube-state-metrics ? If not do you know if there is a way to have it ?

The goal of this task is to be able to detect any changes made on some critical configmap or secret used by my pods.

Regards

**Comment by andyxning** [comment]
For now there are no metrics about configmaps or secrets in kube-state-metrics. It is easy to add them if they support `list` and `watch` method. I will check it to see if it is ok to add them. :)

**Comment by brancz** [comment]
out of curiosity, what do you expect to get from those metrics?

**Comment by younid** [comment]
Hello Frederic, hello Ning,

Thank you a lot for your help.
Sorry if I don't answer kickly or do correctly every think I must/need to do but I 'm not used to work with github.

To answer your question, I need to create some prometheus rules to detect any changes done on secrets and configmaps. I'm working on a project for which it be not allowed to make changes in those ressources without a maintenance window and a prealable request for that.

Regards,
Younid

**Comment by brancz** [comment]
got it, in that case it sounds like it would make sense

**Comment by andyxning** [comment]
@younid @brancz IIUC, we may need a string like hash value to identify the version of a secret or configmap.
