### ISSUE TITLE
port confusion, document default port documentation in docker image

### ISSUE THREAD

**Issue by juliantaylor** [kubernetes/kube-state-metrics#373]
hi,
the default ports for the metrics in the binary is 80 and 81 while the readme says the default for the main metrics is 8080 in the first paragraph and the telemetry port default is not mentioned at all.
To make it worse the docker image sets one of them by entrypoint to 8080 but leaves the telemetry port at the privileged 81.

This is pretty confusing, the readme should not state that the default is 8080 when this it really is 80 in the binary, the documentation should probably mention that the docker image changes the default and the docker image should probably also change the default of the telemetry port so that it does not default to a privileged port (or not change the default at all).

**Comment by andyxning** [comment]
@juliantaylor Thanks for the catch. 👍  Do you have some time to make a PR to correct this?
