### ISSUE TITLE
kube-state-metrics authentication/authorization

### ISSUE THREAD

**Issue by huskerdhf** [kubernetes/kube-state-metrics#381]
Hello,

Within this add-on server, is there any means of enabling authentication and authorization on the kube-state-metrics interface? Similar to the cAdvisor interface there is a significant amount of sensitive information exposed by kube-state-metrics which in a production environment preferably would not be accessible by just anyone or anything running on the K8s cluster. The main K8s project now provides a means of fully securing the cAdvisor /metrics endpoint and it would seem the same general type of functionality would be useful for this project if it is not already available.

If not is there any plan to add such a capability to kube-state-metrics? And if so is there a planned timeframe when that capability will be available?

Alternatively are there any documented design patterns for adding authentication/authorization to the kube-state-metrics interface outside the project?

Thanks,

DaveF

**Comment by brancz** [comment]
We had initially started implementing this directly into kube-state-metrics, but eventually decided against it, and just use a proxy in front of kube-state-metrics. I actually ended up publishing that proxy as a separate project [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy). At CoreOS we use the kube-rbac-proxy to protect kube-state-metrics in the way you describe. This is our manifest: https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/kube-state-metrics/kube-state-metrics-deployment.yaml

**Comment by huskerdhf** [comment]
@brancz Thanks for the response and confirming what I suspected. I'll investigate using the proxy project you referenced.

Cheers, DaveF
