### ISSUE TITLE
Failed to create client: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

### ISSUE THREAD

**Issue by lyq628** [kubernetes/kube-state-metrics#398]
If no configuration about ca in k8s , just execute command:
1.kubectl create clusterrolebinding kube-state-metrics --clusterrole=cluster-admin --serviceaccount=monitoring:kube-state-metrics
2. kubectl create clusterrolebinding prometheus --clusterrole=cluster-admin --serviceaccount=monitoring:prometheus",

kube-state-metrics fails to start and gives the tips:"Failed to create client: open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory"。So is the token a MUST ?

**Comment by brancz** [comment]
If you want to run kube-state-metrics within your cluster, then yes, it's a must. You can however also run kube-state-metrics as if it was outside a cluster and just provide it a kubeconfig.

**Comment by somedayiamold** [comment]
@brancz how can i provide kubeconfig if it runs within cluster, does kube-state-metrics accept environment variables KUBE_CONFIG?

**Comment by andyxning** [comment]
@somedayiamold Sorry for not make myself clear. You can also pass `--kubeconfig` command line argument to kube-state-metrics if the kubernetes cluster does not have a service account file.

Run `make build && ./kube-state-metrics -h` to see more command line arguments that kube-state-metrics supports.

**Comment by somedayiamold** [comment]
@andyxning yes, that's what I did in the dockerfile
