### ISSUE TITLE
two kube-state-metrics significantly deviate in reports over time

### ISSUE THREAD

**Issue by ikruglov** [kubernetes/kube-state-metrics#402]
Hi all,

I have very strong suspicion that kube-state-metrics never does resync and hence a long-running instance will deviate from the reality quite dramatically. At least this is what we see in production when we run two instances of kube-state-metrics watching same k8s cluster. They will end up showing different data quite soon.

I'll explain the problem using pods collector as an example. Please take the explanation with a graint of salt as I'm not big expert in kubernetes ecosystem.

So, pods collector uses [shared informer](https://github.com/kubernetes/kube-state-metrics/blob/master/collectors/pod.go#L200). The share informed gets created [here](https://github.com/kubernetes/kube-state-metrics/blob/master/collectors/collectors.go#L55).
```
func NewSharedInformerList(client rest.Interface, resource string, namespaces []string, objType runtime.Object) *SharedInformerList {
    sinfs := SharedInformerList{}
    for _, namespace := range namespaces {
        slw := cache.NewListWatchFromClient(client, resource, namespace, fields.Everything())
        sinfs = append(sinfs, cache.NewSharedInformer(slw, objType, resyncPeriod))
    }
    return &sinfs
}
```

One of the parameters which NewSharedInformer() receives is resyncPeriod (it's set to 5 min by default). As far as I understand the kubernetes model, resync period is here to limit potential inconsistency between kubernetes and a client (kube-state-metrics in our case). In other words, kube-state-metrics can deviate from the true state of affairs, but it's guaranteed to catch up within resync period. I'm no a big guru in kubernetes so my wording might not be precise, please excuse me in such case.

The piece of client-go which is responsible for syncing aclient with kube-apiservers is [Reflector](https://godoc.org/k8s.io/client-go/tools/cache#NewReflector). The condition which actually triggers a resync is [here](https://github.com/kubernetes/client-go/blob/master/tools/cache/reflector.go#L285). I'll quote it here:
```
            if r.ShouldResync == nil || r.ShouldResync() {
                glog.V(4).Infof("%s: forcing resync", r.name)
                if err := r.store.Resync(); err != nil {
                    resyncerrc <- err
                    return
                }
            }
```

So, whether reflector performs a resync depends on ShouldResync callback being set and the result of calling it. ShouldResync is populated through a sequence of passes which I don't want to mention here. The call of ShouldResync() also goes through the chain of calls and it ends up being in [shouldResync()](https://github.com/kubernetes/client-go/blob/master/tools/cache/shared_informer.go#L436) of sharedProcessor. I'll also quite the function here:

```
func (p *sharedProcessor) shouldResync() bool {
    p.listenersLock.Lock()
    defer p.listenersLock.Unlock()

    p.syncingListeners = []*processorListener{}

    resyncNeeded := false
    now := p.clock.Now()
    for _, listener := range p.listeners {
        // need to loop through all the listeners to see if they need to resync so we can prepare any
        // listeners that are going to be resyncing.
        if listener.shouldResync(now) {
            resyncNeeded = true
            p.syncingListeners = append(p.syncingListeners, listener)
            listener.determineNextResync(now)
        }
    }
    return resyncNeeded
}
```

So, the function roughly implements following logic: go through every available processorListener and ask whether it needs a resync or not. If any of them needs resyncing then return true. If no one needs or there are no listeners then return false.

The "there are no listeners" is key here. The only place which I found where listeners are populated is [addListener()](https://github.com/kubernetes/client-go/blob/5f85fe426e7aa3c1df401a7ae6c1ba837bd76be9/tools/cache/shared_informer.go#L384) function. This function is only called twice inside [AddEventHandlerWithResyncPeriod()](https://github.com/kubernetes/client-go/blob/5f85fe426e7aa3c1df401a7ae6c1ba837bd76be9/tools/cache/shared_informer.go#L326).

These findings lead us to a simple result: if there is no EventHandler than there will be no resyncs.

And this is indeed what happens in kube-state-metrics. It simply created NewSharedInformer and doesn't add any watchers because of it following the different logic of listing pods directly through a [inf.GetStore().List()](https://github.com/kubernetes/kube-state-metrics/blob/master/collectors/pod.go#L204). I'll quote things here once again:
```
    pinfs := NewSharedInformerList(client, "pods", namespaces, &v1.Pod{})
    podLister := PodLister(func() (pods []v1.Pod, err error) {
        for _, pinf := range *pinfs {
            for _, m := range pinf.GetStore().List() {
                pods = append(pods, *m.(*v1.Pod))
            }
        }
        return pods, nil
    })
```

As an attempt to fix the problem I applied this patch to kube-state-metrics:
```
diff --git a/collectors/collectors.go b/collectors/collectors.go
index 875b218..3a59e93 100644
--- a/collectors/collectors.go
+++ b/collectors/collectors.go
@@ -52,7 +52,9 @@ func NewSharedInformerList(client rest.Interface, resource string, namespaces []
        sinfs := SharedInformerList{}
        for _, namespace := range namespaces {
                slw := cache.NewListWatchFromClient(client, resource, namespace, fields.Everything())
-               sinfs = append(sinfs, cache.NewSharedInformer(slw, objType, resyncPeriod))
+               inf := cache.NewSharedInformer(slw, objType, resyncPeriod)
+               inf.AddEventHandler(cache.ResourceEventHandlerFuncs{AddFunc: func(obj interface{}) {}})
+               sinfs = append(sinfs, inf)
        }
        return &sinfs
 }
```

This was enough to start seeing periodical "forcing resync" in logs when running kube-state-metrics with -v=4.

```
# note that resyncPeriod is set to 5 sec here
$ ./kube-state-metrics --v=4 --kubeconfig=kubeconfig --logtostderr --host=127.0.0.1 --port=80 --telemetry-host=127.0.0.1 --telemetry-port=81 --collectors=pods
I0318 21:38:15.768770   16454 main.go:236] Using all namespace
I0318 21:38:15.773566   16454 main.go:274] Testing communication with server
I0318 21:38:15.814821   16454 main.go:279] Running with Kubernetes cluster version: v1.9. git version: v1.9.3. git tree state: clean. commit: d2835416544f298c919e2ead3be3d0864b52323b. platform: linux/amd64
I0318 21:38:15.814903   16454 main.go:281] Communication with server successful
I0318 21:38:15.815600   16454 pod.go:198] collect pod with v1
I0318 21:38:15.815626   16454 main.go:290] Starting kube-state-metrics self metrics server: 127.0.0.1:18081
I0318 21:38:15.815707   16454 main.go:360] Active collectors: pods
I0318 21:38:15.815714   16454 main.go:315] Starting metrics server: 127.0.0.1:18080
I0318 21:38:15.816033   16454 reflector.go:202] Starting reflector *v1.Pod (5s) from k8s.io/kube-state-metrics/collectors/collectors.go:65
I0318 21:38:15.816086   16454 reflector.go:240] Listing and watching *v1.Pod from k8s.io/kube-state-metrics/collectors/collectors.go:65
I0318 21:38:20.860003   16454 reflector.go:286] k8s.io/kube-state-metrics/collectors/collectors.go:65: forcing resync
I0318 21:38:25.860295   16454 reflector.go:286] k8s.io/kube-state-metrics/collectors/collectors.go:65: forcing resync
I0318 21:38:30.860556   16454 reflector.go:286] k8s.io/kube-state-metrics/collectors/collectors.go:65: forcing resync
I0318 21:38:35.860835   16454 reflector.go:286] k8s.io/kube-state-metrics/collectors/collectors.go:65: forcing resync

```
I have been running patched kube-state-metrics in production for a couple of days and didn't notice any deviation in reported data. So, it seems that the patch works. However, I would like somebody to double check my findings. I'm also not sure that the patch is the best possible solution.

Base on my observation of how kube-state-metrics can be wrong in production, I think this is an important bug to get the fix soon. There might be also logical problems in client-go. At least the need to create a handler for an informer to periodically resync seems questionable for me. But, I'm not a big expert so I'm not going to judge much here.

**Comment by brancz** [comment]
Thanks for the thorough investigation! What you are saying sounds reasonable, let's make sure there is not another way that we're missing, otherwise I'm happy to use your suggestion.

@sttts is there something that we're missing, or should we be applying this quick fix and figure out what to do upstream?

**Comment by ncdc** [comment]
The resync takes all of the items in the reflector's / shared informer's cache and broadcasts all of them to all listeners (event handlers). If all you are doing is listing from the store directly, that store should be getting updated constantly as watch events occur.

My initial thinking is this lack of a resync is not the cause of the deviation, but I could certainly be wrong...

**Comment by ikruglov** [comment]
@ncdc, as far as I understand the ecosystem, the problem is that Kubernetes doesn't guarantee delivery of an event. So, without a resync missing an event means deviation. Resync suppose to bring the cache to up-to-date state recovering the system from deviation.

**Comment by ncdc** [comment]
> Kubernetes doesn't guarantee delivery of an event

Essentially correct. If you are relying solely on the apiserver's watch feature to see adds/updates/deletes, there is no guarantee you'll see every event.

> Resync suppose to bring the cache to up-to-date state recovering the system from deviation

Incorrect. Resync takes the current set of items in the cache and broadcasts them to all listeners, so each listener has a chance to process each item. This handles the "missed watch event" case.

**Comment by ikruglov** [comment]
@ncdc, ok, this is interesting.

> If you are relying solely on the apiserver's watch feature

I'm not sure I understand this. What you mean by "solely"? I assumed that Kubernetes guaranteed delivery mechanism is watch + resync. Apparently, it's not the case. How does a system should reliably get *all* events?

**Comment by ncdc** [comment]
My comment about "solely" is that you can't just do a watch and expect to get all updates for all time going forward.

This is the mechanism the shared informer uses (using pods as an example):

1. List all pods
1. Establish a watch on pods
1. If the watch connection is broken:
    1. Go back to step 1

So the key is to relist on connection failure.

A good example of a use case for resync is if you need to periodically compare some in-cluster state against some external state. So you add an event handler and write your code so that it's level driven, not edge driven. In other words, you have to act on the state of the object you receive in your event handler, and you can't rely on seeing every transition. Every resync period (5 minutes, 1 hour, whatever), your handler re-receives all the items in the cache for processing.

**Comment by ikruglov** [comment]
cool, thanks for the clarification. Now I better understand the system. :-)

But we still have original problem of two kube-state-metrics reporting different data. It's going to be quite hard to keep debugging things as I got restart my instances. So, any deviation is gone just naturally and there have been probably not enough time to expose new deviations.

Any suggestion of what I can do to make debugging simpler?

**Comment by ncdc** [comment]
Can you describe the deviations in more detail? What do you expect to see? What are you seeing?

**Comment by ikruglov** [comment]
ahm.. sorry, managed to get miss last message...

The problem which I saw was following. We have two instances of kube-state-metrics which are identically configured. After some time, they start showing different data. For instance, they could list a different set of pods in various states. When I inspected one of them, it showed a stale list of pods - i.e. kube-state-metrics shows that a pod exists via kube_pod_info entry. But kubectl didn't agree with it. Restarting kube-state-metrics resolved the problem.

Nowadays, after my "wrong" patch, I don't see this behavior. But I'm not sure whether this because the underlying issues are fixed or simply because all of my instances get restarted. Or maybe there is something wrong with my configuration. I'm keeping my eye there and will report as soon I get something. I'm fine with close this issue for now.

**Comment by andyxning** [comment]
@ncdc  IIUC, you mean that force relist is only triggered after a connection failure in normal case. Then, what is the difference between relist and resync? Seems they are the same in functionality.

**Comment by ncdc** [comment]
Relist talks to etcd. Resync does not.

Resync allows your controller to reprocess all items in the cache. This is useful, for example, if you need to reconcile the controller's state against some external system.

**Comment by brancz** [comment]
That makes sense, I don't think the resync is causing any deviations in this case, which doesn't mean there can't be another reason for the deviations. It's difficult to fix, if we can't reproduce, my suggestion is that once you see the deviations again, we'll analyse together what those look like and maybe we will have a clearer picture then, regarding what may be going wrong.

**Comment by andyxning** [comment]
> I don't think the resync is causing any deviations in this case, which doesn't mean there can't be another reason for the deviations.

Agreed.

**Comment by dlespiau** [comment]
I have some suspicion this is the same bug as https://github.com/kubernetes/kube-state-metrics/issues/414, but opened a different issue in case it isn't.

**Comment by ikruglov** [comment]
we have traced this issue to problems in our configuration, in particular to LB layer which didn't propagate connectivity errors to kube-state-metrics if kube-apiserver crash in a hard way.
