### ISSUE TITLE
No metric for pods which are force deleted/stopped

### ISSUE THREAD

**Issue by pvanderlinden** [kubernetes/kube-state-metrics#407]
When you delete a pod, or it get's deleted due to a new version, sometimes containers don't shutdown properly, and just hang. Kubernetes will force kill those when this happens after a grace period.

It would be good to have metrics on this, so it can be addressed, but I can't find anything like that, including `kube_pod_container_status_terminated_reason` which doesn't seem to know this. Is there anything like this, or is this a missing feature?

**Comment by brancz** [comment]
I'm not aware that there is a metric for exactly this. kube-state-metrics exposes state exactly as it is available in the API object, so if this information is available there, then I'm happy to evaluate whether we should add it :slightly_smiling_face:

**Comment by andyxning** [comment]
@pvanderlinden Any fields in API objects can help to determine force deleted/stopped?

**Comment by pvanderlinden** [comment]
I have been looking around, the problem is that it looks like the pod information is not available anymore after it actually has been stopped.

The other way I was thinking about was settings an alert of the status of a pod is in the status "Terminating" for too long, but that status seems to be not recorded by kube-state-metrics. In our case that would work, but if you have pods with different grace periods, this still might be a problem (if you have pods which might take a long time to terminate).

**Comment by andyxning** [comment]
> settings an alert of the status of a pod is in the status "Terminating" for too long,

This could be done by subtract the pod termination start time with current time.

> but if you have pods with different grace periods, this still might be a problem (if you have pods which might take a long time to terminate).

As for this, IIUC, what you said `Terninating` to too long means after the grace period?

**Comment by pvanderlinden** [comment]
kube state metrics doesn't record the termination start time? It looks like pods are going from running to terminated, no steps in between in kube state metrics, the api does have a "terminating" state which kube state metrics seems to ignore. @andyxning 

I also realized it also further complicates things as you then have to decrease the scrape time drastically to be able to pick up on it. Maybe this is possible since the improvements made in prometheus 2.

**Comment by brancz** [comment]
I think a metric may be fundamentally the wrong thing here, force termination is an action, and therefore the only real information we could get out of that is an event. A metric that may be useful (albeit not making a lot of sense to be in kube-state-metrics) to accumulate the number of force terminated pods/containers on each node.

**Comment by pvanderlinden** [comment]
You might be right, but I don't think there is anyway to monitor for these things at the moment. The only way to find out if your pods are behaving is to terminate them yourself and time how long it takes them to stop.

**Comment by brancz** [comment]
If force termination emits an event in Kubernetes, then maybe through an events exporter this type of metric may be possible.

**Comment by andyxning** [comment]
Seems no force termination event is emitted.

**Comment by brancz** [comment]
I don't think this issue belongs in kube-state-metrics, as it's neither in a Kubernetes API object nor is kube-state-metrics the source of this action. This should be exposed by the kubelet.
