### ISSUE TITLE
Cronjob support, docs question

### ISSUE THREAD

**Issue by r0fls** [kubernetes/kube-state-metrics#409]
Is this section of the docs still correct?
>If users want to enable this feature when kubernetes version larger than 1.7, It must be configured, with the following parameter setting for apiserver. --runtime-config=batch/v2alpha1=true

It seems that given https://github.com/kubernetes/kube-state-metrics/commit/20c6b1f78a1174cbd95272bc72183d6f96c64db7

Enabling `batch/v2alpha1` in the api server is no longer needed.

**Comment by brancz** [comment]
Yes, you are correct, would you like to create a PR to fix/remove the statement?
