### ISSUE TITLE
Not recognizing pods in an Unknown state

### ISSUE THREAD

**Issue by spirrello** [kubernetes/kube-state-metrics#410]
Hi,

We had two pods in our cluster go into an unknown state however kube-state-metrics isn't recognizing this.  See below:

Output from curl and kubectl:

kube_pod_status_phase{namespace="kube-system",phase="Unknown",pod="filebeat-ht37s"} 0
kube_pod_status_phase{namespace="kube-system",phase="Unknown",pod="filebeat-j1ppj"} 0

kubectl get pods -n kube-system | grep Unknown
filebeat-ht37s                              1/1       Unknown   3          103d
filebeat-j1ppj                              1/1       Unknown   5          103d

Kube-state-metrics version: 1.2
Docker version: 1.12
K8s version: 1.5.4
OS flavor: Ubuntu 16.04 LTS

**Comment by brancz** [comment]
Can you check what the entire Pod object looks like? As in `kubectl get pod filebeat-ht37s -oyaml` and share that?

**Comment by spirrello** [comment]
Thanks for the quick response.

kubectl get pod filebeat-ht37s -n kube-system -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"DaemonSet","namespace":"kube-system","name":"filebeat","uid":"55088a3e-e5b6-11e7-b1fd-005056b546fd","apiVersion":"extensions","resourceVersion":"10876"}}
  creationTimestamp: 2017-12-20T18:48:13Z
  deletionGracePeriodSeconds: 30
  deletionTimestamp: 2018-03-08T20:08:48Z
  generateName: filebeat-
  labels:
    app: filebeat
  name: filebeat-ht37s
  namespace: kube-system
  resourceVersion: "10500067"
  selfLink: /api/v1/namespaces/kube-system/pods/filebeat-ht37s
  uid: 5509dd42-e5b6-11e7-a067-005056b578a1
spec:
  containers:
  - env:
    - name: LOGSTASH_HOSTS
      value: logserver.acme:5043
    - name: LOG_LEVEL
      value: info
    - name: FILEBEAT_HOST
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    image: apsops/filebeat-kubernetes:v0.4
    imagePullPolicy: IfNotPresent
    name: filebeat
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
    terminationMessagePath: /dev/termination-log
    volumeMounts:
    - mountPath: /var/log/containers
      name: varlog
    - mountPath: /var/log/pods
      name: varlogpods
      readOnly: true
    - mountPath: /opt/liaison/docker/containers
      name: varlibdockercontainers
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-blah
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: at4u-lvkc1n06.acme
  restartPolicy: Always
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  volumes:
  - hostPath:
      path: /var/log/containers
    name: varlog
  - hostPath:
      path: /var/log/pods
    name: varlogpods
  - hostPath:
      path: /opt/liaison/docker/containers
    name: varlibdockercontainers
  - name: ƒ
    secret:
      defaultMode: 420
      secretName: default-token-blah
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2017-12-20T18:48:13Z
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: 2018-01-26T21:36:17Z
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: 2017-12-20T18:49:47Z
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a8e99f573f9e8324f50fc3533ee2132463ac050f461df47687de8d24b4804a58
    image: apsops/filebeat-kubernetes:v0.4
    imageID: docker-pullable://apsops/filebeat-kubernetes@sha256:49e85f0be6ccac014dd9ff814f63a04991cd2c5ed2d4b84befa77152860927dd
    lastState:
      terminated:
        containerID: docker://d1af05e5b60af52ab95490583d00fd2f8a9cbd7d093a2944c34428b4af1c5f58
        exitCode: 0
        finishedAt: 2018-01-26T21:35:26Z
        reason: Completed
        startedAt: 2018-01-26T21:33:01Z
    name: filebeat
    ready: true
    restartCount: 3
    state:
      running:
        startedAt: 2018-01-26T21:36:16Z
  hostIP: 10.153.66.46
  message: Node node06.acme which was running pod filebeat-ht37s is
    unresponsive
  phase: Running
  podIP: 10.23.79.64
  reason: NodeLost
  startTime: 2017-12-20T18:48:13Z

**Comment by brancz** [comment]
The problem is that the way it is displayed by kubectl is not actually the `phase` as defined in the Pod object. We'll have to find out what the kubectl logic is to print "Unknown" and see if we can figure that out from the Pod object.

**Comment by andyxning** [comment]
According to https://github.com/kubernetes/kubernetes/blob/master/pkg/printers/internalversion/printers.go#L597-L601, it seems that when a pod:
* is in a deleted state, i.e., `pod.DeletionTimestamp != nil`
* the node pod is running on is unresponsive, i.e., `pod.Status.Reason == node.NodeUnreachablePodReason`

**Comment by andyxning** [comment]
I have opened a PR #420 to fix this. However, i think kubectl should be updated to respect the new Unknown phase and set the pod phase to Unknown when the criteria are met. We can use #420 to mitigate this. But in the long run, kubectl or pod controller manager should be updated to use the new pod Unknown phase.

**Comment by ikruglov** [comment]
I would like to comment on this issue. Sorry for doing this on a closed issue.

We've also faced a similar issue in our setup. We had the case when the data represented by kube-state-metrics didn't match kubectl's output.

What we found is that kube_pod_status_phase{} metric and what kubectl reports under STATUS column are two different things.

Base on the metrics name and description given to it I conclude that kube_pod_status_phase{} is here to track changes in "Phase" field of a pod object. Please correct me if I'm wrong here.

kubectl logic of STATUS field is implemented in [printPod](https://github.com/kubernetes/kubernetes/blob/d39bfa0d138368bbe72b0eaf434501dcb4ec9908/pkg/printers/internalversion/printers.go#L526) function and includes a quite complicated heuristic. For instance, the function looks inside state of initContainer and "normal" containers. As a result, it can produces statuses like: "ExitCode:%d" or "Init:ExitCode:%d". This status information is never propagated to pod object as far as I understand it. The code which @andyxning pointed out is also inside printPod function.

So, I have a couple of thoughts to share. I have a feeling that the patch introduced in this issue mixes "two worlds." Moreover, it does so partially. Let me ellaborate:
1) If kube_pod_status_phase{} is here to keep track of pod.Status.Phase we should probably keep it be so. So, avoid mixing kubectl logic.
2) Alternatively, if you think that it's fine to have kubectl's login in kube_pod_status_phase{} we, perhaps, should do the full mixing. So, also port all these "ExitCode:%d" states.

My personal opinion lies in the third option (this is what I implemented internally with intent to propose upstream):
3) implement another metric which fully mimics kubectl's STATUS field behaivour:
```
    descPodStatus = prometheus.NewDesc(
        "kube_pod_status",
        "The pods current status as kubectl would report it.",
        []string{"namespace", "pod", "status"}, nil,
    )
```
The implementation is the almost one-to-one copy from podPrint function. Gladly, the function is structured in a way that makes curving out logic be a non-challenging task.

But, of course, it comes at the cost of extra maintenance.

What do you guys think?

P.S. Happy to open a separate issue.

**Comment by andyxning** [comment]
> Base on the metrics name and description given to it I conclude that kube_pod_status_phase{} is here to track changes in "Phase" field of a pod object. 

Yes. This is the truth.

According to the name of `kube_pod_status_phase`, it is just the reflection of pod status phase. We should not change this.

I am wondering why you need status representation like `ExitCode:%d`. 

Even we finally choose the third way to add a new metric, copy and paste the logic from kubectl to kube-state-metrics should not be so difficult(just imagine like this :) ). But it will be difficult to maintain it to keep up with kubectl. A bettter way is to make the logic in kubectl pkg referencable and reference it in kube-state-metrics.

**Comment by andyxning** [comment]
@ikruglov

**Comment by ikruglov** [comment]
> According to the name of kube_pod_status_phase, it is just the reflection of pod status phase. We should not change this.

@andyxning, what do you mean? Do you think we should revert https://github.com/kubernetes/kube-state-metrics/pull/420/commits/5885f6d41451f974f7c5f32fcee8b3fed84e4fbf?

> I am wondering why you need status representation like ExitCode:%d.

I don't particularly need ExitCode:%d. But what I found confusing is that none of the metrics provided by kube-state-metrics reflect pod's status as kubectl would report it. Initially, when I started working with kube-state-metrics, I thought that this is kube_pod_status_phase{} but later realized that this is a not correct assumption. I'm wondering if I'm alone with this feeling?

> Even we finally choose the third way to add a new metric, copy and paste the logic from kubectl to kube-state-metrics should not be so difficult(just imagine like this :) ). But it will be difficult to maintain it to keep up with kubectl. A bettter way is to make the logic in kubectl pkg referencable and reference it in kube-state-metrics.

I agree that converting private printPod() into something reusable in kube-state-metrics would be a more sustainable approach.

**Comment by andyxning** [comment]
No. What i mean is that `kube_pod_status_phase` is just a reflection of pod status phase instead of the reflection of kubectl output. We have state this in the [README.md](https://github.com/kubernetes/kube-state-metrics#overview) second paragraph.

**Comment by andyxning** [comment]
@ikruglov

**Comment by ikruglov** [comment]
ok, this makes sense. I mean this paragraph:

> That kube-state-metrics is about generating metrics from Kubernetes API objects without modification. This ensures, that features provided by kube-state-metrics have the same grade of stability as the Kubernetes API objects themselves. In turn this means, that kube-state-metrics in certain situation may not show the exact same values as kubectl, as kubectl applies certain heuristics to display comprehensible messages. kube-state-metrics exposes raw data unmodified from the Kubernetes API, this way users has all the data they require and perform heuristics as they see fit.

Just one question. I don't understand how https://github.com/kubernetes/kube-state-metrics/commit/5885f6d41451f974f7c5f32fcee8b3fed84e4fbf fits there. @andyxning, @brancz  can you please clarify? I have an impression that it does quite the opposite. The commit embeds kubectl's logic into kube-state-metrics.

**Comment by ikruglov** [comment]
Overall, would you guys be willing to accept a pull request with proposed metric?
```
    descPodStatus = prometheus.NewDesc(
        "kube_pod_status",
        "The pods current status as kubectl would report it.",
        []string{"namespace", "pod", "status"}, nil,
    )
```
