### ISSUE TITLE
kube-state-metrics keeps failed pods around for kube_pod_* metrics

### ISSUE THREAD

**Issue by dlespiau** [kubernetes/kube-state-metrics#414]
Some `kube_pod_*` metrics exist for Failed pods:
```
kube_pod_info
kube_pod_owner
kube_pod_labels
kube_pod_created
kube_pod_start_time
```

`kube_status_phase` shows that kube-state-metrics is populating this group of metrics with information about the failed (non running) pods:
![screenshot from 2018-04-04 13-35-16](https://user-images.githubusercontent.com/7986/38307913-46b05688-380d-11e8-93d2-a62c434891ee.png)

`kubectl` is indeed confirming there's only one pod running (and so are the `kube_pod_container_*` metrics).

I would expect the metrics above to only show `Pending|Running` pods, maybe `Unknown` but I'm not sure when the last value is set and seems like it could be a transient state more than anything else.

**Comment by dlespiau** [comment]
Hi Andy. That makes sense, but your "As stated many times in other places" makes me think that's not what people would expect the default behaviour to be, ie. by default report only running pods and join with `kube_status_phase` for error conditions. That said, that'd be a "API" breaking change, so that certainly seems like a deal breaker.

Maybe having it somewhere at a prominent place in the docs would alleviate the problem of an unexpected behaviour, it seems like a big trap people fall into.

**Comment by andyxning** [comment]
@dlespiau IMHO, it should be a common sense that metrics like `kube_pod_info` should contain all the object of that type. So, i do not know where we should add this statement. WDYT @brancz

**Comment by brancz** [comment]
I think it would be fair to add a note high in then readme calling out that kube-state-metrics is about representing the state of the Kubernetes API as metrics as opposed to “what kubectl shows”.

**Comment by andyxning** [comment]
@brancz Will you help to add this tip?
