### ISSUE TITLE
kms 1.3.0 fails to parse certificate due to Go version

### ISSUE THREAD

**Issue by dannyk81** [kubernetes/kube-state-metrics#416]
Similar to https://github.com/prometheus/prometheus/issues/3983

For certificates with non-fqdn values in dnsName fields, applications built with certain Go versions (1.9.<something> -> 1.10) will fail to communicate with the apiserver.

```
F0406 16:58:08.867531       1 main.go:245] Failed to create client: ERROR communicating with apiserver: Get https://10.82.16.1:443/version: tls: failed to parse certificate from server: x509: cannot parse dnsName "K8s foo bar"
```

Since "K8s foo bar" is not an fqdn, tls can't parse it won't allow to establish a connection.

This issue was fixed/mitigated in Go 1.10.1
https://groups.google.com/forum/m/#!msg/golang-announce/IkPkOF8JqLs/TFBbWHJYAwAJ

**Comment by andyxning** [comment]
@dannyk81 Have you ever try to compile kube-state-metrics with go 1.10.1 and test it against your Kubernetes cluster? If that helps to resolve the problem, we definitely need to move the go version for building kube-state-metrics to 1.10.1 and maybe re-push it to the quay.io and gcr.io registry.

**Comment by dannyk81** [comment]
@andyxning indeed, I've compiled it with Go 1.10.1 and it works perfectly with the same k8s cluster.

Sorry for not updating earlier.

**Comment by andyxning** [comment]
@dannyk81 Thanks for the feedback. I have prepared a PR https://github.com/kubernetes/kube-state-metrics/pull/421 to help check the go version when `make build`. Hope this can help us avoid problems related with go version.

**Comment by andyxning** [comment]
I have test that `docker pull quay.io/coreos/kube-state-metrics:v1.3.1` is working. @dannyk81 Can you please give it a try and send some feedback. :)

Once it is ok and we should close this issue.

**Comment by dannyk81** [comment]
Thanks @andyxning! I'm deploying it right now, will provide feedback shortly.

**Comment by dannyk81** [comment]
@andyxning v.1.3.1 works great, thanks a lot!

You can close this issue.
