### ISSUE TITLE
Job success and fail metrics don't appear if kube-state-metrics was offline

### ISSUE THREAD

**Issue by ryanmcnamara** [kubernetes/kube-state-metrics#431]
If a k8s job is created + succeeds or fails while kube-state-metrics is offline, kube-state-metrics will not increment eith the `kubernetes_state.job.succeeded` or the `kubernetes_state.job.failed` metric, even after kube-state-metrics comes back online. The jobs still exist as "completed" in k8s.

Additionally, the same thing happens if a job is created and completes very quickly (suppose it is created and completed 10s later), under certain circumstances. I believe this is related to kube-state-metrics (default) 20s poll

**Comment by andyxning** [comment]
What kube-state-metrics does is that it will query kubernetes resource status and spec and convert some key field into a metric. 

> the same thing happens if a job is created and completes very quickly (suppose it is created and completed 10s later), under certain circumstances. I believe this is related to kube-state-metrics (default) 20s poll

Yes. it is related with the 20s pull interval. Maybe some status change happens during the pulling interval. It will not be reflected by kube-state-metrics. But, some final status such as job failed or job complete will be collected and corresponding metric's value will be altered. 

> If a k8s job is created + succeeds or fails while kube-state-metrics is offline, kube-state-metrics will not increment eith the kubernetes_state.job.succeeded or the kubernetes_state.job.failed metric, even after kube-state-metrics comes back online. The jobs still exist as "completed" in k8s.

This may be when a job is succeeds or fails, the `Succeeded` or `Failed` status fields will be be setted and instead the job complete condition will be setted.

**Comment by andyxning** [comment]
Close this as this is at some point the desired result. @ryanmcnamara Please feel free to reopen it if you still have some questions. :)
