### ISSUE TITLE
Release 0.3.0 is not pushed up into the container registry

### ISSUE THREAD

**Issue by lymichaels** [kubernetes/kube-state-metrics#44]
It is currently not there.

> 
docker pull gcr.io/google_containers/kube-state-metrics:v0.3.0
Pulling repository gcr.io/google_containers/kube-state-metrics
Tag v0.3.0 not found in repository gcr.io/google_containers/kube-state-metrics

**Comment by brancz** [comment]
Sorry about not mentioning it, we have triggered the image to be pushed, but it hasn't happened yet, sorry about that!

**Comment by brancz** [comment]
Just as a side note, this is currently a manual process and we have triggered someone at google to do this for us. 🙂 The image should be arriving within the next few days hopefully.

**Comment by brancz** [comment]
Image is now available 🙂 

```
$ docker pull gcr.io/google_containers/kube-state-metrics:v0.3.0
v0.3.0: Pulling from google_containers/kube-state-metrics

4499908d67e2: Pull complete 
a3ed95caeb02: Pull complete 
Digest: sha256:5b933aa0556f4410b3aeeeabfdbb1dd0769eaad9d4c31a2e0a906acf805493bd
Status: Downloaded newer image for gcr.io/google_containers/kube-state-metrics:v0.3.0
```
