### ISSUE TITLE
pod resource metrics should account for pod conditions

### ISSUE THREAD

**Issue by andrewsykim** [kubernetes/kube-state-metrics#440]
I have a cluster where kube-state-metrics reports that the total requested memory on a node is greater than the allocatable memory of the node. 
```
sum(kube_pod_container_resource_requests_memory_bytes{node="node-name"}) >
sum(kube_node_status_capacity_memory_bytes{node="node-name"})
```

From a quick glance at the code it seems like kube-state-metrics collects the requested memory of a pod regardless of its condition (running, completed, evicted). So in the event a kubernetes job that requests a lot of resources leaves pods in the `Completed` state, the memory used by those pods are included in `kube_pod_container_resource_requests_memory_bytes{node="node-name"}` until Kubernetes decides to delete the pod resource. 

I think the correct behaviour is to either only collect pods that are running or expose the pod conditions as labels. Happy to help put in the work to get this fixed once we agree on what is the best step forward.

**Comment by brancz** [comment]
As stated in the readme, kube-state-metrics is about reflecting exactly the data presented by the Kubernetes API:

> That kube-state-metrics is about generating metrics from Kubernetes API objects without modification. This ensures, that features provided by kube-state-metrics have the same grade of stability as the Kubernetes API objects themselves. In turn this means, that kube-state-metrics in certain situation may not show the exact same values as kubectl, as kubectl applies certain heuristics to display comprehensible messages. kube-state-metrics exposes raw data unmodified from the Kubernetes API, this way users has all the data they require and perform heuristics as they see fit.

In your case you just need to make sure to select pods in running state, you can do so by joining the metric that exposes the state onto the one exposing memory/cpu request.

**Comment by andrewsykim** [comment]
Thanks for the quick response @brancz! I took your advice and was able to get a join query, here it is for anyone else would might need it

```
kube_pod_container_resource_requests_cpu_cores * on(pod) group_left kube_pod_status_phase{phase="Running"}
```

if you wanted to get the sum of all `Running` pods and compare what the total % used in your cluster is you can do 
```
sum(kube_pod_container_resource_requests_memory_bytes * on(pod) group_left kube_pod_status_phase{phase="Running"}) / sum(kube_node_status_allocatable_memory_bytes) * 100) 
```
