### ISSUE TITLE
Is v1.3.1 officially released?

### ISSUE THREAD

**Issue by unterstein** [kubernetes/kube-state-metrics#443]
Hey 👋 

I am fairly enjoying this image released on `https://quay.io/repository/coreos/kube-state-metrics?tag=latest&tab=tags`, thank you very much! I wondered if version 1.3.1 is officially released, because it is not tagged as `latest` in the image repo and not declared as latest version in the `latest version` section of the readme. If it is officially released, would it be possible to also tag the v1.3.1 as latest? This would be awesome!

Thanks :)

**Comment by mxinden** [comment]
As https://github.com/kubernetes/kube-state-metrics/pull/429 is merged, it seems like we have not properly done all the after-work. @brancz what do you think?

> and not declared as latest version in the latest version section of the readme.

@unterstein would you mind creating a PR for this?

**Comment by unterstein** [comment]
Sure ♥️ 

I mean obviously I can change this in the `README.md`, but I might need a minute for the Makefile adaption (if I'm correct that you do the magic there).

**Comment by unterstein** [comment]
Thank you for updating the PR @mxinden !

**Comment by brancz** [comment]
Pushed the latest tag, sorry about that. Some additional automation for version bumps would be lovely :slightly_smiling_face: .

**Comment by andyxning** [comment]
@unterstein @mxinden 
> I wondered if version 1.3.1 is officially released

The answer is yes. The v1.3.1 is the newest official release.

**Comment by unterstein** [comment]
Should the currently build and published version should be automatically tagged as latest? What about bugfix releases for older versions?

**Comment by unterstein** [comment]
Thank you very much for your help! :) Closing this now.

**Comment by glasser** [comment]
Should you also update the tag in kubernetes/kube-state-metrics-deployment.yaml to v1.3.1, and merge into master so that CHANGELOG mentions 1.3.1 on master?

**Comment by andyxning** [comment]
@glasser Thanks for pointing this out.

**Comment by andyxning** [comment]
@brancz Once kubeCon ending and you have some time please take a look at:
> merge into master so that CHANGELOG mentions 1.3.1 on master?

**Comment by andyxning** [comment]
@brancz Please take a look at this
> Should you also update the tag in kubernetes/kube-state-metrics-deployment.yaml to v1.3.1, and merge into master so that CHANGELOG mentions 1.3.1 on master?
