### ISSUE TITLE
Differences between metrics-server repo and kube-state-metrics repo

### ISSUE THREAD

**Issue by Renol7** [kubernetes/kube-state-metrics#450]
I know that this is not a bug neither a request but I don't find a forum where I can ask this question,

Maybe it's a stupid question but... what is the differences between this repo and kubernetes/kube-state-metrics (https://github.com/kubernetes/kube-state-metrics/) repo?

**Comment by andyxning** [comment]
The relationship between metrics-server and kube-state-metrics is almost the same as the relationship between Heapster and kube-state-metrics as [stated in the readme](https://github.com/kubernetes/kube-state-metrics#kube-state-metrics-vs-heapster).

Also, there is a PR to deprecate Heapster in favor of metrics-server/metrics-api pipeline for Kubernetes in https://github.com/kubernetes/heapster/pull/2022

**Comment by Renol7** [comment]
Nice to read you!
I was confused because kube-state-metrics name is similar to metrics-server,
Also, the metrics functionality look similar from my side... haha

The link https://github.com/kubernetes/heapster/pull/2022 helped me understand this,
Thank you very much!
