### ISSUE TITLE
NodeLost can't be Feedback to the  pod kube_pod_container_status 

### ISSUE THREAD

**Issue by piaoyu** [kubernetes/kube-state-metrics#460]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
> /kind feature

**What happened**:
NodeLost can't be Feedback to the  pod kube_pod_container_status 
```
kube-system           log-sender-4b46h                                        1/1       NodeLost                0          83d
```
**What you expected to happen**:
kube_pod_container_status can check the NodeLost status

**How to reproduce it (as minimally and precisely as possible)**:
make  a node  crash

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
#kubectl version
Client Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-dirty-20180502", GitCommit:"2255ac8bd29ca31e1afa51c542709758af9ff98e", GitTreeState:"dirty", BuildDate:"2018-05-02T17:06:36Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.0-dirty-20180502", GitCommit:"2255ac8bd29ca31e1afa51c542709758af9ff98e", GitTreeState:"dirty", BuildDate:"2018-05-02T17:06:36Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Kube-state-metrics image version
kube-state-metrics:v1.3.1

**Comment by andyxning** [comment]
@piaoyu The `NodeLost` is the output from kubectl. What kube-state-metrics does is that:
> That kube-state-metrics is about generating metrics from Kubernetes API objects without modification. This ensures, that features provided by kube-state-metrics have the same grade of stability as the Kubernetes API objects themselves. In turn this means, that kube-state-metrics in certain situation may not show the exact same values as kubectl, as kubectl applies certain heuristics to display comprehensible messages. kube-state-metrics exposes raw data unmodified from the Kubernetes API, this way users has all the data they require and perform heuristics as they see fit.

So, it may be true that kube-state-metrics will not show the condition which are possible from kubectl.

Actually we have port some logic from kubectl to kube-state-metrics to keep it consistent to end users. But that should be quite simple and easy to maintain with the state as kubectl's evolvement.

If you figure out that it is easy to add the support from `NodeLost` to kube-state-metrics. I can help to review PR. :)

**Comment by andyxning** [comment]
BTW, i can not reproduce this by `make a node to NotReady`.

**Comment by piaoyu** [comment]
@andyxning just make a node crash to reproduce this.

**Comment by piaoyu** [comment]
It seems a bug in Kubernetes kubelet. https://github.com/kubeflow/tf-operator/issues/720
