### ISSUE TITLE
Bad certificate 

### ISSUE THREAD

**Issue by aabed** [kubernetes/kube-state-metrics#47]
I get this error when I start the pod
do I need to change my CA?
or there is a workaround 
` Failed to create client: ERROR communicating with apiserver: Get https://10.254.0.1:443/version: x509: certificate is valid for 10.0.1.5, 10.0.0.1, not 10.254.0.1
goroutine 1 [running]:
k8s.io/kube-state-metrics/vendor/github.com/golang/glog.stacks(0x1cc5700, 0xc400000000, 0xcd, 0x1e8)
        src/k8s.io/kube-state-metrics/vendor/github.com/golang/glog/glog.go:766 +0xa5
k8s.io/kube-state-metrics/vendor/github.com/golang/glog.(*loggingT).output(0x1ca5220, 0xc400000003, 0xc42016cc00, 0x1c402df, 0x7, 0x56, 0x0)
        src/k8s.io/kube-state-metrics/vendor/github.com/golang/glog/glog.go:717 +0x337
k8s.io/kube-state-metrics/vendor/github.com/golang/glog.(*loggingT).printf(0x1ca5220, 0x3, 0x1475343, 0x1b, 0xc420645ec8, 0x1, 0x1)
        src/k8s.io/kube-state-metrics/vendor/github.com/golang/glog/glog.go:655 +0x14c
k8s.io/kube-state-metrics/vendor/github.com/golang/glog.Fatalf(0x1475343, 0x1b, 0xc420645ec8, 0x1, 0x1)
        src/k8s.io/kube-state-metrics/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
        src/k8s.io/kube-state-metrics/main.go:86 +0x20b `

**Comment by brancz** [comment]
Can you provide more information on how you are running `kube-state-metrics`?

- Version
- Flags (`in-cluster`, `apiserver`, `kubeconfig`, `port`)
- Kubernetes version

**Comment by brancz** [comment]
Typically if you have a kubeconfig that works kube-state-metrics should also work. Same typically goes for `--in-cluster` without further configuration besides a `port`.

**Comment by aabed** [comment]
@brancz I passed kubeconfig 
--in-cluster=false
--port=8080 
When I use it in-cluster it works

**Comment by brancz** [comment]
That's interesting! It should actually fail when you do `--in-cluster=false` and don't specify an `--apiserver`. When you do `kubectl get nodes`, it works without disabling tls checking etc. and the context for the cluster you want to access it the currently in use context for the kubeconfig?

**Comment by aabed** [comment]
Well, I forgot to mention that, I passed the apiserver
as for the kubeconfig tls is not disabled 
I don't know about the context TBH

**Comment by aabed** [comment]
it gets even weirder 
When I deploy in any other namespace but default or kube-system, I get the same error then it turns into

` Failed to create client: ERROR communicating with apiserver: the server has asked for the client to provide credentials `

**Comment by aabed** [comment]
@brancz I've had a problem with my kube-controller-manager
I have two masters, one of them was holding the lock in the elections, everything works now inside the cluster

I am closing this
