### ISSUE TITLE
kube_node_status_phase not found

### ISSUE THREAD

**Issue by Ewocker** [kubernetes/kube-state-metrics#472]
### kind bug

**What happened**:
Could not find metric kube_node_status_phase in metrics

**What you expected to happen**:
I should be there as part of the node-metrics doc shows.

**How to reproduce it (as minimally and precisely as possible)**:
Go to the prometheus UI and type this in the Expression and you will see lots of thing showing up but not this metric.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9
- Kube-state-metrics image version v1.3.1

**Comment by andyxning** [comment]
Firstly, kube-state-metrics will only emit `kube_node_status_phase` metric when `NODE.Status.Phase` is not empty.

According to the doc comment about [`NodePhase`](https://github.com/kubernetes/api/blob/cfe4a76edf6d17ea00c8b47fabf55edfa5f6c994/core/v1/types.go#L3882-L3886) has been deprecated and will never be populated.
> // NodePhase is the recently observed lifecycle phase of the node.
	// More info: https://kubernetes.io/docs/concepts/nodes/node/#phase
	// The field is never populated, and now is deprecated.

So, it is desired that `kube_node_status_phase` metric is not emitted.

**Comment by Ewocker** [comment]
Thanks for the explanation
