### ISSUE TITLE
Report CPU and Memory requests and limits

### ISSUE THREAD

**Issue by dominikschulz** [kubernetes/kube-state-metrics#48]
We are trying to keep an eye on the overall CPU and Memory requests and limits across the cluster.

`kubectl describe nodes` reports this information per node, but this exporter does not seem to expose it.

Example output:

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted. More info: http://releases.k8s.io/HEAD/docs/user-guide/compute-resources.md)
  CPU Requests	CPU Limits	Memory Requests	Memory Limits
  ------------	----------	---------------	-------------
 1095m (54%)	5480m (274%)	786Mi (10%)	3418Mi (45%)
```

As kubectl is reporting this information it is certainly available to this exporter as well.

Is there any way to get these numbers from the already exported metrics or could someone look into exporting them?

IMHO these "Cluster Usage" metrics are the most important metrics K8s has, and right now it's a little hard (or at least unclear) how to get them.

**Comment by matthiasr** [comment]
Requests are already there (#35,#40). Would you like to submit a PR for limits?

**Comment by dominikschulz** [comment]
Maybe. Need to look into it. Thanks very much for the pointer where to start.
