### ISSUE TITLE
can't see ReplicationController metric

### ISSUE THREAD

**Issue by like-inspur** [kubernetes/kube-state-metrics#480]
I have install kubernetes-state-metric v1.3.1 on kubernetes v1.9.5 cluster, but I can't see some metrics like kube_replicationcontroller_*. I don't know why, so need some help. Thank you! @gnufied @ncdc @willb @rphillips @mml

**Comment by brancz** [comment]
Do you actually have any `ReplicationController` objects? Typically this object it not widely used anymore. Usually the `ReplicaSet` through a `Deployment` is used.

You can check with:

```
kubectl get replicationcontrollers --all-namespaces
```

kube-state-metrics won't show any metrics if there are none of these objects.

**Comment by andyxning** [comment]
Close this since this seems not a kube-state-metrics problem. 

Feel free to reopen it if you still have some problems. :) @like-inspur
