### ISSUE TITLE
Document resource limit configuration

### ISSUE THREAD

**Issue by trondhindenes** [kubernetes/kube-state-metrics#481]
/kind feature

**What happened**:
I notice that kube-state-metrics has its on magic in terms of resource governing thru the "pod-nanny" sidecar. It's unclear to me how to tune resource settings for kube-state-metrics, since I gather it's not done using the regular `resources` attribute on the deployment.

**What you expected to happen**:
I'd like to find clear documentation on how to set up memory/cpu limits using the supplied kubernetes manifests.

**Comment by andyxning** [comment]
@trondhindenes Actually kube-state-metrics have a statement about resource usage as for cluster nodes number. It is [here](https://github.com/kubernetes/kube-state-metrics#resource-recommendation). 

I think it will satisfy your requirement.

**Comment by andyxning** [comment]
> why you configure it using the pod-nanny thingy, and how to change resource limits if needed.

Yep. pod-nanny maybe a little non intuitional. Will add a description about this in a later PR.
