### ISSUE TITLE
Report the setting of service

### ISSUE THREAD

**Issue by WakeupTsai** [kubernetes/kube-state-metrics#486]
Hi, is it possible to report the port setting of k8s service? Such like TargetPort and NodePort.
Really thanks.

**Comment by brancz** [comment]
This is generally possible, but what kind of alerting rule are you intending to use this type of metric for?

**Comment by WakeupTsai** [comment]
Actually, I just want this info to put in my UI (which collects all the data from prometheus). So I think this data could just put in the element label.

**Comment by brancz** [comment]
That won't work as ports are an array so we will need a separate metric for that. I'm fine with adding this, but users need to be aware that this can have scalability implications as it will create a metric per service per port.

**Comment by WakeupTsai** [comment]
In my situation, this metric can help me a lot, can you add this?

**Comment by andyxning** [comment]
> That won't work as ports are an array so we will need a separate metric for that. I'm fine with adding this, but users need to be aware that this can have scalability implications as it will create a metric per service per port.

With the new whitelist and blacklist functionalities in #488 , it should be fine to add this metric to kube-state-metrics and leave the option to end users.
