### ISSUE TITLE
'job' label on Job metrics clashed with Prometheus job label

### ISSUE THREAD

**Issue by tomwilkie** [kubernetes/kube-state-metrics#495]
See https://github.com/kubernetes-monitoring/kubernetes-mixin/pull/46

Perhaps we should consider changing it to `job_name`?

**Comment by brancz** [comment]
`job_name` is going to land in v1.4.0 of kube-state-metrics, so yes it's probably worth waiting as we are about to kick off the release train for that.

**Comment by tomwilkie** [comment]
Excellent, thanks @brancz.

/cc @jdbaldry

**Comment by brancz** [comment]
RE: https://github.com/kubernetes/kube-state-metrics/pull/487
