### ISSUE TITLE
Make metric collection synchronous

### ISSUE THREAD

**Issue by fabxc** [kubernetes/kube-state-metrics#5]
Currently metrics get updated every 10 seconds in the background. This means scrapers record metrics that are off by an unknown duration of 0 to 10 seconds. It also means that the maximum sampling interval is fixed to 10 seconds, which does not generally fit every use case.

When writing Prometheus exporters, the best practice approach is to gather the data synchronously as `/metrics` is accessed to guarantee accurate sample data. Sampling frequency should be defined by the clients.

I'd like this exporter to follow that approach. I understand that the current behavior is an easy way to prevent overloading (esp. with multiple clients). If development on this repo is continued   quota and auth have to be addressed anyway to defend against mis-behaving clients. But we probably shouldn't limit possibilities at the core of the application.

@kubernetes/sig-instrumentation

**Comment by matthiasr** [comment]
At what request rate would overload become an issue?

I can see it become problematic if the exporter has to actually fetch the information from the API. However, with the caches in the Go client, it's possible to keep the whole state of a Kubernetes cluster in local memory (and it doesn't take much of that either). This is automatically up to date through watches. Crunching the numbers from that is a pure CPU issue.

**Comment by fabxc** [comment]
Yes, with the state of things it would fetch all the info from the API. I wasn't aware the client is actually doing that elaborate caching. That's makes things a lot easier.

I have no benchmarks on this but async throttling to 10sec seems to prematurely optimize. With the caching I expect us to come quite far and then we can address the particular concerns through quotas, auth, deduplicating scrapes in a very narrow window etc.
 There's even discussion to have safety guards in the client library (https://github.com/prometheus/client_golang/issues/179).

Way more important seems to be to have scrape parameters, for the exporter as well as clients. We don't want to generate and ingest the entire k8s state in form of metrics if we only care about pod metrics in namespace X. There's an issue in the client library for that (https://github.com/prometheus/client_golang/issues/135) for a standardized approach. Adding a custom one here is also entirely possible.

**Comment by matthiasr** [comment]
> I wasn't aware the client is actually doing that elaborate caching.

There are some extra steps to do that, but it's possible.

**Comment by brancz** [comment]
This should be solved with #6, #8 and #9 being merged, right?

**Comment by fabxc** [comment]
Yes
