### ISSUE TITLE
kube_cronjob_next_schedule_time has time in the past

### ISSUE THREAD

**Issue by balous** [kubernetes/kube-state-metrics#500]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:
I've got a cron job with:
- lastScheduleTime: 2018-07-24T00:00:00Z
- schedule: 0 2 * * *
- creationTimestamp: 2018-06-06T13:55:15Z

For this cronjob, current value of *kube_cronjob_next_schedule_time* metric is 1532397600 (now it is 1532433916, so it is in the past). When formated for my timezone (+0200), the time is 2018-07-24 02:00:00 which is equal to the time the job was run tonight.

**What you expected to happen**:
*kube_cronjob_next_schedule_time* should contain time in the future (i.e. 2018-07-25 02:00:00).

**How to reproduce it (as minimally and precisely as possible)**:
It happens to all my cron jobs so I suppose it is enough to create a cronjob and check *kube_cronjob_next_schedule_time*'s value.

**Anything else we need to know?**:
I've also played with another job, which was created 47 days ago and was suspended since the beginning. I unsuspended it, checked the metric and got 47.75 days in the past.

Also note that the cluster's hosts timezone is set to CEST.

**Environment**:
- Kubernetes version (use `kubectl version`): N/A
- Kube-state-metrics image version 1.3.1, 1.2.0 and 1.1.0 (not tested the earlier versions)

**Comment by balous** [comment]
I poked around a bit and it seems that K8S API is reporting timestamps with UTC timezone designator (the Z at the end).

**Comment by brancz** [comment]
Interesting, so you are saying, that the Kubernetes API is not respecting your timezone settings, and as a result kube-state-metrics is using the same "wrong" timezone. That seems plausible, we should open a new issue on Kubernetes in that case.

**Comment by balous** [comment]
I think that kubernetes API works correctly - I don't need the API to keep the timezone, I just need that the status contains correct timestamp.

I.e. the job is specified to run at 2AM and the server is in CEST. The job have been started at 2AM CEST. Just the API shows 0AM UTC, which represents the same point in time so there is no problem in it.

**Comment by brancz** [comment]
That would mean we need to teach kube-state-metrics the timezone that the cronjob is working off of, which would either mean we need to read it from somewhere (if that information would actually be correct, I don't know) or allow it to be passed as a flag. What do you think?

**Comment by balous** [comment]
Yes, I was thinking about it and got to the same conclusion.

**Comment by balous** [comment]
But this is not all - I am not getting the next schedule time shifted by my timezone offset. The original problem was that I am getting something that looks like last run time.

**Comment by brancz** [comment]
I think that's because next schedule time is based on the UTC time, and kube-state-metrics thinks it's in UTC. So if we make sure kube-state-metrics parses the timestamp as UTC but calculates the next time with the configured timezone then we should get the right unix timestamp (I think .. timezone stuff is confusing, we should write proper unit tests for this).

**Comment by balous** [comment]
So I've tried to set timezone in the container:

- setting TZ environment variable to 'Europe/Prague' has no effect

- however, kube-state-metrics reacts to /etc/timezone file. Having this file with the proper content in the container fixed my problem

So now I think this is definitely timezone problem. If we can set the kube-state-metrics's timezone to the same zone that is used by the cluster, the problem is fixed.

**Comment by brancz** [comment]
I'm not sure setting the timezone to the cluster's timezone is possible unless you do something rather hacky, like mount the hosts `/etc/timezone` file into the container with a hostpath. I still feel like the flag to set the timezone is the best option.

**Comment by balous** [comment]
True, /etc/timezone is not the way. But consider using TZ variable instead of adding a new CLI flag for this - it is pretty standard, many apps (i.e. date) obey it.

**Comment by brancz** [comment]
sure I think we can do both and have the flag default to the value of the TZ environment variable

**Comment by zerda** [comment]
Mapping `/etc/localtime` in host to container worked, but environment `TZ=Asia/Shanghai` not.

We still need a better way (may TZ env support ?) to specify timezone with kube-state-metrics.

**Comment by fzyzcjy** [comment]
Facing the same problem. Is there any updates?

**Comment by fzyzcjy** [comment]
@zerda Hi how did you map the `/etc/localtime`? I tried the following but with errors:

```
...
      containers:
      - name: {{ .Chart.Name }}
        volumeMounts:
        - name: host-etc
          mountPath: /etc/localtime
          subPath: localtime
          readOnly: true
      volumes:
        - name: host-etc
          hostPath:
            path: /etc
```

```
Error: failed to prepare subPath for volumeMount "host-etc" of container "kube-state-metrics"
```
