### ISSUE TITLE
Consider renaming "pod" labels to "pod_name" and "container" labels to "container_name"

### ISSUE THREAD

**Issue by ehashman** [kubernetes/kube-state-metrics#501]
/kind feature

Currently, the `kube_pod_*` metrics use the label "pod" to refer to the name of the pod in the timeseries and "container" to refer to container names within the pod.

Cadvisor, however, uses "pod_name" to refer to the names of pods and "container_name" to refer to names of containers. 

This difference makes it difficult to do joins on KSM metrics and cadvisor metrics, leading me to write queries like this one (which calculates the percentage of real utilization of quota per container -- namespace and podname templated in Grafana):

```
sum(irate(container_cpu_usage_seconds_total{namespace="$namespace",pod_name="$podname",container_name!="POD"}[1m])) by (container_name) / sum(label_join(kube_pod_container_resource_requests_cpu_cores{namespace="$namespace",pod="$podname"}, "container_name", "", "container")) by (container_name)
```

With normalized labels I could just write

```
sum(irate(container_cpu_usage_seconds_total{namespace="$namespace",pod_name="$podname",container_name!="POD"}[1m])) by (container_name) / sum(kube_pod_container_resource_requests_cpu_cores{namespace="$namespace",pod="$podname"}) by (container_name)
```

Is it possible to rename the "pod" labels to match "pod_name" and "container" labels to match "container_name" to normalize between these different data sources? I can certainly write a patch for this.

**Why propose this here rather than telling cadvisor to match KSM?**

Because e.g. "container_name" is a more descriptive label name than using "container" to refer to the name of a container :)

**Environment**:
- Kubernetes version (use `kubectl version`):  1.8.7-21 with internal patches 
- Kube-state-metrics image version: 1.2.0

**Comment by brancz** [comment]
If anything we should rename the cAdvisor labels to `pod` and `container` as it currently violates the [Kubernetes instrumentation guidelines](https://github.com/kubernetes/community/blob/master/contributors/devel/instrumentation.md). Furthermore Kubernetes does not have any stability guarantees regarding metrics, but kube-state-metrics does, meaning that even if we wanted to change these, it would require a major version bump.

**Comment by ehashman** [comment]
I figured this would require a major version bump, that is not a problem.

I'll file an accompanying bug against cadvisor and see what they say. I was unaware of the k8s instrumentation guidelines until now!

**Comment by ehashman** [comment]
It looks like Kubernetes itself (when providing the cAdvisor metrics via its API /api/v1/nodes/$node/proxy/metrics/cadvisor: see [here](https://github.com/kubernetes/kubernetes/blob/097f300a4d8dd8a16a993ef9cdab94c1ef1d36b7/pkg/kubelet/cadvisor/cadvisor_linux.go#L96-L98)) is guilty of the naming inconsistency. So I'll file a bug against Kubernetes directly rather than cAdvisor.

**Comment by brancz** [comment]
Yes sorry I should have mentioned that. Taking the discussion there.

**Comment by abursavich** [comment]
Just throwing it out there that you can use [relabeling](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#relabel_config) to clean up your queries before upstream comes around.

**Comment by ehashman** [comment]
Closing this bug against KSM; this is going to be taken care of as part of the Kubernetes metrics overhaul planned for the 1.3 release on the cAdvisor side.
