### ISSUE TITLE
kube state metrics doesn't report init container pod metrics

### ISSUE THREAD

**Issue by thedebugger** [kubernetes/kube-state-metrics#502]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
Can't see pod container metrics for init containers.

**What you expected to happen**:
Should see pod container metrics for init container like the "main" container

**How to reproduce it (as minimally and precisely as possible)**:
deploy a pod with an init container and check for "kube_pod_container_status_terminated" metric. It doesn't contain init metrics.

**Anything else we need to know?**:
The [code right](https://github.com/kubernetes/kube-state-metrics/blob/master/pkg/collectors/pod.go#L383) now only looks at ContainerStatus which doesn't provide status for InitContainers

**Environment**:
- All Kubernetes version
- All Kube-state-metrics image version

**Comment by brancz** [comment]
There should be metrics on this, however, kube-state-metrics fundamentally only produces metrics for things that can be found in the API object, meaning as long as those don’t have that information we can’t create metrics for it.

**Comment by thedebugger** [comment]
I understand. But what i can tell from source that kube-state-metrics doesn't read the init container status which is available in the API [here](https://github.com/kubernetes/kube-state-metrics/blob/master/vendor/k8s.io/api/core/v1/types.go#L3035). Right? I might be able to create a PR to include it if it makes sense. Thoughts?

**Comment by brancz** [comment]
Yes that is correct, we'd be more than happy about a PR to add these! :slightly_smiling_face:
