### ISSUE TITLE
Show pod uid in the kube_pod_info metrics

### ISSUE THREAD

**Issue by WakeupTsai** [kubernetes/kube-state-metrics#507]
/kind feature

Hi, I'm wondering is it possible to show the pod uid as the label in the kube_pod_info metrics?

Thanks.

**Comment by WakeupTsai** [comment]
Thanks for your reply. Another question, if I want to create a PR for this issue, should I also add the uid of deployment, StatefulSet, service, etc.  Or just adding the uid of pod is fine?

**Comment by brancz** [comment]
If you have no need for the other one's I prefer to add features as they become necessary rather than adding them because they may be useful.
