### ISSUE TITLE
Wrong metric for kube_daemonset_status_number_misscheduled 

### ISSUE THREAD

**Issue by vidhy** [kubernetes/kube-state-metrics#511]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I am able to see the kube_daemonset_status_number_misscheduled metric value is 1 for few of my daemonsets. But when i check the daemonsets and corresponding pods they are running properly on all the worker nodes. 

I guess It is because of the cluster autoscaler. New node gets added and removed dynamically. Probabaly that is not being reflected in the metrics exposed.

Unable to understand what does this metric mean. It would be better if we have explanation on the metrics being exposed.

**What you expected to happen**:
kube_daemonset_status_number_misscheduled  metric value to remain 0

**How to reproduce it (as minimally and precisely as possible)**:
Setup a kube cluster with cluster autoscaler enabled. Have a daemonset. Autoscale the cluster nodes by increasing replicas of any pod. Check the kube_daemonset_status_number_misscheduled  metric.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
1.9.6
- Kube-state-metrics image version
v1.2.0

**Comment by brancz** [comment]
Could you check the `status` of the daemonsets that seem to have the wrong metric?

Just do

```
kubectl -n <namespace> get <daemonset-name> -oyaml
```

For the daemonset you are talking about and share the output here.

**Comment by andyxning** [comment]
@vidhy 
> I am able to see the kube_daemonset_status_number_misscheduled metric value is 1 for few of my daemonsets. But when i check the daemonsets and corresponding pods they are running properly on all the worker nodes.

Does this metric value is level-trigger or edge-trigger. Cluster autoscaler is possible the root reason for resulting this only if the value for `kube_daemonset_status_number_misscheduled` is edge-trigger. Once the cluster has been autoscaled, but the daemonset pods has not been successfully deployed on that node, there maybe a temporary state that some nodes are misscheduled.

**Comment by andyxning** [comment]
This is somewhat related with daemonset instead of kube-state-metrics, IMO.

**Comment by brancz** [comment]
Agreed. kube-state-metrics is correctly exposing the state of the object at a point in time.

**Comment by andyxning** [comment]
/close

Since this seems not a kube-state-metrics bug. @vidhy Feel free to reopen it if you still have some questions.
