### ISSUE TITLE
No Cronjobs metrics were exposed

### ISSUE THREAD

**Issue by vielktus** [kubernetes/kube-state-metrics#512]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

**What happened**:
I installed kube-state-metrics to my Minikube using prometheus-operator. Prometheus can discover this target. I even ssh to MInikube and do a curl to the target link to get the list of metrics. However, the list returned without any Cronjobs metrics.
Do I need to add some args to running kube-state-metrics container to expose Cronjob metrics ? 

**What you expected to happen**:
Prometheus can scrape Cronjob metrics like this https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/cronjob-metrics.md

**How to reproduce it (as minimally and precisely as possible)**:
```helm install -n kube-prometheus helm/kube-prometheus

**Anything else we need to know?**:
The current version I use in Prometheus Operator for kube-state-metrics is v1.2.0. I tried with 1.3.1 but still no luck

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Kube-state-metrics image version: v1.2.0 and 1.3.1

**Comment by vielktus** [comment]
[metrics.txt](https://github.com/kubernetes/kube-state-metrics/files/2289169/metrics.txt)
Im sending the metrics I got from kube-state-metrics.

**Comment by brancz** [comment]
Do you actually have any `CronJob` objects? kube-state-metrics will only expose metrics about the objects that exist.

**Comment by vielktus** [comment]
Oh, sorry, my bad. Yes, I haven't created any jobs on minikube yet. Thanks @brancz , thi can be closed now.
