### ISSUE TITLE
Missing metrics ( kube_job_* & others )

### ISSUE THREAD

**Issue by snegivulcan** [kubernetes/kube-state-metrics#523]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

/kind bug

**What happened**: Several metrics are missing like `kube_job_*` 

**What you expected to happen**: Expect to see all the metrics as documented in the wiki

**How to reproduce it (as minimally and precisely as possible)**: Deployed kube-state-metrics v1.3.1 into GKE ( GCP's managed Kubernetes service ). I used the kubernetes specs as given in this repository, but without Role and Role bindings.

**Anything else we need to know?**:

**Environment**: GKE. 
- Kubernetes version (use `kubectl version`): 1.9.7+
- Kube-state-metrics image version: v1.3.1

**Comment by zouyee** [comment]
At first, using `kubectl get jobs --all-namespaces=true`, if the result is none, I think it is the problem of ksm, otherwise， you will need to check out your configuration of authN ，such as rbac, abac, etc.

**Comment by andyxning** [comment]
/close

Since this seems not a kube-state-metrics bug. @snegivulcan Feel free to reopen it if you still have some questions.
