### ISSUE TITLE
user self define labels from resource labels or fields

### ISSUE THREAD

**Issue by du2016** [kubernetes/kube-state-metrics#527]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

for example ,some times ,user want to hold pod labels such as a label named product,use it to send mail to email group

**What you expected to happen**:

user can self add  fields or labels to metrics labels

**How to reproduce it (as minimally and precisely as possible)**:
for example ,some times ,user want to hold pod labels,such as a label named product,use it  send mail to email group

**Comment by brancz** [comment]
Labels of pods are available as prometheus labels through the kube_pod_labels metric. You can join this information onto any other metric.

**Comment by andyxning** [comment]
Close this since it seems that the requirement has already been addressed. 
@du2016 Feel free to reopen this once you still have some questions.
