### ISSUE TITLE
namespace quota info feature

### ISSUE THREAD

**Issue by Kami-no** [kubernetes/kube-state-metrics#528]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
There is no info about namespace quota

**What you expected to happen**:
Namespace quota info. It makes capacity planing for namespace simple.

**Comment by dohnto** [comment]
What other info, besides [kube_resourcequota_created](https://github.com/kubernetes/kube-state-metrics/blob/579952020a2d57b8960365c9e30af3b1fb71b15a/pkg/collectors/resourcequota.go#L33) and  [kube_resourcequota](https://github.com/kubernetes/kube-state-metrics/blob/579952020a2d57b8960365c9e30af3b1fb71b15a/pkg/collectors/resourcequota.go#L39), do you need?

**Comment by Kami-no** [comment]
You're right, thank you. I've missed it =(
