### ISSUE TITLE
Expose CronJob FailedNeedsStart state in some way

### ISSUE THREAD

**Issue by 2rs2ts** [kubernetes/kube-state-metrics#530]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**: We had a test cluster that was down for a long time due to a power outage, so some CronJobs failed to start and entered a FailedNeedsStart state. It was a while until we noticed this.

**What you expected to happen**: We expected that there would be some metric for this but it seems not. Maybe I am just missing something so please tell me if so.

**How to reproduce it (as minimally and precisely as possible)**: I believe you can repro by creating a cronjob to be run soon, then shutting down your entire control plane until that time passes, but I have not bothered to do that.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.5
- Kube-state-metrics image version: 1.3.1

**Comment by andyxning** [comment]
> some CronJobs failed to start and entered a FailedNeedsStart state

@2rs2ts You seem this with `kubectl`? Which command do you use for getting the `FailedNeedsStart` state.

**Comment by 2rs2ts** [comment]
Looks like you have to miss the start time not once but many times: https://github.com/kubernetes/kubernetes/blob/master/pkg/controller/cronjob/utils.go#L146

@andyxning just create a cronjob that runs every minute or something then take down your control plane overnight 😴

**Comment by andyxning** [comment]
@2rs2ts I have tested this in my local environment. It turns out that when such a situation happens, a `FailedNeedStart` event will be emitted. we can not emit metrics based on events for now.
```
xn@local:~$ kubectl describe cronjob hello
Name:                       hello
Namespace:                  default
Labels:                     <none>
Annotations:                <none>
Schedule:                   */1 * * * *
Concurrency Policy:         Allow
Suspend:                    False
Starting Deadline Seconds:  <unset>
Selector:                   <unset>
Parallelism:                <unset>
Completions:                <unset>
Pod Template:
  Labels:  <none>
  Containers:
   hello:
    Image:  busybox
    Port:   <none>
    Args:
      /bin/sh
      -c
      date; echo Hello from the Kubernetes cluster
    Environment:     <none>
    Mounts:          <none>
  Volumes:           <none>
Last Schedule Time:  Tue, 04 Sep 2018 12:12:00 +0800
Active Jobs:         <none>
Events:
  Type     Reason            Age                From                Message
  ----     ------            ----               ----                -------
  Warning  FailedNeedsStart  20m (x2 over 20m)  cronjob-controller  Cannot determine if job needs to be started: Too many missed start time (> 100). Set or decrease .spec.startingDeadlineSeconds or check clock skew.
```

**Comment by 2rs2ts** [comment]
I understand that you cannot emit metrics based on events but I want this issue to remain open so we don't forget to get around to it someday. I'd like to not have to come back here and comment every 90 days. Is there a way to tell the bot not to mark an issue as stale?

**Comment by brancz** [comment]
There is an initiative on-going, I think it's better to just follow that: https://github.com/kubernetes/kubernetes/issues/69676#issuecomment-442391695

**Comment by ArcticSnowman** [comment]
The underlying issue is here: https://github.com/kubernetes/kubernetes/issues/42649

**Comment by 2rs2ts** [comment]
@ArcticSnowman I'm not sure that FailedNeedsStart is _only_ caused by my repro case, and I think that metrics should still be exposed

**Comment by 2rs2ts** [comment]
/reopen

As my company has ramped up its use of Kubernetes this has become much more pressing. As I had predicted, there are many other reasons why this happens to my users, the most common one is that they wrote a bug. Kubernetes events are not sufficient for us because of the way Datadog (our monitoring solution) handles them. It'd be GREAT for there to be a metric for cronjob status that can tell you if a job is in this state.

**Comment by 2rs2ts** [comment]
I shudder to think of the collective amount of wasted human lifespan on telling these stale bots like fejta to not close our issues.

**Comment by dgrisonnet** [comment]
> At my company we have hundreds of different CronJobs per cluster, and they don't fall neatly into just a few SLA buckets. So we really want to be able to see if a CronJob enters a bad state, rather than waiting for some lack of a good state

The thing is that kube-state-metrics is a project that exposes metrics based on a 1:1 mapping with Kubernetes objects and as of today, the CronJob object doesn't have any notion of state (https://github.com/kubernetes/api/blob/v0.23.6/batch/v1/types.go#L431-L445). There is indeed some state-related information exposed in the events, but that is out of kube-state-metrics scope. As such, I would recommend moving the discussion of adding states/reasons to the Cronjob statuses to the Kubernetes project.

**Comment by bryanasdev000** [comment]
Sorry to bump such old issue, but in my case this helped  a lot https://world.hey.com/nathan/kubernetes-cronjob-freshness-monitoring-with-prometheus-7a32cbb0 .
