### ISSUE TITLE
kube_node_info has wrong instance info

### ISSUE THREAD

**Issue by snegivulcan** [kubernetes/kube-state-metrics#540]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

I run `kube_node_info` in my 3 node k8s cluster and it the returns following results

```
kube_node_info{container_runtime_version="docker://17.3.2",instance="gke-boshupgrade-default-pool-abcdefgh-jj46",job="kubernetes-pods",k8s_app="kube-state-metrics",kernel_version="4.4.111+",kubelet_version="v1.9.7-gke.6",kubeproxy_version="v1.9.7-gke.6",node="gke-boshupgrade-default-pool-abcdefgh-jj46",os_image="Container-Optimized OS from Google",pod_template_hash="3967561728",provider_id="gce://ss-infrastructure/us-west1-a/gke-boshupgrade-default-pool-abcdefgh-6ct4"}       1
kube_node_info{container_runtime_version="docker://17.3.2",instance="gke-boshupgrade-default-pool-abcdefgh-jj46",job="kubernetes-pods",k8s_app="kube-state-metrics",kernel_version="4.4.111+",kubelet_version="v1.9.7-gke.6",kubeproxy_version="v1.9.7-gke.6",node="gke-boshupgrade-default-pool-abcdefgh-jj46",os_image="Container-Optimized OS from Google",pod_template_hash="3967561728",provider_id="gce://ss-infrastructure/us-west1-a/gke-boshupgrade-default-pool-abcdefgh-91dz"}       1
kube_node_info{container_runtime_version="docker://17.3.2",instance="gke-boshupgrade-default-pool-abcdefgh-jj46",job="kubernetes-pods",k8s_app="kube-state-metrics",kernel_version="4.4.111+",kubelet_version="v1.9.7-gke.6",kubeproxy_version="v1.9.7-gke.6",node="gke-boshupgrade-default-pool-abcdefgh-jj46",os_image="Container-Optimized OS from Google",pod_template_hash="3967561728",provider_id="gce://ss-infrastructure/us-west1-a/gke-boshupgrade-default-pool-abcdefgh-jj46"}
```

Note - the node/instance are same for all 3 entries. But i do see provider_id has right node info.

**What you expected to happen**:

I expect the instance to contain the actual correct node value

**How to reproduce it (as minimally and precisely as possible)**:

Running a 3 nodes K8s cluster in using GKS in Google Cloud. Have KubeStateMetrics ( v1.4.0 ) as a Kubernetes deployment.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

```
root@1b0a13227276:/vulcan-platform-tools# kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9+", GitVersion:"v1.9.7-gke.6", GitCommit:"9b635efce81582e1da13b35a7aa539c0ccb32987", GitTreeState:"clean", BuildDate:"2018-08-16T21:33:47Z", GoVersion:"go1.9.3b4", Compiler:"gc", Platform:"linux/amd64"}

```

- Kube-state-metrics image version
v1.4.0

**Comment by mxinden** [comment]
@snegivulcan would you mind posting the output of `kubectl get nodes -oyaml` here?

**Comment by mxinden** [comment]
That is indeed very confusing. @snegivulcan are you able to reproduce this on other clusters as well?

**Comment by snegivulcan** [comment]
@mxinden - Our developer platform allows us to spin up ephemeral clusters and end to end stack on demand. We observe this issue in every single environment.

**Comment by mxinden** [comment]
@snegivulcan Would you mind deploying the following debug container in one of the clusters and posting the logs here?

quay.io/mxinden/kube-state-metrics:v1.4.0-node-debug

It is kube-state-metrics v1.4.0 with the following patch:

```diff
diff --git a/pkg/collectors/node.go b/pkg/collectors/node.go
index d785bdd..f671564 100644
--- a/pkg/collectors/node.go
+++ b/pkg/collectors/node.go
@@ -17,6 +17,8 @@ limitations under the License.
 package collectors
 
 import (
+       "fmt"
+
        "github.com/golang/glog"
        "github.com/prometheus/client_golang/prometheus"
        "golang.org/x/net/context"
@@ -216,6 +218,8 @@ func nodeLabelsDesc(labelKeys []string) *prometheus.Desc {
 }
 
 func (nc *nodeCollector) collectNode(ch chan<- prometheus.Metric, n v1.Node) {
+       fmt.Printf("generating metrics for node %q with provider id %q\n", n.Name, n.Spec.ProviderID)
+
        addGauge := func(desc *prometheus.Desc, v float64, lv ...string) {
                lv = append([]string{n.Name}, lv...)
                ch <- prometheus.MustNewConstMetric(desc, prometheus.GaugeValue, v, lv...)
~
~
~
```

In case you want to build it yourself, here is the branch: https://github.com/mxinden/kube-state-metrics/tree/node-debug.

**Comment by snegivulcan** [comment]
@mxinden - Thank you again for your response. Here are the logs

https://gist.github.com/snegivulcan/d5c4712efc24d3d109813dd2ec642df6

**Comment by mxinden** [comment]
Interesting. Thanks for bearing with us so far!

What I wonder is whether this issue arises in kube-state-metrics or Prometheus.

Could you post the output directly of the kube-state-metrics `/metrics` endpoint here? I guess the output above in your initial issue description is taken by querying Prometheus, right?

Something like:

```bash
kubectl port-forward  kube-state-metrics 8080
curl localhost:8080 | grep kube_node_info
```
