### ISSUE TITLE
Add metrics for PodDisruptionBudget objects

### ISSUE THREAD

**Issue by gregory-lyons** [kubernetes/kube-state-metrics#546]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

**What you expected to happen**:
It would be cool to have metrics for PDB objects for visibility into availability and possible disruptions. I can start working on this if it sounds like a reasonable proposal.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version

**Comment by brancz** [comment]
Yes I think this sounds reasonable. @mxinden how far are we landing a first version of the architectural changes that we planned? I’d prefer to avoid clashes for both of your work.

**Comment by mxinden** [comment]
@brancz https://github.com/kubernetes/kube-state-metrics/pull/534/ architectural changes are mostly done, only missing some test fixes and some performance tests on real clusters.

@gregory-lyons If you don't mind I would like to get https://github.com/kubernetes/kube-state-metrics/pull/534/ in first. In case you already started working on this, I can adapt it once https://github.com/kubernetes/kube-state-metrics/pull/534/ is ready to merge. What do you think?

**Comment by gregory-lyons** [comment]
@mxinden sorry I did not see your response until now and I had already started working on it so I just pushed up #551 

If you want to wait until after #534 is merged, perhaps I can adapt it as needed.

**Comment by mxinden** [comment]
@gregory-lyons https://github.com/kubernetes/kube-state-metrics/pull/534 merged today. Let me know if I can help you adapting to the changes. I a sorry for the inconvenience.
