### ISSUE TITLE
Add metric for access mode for persistent volume claims 

### ISSUE THREAD

**Issue by EmilyM1** [kubernetes/kube-state-metrics#554]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature

/kind feature

**What happened**:

**What you expected to happen**:

It would be helpful to be able to see access modes on persistent volume claims.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version

**Comment by brancz** [comment]
See my answer in #555 :slightly_smiling_face: .

**Comment by chancez** [comment]
AccessMode is a field on the PV in the spec. (see #555). What one supports is providerSpecific, but the value itself is on the resource regardless, otherwise PVC controller couldn't find PVs that fulfill it.
