### ISSUE TITLE
Add metric for persistent volume size

### ISSUE THREAD

**Issue by EmilyM1** [kubernetes/kube-state-metrics#555]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature

 /kind feature

**What happened**:

**What you expected to happen**:
It would be helpful to see the size of persistent volumes.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version

**Comment by brancz** [comment]
PersistentVolume sizes are specific to the provider. The kubelet exposes metrics about PersistentVolumeClaims mounted on the particular node, maybe that's what you are looking for?

**Comment by chancez** [comment]
Capacity is a field that isn't provider specific.

```
        {
            "apiVersion": "v1",
            "kind": "PersistentVolume",
            "metadata": {
                "annotations": {
                    "kubernetes.io/createdby": "gce-pd-dynamic-provisioner",
                    "pv.kubernetes.io/bound-by-controller": "yes",
                    "pv.kubernetes.io/provisioned-by": "kubernetes.io/gce-pd"
                },
                "creationTimestamp": "2018-10-18T00:08:49Z",
                "finalizers": [
                    "kubernetes.io/pv-protection"
                ],
                "labels": {
                    "failure-domain.beta.kubernetes.io/region": "us-west1",
                    "failure-domain.beta.kubernetes.io/zone": "us-west1-a"
                },
                "name": "pvc-fbaf9e97-d269-11e8-b137-42010a8a0005",
                "resourceVersion": "680104",
                "selfLink": "/api/v1/persistentvolumes/pvc-fbaf9e97-d269-11e8-b137-42010a8a0005",
                "uid": "fd43b20d-d269-11e8-b137-42010a8a0005"
            },
            "spec": {
                "accessModes": [
                    "ReadWriteOnce"
                ],
                "capacity": {
                    "storage": "5Gi"
                },
                "claimRef": {
                    "apiVersion": "v1",
                    "kind": "PersistentVolumeClaim",
                    "name": "hdfs-namenode-data-hdfs-namenode-0",
                    "namespace": "metering-ci2-integration-master",
                    "resourceVersion": "680010",
                    "uid": "fbaf9e97-d269-11e8-b137-42010a8a0005"
                },
                "gcePersistentDisk": {
                    "fsType": "ext4",
                    "pdName": "kubernetes-dynamic-pvc-fbaf9e97-d269-11e8-b137-42010a8a0005"
                },
                "persistentVolumeReclaimPolicy": "Delete",
                "storageClassName": "standard"
            },
            "status": {
                "phase": "Bound"
            }
     }
```

**Comment by brancz** [comment]
Sorry you’re absolutely right. I was thinking about the usage of the volume. This seems reasonable.

**Comment by yeplaa** [comment]
Kubernetes exposes metrics regarding the volume size : 

kubelet_volume_stats_available_bytes
kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
kubelet_volume_stats_inodes_used
kubelet_volume_stats_used_bytes

Would it be possible for kube-state-metrics to retrieve them to expose them later?

**Comment by yeplaa** [comment]
Kubernetes exposes metrics regarding the volume size :

kubelet_volume_stats_available_bytes
kubelet_volume_stats_capacity_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
kubelet_volume_stats_inodes_used
kubelet_volume_stats_used_bytes

@brancz Would it be possible for kube-state-metrics to retrieve them to expose them later?

**Comment by brancz** [comment]
kube-state-metrics strictly only converts API objects into metrics, as long as this is not part of a Kubernetes API object, kube-state-metrics will not expose it.

**Comment by chancez** [comment]
@brancz This is exposed by the kube API. PVs have a stoage capacity just like PVCs have a requested capacity. This isn't about used.

**Comment by brancz** [comment]
@chancez I was only referring to @yeplaa's comment. Anything contained in an API object is perfectly valid to be added.

**Comment by chancez** [comment]
@brancz Ah, I see. I agree. I will end up using this above metrics in the future, but that's another story. (I don't think those are collected yet)

**Comment by yeplaa** [comment]
@brancz @chancez To understand, do you intend to integrate these metrics on Kube-state-metrics, or not? Is there an interest for you?

**Comment by brancz** [comment]
Capacity and request are valid as they come directly from API objects, but not any of these:

```
kubelet_volume_stats_available_bytes
kubelet_volume_stats_inodes
kubelet_volume_stats_inodes_free
kubelet_volume_stats_inodes_used
kubelet_volume_stats_used_bytes
```

**Comment by yeplaa** [comment]
OK thank's for your reply @brancz. 
Actually with kube-state-metrics, the kube_persistentvolumeclaim_resource_requests_storage_bytes metric indicates the capacity of storage requested.. To follow then the possibility to have the stats_used or stats_available of PVC.
