### ISSUE TITLE
Kube-State-Metrics doesnt show any kubernetes related metrics 

### ISSUE THREAD

**Issue by hegdedarsh** [kubernetes/kube-state-metrics#556]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
>  bug
> /kind feature

**What happened**:
kube-state-metrics is running fine, and when i open it, i get the metrics, but i dont see any kubernetes related metrics for this, doesnt these get enabled by default, or do we need to configure something.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (1.12.1)
- Kube-state-metrics image version (1.4)

**Comment by brancz** [comment]
Can you be more specific in what metrics you got and what you expected? Did you maybe request the wrong port? (there is 1 port exposing metrics about kube-state-metrics itself, and 1 for kubernetes metrics)
