### ISSUE TITLE
Next release date?

### ISSUE THREAD

**Issue by alapidas** [kubernetes/kube-state-metrics#557]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

Wondering when the next release will be, looking to pick up https://github.com/kubernetes/kube-state-metrics/commit/d171c3e440ab4a492f7fc966fdbf98cb26417783

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version

**Comment by mxinden** [comment]
Most of the performance refactoring is done (https://github.com/kubernetes/kube-state-metrics/pull/534), but I need to re-enable the white-/blacklisting feature and figure out whether to go with gzip by default or not (https://github.com/kubernetes/kube-state-metrics/pull/563). Anyone else have any blockers for an alpha release?

**Comment by brancz** [comment]
Once we're at feature parity again, let's move forward with the pre-release.

**Comment by fedevegili** [comment]
Any update here? Related merges seems merged

**Comment by mxinden** [comment]
@fedevegili we just merged the last optimization. I suggest merging everything into master next and then we can cut the first alpha.
