### ISSUE TITLE
Documentation slightly wrong for GKE cluster-admin-binding

### ISSUE THREAD

**Issue by AjayTripathy** [kubernetes/kube-state-metrics#558]
**What happened**:
Documentation issue only:
kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud info | grep Account | cut -d '[' -f 2 | cut -d ']' -f 1) does not work as expected, due to a gcloud / IAM case sensitivity bug 

**What you expected to happen**:

> Ajays-MBP-2:kube-state-metrics atripathy$ kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=$(gcloud info | grep Account | cut -d '[' -f 2 | cut -d ']' -f 1)
> clusterrolebinding.rbac.authorization.k8s.io/cluster-admin-binding created

This should have sufficed.

Ajays-MBP-2:kube-state-metrics atripathy$ gcloud info | grep Account | cut -d '[' -f 2 | cut -d ']' -f 1
4tripathy@gmail.com

Note that this returns 4tripathy@gmail.com, but my IAM is actually 4Tripathy@gmail.com , and IAMs are case sensitive. Proof in pudding:

> kubectl apply -f kubernetes/
> clusterrolebinding.rbac.authorization.k8s.io/kube-state-metrics created
> deployment.apps/kube-state-metrics created
> rolebinding.rbac.authorization.k8s.io/kube-state-metrics created
> serviceaccount/kube-state-metrics created
> service/kube-state-metrics created
> Error from server (Forbidden): error when creating "kubernetes/kube-state-metrics-cluster-role.yaml": clusterroles.rbac.authorization.k8s.io "kube-state-metrics" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["secrets"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["nodes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["resourcequotas"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["resourcequotas"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["replicationcontrollers"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["replicationcontrollers"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["limitranges"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["limitranges"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["persistentvolumeclaims"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["persistentvolumes"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["persistentvolumes"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["namespaces"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["endpoints"], APIGroups:[""], Verbs:["watch"]} PolicyRule{Resources:["daemonsets"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["daemonsets"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["replicasets"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["replicasets"], APIGroups:["extensions"], Verbs:["watch"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["list"]} PolicyRule{Resources:["statefulsets"], APIGroups:["apps"], Verbs:["watch"]} PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["list"]} PolicyRule{Resources:["cronjobs"], APIGroups:["batch"], Verbs:["watch"]} PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["list"]} PolicyRule{Resources:["jobs"], APIGroups:["batch"], Verbs:["watch"]} PolicyRule{Resources:["horizontalpodautoscalers"], APIGroups:["autoscaling"], Verbs:["list"]} PolicyRule{Resources:["horizontalpodautoscalers"], APIGroups:["autoscaling"], Verbs:["watch"]}] user=&{4Tripathy@gmail.com  [system:authenticated] map[user-assertion.cloud.google.com:[AGKDXmqHQCiuI5hD1t3PsVXh71YaUiVh5vn9/vxeCyHASpcCn874WfC61v4iotOV9G5gMq22wdFzEs0uApoGf1o0Jdzu+mYc8+qZYcevBqeXhVbhNLQa0TFOUcxP5L2LQVsDsgmSoo2A2v9QZadNt7UNPaXgY3dPHuBvIQY0ysPQ53nxMKbkKf5+/A+WFLxNrm0DkqGGJp6XSdVAz4jd0xz5S0EXLUYLOF5JpYE=]]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
> Error from server (Forbidden): error when creating "kubernetes/kube-state-metrics-role.yaml": roles.rbac.authorization.k8s.io "kube-state-metrics-resizer" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["deployments"], ResourceNames:["kube-state-metrics"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["deployments"], ResourceNames:["kube-state-metrics"], APIGroups:["extensions"], Verbs:["update"]}] user=&{4Tripathy@gmail.com  [system:authenticated] map[user-assertion.cloud.google.com:[AGKDXmqHQCiuI5hD1t3PsVXh71YaUiVh5vn9/vxeCyHASpcCn874WfC61v4iotOV9G5gMq22wdFzEs0uApoGf1o0Jdzu+mYc8+qZYcevBqeXhVbhNLQa0TFOUcxP5L2LQVsDsgmSoo2A2v9QZadNt7UNPaXgY3dPHuBvIQY0ysPQ53nxMKbkKf5+/A+WFLxNrm0DkqGGJp6XSdVAz4jd0xz5S0EXLUYLOF5JpYE=]]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews" "selfsubjectrulesreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swagger-2.0.0.pb-v1" "/swagger.json" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
> 

bleh, okay, let's back up. Went to go check my IAM and noted it was 4Tripathy@gmail.com, so I went ahead and gave that a shot

> Ajays-MBP-2:kube-state-metrics atripathy$ kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=4Tripathy@gmail.com
> clusterrolebinding.rbac.authorization.k8s.io/cluster-admin-binding created
>
> Ajays-MBP-2:kube-state-metrics atripathy$ kubectl apply -f kubernetes/
> clusterrolebinding.rbac.authorization.k8s.io/kube-state-metrics unchanged
> clusterrole.rbac.authorization.k8s.io/kube-state-metrics created
> deployment.apps/kube-state-metrics unchanged
> rolebinding.rbac.authorization.k8s.io/kube-state-metrics unchanged
> role.rbac.authorization.k8s.io/kube-state-metrics-resizer created
> serviceaccount/kube-state-metrics unchanged
> service/kube-state-metrics unchanged
> 

It works.

**How to reproduce it (as minimally and precisely as possible)**:
Add a username to GKE with capital letters and repeat the above :)

**Anything else we need to know?**:
Recommend that for GKE users, the documentation has some instructions about checking your IAM instead of the one-liner.

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version

Actually, as the bug lies with IAM/gcloud interaction, likely Kubernetes version is not relevant.

> gcloud --version
> Google Cloud SDK 220.0.0
> app-engine-python 1.9.77
> bq 2.0.34
> cloud-datastore-emulator 2.0.2
> core 2018.10.08
> gcloud 
> gsutil 4.34

**Comment by mxinden** [comment]
@AjayTripathy thanks for the detailed report. I think the maintainers welcome pull-requests for documentation at all times.
