### ISSUE TITLE
How to get the uptime of a particular deployment ? kube_deployment_created seems to be wrong

### ISSUE THREAD

**Issue by Siva10** [kubernetes/kube-state-metrics#561]
/kind bug

**I'm able to see the right `Creation time` of a particular deployment in the k8s dashboard but the time in the metric `kube_deployment_created`seems to be wrong**:

**I expected the metric kube_deployment_created to be same as the creation time seen for a deployment in the k8s dashboard of a cluster**:

**This issue can be reproduced by creating a deployment in a cluster and take note of the creation time and see if its the same as the one appearing for the deployment in a result of the metric kube_deployment_created**:

**I'm trying to know the uptime of a particular deployment, pls point me to any other way of getting it**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.3
- Kube-state-metrics image version: 1.4.0

**Comment by brancz** [comment]
Could you please elaborate what values you got, and which values you expected?

**Comment by Siva10** [comment]
I'm expecting a value in recent past for a deployment ,something like `1529451900000`, but always pointing to a very old time like `1529480715`

**Comment by brancz** [comment]
those numbers are different in their unit, the first one you mentioned is in milliseconds the second one in seconds.

**Comment by Siva10** [comment]
@brancz Thanks for your reply. Sorry about that, I have updated it. I think there is a misunderstanding from my side as i considered the time is in milliseconds instead of seconds. Thanks again for your time!
