### ISSUE TITLE
kube_pod_container_status_terminated_reason not show pod OOMkilled correctly

### ISSUE THREAD

**Issue by chuonglh** [kubernetes/kube-state-metrics#570]
Currently, we have noticed that metric kube_pod_container_status_terminated_reason not show correctly metric when pods is OOMkilled.

<img width="671" alt="screen shot 2018-10-25 at 11 17 45" src="https://user-images.githubusercontent.com/19338075/47475859-b114ad00-d847-11e8-98a3-abeaecdfcc22.png">
<img width="670" alt="screen shot 2018-10-25 at 11 17 51" src="https://user-images.githubusercontent.com/19338075/47475861-b1ad4380-d847-11e8-8b39-3769cce58898.png">
<img width="667" alt="screen shot 2018-10-25 at 11 18 08" src="https://user-images.githubusercontent.com/19338075/47475862-b245da00-d847-11e8-8b46-21b190bf7aea.png">

Pod is killed at 8:00 when reach the mem limit but the status still 0 in pod status

**Comment by jutley** [comment]
This metric reports the reason for why the container is CURRENTLY terminated.

If you scrape a metric, the container terminates, the container starts up, and then you scrape your next data point, you'll have missed the value.

I created a PR to address this (https://github.com/kubernetes/kube-state-metrics/pull/535) which will be in the next release. There will be a new metric that reports the reason for the most recent termination, completely separate from the current container status.

**Comment by chuonglh** [comment]
Thank you very much, I really appreciate it.
