### ISSUE TITLE
Feature: Make  kube-state-metrics a library

### ISSUE THREAD

**Issue by LiliC** [kubernetes/kube-state-metrics#579]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What:**
This is a follow up from https://github.com/kubernetes/kube-state-metrics/pull/575. Some functions were exposed in that PR, but would like to continue the disucsion to make more of a usuable library.

**How:**
```
pkg
├── collector // functions needed to create a collector, this would be used in the builder pkg and externally 
├── internal
│   └── builder // content of the current upstream resource collectors which would consume the collector pkg
├── metrics // what is currently there but also move the utils/helper functions from collectors. Also the metricHandler interface as that would be useful to expose and reuse elsewhere.

```

cc @mxinden @brancz

**Comment by brancz** [comment]
Moving anything that is not lib or main to an internal package sounds like a good idea. I think I would like to hold off on rearranging before the final v1.5.0 release (which we should be cutting rather soon). How does that sound?

**Comment by mxinden** [comment]
With v1.5.0 cut, I am happy to review the refactoring suggested above. Feel free to ping me @LiliC on the PR.

**Comment by mxinden** [comment]
//CC @wanghaoran1988 for the work on https://github.com/wanghaoran1988/openshift-state-metrics
