### ISSUE TITLE
[Question] No real cpu / memory usage report is given?

### ISSUE THREAD

**Issue by aisensiy** [kubernetes/kube-state-metrics#580]
https://github.com/kubernetes/kube-state-metrics/blob/master/Documentation/pod-metrics.md This document shows no `cpu` or `memory` usage for current state? So...I can not collect any real time data for pods or containers?

**Comment by jutley** [comment]
This project strictly pulls data from the Kubernetes API, which doesn't report this type of information.

For realtime data, you'll want to pull the metrics from cAdvisor running on each kubelet. 

Here are the metrics this provides:
https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md

And here is an article that discusses how to use these metrics:
https://blog.freshtracks.io/a-deep-dive-into-kubernetes-metrics-part-3-container-resource-metrics-361c5ee46e66

**Comment by aisensiy** [comment]
Ok, thanks for your reply. I found that `metrics server` support this metrics.
