### ISSUE TITLE
Missing metrics about pods in status failed and the reason

### ISSUE THREAD

**Issue by omerlh** [kubernetes/kube-state-metrics#583]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
I have a few pods in failed state, due to out of CPU, for example:
```
Status:             Failed
Reason:             OutOfcpu
```
I couldn't find a metric I can use to monitor pods in this state. By looking on the code, it seems that this state is not collected - only waiting or terminated.

**What you expected to happen**:
Be able to monitor how many pods are in this state and why (by the reason).

**How to reproduce it (as minimally and precisely as possible)**:
Create a cluster with pods in failed status

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}`
- Kube-state-metrics image version: `quay.io/coreos/kube-state-metrics:v1.4.0z

**Comment by brancz** [comment]
I think we treat the reason as an enum, so we need to specifically list each reason.

**Comment by omerlh** [comment]
But is the status failed is reported? I couldn't find it...

**Comment by brancz** [comment]
What is the `kubectl -n <namespace> get pod <pod-name> -oyaml` output of the pod that failed. Can you share that?

**Comment by omerlh** [comment]
```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/created-by: |
      {"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"<>","name":"<>","uid":"06b71594-e5ba-11e8-a1d6-000d3a383b6d","apiVersion":"extensions","resourceVersion":"3385905"}}
  creationTimestamp: 2018-11-12T12:13:02Z
  labels:
    app: <>
    release: <>
  name: <>-6b856555cf-mzx66
  namespace: <>
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: <>-6b856555cf
    uid: 906d3336-e674-11e8-a6b2-000d3a58db8b
  resourceVersion: "2823988"
  selfLink: /api/v1/namespaces/<>/pods/<>-6b856555cf-mzx66
  uid: 4d7f93c7-e674-11e8-a6b2-000d3a58db8b
spec:
  automountServiceAccountToken: true
  containers:
  - envFrom:
    - configMapRef:
        name: <>
    image: <>
    imagePullPolicy: Always
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: <>
        port: <>
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: <>
    ports:
    - containerPort: <>
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: <>
        port: <>
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 500m
        memory: 600Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: <>-token-jx4wn
      readOnly: true
  dnsPolicy: ClusterFirst
  nodeName: <>
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: <>
  serviceAccountName: <>
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: <>-token-jx4wn
    secret:
      defaultMode: 420
      secretName: <>-token-jx4wn
status:
  message: 'Pod Node didn''t have enough resource: cpu, requested: 100, used: 8000,
    capacity: 8000'
  phase: Failed
  reason: OutOfcpu
  startTime: 2018-11-12T12:23:31Z
```

**Comment by brancz** [comment]
The `kube_pod_status_phase` metric should be set to `1` for the time-series that has the `phase="Failed"` label.

**Comment by omerlh** [comment]
Yep, that give me part of what I was looking for. To add a reason, I guess I need to add something [here](https://github.com/kubernetes/kube-state-metrics/blob/a6c7846dbfa03c5da43da0434830168e56f9f039/pkg/collectors/pod.go#L85), correct? 
Is that something that will be merged?

**Comment by brancz** [comment]
A new reason would be listed here: https://github.com/kubernetes/kube-state-metrics/blob/a6c7846dbfa03c5da43da0434830168e56f9f039/pkg/collectors/pod.go#L40

And yes an extension to that would be accepted :slightly_smiling_face: .

**Comment by omerlh** [comment]
Good to know :) added to my backlog

**Comment by hairyhenderson** [comment]
> I think we treat the reason as an enum, so we need to specifically list each reason.

@brancz is there a reason for an enum instead of just using the `reason` field as-is?

**Comment by brancz** [comment]
That way there would be no timeseries for those states, even though they are possible states. Generally speaking you want to make sure that any timeseries that could be there, should be there for discoverability and aggregations.

**Comment by brancz** [comment]
Phases are captured here: https://github.com/kubernetes/kube-state-metrics/blob/master/pkg/collectors/pod.go#L222-L242

**Comment by omerlh** [comment]
I'm looking for a list of possible failed reason, to create the metric properly.
