### ISSUE TITLE
Collisions between metrics of same name but different namespace

### ISSUE THREAD

**Issue by gregory-lyons** [kubernetes/kube-state-metrics#585]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
As of #534, metric stores use a map keyed by object name:
https://github.com/mxinden/kube-state-metrics/blob/234d788a0d5cfac2b5bf33153afd3b944c39b220/pkg/metrics_store/metrics_store.go#L41

This a poor key choice given that Kubernetes allows you to have objects with the [same name across different namespaces](https://kubernetes.io/docs/concepts/overview/working-with-objects/namespaces/#when-to-use-multiple-namespaces). For any objects with duplicate names, kube-state-metrics now reports metrics for only one of them at a time.

We observed this problem in our cluster, as many of our object names are duplicated across namespaces. We have seen that kube-state-metrics switches which object it is reporting, possibly due to watches expiring/refreshing at staggered times, but only ever one object at once.

**What you expected to happen**:
kube-state-metrics should display metrics for all objects (some combination or hash of name+namespace might be a better key).

**How to reproduce it (as minimally and precisely as possible)**:
Create two objects with same name in different namespaces, and observe that kube-state-metrics only reports one.
```
glyons@mbp-005245 ~ $ kubectl create ns ns1
namespace "ns1" created
glyons@mbp-005245 ~ $ kubectl create ns ns2
namespace "ns2" created
glyons@mbp-005245 ~ $ kubectl create secret generic -n ns1 my-secret
secret "my-secret" created
glyons@mbp-005245 ~ $ kubectl create secret generic -n ns2 my-secret
secret "my-secret" created
glyons@mbp-005245 ~ $ $GOPATH/bin/kube-state-metrics --port=8080 --telemetry-port=8081 --host=localhost --kubeconfig=/Users/glyons/.kube/config &
[1] 70921
glyons@mbp-005245 ~ $ curl -s localhost:8080/metrics | grep my-secret
kube_secret_info{namespace="ns1",secret="my-secret"} 1
kube_secret_type{namespace="ns1",secret="my-secret",type="Opaque"} 1
kube_secret_created{namespace="ns1",secret="my-secret"} 1.542316991e+09
kube_secret_labels{namespace="ns1",secret="my-secret"} 1
kube_secret_metadata_resource_version{namespace="ns1",resource_version="4437",secret="my-secret"} 1
glyons@mbp-005245 ~ $ kubectl get secrets --all-namespaces | grep my-secret
ns1           my-secret                                        Opaque                                0         2m
ns2           my-secret                                        Opaque                                0         2m
```

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10
- Kube-state-metrics image version: Custom-built version with HEAD at https://github.com/kubernetes/kube-state-metrics/commit/a166def64d0b9add5851a95171239bca382215fb

**Comment by gregory-lyons** [comment]
@mxinden @brancz

**Comment by mxinden** [comment]
Thanks for the detailed report and thanks for testing out the current master version.

You are absolutely right. This should have been:

```golang
s.metrics[string(o.GetUID())] = familyStrings
```

I will follow up with a patch.
