### ISSUE TITLE
[feature] calculation of job runtime

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/kube-state-metrics#602]
Currently completion time and start time exist.  Is there any easy way to currently calculate runtime with those 2 metrics?

**Comment by sstarcher** [comment]
Currently it's possible to subtract the 2 values, but that gives you a timeslice that goes forward forever until the next job run of the same name vs a point in time.

**Comment by brancz** [comment]
kube-state-metrics fundamentally doesn't perform aggregations, it can only expose what the kubernetes object has in terms of information and turn exactly that into a metric. Generally that type of metric sounds like it would make sense as a histogram or summary, however the histogram would need to have chosen buckets and the summary would not be aggregatable. I think you're best off writing a new component that listens to job events and aggregates them by their runtime.
