### ISSUE TITLE
Feature request: HA for kube-state-metrics

### ISSUE THREAD

**Issue by whypro** [kubernetes/kube-state-metrics#611]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Currently, kube-state-metrics is running only one instance in the cluster. If node become down, metrics will be disappeared for minutes before a new instance is ready. 

Thanks for @brancz 's suggestion in https://github.com/kubernetes/kube-state-metrics/issues/147#issuecomment-305193110. There are two ways described to make kube-state-metrics HA:

> 1. use a pessimistic approach when querying for kube-state-metrics, and perform for example doing something like:
>     max by(namespace, pod) (kube_pod_container_status_restarts)
> 3. Instead of whitebox monitoring kube-state-metrics put it behind a service and load balance to the instances.

However, if using method 1, we should modify most of our rules. If using method 2, we should configure a blackbox exporter or add additional-scrape-config to prometheus instance. The latter one will increase a little maintenance burden and have some inconsistent problems .

**What you expected to happen**:

So, how about using standby strategy to implement HA. For examples:

1. There are 3 kube-state-metrics replicas
2. ksm 1 ready and acquire leader lease successfully
3. ksm 1 start serve some metrics
4. ksm 2 and ksm 3 become ready and try to acqure lease but failed
5. ksm 2 and ksm 3 enter standby mode, wait for lease and serve empty metrics 
6. ksm 1 down, ksm 2 acquire lease, start serve metrics immediately, ksm 3 keep waiting.
7. a new instance ksm 4 is created and ready. it become standby mode because acquire lease failed.

It would ensure multiple kube-state-metrics instances expose single metric at the same time. And maybe it could be implemented by leaderelection pkg of k8s client-go conveniently.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version

**Comment by brancz** [comment]
I still feel the pessimistic approach is better suited for this, otherwise you have to convince Prometheus to append metrics to the "old leader's" time-series (this is possible, but semantics may become fragile).

@bbrazil what are your thoughts on this?

**Comment by brian-brazil** [comment]
Yeah, any form of load balancing or leader election breaks counters.

I'd personally just run one, and live with the lack of metrics while it's getting rescheduled.

**Comment by brancz** [comment]
Yeah I agree with that. Fwiw that's how we do run it everywhere :slightly_smiling_face: .

**Comment by y-batsianouski** [comment]
Does any one tried that approach https://tunein.engineering/implementing-leader-election-for-kubernetes-pods-2477deef8f13 ?

**Comment by tomaaron** [comment]
@y-batsianouski interesting approach but there seems to be a problem with the latest leader-elector docker image as you can read [here](https://github.com/kubernetes/contrib/issues/2930)

**Comment by y-batsianouski** [comment]
@mxinden Maybe I miss something. But can you please explain the "counter breakage" problem? What is this and what it's effects?

We are running k8s on amazon spot instances and time to time have instances to be reschedulled. But I didn't see any problems except gaps in metrics...

**Comment by mxinden** [comment]
> But can you please explain the "counter breakage" problem?

@y-batsianouski sure!

**General**

Counters are monotonically increasing metrics. They are not allowed to decrease at any time (one exception mentioned further below). Given Prometheus scraping one exporter, replicated twice, load balanced e.g. via round-robin. Say replica one is lagging behind a bit. On the first scrape Promtheus might hit replica one, exposing counter _a_ at value 5, on the second scrape Prometheus might hit replica two, exposing counter _a_ at value 4. Hence the counter decreased, breaking the semantic of its metric type.

Now what happens in the case when a target gets rescheduled and thereby all counters reset (the referenced exception above): This will be detected by Prometheus, treating the reset not as a decrease, but rather interpreting it as a reset to zero right before the first decreasing data point.

In the before mentioned example, given that the metrics exposed by the two replicas do not differ in any labels, this would result in the counter not being equal to 5 or 4, but rather 9. For more details, see [this blog post](https://www.robustperception.io/how-does-a-prometheus-counter-work) by @brian-brazil.

**kube-state-metrics specific**

Given that kube-state-metrics pretty much only exposes gauges, not counters, I guess you could run two replicas behind a load balancer, best configured to be sticky, e.g. via hashing the client ip. As mentioned by @whypro this would of course include the operational overhead of operating the load balancer and the additional complexity and increase of the possible failure scenarios.

// @brian-brazil @brancz please correct me, or add more details in case I am missing something.

**Comment by Dolape1983** [comment]
Hi, this was implemented ? Thanks in advance.

**Comment by tariq1890** [comment]
@Dolape1983 Please read this - https://github.com/kubernetes/kube-state-metrics#horizontal-scaling-sharding

**Comment by ryanisnan** [comment]
This should be reopened as it is still a valid feature request.

**Comment by ryanisnan** [comment]
Could replicas that _know_ they are replicas (via the leader election process) simply query the leader when queried by Prometheus? Wouldn't that fix the bouncing scrape count?

**Comment by y-eight** [comment]
I have tried to implement KSM HA without having the issue of multiple metrics (one for KSM pod and no need for avg function etc.).

This is indeed possible by using a ScapeConfig instead of a ServiceMonitor for KSM cluster metrics.

Example:
```YAML
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: kube-state-metrics-cluster-metrics
  namespace: <NS>
spec:
  staticConfigs:
  - targets:
    - <ksm-service-name>.<NS>.svc:8080
  job: kube-state-metrics
  honorLabels: true
```

The configuration would use the K8s Service LB functionality and return metrics for just one pod. In case one is crashing, no problem. Instead of using the CRD of the Prometheus-Operator the config can be directly passed to the Prometheus in the config yaml.

For KSMs own metrics the ServiceMonitor can still be used with port 8081 since KSM is exposing its own metrics there.

**Comment by jenciso** [comment]
> I have tried to implement KSM HA without having the issue of multiple metrics (one for KSM pod and no need for avg function etc.).
> 
> This is indeed possible by using a ScapeConfig instead of a ServiceMonitor for KSM cluster metrics.
> 
> Example:
> 
> apiVersion: monitoring.coreos.com/v1alpha1
> kind: ScrapeConfig
> metadata:
>   name: kube-state-metrics-cluster-metrics
>   namespace: <NS>
> spec:
>   staticConfigs:
>   - targets:
>     - <ksm-service-name>.<NS>.svc:8080
>   job: kube-state-metrics
>   honorLabels: true
> The configuration would use the K8s Service LB functionality and return metrics for just one pod. In case one is crashing, no problem. Instead of using the CRD of the Prometheus-Operator the config can be directly passed to the Prometheus in the config yaml.
> 
> For KSMs own metrics the ServiceMonitor can still be used with port 8081 since KSM is exposing its own metrics there.

Hi there. I created a [[kube-state-metrics] Use scrapeConfig to have HA prometheus-community/helm-charts#5470](https://github.com/prometheus-community/helm-charts/pull/5470) with this idea. Please, could you comment on it to validate the approach suggested? thx
