### ISSUE TITLE
Not able to get "kube_node_status_phase" metric

### ISSUE THREAD

**Issue by amolsh** [kubernetes/kube-state-metrics#64]
I am running Kubernets on coreos. For monitoring, I am using Prometheus, Grafana and kube-state metrics.
I wanted to check status of nodes in cluster , whether  they are running or not. I thought, I could get info from "kube_node_status_phase" metric. But , it is not showing in prometheus. Except this, I am able to see all metrics.
Can anyone help me to sort this out?

**Comment by brancz** [comment]
The `kube_node_status_phase` metric is only set if it is actually [set on the object](https://github.com/kubernetes/kube-state-metrics/blob/d07f95ec5cf4ec4a66b3ebf0a4c2f3d7403a0fbb/node.go#L159). A quick check on my clusters showed that is it actually never set. So I looked at the [documentation](https://github.com/kubernetes/client-go/blob/24a02a6d7d2c9a21b12a3eb35c71c784e63825f4/pkg/api/v1/types.go#L2903-L2907) and it revealed, that it is deprecated and never set.

As we are trying to reflect the API as much as possible I think the best thing to do is to just remove that metric entirely. What were you hoping to observe with this metric? Does the `kube_node_status_ready` suffice?

**Comment by andyxning** [comment]
Close this as the [comment by @brancz](https://github.com/kubernetes/kube-state-metrics/issues/64#issuecomment-271530507) has state the reason for not having `kube_node_status_phase`.

@amolsh Please re-open this if you still have some questions. :)
