### ISSUE TITLE
Installation process give me error due Kustomization.yaml file

### ISSUE THREAD

**Issue by jenciso** [kubernetes/kube-state-metrics#653]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Error during the installation of ksm

**What you expected to happen**:
The easy installation process should terminate correctly. But when I apply the kubectl command, it show me an error. It is due the kustomization.yaml file

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl apply -f kubernetes`
show this error: 
error: error validating "kubernetes/kustomization.yaml": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false

**Anything else we need to know?**:
The kustomization.yaml file was added 4 days ago and it resides into the kubernetes directoy, is for that reason that apply command give this error. @mgoodness 

**Environment**: Kubernetes 1.13.2
- Kubernetes version (use `kubectl version`): 1.13.2
- Kube-state-metrics image version 1.5.0

**Comment by mgoodness** [comment]
Damn, sorry. Fix incoming.
