### ISSUE TITLE
Documentation of metrics-server is misleading

### ISSUE THREAD

**Issue by wfernandes** [kubernetes/kube-state-metrics#667]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
This is a bug report for the documentation section [kube-state-metrics vs. metrics-server(Heapster)](https://github.com/kubernetes/kube-state-metrics#kube-state-metrics-vs-metrics-serverheapster).

Although, the metrics-server is known as a light-weight heapster, I feel that the documentation has some misleading points. For example in the kube-state-metrics README it says,

> metrics-server(Heapster) is a project which fetches metrics (such as CPU and memory utilization) from the Kubernetes API server and nodes and sends them to various time-series backends such as InfluxDB or Google Cloud Monitoring.

This is incorrect when looking at:
- the [docs of the metrics-server](https://github.com/kubernetes/community/blob/5b2e4f19565f62c5af3803d82d21fc6fb8d7d7d8/contributors/design-proposals/instrumentation/metrics-server.md#design) 
> It will be a cluster level component which periodically scrapes metrics from all Kubernetes nodes served by Kubelet through Summary API. Then metrics will be aggregated, stored in memory (see Scalability limitations) and served in Metrics API format.

- and the [monitoring pipeline design proposal](https://github.com/kubernetes/community/blob/5b2e4f19565f62c5af3803d82d21fc6fb8d7d7d8/contributors/design-proposals/instrumentation/monitoring_architecture.md#core-metrics-pipeline)
> These sources [kubelet, resource estimator] are scraped by a component we call metrics-server which is like a slimmed-down version of today's Heapster. metrics-server stores locally only latest values and has **no sinks**

**What you expected to happen**:

Perhaps this section should focus on the differences between kube-state-metrics and metrics-server and ignore references to heapster since it is going to be deprecated anyways.

Sections like.

> metrics-server(Heapster) only needs to fetch, format and forward metrics that already exist, in particular from Kubernetes components, and write them into sinks, which are the actual monitoring systems

> metrics-server(Heapster) is a project which fetches metrics (such as CPU and memory utilization) from the Kubernetes API server and nodes and sends them to various time-series backends such as InfluxDB or Google Cloud Monitoring.

should be deleted.

**Comment by brancz** [comment]
You're absolutely right with all your statements. Could you open a PR to modify the readme? :slightly_smiling_face:

**Comment by wfernandes** [comment]
@brancz When you get the chance I would appreciate a review on my PR. I'm happy to make any changes :)
