### ISSUE TITLE
Not able to get kube_pod_container_limits_cpu_cores metric

### ISSUE THREAD

**Issue by stvnwrgs** [kubernetes/kube-state-metrics#67]
I'm not able to see the `kube_pod_container_limits_cpu_cores` metric in prometheus. But i can see other metrics like: `kube_pod_container_requested_cpu_cores`

Setup:
GKE with k8s 1.5.1

Maybe related? #64

**Comment by brancz** [comment]
The `kube_pod_container_limits_cpu_cores` metric is [only set](https://github.com/kubernetes/kube-state-metrics/blob/d07f95ec5cf4ec4a66b3ebf0a4c2f3d7403a0fbb/pod.go#L190) if the pod actually has a CPU limit set. Can you make sure that this is the case for the object you are expecting it for?

**Comment by stvnwrgs** [comment]
Yes, I'm sure that I have multiple containers inside my pod with a CPU limit.

**Comment by decker502** [comment]
I get the same issue.

**Comment by brancz** [comment]
I currently don't have much bandwidth to look into this, if someone can investigate this and/or open a PR I'm happy to review it or fix it once we have found the source of the problem.

**Comment by stvnwrgs** [comment]
@decker502, @brancz I found the problem. The documentation is newer than the latest release. 
Limits are not exported in 0.3.0.

@brancz do you have an idea about the next release date? We need that stuff for our alerts =/

**Comment by brancz** [comment]
@stvnwrgs I'm gonna be working towards a new release in the upcoming days. There are a few things that we want to include in this release that are not quite done, but should be relatively quick - so stay tuned, it should happen rather sooner than later! :slightly_smiling_face:

**Comment by stvnwrgs** [comment]
It's available in the current release
