### ISSUE TITLE
Graphite integration

### ISSUE THREAD

**Issue by akshatgit** [kubernetes/kube-state-metrics#678]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
We use graphite as the default tool to store system and application metrics in our infra. It would be great if we could directly send metrics using kube-state-metrics to an external graphite endpoint. 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version

**Comment by brancz** [comment]
kube-state-metrics does and will only support the Prometheus exposition format, and in the future the OpenMetrics format. Other formats are out of scope of this project and are asked to write general purpose converters from Prometheus/OpenMetrics format to other monitoring systems.
