### ISSUE TITLE
Missing quay.io/gcr arm64 images?

### ISSUE THREAD

**Issue by jmreicha** [kubernetes/kube-state-metrics#680]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

I see there are instructions in the `Makefile` for building and pushing multiarch images, but don't actually see the images on the registries, just the amd64 image.

```
manifest-tool inspect k8s.gcr.io/kube-state-metrics:v1.5.0
k8s.gcr.io/kube-state-metrics:v1.5.0: manifest type: application/vnd.docker.distribution.manifest.v2+json
      Digest: sha256:37c4ddfa160043a7fd73703b7cae41cf38b692ca19c1dff722293c90a386b59f
Architecture: amd64
          OS: linux
    # Layers: 2
      layer 1: digest = sha256:cd784148e3483c2c86c50a48e535302ab0288bebd587accf40b714fffd0646b3
      layer 2: digest = sha256:cff0390a13ca215dcab67321b8e7d4a84955bb5fa0fd39de426d4621bc864c02
```

**What you expected to happen**:

I was expecting to see manifests/images for different architectures (as listed in the Makefile).  Am I missing something here?

**Comment by brancz** [comment]
This is as intended right now, it's not a bug. We simply have not setup the infrastructure, and would like to avoid having to maintain repositories for x amount of architectures. Beyond that none of the kube-state-metrics maintainers are Google employees so we rely on Google employees to publish these images, meaning there is little we can do for the gcr.io images.

**Comment by jmreicha** [comment]
@brancz So the Google registry allows for "fat" manifests, which means you can use one image name and publish multiple architectures, otherwise I think it would maybe just be a matter of creating the new image repos on quay.io.  Is that something you'd be interested in trying?  Is there anybody from Google (or elsewhere) that I can bug 😄 

I think there are a lot of ARM enthusiasts that would appreciate the effort as more and more Kubernetes components and projects are adding multiarch support.

**Comment by brancz** [comment]
cc @DirectXMan12 @piosz @kawych @loburm @serathius

**Comment by serathius** [comment]
You can bug me. 

I would suggest pushing arm image into `k8s.gcr.io/kube-state-metrics-arm64:v1.5.0`, as this is how we do for other kubernetes images. 
Josh, Fredric is this ok?

**Comment by brancz** [comment]
I'm ok with that, thanks @serathius!

**Comment by serathius** [comment]
New images that are now available:
```
k8s.gcr.io/kube-state-metrics-arm64:v1.5.0
k8s.gcr.io/kube-state-metrics-arm:v1.5.0
k8s.gcr.io/kube-state-metrics-s390x:v1.5.0
k8s.gcr.io/kube-state-metrics-ppc64le:v1.5.0
```

**Comment by jmreicha** [comment]
Just verified the arm64 image is working so I'm good to close.  Thanks for helping out @brancz and @serathius!

**Comment by autarchprinceps** [comment]
> You can bug me.
> 
> I would suggest pushing arm image into `k8s.gcr.io/kube-state-metrics-arm64:v1.5.0`, as this is how we do for other kubernetes images.
> Josh, Fredric is this ok?

@serathius 
This is not ok. It needs to be under the same name as part of the fat manifest, or else manual intervention is required on multi instance Kubernetes clusters. Naming images after architectures is obsolete.

**Comment by serathius** [comment]
New release process https://github.com/kubernetes/kube-state-metrics/issues/1089 should release `k8s.gcr.io/kube-state-metrics/kube-state-metrics` as a FAT manifest
