### ISSUE TITLE
Make container/E2e tests are not referring to the latest image tag of kube-state-metrics

### ISSUE THREAD

**Issue by tariq1890** [kubernetes/kube-state-metrics#684]
We are still extracting `v1.5.0-alpha` as the latest release version when running the `e2e` tests and `make container`

This is probably happening because `git describe --abbrev=0` returns the following
`v1.5.0-alpha.0`

We would need to push the latest tag `1.5.0` to the current master.

/cc @mxinden @brancz

**Comment by mxinden** [comment]
We could create the following pull request https://github.com/kubernetes/kube-state-metrics/compare/master...release-1.5?expand=1 or, given that the last release was more than a month ago, prepare for v1.6.0 instead. What do you all think?

**Comment by brancz** [comment]
Generally, I've been thinking if using `git describe --abbrev=0` is really the best thing to do. I think I'd prefer to switch to a `VERSION` file in the root of the repo and use that. When debugging a container/repo it's much easier to discover the version that way.

**Comment by mxinden** [comment]
`VERSION` file sounds good to me.
