### ISSUE TITLE
resourcequota metrics missing in v1.5.0

### ISSUE THREAD

**Issue by benjaminhuo** [kubernetes/kube-state-metrics#685]
![snip20190227_336](https://user-images.githubusercontent.com/18525465/53482846-1e1ca580-3abb-11e9-8b3f-20558ed0fd67.png)
![snip20190227_337](https://user-images.githubusercontent.com/18525465/53482848-1e1ca580-3abb-11e9-846c-d4608ae15420.png)
![snip20190227_338](https://user-images.githubusercontent.com/18525465/53482850-1eb53c00-3abb-11e9-9aed-fb91e6f5102c.png)

Is resourcequota metrics like kube_resourcequota removed in kube-state-metrics v1.5.0?
I'm using prometheus deploy by prometheus operator 0.27, but cannot find resourcequota related metrics anymore as I can in v1.3.2
If it's removed, how can I get it back?

Thanks very much
Ben

**Comment by brancz** [comment]
Do you actually have `ResourceQuota` objects?

```
kubectl get resourcequota --all-namespaces
```

**Comment by benjaminhuo** [comment]
Sorry, my bad.
It's a new test env without resourcequota.
BTW, I'm looking forward to enjoy the new performance improve in this new version.

Thanks
Ben

**Comment by benjaminhuo** [comment]
Another unrelated question : the ingress metrics mentioned in [ingress-metrics](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/ingress-metrics.md) were added after release v1.5.0, which means they are not available in v1.5.0 , right?

**Comment by brancz** [comment]
Precisely. They will be available in v1.6.0. There is no planned release date yet as there are a number of outstanding pull requests.

**Comment by benjaminhuo** [comment]
Good to know know that :)
I'll keep an eye on this and see if I can help.

Ben
