### ISSUE TITLE
Add time metrics

### ISSUE THREAD

**Issue by cgetzen** [kubernetes/kube-state-metrics#687]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
There is no way to track how long most pod/container events take. I would like to be able to track pull times, start times, etc.

**What you expected to happen**:
For all kube_pod_container_status_* events, I would like to have access to a kube_pod_container_status_*_time, in order to track how long events take.

**Comment by brancz** [comment]
These are not available in the pod API are they? That would not make these metrics a good fit for kube-state-metrics. Besides that metrics are best instrumented where the action actually happens so everything you’re asking for should be a metric on the container runtime.

**Comment by cgetzen** [comment]
Correct, I don't believe they are. It looks like it is a part of [events](https://godoc.org/k8s.io/api/core/v1#Event) however. In addition to container metrics, I'm hoping to capture image pull times, etc. which I think the events api would broadly apply to. Is there a reason why kube-state-metrics doesn't capture events now, and would contributions be accepted there?

**Comment by brancz** [comment]
Events are out of scope for kube-state-metrics, but in a general sense I think it would be useful to have an exporter that aggregates events into metrics, we would just need to be careful about cardinality.
