### ISSUE TITLE
kube_job_spec_active_deadline_seconds not present when job fails

### ISSUE THREAD

**Issue by estahn** [kubernetes/kube-state-metrics#691]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

* A Job has exceeded it's `activeDeadlineSeconds` and was terminated.
* I wanted to alert on these by using the following rule:

```
sum by(job_name) (kube_job_status_completion_time{job_name!=""} - kube_job_status_start_time) > max by(job_name) (kube_job_spec_active_deadline_seconds{job_name!=""})
```
This will not work as `kube_job_spec_active_deadline_seconds` is not populated for this failing job.

**What you expected to happen**:

Have specs available regardless of whether the job fails.

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-13T23:15:13Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.6", GitCommit:"b1d75deca493a24a2f87eb1efde1a569e52fc8d9", GitTreeState:"clean", BuildDate:"2018-12-16T04:30:10Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Kube-state-metrics image version

```
quay.io/coreos/kube-state-metrics:v1.4.0
```

**Comment by brancz** [comment]
This is not a bug, this is in line with how this is exposed on the Kubernetes API. If a completionTime is not nil we expose it, if it is nil, exposing something would be wrong:

https://github.com/kubernetes/kube-state-metrics/blob/bebada61dcfc0004d434fba55e84478ab9d85ab2/internal/collector/job.go#L253-L258

I don't think there is an issue in kube-state-metrics here.

**Comment by estahn** [comment]
@brancz Thanks for your response, but I'm saying the metric `kube_job_spec_active_deadline_seconds` is **NOT** present. The metric `kube_job_status_completion_time` is present and showing the time it took to "complete", even though it was terminated.

**Comment by estahn** [comment]
@brancz After revisiting this it appears I have been wrong.

Is there any way to evaluate how long a failed job was running?

**Comment by brancz** [comment]
I don't use any `Job`s in the clusters I oversee, so I can't investigate. Generally speaking if the data is not in the Kubernetes object, then kube-state-metrics won't expose it.

**Comment by estahn** [comment]
@brancz Fair enough :)
