### ISSUE TITLE
Discuss cutting kube-state-metrics v1.6.0

### ISSUE THREAD

**Issue by mxinden** [kubernetes/kube-state-metrics#697]
Given that the last release was cut ~2 month ago and *master* being ahead of *release-1.5* by 107 commits, what do you all think of cutting a *v1.6.0* release?

**Comment by brancz** [comment]
Sounds good to me :+1:

**Comment by tariq1890** [comment]
Possible to fit PRs #610 and #654 into the release?

**Comment by brancz** [comment]
#654 is already merged, so yes, #610 I'm not so sure about as it will need some follow up and I'd be ok if it lands in the next release

**Comment by tariq1890** [comment]
Whoops typo I meant #650

**Comment by tariq1890** [comment]
Sure, I understand. Also, if it doesn't have any activity, I don't mind picking one of them up. We can also open it up to potential contributors in the Kubernetes slack. Thoughts?

**Comment by tariq1890** [comment]
Or if we want to cut the 1.6.0 release sooner, we can just wait until the next minor release too

**Comment by brancz** [comment]
Pinging people on kubernetes slack as a first measure sounds like a good idea. As we don’t have a regular release cadence, I think it’s ok to also cut the next minor release closer to this one if needed.

**Comment by tariq1890** [comment]
Let's cut this!

**Comment by brancz** [comment]
Agreed. @mxinden you want to take care of this?

**Comment by brancz** [comment]
v1.6.0 has already been released.
