### ISSUE TITLE
Export readiness and liveness metrics

### ISSUE THREAD

**Issue by okke-formsma** [kubernetes/kube-state-metrics#699]
/kind feature
Currently there is no way to monitor liveness and readiness probe failures using kube-state-metrics. I would very much like to be able to see these for every pod.

**Comment by brancz** [comment]
The kubelet has the `/metrics/probes` path, which exposes the results of probes. Given that's where the metrics originate that's also a better place that the kubelet :slightly_smiling_face: .

**Comment by krish7919** [comment]
> The kubelet has the /metrics/probes path, which exposes the results of probes. Given that's where the metrics originate that's also a better place that kube-state-metrics 🙂 .

@brancz Can you please elaborate on this? We are currently using Datadog with our k8s cluster and the dd-agent does not seem to get this metric.

**Comment by brancz** [comment]
I know nothing about the datadog agent so I can’t say why. I see them in Prometheus :)

**Comment by sravanthi1993** [comment]
> I know nothing about the datadog agent so I can’t say why. I see them in Prometheus :)

@brancz: Can you please share how to configure prometheus.yml to get these probe metrics ?

**Comment by adamjk-dev** [comment]
+1 @brancz Can you elaborate on how you are finding the liveness/readiness probes via Promtheus? I have the same interest and am not finding the metrics as is. Maybe this depends on the version of k8s/kube-state-metrics/prometheus or the configuration. Thanks!

**Comment by sb1975** [comment]
/remove-lifecycle stale
/reopen

This is a good requirement which is needed to be available to show on Prometheus Dashboard using Grafana. Couldnt find any Grafana dashboard or Prometheus command to show this.

/help-needed

**Comment by brancz** [comment]
These metrics already exist on the kubelet endpoint [`/metrics/probes`](https://github.com/kubernetes/kubernetes/blob/8568d1843daababe70763b30ae897388710b2216/pkg/kubelet/server/server.go#L81), which I think it belongs.

**Comment by acannon828** [comment]
@brancz What are the metric names in Prometheus that you're seeing?

**Comment by janotav** [comment]
@acannon828 and others who might stumble upon this thread searching for the same:

prober_probe_total

**Comment by qlaall** [comment]
this is a probe sample in prometheus-configmap.yaml:

`
    - job_name: 'kubelet-probes'
      kubernetes_sd_configs:
        - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
        - action: labelmap
          regex: __meta_kubernetes_node_label_(.+)
        - target_label: __address__
          replacement: kubernetes.default.svc:443
        - source_labels: [__meta_kubernetes_node_name]
          regex: (.+)
          target_label: __metrics_path__
          replacement: /api/v1/nodes/${1}/proxy/metrics/probes
`

then youcan find prober_probe_total in Prometheus
