### ISSUE TITLE
some metrics such as kube_pod_container_ cannot scrape

### ISSUE THREAD

**Issue by dengceltics** [kubernetes/kube-state-metrics#703]

**Comment by dengceltics** [comment]
Pod log shows: dial tcp 10.233.0.1:443: connect: connection refused 、too old resource version :398

**Comment by dengceltics** [comment]
Pod log shows: dial tcp 10.233.0.1:443: connect: connection refused 、too old resource version :398

**Comment by brancz** [comment]
That's just logging from the informers, it will re-attempt until it succeeds. Are you seeing lots of these being logged quickly? If not then this is perfectly fine and even expected.

**Comment by dengceltics** [comment]
> That's just logging from the informers, it will re-attempt until it succeeds. Are you seeing lots of these being logged quickly? If not then this is perfectly fine and even expected.

![1](https://user-images.githubusercontent.com/42082255/54793741-e4d0f300-4c7e-11e9-96df-613fd844e9a1.PNG)

Tried it all the time, but it didn't work.

**Comment by brancz** [comment]
You seem to have a lot of connection refused, that doesn't seem to be a problem with kube-state-metrics per se, it looks more like a setup problem of your cluster.
