### ISSUE TITLE
Support for PersistentVolume cloud volumeID metric/label

### ISSUE THREAD

**Issue by chancez** [kubernetes/kube-state-metrics#704]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

I'm not sure how this should work; but it would be useful to have a metric or label added to PV metrics that indicates the cloud volumeID of a volume. It's provider specific; so I'm not sure the best way to go about it.

At the end of the day, I'm expecting a new metric (or many metrics) with the value of `spec.gcePersistentDisk.pdName` from a GCE PV or `spec. awsElasticBlockStore.volumeID` from an AWS PV stored in a label.

**Comment by brancz** [comment]
As this is flat information, I think this could even be part of an info metric, just the amount of labels might be problematic. How many volume providers are currently supported? Are all of those identifying infos flat?

**Comment by brancz** [comment]
Also this may change with CSI so may become less of a source of truth.

**Comment by chancez** [comment]
I think the main thing is you would need to be able to determine both the ID and what cloud the ID is for. If we only have a label "volume_id` in a metric; that wouldn't be enough to determine if it's a volume on GCE/AWS (thinking about multi-cloud or setups with multiple volume providers). StorageClass wouldn't work either since that's not 100% required to be used (can manually create a PV).

**Comment by chancez** [comment]
I do think putting this into an `info` metric makes sense though.

**Comment by brancz** [comment]
I was thinking of calling the labels `gce_persistent_disk_name`, `ebs_volume_id`. A single PV doesn't have multiple of these set. I don't see the difference between separate metrics and combining all of these as labels in one metric.

**Comment by chancez** [comment]
That's fine. I wasn't sure if it was best practice to omit labels in these cases (enum style metric i guess?). 👍

**Comment by brancz** [comment]
Generally an enum style metric would be nice, but have too huge of a cardinality here, plus I don't see a huge gain of zero-ing the other enum values in this case, as it's primarily meta-data.

**Comment by povilasv** [comment]
@brancz / @lilic  any chance we can release a version with commit https://github.com/kubernetes/kube-state-metrics/pull/1146 ? So that we can close this issue ;)

**Comment by brancz** [comment]
new features will only land in kube-state-metrics 2.0, if you would like to see this version sooner, please help us complete the 2.0 roadmap :) #569

**Comment by povilasv** [comment]
thanks for the info :)

**Comment by lilic** [comment]
This change #1146 was included in the 2.0 pre-release, is there anything left to do here?

**Comment by brancz** [comment]
I don't think so, let's close here :)
