### ISSUE TITLE
kube-static-metrics addon-resizer error

### ISSUE THREAD

**Issue by liuwenjiegithub** [kubernetes/kube-state-metrics#706]
ERROR: logging before flag.Parse: I0326 14:44:55.136801       1 pod_nanny.go:81] Watching namespace: kube-system, pod: kube-state-metrics-65f9c6fcdf-gcbrm, container: kube-state-metrics.
ERROR: logging before flag.Parse: I0326 14:44:55.136808       1 pod_nanny.go:82] storage: MISSING, extra_storage: 0Gi
ERROR: logging before flag.Parse: I0326 14:44:55.138236       1 pod_nanny.go:171] Failed to read data from config file "MISSING/NannyConfiguration": open MISSING/NannyConfiguration: no such file or directory, using default parameters
ERROR: logging before flag.Parse: I0326 14:44:55.138294       1 pod_nanny.go:109] cpu: 100m, extra_cpu: 1m, memory: 100Mi, extra_memory: 2Mi
ERROR: logging before flag.Parse: I0326 14:44:55.138315       1 pod_nanny.go:138] Resources: [{Base:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI} ExtraPerNode:{i:{value:1 scale:-3} d:{Dec:<nil>} s:1m Format:DecimalSI} Name:cpu} {Base:{i:{value:104857600 scale:0} d:{Dec:<nil>} s:100Mi Format:BinarySI} ExtraPerNode:{i:{value:2097152 scale:0} d:{Dec:<nil>} s:2Mi Format:BinarySI} Name:memory}]

kubernetes 1.13.3
addon-resizer:1.8.3

**Comment by avdhoot** [comment]
facing same issue

**Comment by avdhoot** [comment]
To things work changed version of  `addon-resizer:1.8.4` & Changed memory(base) arg of addon-resizer container to `--memory=500Mi` . Not sure that much memory is required by 'kube-state-metrics' are not. Launched kube-state-metrics container is taking around `498Mi` Hope it help.

**Comment by brancz** [comment]
Sounds like we also need to configure a parameter for storage?

**Comment by avdhoot** [comment]
Memory usage are down. 
![kube-metrics](https://user-images.githubusercontent.com/1314627/55327771-75da7200-54a8-11e9-9045-2b93ab5ff132.png)

**Comment by brancz** [comment]
did you deploy a new version of kube-state-metrics? v1.5.0 had major memory improvements :)

**Comment by avdhoot** [comment]
Yep. It is `1.5.0`

**Comment by brancz** [comment]
In that case this is a good graph no? :) the memory improvements worked

**Comment by zouyee** [comment]
https://github.com/kubernetes/autoscaler/pull/559
