### ISSUE TITLE
Add label for priority class in kube_pod_info

### ISSUE THREAD

**Issue by sylr** [kubernetes/kube-state-metrics#712]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

It would be nice to be able to have information about the priority class to write alerts that does not involve low priority pods.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.13.5
- Kube-state-metrics 1.5.0

**Comment by brancz** [comment]
Priority class is flat information on the Pod object, so adding the label to `kube_pod_info` would be more appropriate I think, but generally I think this is a good idea to add.

**Comment by chenk008** [comment]
@brancz Can I work on this?
/assign @chenk008

**Comment by brancz** [comment]
@chenk008 go for it! :)
