### ISSUE TITLE
New metric for PVC resize status

### ISSUE THREAD

**Issue by luarx** [kubernetes/kube-state-metrics#714]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
In Kubernetes v1.11 the persistent volume expansion feature is being promoted and we can use it to resize PVC. But kube-state-metrics doesn't have a metric to know if a PVC is "**resizing**"/"**already resized but pending of a pod restart**"/"**resized**".

It would be useful to know if a pod must be restarted so that Kubernetes can resize the filesystem of a persistent volume.

**What you expected to happen**:
Have a metric to know resize state of a PVC and use it to configure alerts of pods that must be restarted to be able to resize the volume.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.9
- Kube-state-metrics image version

**Comment by brancz** [comment]
The use case makes perfect sense! How does this show in the PVC object? As that's what we would need to create metrics off of.

**Comment by luarx** [comment]
Great! I appreciate that :D 

In the PVC object there are **3 resizing phases**:

1. **NORMAL** status without asking for a resize or **AFTER RESIZING A PVC**
![no_resize_required](https://user-images.githubusercontent.com/22997139/55786946-8d6fb700-5ab5-11e9-80f8-084b5817f272.png)

2. Volume **RESIZING**
![resizing](https://user-images.githubusercontent.com/22997139/55787083-c90a8100-5ab5-11e9-8670-af156e0ae067.png)

3. **FILE SYSTEM RESIZE PENDING**. In this phase pod must be restarted so that it could be done.
![resize_pending](https://user-images.githubusercontent.com/22997139/55787157-f7885c00-5ab5-11e9-8b90-2079ab611508.png)

So I propose the following metric:
- Name: `kube_persistentvolumeclaim_resized_phase`
- Phases:
  - Resizing
  - Pending 
  - Completed (PVC is not in one of the previous phases)
- Fields (the same as kube_persistentvolumeclaim_status_phase):
`kube_persistentvolumeclaim_resized_phase{endpoint="",instance="",job="",namespace="",persistentvolumeclaim="",phase="",pod="",service=""}`

What do you think?

**Comment by brancz** [comment]
I think having condition metric like we do for pods and nodes would be more appropriate here.

**Comment by luarx** [comment]
Are you talking about `kube_node_status_condition`? I has 3 status values: true/false/unknow...will we define our 3 phases instead of those so?

**Comment by brancz** [comment]
It has the `condition` _and_ `status`, which seems to be a similar circumstance here. We would have the `type` and `status`, which are the required fields for that struct and essentially enums.

**Comment by luarx** [comment]
Yes, it makes sense! It would work for me :)

**Comment by brancz** [comment]
You want to give it a go? :)

**Comment by zouyee** [comment]
It is helpful to troubleshoot the volume condition!

**Comment by luarx** [comment]
> You want to give it a go? :)

It would be great but I don't have enough time at this time :(

**Comment by ankitsinhaiiitg** [comment]
Hello, can I work on this issue?

**Comment by luarx** [comment]
Sure, I think so! 😃
