### ISSUE TITLE
addon-resizer ERROR logging before flag.Parse

### ISSUE THREAD

**Issue by leo1515416043** [kubernetes/kube-state-metrics#725]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
```
ERROR: logging before flag.Parse: E0419 11:50:42.383699       1 nanny_lib.go:87] only the following media types are accepted: application/json, application/yaml, application/vnd.kubernetes.protobuf
```
**What you expected to happen**:
NO ERROR log
**How to reproduce it (as minimally and precisely as possible)**:
just follow [this official deployment](https://github.com/coreos/kube-prometheus/blob/master/manifests/kube-state-metrics-deployment.yaml)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.9.4
- Kube-state-metrics image version: k8s.gcr.io/addon-resizer:1.8.4

**Comment by zouyee** [comment]
https://github.com/kubernetes/autoscaler/pull/1792

**Comment by joprice** [comment]
I'm seeing this running v1.9.5: 

```
ERROR: logging before flag.Parse: E0505 16:14:28.402686       1 reflector.go:205] k8s.io/autoscaler/addon-resizer/nanny/kubernetes_client.go:107: Failed to list *v1.Node: v1.NodeList: Items: []v1.Node: v1.Node: ObjectMeta: v1.ObjectMeta: readObjectFiel  dAsBytes: expect : after object field, parsing 2015 ...:{},
```

Did the fix get pulled into a later version?
