### ISSUE TITLE
Release 0.4

### ISSUE THREAD

**Issue by therc** [kubernetes/kube-state-metrics#73]
There are new changes such as Daemonset metrics and per-container limits, but the last release is 0.3, from November. Also, I have code for the Datadog agent to scrape k-s-m for the new data, but quite understandably the maintainers want to see a new official release before accepting my change.

What does it take or who needs to be convinced to make a new release?

**Comment by brancz** [comment]
New release coming up soon :slightly_smiling_face:

**Comment by brancz** [comment]
I'm on my way traveling to FOSDEM, so I may not get to do the release today, but it should happen tomorrow if not today. Unfortunately I am not in control of the container images on gcr and have to ping google employees to do that for us, so I'm guessing those will only be pushed some time next week.

@piosz is there any way we can automate this and have us trigger it when needed? If not would it maybe be possible for us to get access to the gcr repo for kube-state-metrics? (if not take this as my warning that I will bother you again some time next week regarding this :wink: )

**Comment by piosz** [comment]
AFAIK there is an effort to allow making core Kubernetes releases outside of Google. I don't know the details but when it's done this, and other projects should follow this path. In the meantime I release new version of kube-state-metrics. Ping me on slack or email once it's ready.

@saad-ali @grodrigues3 do you know what is the status of the mentioned changes?

**Comment by saad-ali** [comment]
Making kubernetes core releases a non-Google dependent process is something that @david-mcmahon is working on for 1.7 by implementing a continuous release system.
