### ISSUE TITLE
metrics ”kube_pod_container_status_restarts_total”  add pod_ip in the label  

### ISSUE THREAD

**Issue by gjpei2** [kubernetes/kube-state-metrics#731]
hello.
i am using kube-state-metrics monitor my k8s,i want to know pod_ip  when my pod is restarting,it should become a label when alert is fring .but the metrics's label haven't this items, of course ,the metrics kube_pod_info has this label ,but i don't know how to give this ip to my alertmanager when my pod restarting,or can we add this label to the metrics,”kube_pod_container_status_restarts_total”.
please don't care my poor English
thanks!

**Comment by brancz** [comment]
You are looking to join metrics. See some examples here: https://github.com/kubernetes/kube-state-metrics/tree/master/docs#join-metrics

**Comment by gjpei2** [comment]
@brancz  it is useful ,thanks a lot! 
i will close this issue
