### ISSUE TITLE
[feature-request] Deployment Conditions

### ISSUE THREAD

**Issue by vdavidoff** [kubernetes/kube-state-metrics#74]
That'd be great if kube-state-metrics exposed Deployment Conditions. My use case is to easily know if a Deployment is in progress or not, which I plan to use along with Prometheus and an inhibit rule in AlertManager.

I see Deployment Conditions were added to the go k8s client around git commit ae6775eeec5cc9e96cc5cec848f589158acf7d92, and I have tried to add this support in myself by modifying kube-state-metrics, but I'm running into issues building against the newer go client. This is at least partly because I'm hacking at it right now - I don't really know golang or the process of golang development.

I'm happy to keep trying on this, but it's possible one of you will figure it out before I do.

**Comment by vdavidoff** [comment]
Well, I read some stuff and got it to build with my changes and HEAD from go client. Tomorrow I'll see if stuff actually works as I think it should.

**Comment by brancz** [comment]
I wanted to update to latest version of client-go as well, so if you can already do that in the process of implementing this feature, that would be great!

**Comment by vdavidoff** [comment]
Well, I think my changes worked. But in the process of confirming they did what I wanted, I think I learned that the "Progressing" Deployment Condition doesn't work how I thought it would. I suspected it'd be removed from the Deployment Conditions once a rollout was complete, but it appears to exist in perpetuity. I think the following is how Kubernetes determines if a rollout is complete/successful (without ever removing the "Progressing" condition):

pkg/controller/deployment/util/deployment_util.go: 1009 (v1.5.1)
```
// DeploymentComplete considers a deployment to be complete once its desired replicas equals its
// updatedReplicas and it doesn't violate minimum availability.
func DeploymentComplete(deployment *extensions.Deployment, newStatus *extensions.DeploymentStatus) bool {
        return newStatus.UpdatedReplicas == deployment.Spec.Replicas &&
                newStatus.AvailableReplicas >= deployment.Spec.Replicas-MaxUnavailable(*deployment)
}
```

If I'm not wrong, then I think I just need to expose max unavailable replicas (for now at least, as `kube_deployment_spec_strategy_rollingupdate_max_unavailable`) from the Deployment spec. Once I have that, I can use it in conjunction with the following metrics that are already available via kube-state-metrics:
* kube_deployment_spec_replicas
* kube_deployment_status_replicas
* kube_deployment_status_replicas_available
* kube_deployment_status_replicas_unavailable
* kube_deployment_status_replicas_updated

I have successfully modified kube-state-metrics to buid against HEAD of k8s.io/client-go (which I think I no longer require, but it sounds like you'd be happy to have working anyway) and to expose kube_deployment_spec_strategy_rollingupdate_max_unavailable, correctly handling if it's a percentage (string) or an integer.

I'm still figuring out the proper way to update the GoDep bits to account for the new version of client-go. But once I feel like I have figured that out properly, I will submit a PR and someone can tell me what I got wrong.

Which version of client-go are you looking to build against? The newest stable release? Beta release? Some specific commit? I can tell you that Deployment Conditions don't appear to be exposed in the newest stable release, but I also don't care about them anymore, I don't think, so I don't *think* I need a specific version of client-go.

**Comment by vdavidoff** [comment]
I submitted a [pull request](https://github.com/kubernetes/kube-state-metrics/pull/75) but I guess some tests are failing. I'll circle back to that.

**Comment by vdavidoff** [comment]
Test fixed.

**Comment by vdavidoff** [comment]
I'm closing this even though Deployment Conditions weren't implemented, since this turned into a different request as things progressed, and the related PR is merged.
