### ISSUE TITLE
Everything is a Gauge! (except "kube_pod_container_status_restarts_total")

### ISSUE THREAD

**Issue by zuzzas** [kubernetes/kube-state-metrics#743]
/kind bug

We are building a hacky highly-available kube-state-metrics installation. For it to work, though, we've got to ensure that everything is Gauge in kube-state-metrics. And it made perfect sense for it to be, since it's basically just an adapter between Kubernetes API and Prometheus exposition format. But there is one [thing](https://github.com/kubernetes/kube-state-metrics/blob/master/internal/collector/pod.go#L484) that is a Counter.

Is there a reason for it to be a counter? Can we make it a Gauge?

**Comment by brancz** [comment]
I wouldn't call this a bug, restarts _are_ monotonically increasing, so they are a counter. Why do you need it to be a gauge? If you want high availability with kube-state-metrics you will have to scrape two identical replicas, and handle "deduplication" at query time.

**Comment by zuzzas** [comment]
I wouldn't call that a bug too. I didn't know what label makes more sense.

But what if we scrape a ClusterIP type Service (yes, that would require some Prometheus hacking)? There won't be any duplication. And it should, theoretically, work if everything is a Gauge.

Restarts are monotonically increasing, but those are recorded [here](https://github.com/kubernetes/kube-state-metrics/blob/master/internal/collector/pod.go#L493). Because kube-state-metrics is nothing more than an adapter to Kubernetes API. In that concrete case an adapter to Pod Status field. Am I wrong?

**Comment by mxinden** [comment]
> Because kube-state-metrics is nothing more than an adapter to Kubernetes API.

Kube-state-metrics is an adapter to the Kubernetes API with a replicated cache of the Kubernetes cluster state. A scrape request to kube-state-metrics does not result in a request by kube-state-metrics to the Kubernetes API. Instead kube-state-metrics leverages [Kubernetes informers](https://github.com/kubernetes/client-go/tree/master/tools/cache) to keep its local cache up to date within a reasonable delay boundary.

> But what if we scrape a ClusterIP type Service (yes, that would require some Prometheus hacking)? There won't be any duplication. And it should, theoretically, work if everything is a Gauge.

The interworking of kube-state-metrics and the Kubernetes API is not [linearizable](https://en.wikipedia.org/wiki/Linearizability). Thus if you have two replicas of kube-state-metrics, there is no guarantee that they would give the same response. One of them might for example lag behind several updates. Even though consistent within a single Kubernetes object thus always returning consistent states, kube-state-metrics does not guarantee cross-kubernetes-object consistency or up-to-date responses. 

> We are building a hacky highly-available kube-state-metrics installation.

Maybe you can add some more details on what you are trying to achieve so we understand the situation at hand better.

**Comment by zuzzas** [comment]
Well, yeah, the Store component may go out of sync, which throws the whole idea into a garbage bin. Thanks for confirming my fears! :)
