### ISSUE TITLE
Add possibility to run Kube-state-metrics without cluster-reader role

### ISSUE THREAD

**Issue by kalote** [kubernetes/kube-state-metrics#751]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
I'm trying to use kube-state-metrics in an openshift 3.7 environment, without cluster-reader role. I would like to use kube-state-metrics without cluster-reader role. 

**What you expected to happen**:
Provided a service account that has admin / reader access on specific namespaces (let's say, 3 NS / 10 NS total in the cluster), i would like "kube-*" metrics to be exposed for the resources available in those specific NS.

**How to reproduce it (as minimally and precisely as possible)**:
Try to run kube-state-metrics without cluster reader role by providing a serviceaccount that is admin or reader on multiple NS (roleBinding).

**Anything else we need to know?**:
Let me know if I can help in any way making this feature :)

**Environment**:
- Kubernetes version: Openshift 3.7.72 / Kubernetes 1.7.6
- Kube-state-metrics image version: quay.io/coreos/kube-state-metrics:v1.6.0

**Comment by kalote** [comment]
After going into more research, it seems that using a combination of `--collectors` and `--namespace` allow me to do what I wanted.

I think this options are not super present / explained in your documentation. I had to go through Helm chart to find out about those command lines arguments. Maybe an entry could be added in the documentation?

Anyway, No issue, all works fine now :)

**Comment by brancz** [comment]
Seems like you've already found the answer. Would you like to create a PR to add this to the docs?
