### ISSUE TITLE
Auth failures when using projected service account token volumes

### ISSUE THREAD

**Issue by jtackaberry** [kubernetes/kube-state-metrics#753]
When kube-state-metrics is configured with to use a projected token volume (e.g. if the BoundServiceAccountTokenVolume feature gate is enabled, or if explicitly configured for the kube-state-metrics pod), it fails to periodically re-read the token file, resulting in a barrage of auth errors on the apiserver:

```
E0514 15:31:13.734348       1 authentication.go:65] Unable to authenticate the request due to an error: [invalid bearer token, Token has expired.]
```

kube-state-metrics should re-read the token periodically.  The same problem was [reported against metrics server](https://github.com/kubernetes-incubator/metrics-server/issues/232) and the comment there was that a recent client-go library takes care of this for you, but kube-state-metrics appears to have vendored a sufficiently new version of client-go so this may be a different sort of bug.

/kind bug

Kubernetes: 1.14.1
kube-state-metrics: 1.6.0

**Comment by brancz** [comment]
Interesting. We use v1.14 https://github.com/kubernetes/client-go/commit/6ee68ca5fd83, I would have thought that already does this. We'll need to investigate what we would need to do different to make this work correctly.

**Comment by zouyee** [comment]
https://kubernetes.io/docs/concepts/storage/volumes/#projected
`The expirationSeconds is the expected duration of validity of the service account token. It defaults to 1 hour and must be at least 10 minutes (600 seconds). An administrator can also limit its maximum value by specifying the --service-account-max-token-expiration option for the API server. 
`

**Comment by brancz** [comment]
/remove-lifecycle stale

@jtackaberry we've upgraded the client-go dependencies since this was opened. Have you been able to test this since?

**Comment by brancz** [comment]
Could someone verify whether this is still the case?

/remove-lifecycle stale
