### ISSUE TITLE
Allow wildcards/grouping of metrics to whitelist/blacklist

### ISSUE THREAD

**Issue by hunterchris** [kubernetes/kube-state-metrics#759]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
I cannot whitelist/blacklist a bulk of metrics that are being exposed.

**What you expected to happen**:
I expected to use wildcards to allow blacklisting for example `*_labels*` metrics.

**How to reproduce it (as minimally and precisely as possible)**:
¯\_(ツ)_/¯

**Anything else we need to know?**:
I'm running an EKS cluster and as all my infra is in AWS, I was hoping to be able to use CloudWatch to monitor the state of my cluster. 
I'm using the prometheus-to-cloudwatch (https://github.com/cloudposse/prometheus-to-cloudwatch) scraper which seems to be working ok but the problem is that I'm getting a huge amount of metrics (around 220k metrics) and many of them are completely useless.
I want to be able to disable all the metrics that are meaningless (in the sense of cluster's health, i.e. the metrics `kube_*_info` or `kube_*_labels`) and reduce the amount of money spent on Cloudwatch; as an idea, ~220K metrics per month costs ~800USD.

**Environment**:
- Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

- Kube-state-metrics image version
`1.6.0`

**Comment by brancz** [comment]
Selection by regex seems pretty reasonable.

**Comment by mxinden** [comment]
Sounds like a good feature. @hunterchris would you like to look into the implementation of it?

**Comment by hunterchris** [comment]
I wish I could @mxinden, sadly I can't `Go` that far :(

**Comment by tariq1890** [comment]
I'll take a crack at this.
