### ISSUE TITLE
Documentation links to a prometheus configuration that has been updated

### ISSUE THREAD

**Issue by chrismgrayftsinc** [kubernetes/kube-state-metrics#761]
**Is this a BUG REPORT or FEATURE REQUEST?**:

Bug report

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

README.md links to https://raw.githubusercontent.com/prometheus/prometheus/master/documentation/examples/prometheus-kubernetes.yml which recently updated to comment out some annotations that are referenced in the README.md (see https://github.com/prometheus/prometheus/commit/03a9e7f72e072c6d29f422425d8acd91a957836b#diff-416ffe38e4360ad5f27d8a034963c260)

**What you expected to happen**:

Ideally a reference prometheus configuration could be included in the README.md so that it is not relying on a different project's moving codebase.

**Comment by brancz** [comment]
I think I’d prefer not linking to any Prometheus config. This is supposed to be up to the user, I feel giving any config will make it seem like people have to do it that way.

**Comment by chrismgrayftsinc** [comment]
Sounds good to me.  I found having the example Prometheus config helpful but not so much so that I couldn't have figured it out myself.

**Comment by brancz** [comment]
Do you want to create a PR to remove it? :)

**Comment by zimmertr** [comment]
I think it would be at least worth including an example or linking to the example within Prometheus' repo so that new users aren't left confused how to use this. This was quite difficult for me to figure out since I haven't used Prometheus before now.
