### ISSUE TITLE
SchemaError(io.k8s.api.apps.v1beta1.ScaleStatus): invalid object doesn't have additional properties

### ISSUE THREAD

**Issue by NullP0interEx** [kubernetes/kube-state-metrics#766]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
> /kind feature

**What happened**:

SchemaError(io.k8s.api.apps.v1beta1.ScaleStatus): invalid object doesn't have additional properties

**What you expected to happen**:

https://www.digitalocean.com/docs/kubernetes/how-to/monitor-advanced/

**How to reproduce it (as minimally and precisely as possible)**:
Setup on new DO Cluster (FRA1 - 1.14.2-do.0)

git clone git@github.com:kubernetes/kube-state-metrics.git
kubectl create -f kube-state-metrics/kubernetes/

**Anything else we need to know?**:
no
**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.7", GitCommit:"0c38c362511b20a098d7cd855f1314dad92c2780", GitTreeState:"clean", BuildDate:"2018-08-20T10:09:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

- Kube-state-metrics image version

master

**Comment by tariq1890** [comment]
Your `kubectl` seems quite old. Could you use the latest `kubectl` and let us know if you still face the same error?

**Comment by NullP0interEx** [comment]
thx, works for me

**Comment by NullP0interEx** [comment]
I'm glad it worked so fast, I appreciate the support.

**Comment by tariq1890** [comment]
You're very welcome :)!
