### ISSUE TITLE
Add target and current cpu utilization in hpa metrics

### ISSUE THREAD

**Issue by mohit-gupta** [kubernetes/kube-state-metrics#768]
Want to monitor the current and target CPU utilization for deployments via Prometheus. However, it does not seem to available in the current list of HPA metrics (https://github.com/kubernetes/kube-state-metrics/blob/1dfe6681e9/docs/horizontalpodautoscaler-metrics.md). 

Is there any other way to get these values in Prometheus? If not, can they be added to the HPA metrics?

**Comment by brancz** [comment]
Utilization metrics should be scraped from cAdvisor, which is built into the kubernetes kubelet. kube-state-metrics is just about converting API objects to Prometheus metrics.

**Comment by janzantinge** [comment]
The HPA target CPU utilization isn't published by cAdvisor is it? It seems like there should be another HPA metric like kube_hpa_spec_target{metric="cpu"...} or something along those lines that can publish the resource target part of the HPA spec. I may be missing something as I'm still pretty new to k8s.

**Comment by brancz** [comment]
Sorry I think I misunderstood last time, as this is more or less a static value on the HPA object, this should indeed come from kube-state-metrics.

/reopen

**Comment by janzantinge** [comment]
@brancz Is this something I can contribute?

**Comment by brancz** [comment]
I believe it’s already in progress https://github.com/kubernetes/kube-state-metrics/pull/961

**Comment by janzantinge** [comment]
IIUC that PR doesn't include the target utilization values specified in the Spec, only the current utilization values in the Status.

**Comment by brancz** [comment]
You're right. Feel free to open another PR in that case :)

**Comment by janzantinge** [comment]
Here goes nothing!
