### ISSUE TITLE
Some metrics are not valued

### ISSUE THREAD

**Issue by SergeJazz** [kubernetes/kube-state-metrics#778]
**What happened**:
Some metrics are not valued such as:
```
kube_statefulset
kube_deployment
```
![issue-1](https://user-images.githubusercontent.com/15245376/58798193-478d2600-8602-11e9-8709-2d1131d5769a.png)

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): **1.14.2**
- Kube-state-metrics image version: **v1.6.0**

**Comment by xieyanker** [comment]
Maybe your k8s cluster does not exist these resources, you can use `kubectl get statefulset --all-namespacs`, and I think your service does not include externalIP's metadata.

**Comment by SergeJazz** [comment]
Thank for your answer @xieyanker  
I thought that it should display the metric line with 0 or with an empty string if the resource does not exist on the cluster. No ?

Thus, I have deployment on the cluster, and the same problem

![issue-2](https://user-images.githubusercontent.com/15245376/58799996-106d4380-8607-11e9-8bee-eaacb8eabced.png)

**Comment by brancz** [comment]
This is expected. We always write the type and help text to the output even if there is no associated metrics. While this doesn't hurt, it's also a little weird. Marking it as an enhancement.

**Comment by VF-mbrauer** [comment]
In our cluster v1.13.4 the kube_deployment is not populated when using v1.6.0. I have tested both 1.5.0 and 1.6.0 with not other change in the cluster. I only edited the deployment and changed only the image version and found the same problem as observed above.

**collectors used:**
```
   - --collectors=configmaps
    - --collectors=cronjobs
    - --collectors=daemonsets
    - --collectors=deployments
    - --collectors=endpoints
    - --collectors=horizontalpodautoscalers
    - --collectors=jobs
    - --collectors=limitranges
    - --collectors=namespaces
    - --collectors=nodes
    - --collectors=persistentvolumeclaims
    - --collectors=persistentvolumes
    - --collectors=poddisruptionbudgets
    - --collectors=pods
    - --collectors=replicasets
    - --collectors=replicationcontrollers
    - --collectors=resourcequotas
    - --collectors=secrets
    - --collectors=services
    - --collectors=statefulsets
```

**Comment by brancz** [comment]
@VF-mbrauer This could be due to the change of using the apps/v1 API now.

**Comment by VF-mbrauer** [comment]
OK @brancz, could be or couldn't. But what are the next steps here. This needs to be fixed. We are now back with 1.5.0 as 1.6.0 is not working as expected and described in the design. Therefore will it be treat as a bug now? What are the next actions?

**Comment by brancz** [comment]
Could you please create a separate issue? As this is not the same as what you are seeing. This issue is about the help and type text being printed, even if there are no metrics in the output. You're saying there should be output where there is not.

**Comment by VF-mbrauer** [comment]
Thanks @brancz, I have created a new issue for that.
`https://github.com/kubernetes/kube-state-metrics/issues/789`
