### ISSUE TITLE
Create rarely-used counters as-needed

### ISSUE THREAD

**Issue by bboreham** [kubernetes/kube-state-metrics#787]
/kind feature

Several `GenerateFunc` implementations in `pod.go` pre-create all possible metrics, so I have thousands of series for `CrashLoopBackOff`, `InvalidImageName`, `OOMKilled`, `DeadlineExceeded`, etc., etc., even though only one or two of those are ever non-zero for any container.

I propose that these are created only if the value is non-zero, so as to reduce the load generating, scraping and storing these series.

(The implementation is not trivial, as it is necessary to know where a non-zero value was previously output in order to generate a zero from then on)

**Comment by brancz** [comment]
Generally this is how we decided long ago to map enum types into Prometheus metrics. The nice thing about this is that it's easily extensible, but I agree, that this produces a huge amount of metrics. Maybe we can for metrics where we definitely know the possible values, have a atoi type definition and make the value represent the "current" enum value.

@brian-brazil what are your thoughts on this?

**Comment by bboreham** [comment]
I am not proposing to change the mapping.

**Comment by brancz** [comment]
Right, I was trying to see if there was a way to potentially not create the same amount of series.

**Comment by bboreham** [comment]
I think any change in the data model would result in _more_ series while we deprecated the old way and introduced the new.  Plus lots of complexity for consumers who need to deal with both.

Do you have a view on what I did propose?

**Comment by brancz** [comment]
I understand what you're proposing, but I don't see a way of doing:

> (The implementation is not trivial, as it is necessary to know where a non-zero value was previously output in order to generate a zero from then on)

without making kube-state-metrics stateful or introduce a database, which both sounds like a bad idea.

So the only way of reducing that I can see is only expose the metric for the state that is "current" (or do something else entirely).

**Comment by brian-brazil** [comment]
Your options are to either expose one series per state, or a single series that indicates the current state. Doing otherwise will break common PromQL expressions against them.

**Comment by brian-brazil** [comment]
One thing you can do is collapse states, so various rare failure states could be combined into one reported state.

**Comment by bboreham** [comment]
@brancz why could the state not be in memory?  If the pod is replaced the old series will go away anyway.

**Comment by bboreham** [comment]
@brian-brazil can you give any pointers to the PromQL expressions that would be broken?  My imagination is failing me.

Note I am still proposing one series per state, just to omit the states that the pod was never in.

**Comment by bboreham** [comment]
Maybe "compute the percentage of pods that are in each state"?

**Comment by brian-brazil** [comment]
Yes, that'd break.
