### ISSUE TITLE
kube_pod_container_status_waiting_reason with Init:CrashLoopBackOff

### ISSUE THREAD

**Issue by rubendob** [kubernetes/kube-state-metrics#788]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
We can get the right values when some container gets stuck in ImagePullBackOff or ErrImagePull using this query:

`kube_pod_container_status_waiting_reason{reason=~"CrashLoopBackOff|ErrImagePull|ImagePullBackOff|Init:CrashLoopBackOff",namespace="prod-apo-api"} > 0`

but when it comes to another status like Init:0/1, Init:Error, Init:CrashLoopBackOff we can't get any value but 0. In our case, the pod is being created by a cronjob with deploy InitContainers and then other containers later.

**What you expected to happen**:
Get a value of 1 just like happens with ImagePullBackOff

```
Element | Value
-- | --
kube_pod_container_status_waiting_reason{app="kube-state-metrics",chart="kube-state-metrics-1.6.4",container="test-metrics",heritage="Tiller",instance="aks-default-28103052-4",job="kubernetes-service-endpoints",kubernetes_name="kube-state-metrics",kubernetes_namespace="default",namespace="prod-apo-api",pod="test-metrics",reason="ImagePullBackOff",release="kube-state-metrics"} | 1
```

So we can be aware when something happens with the InitContainers

```
apo-api-analitica-1560020400-bzshk   0/1       Init:0/1   1061      3d
apo-api-analitica-1560020400-bzshk   0/1       Init:Error   1061      3d
apo-api-analitica-1560020400-bzshk   0/1       Init:CrashLoopBackOff   1061      3d
```

**Environment**:
- Kubernetes version (use `kubectl version`):1.12.7-gke.10
- Kube-state-metrics image version:quay.io/coreos/kube-state-metrics:v1.6.0

**Comment by tariq1890** [comment]
The next release of `kube-state-metrics` will expose Init container statuses as well. Looks like your pod failed because of the initContainer not starting up successfully. 

Would querying the statuses of the initContainers directly work for you?

**Comment by rubendob** [comment]
Hi  @tariq1890 

excellent news then!

I think I can handle the issue with different query. In our particular environment, the cronjob launches a pod with initContainer and then after it completes successfully, second container is launched. So as the first container has errors eventually he got stuck in Init:CrashLoopBackOff

560416400-7bf2l    0/1     Init:CrashLoopBackOff   48         3h55m

and it seems we could handle this behaviour with query:
kube_pod_container_status_waiting{container="restartsender",namespace!~"default|kube-system|logging|monitoring|kube-public"} > 0

Anyway would be more elegant to detect problems with the Init:X status in next releases.

Thanks!
