### ISSUE TITLE
kube_deployment Metric is not populated when using v1.6.0.

### ISSUE THREAD

**Issue by VF-mbrauer** [kubernetes/kube-state-metrics#789]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
In our cluster `v1.13.4` the `kube_deployment` is not populated when using `v1.6.0`. I have tested both 1.5.0 and 1.6.0 with not other change in the cluster. I only edited the deployment and changed only the image version and found the same problem as observed above.
**What you expected to happen**:
`kube_deployment`should be part of the Metric which I can query for example in Prometheus.

**How to reproduce it (as minimally and precisely as possible)**:
Install Metrics v1.6.0 and go to Prometheus and check if this values getting populated.

**Anything else we need to know?**:

_collectors used:_
```
   - --collectors=configmaps
    - --collectors=cronjobs
    - --collectors=daemonsets
    - --collectors=deployments
    - --collectors=endpoints
    - --collectors=horizontalpodautoscalers
    - --collectors=jobs
    - --collectors=limitranges
    - --collectors=namespaces
    - --collectors=nodes
    - --collectors=persistentvolumeclaims
    - --collectors=persistentvolumes
    - --collectors=poddisruptionbudgets
    - --collectors=pods
    - --collectors=replicasets
    - --collectors=replicationcontrollers
    - --collectors=resourcequotas
    - --collectors=secrets
    - --collectors=services
    - --collectors=statefulsets
```

**Environment**:
- Kubernetes version (use `kubectl version`): **v1.13.4**
- Kube-state-metrics image version: **1.6.0**

**Comment by tariq1890** [comment]
What is the `apiVersion` of the deployment in your k8s cluster?

**Comment by VF-mbrauer** [comment]
apiVersion: `extensions/v1beta1`

**Comment by tariq1890** [comment]
Can you confirm if your `cluster-role` yaml is updated to allow for list/watch operations on deployments in the `apps` apiGroup?

You can check [here](https://github.com/kubernetes/kube-state-metrics/blob/e61670627018010350a963dcb4e276ac10a5d57f/kubernetes/kube-state-metrics-cluster-role.yaml#L29) to get an idea.

**Comment by VF-mbrauer** [comment]
This is an extract of the area you asked for:
```
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - list
  - watch
```
BUT, even when the `deployment`is missing under resources, why is it then working with v1.5.0 ?

**Comment by tariq1890** [comment]
because with `1.5.0` the deployments listWatch was created under the `extensions` apiGroup.

**Comment by VF-mbrauer** [comment]
OK, in Extensions it looks like this:
```
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - list
  - watch
```

**Comment by tariq1890** [comment]
Yes, so you can update the `apps` apiGroup to include `deployments` as a resource. Hopefully, that should solve your issue.

**Comment by tariq1890** [comment]
Generally, when you update the `kube-state-metrics` version, it is always recommended to use the updated kubernetes manifests that come with it. 

Alternatively, you could use the `kube-state-metrics` helm chart which comes packaged with all the kubernetes mainfests required to stand up a functional `kube-state-metrics` successfully on a k8s cluster.

You can find the helm chart [here](https://github.com/helm/charts/tree/master/stable/kube-state-metrics) .

**Comment by tariq1890** [comment]
@VF-mbrauer  Please confirm if this works for you so that we may close this issue.

**Comment by VF-mbrauer** [comment]
@tariq1890 Let me check on our side and come back to you asap. Thanks for now and the support so far.

**Comment by VF-mbrauer** [comment]
@tariq1890 We will put that as part of the new Deployment as standard in our YAML-Files. So issue can be closed. Again many Thanks for the great support. Cheers Maik
