### ISSUE TITLE
Collect componentstatuses info

### ISSUE THREAD

**Issue by sstarcher** [kubernetes/kube-state-metrics#79]
It would be nice to collect the health for the componentstatuses objects

**Comment by zouyee** [comment]
is it necessary to take the time to finish？ @brancz

**Comment by brancz** [comment]
it's an addition but nothing blocking 1.0

**Comment by zouyee** [comment]
https://github.com/kubernetes/kube-state-metrics/pull/219

**Comment by andyxning** [comment]
close via #219
