### ISSUE TITLE
The CI tools used by kube-state-metrics need version bumping.

### ISSUE THREAD

**Issue by tariq1890** [kubernetes/kube-state-metrics#790]
Kube-state-metrics uses a lot of tools for its continuous integration processes and many of them should be updated to their latest stable versions.

- Prometheus (E2E tests)
- Minikube (E2E tests)
- Kubernetes Version (E2E tests)
- Golangci-lint (Makefile)

/good-first-issue

**Comment by andyxning** [comment]
This is somewhat a good way for new contributors to learn and make a contribution. Let's wait this for about 3 days to see if someone can pick this up! :)

**Comment by brancz** [comment]
If possible maybe even moving away from minikube to kind as well as moving from Travis CI to prow.

**Comment by andyxning** [comment]
> If possible maybe even moving away from minikube to kind as well as moving from Travis CI to prow.

I agree. This would a big change and need more time.

**Comment by brancz** [comment]
That’s fair, yes.

**Comment by reetasingh** [comment]
@tariq1890 I will take this

**Comment by mxinden** [comment]
> as well as moving from Travis CI to prow.

Cross referencing the discussion with sig-release here: https://groups.google.com/forum/#!topic/kubernetes-sig-instrumentation/rq-Q0gbszyY
