### ISSUE TITLE
Wrong description about metrics-server in README.md

### ISSUE THREAD

**Issue by AvTiMp** [kubernetes/kube-state-metrics#794]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
In README, [it](https://github.com/kubernetes/kube-state-metrics#kube-state-metrics-vs-metrics-server) says 

> The metrics-server is a project that has been inspired by Heapster and is implemented to serve the goals of the Kubernetes Monitoring Pipeline

but according to [monitoring architecture](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/instrumentation/monitoring_architecture.md#executive-summary)

> A core metrics pipeline consisting of Kubelet, a resource estimator, a slimmed-down Heapster called metrics-server, and the API server serving the master metrics API

So the **metrics-server** project should be  implemented to serve the goals of **the core metrics pipeline**, or to server the goals of **Kubernetes monitoring architecture**

**What you expected to happen**:

 the **metrics-server** project should be  implemented to serve the goals of **the core metrics pipeline**, or to server the goals of **Kubernetes monitoring architecture**

**Comment by brancz** [comment]
Happy to have his be adapted, no strong opinion.

**Comment by tariq1890** [comment]
@AvTiMp Please feel free to submit a PR for this :).
