### ISSUE TITLE
Cutting kube-state-metrics 1.7.0

### ISSUE THREAD

**Issue by tariq1890** [kubernetes/kube-state-metrics#796]
As of this post, we have had 82 commits since the last release.

Given that we added some new resources (also about to add one more), we should definitely look at cutting a release. I propose that we cut a new release soon after a new version of kubernetes is out and we vendor that to kube-state-metrics.

Thoughts? @brancz @mxinden @andyxning @zouyee

**Comment by brancz** [comment]
sgtm :+1:

**Comment by andyxning** [comment]
lgtm. Kubernetes 1.15 has been released. https://github.com/kubernetes/kubernetes/releases/tag/v1.15.0. 

We can cut a new rc release for kube-state-metrics.

**Comment by tariq1890** [comment]
We need to wait for them to cut the 1.15 releases for api and apimachinery.

**Comment by brancz** [comment]
I’d say we should wait for the VPA metrics to land and 1.15 dependencies, then we cut 1.7

**Comment by kennethredler** [comment]
Any updates on 1.7 release ETA or work to be done to wrap this up?

**Comment by brancz** [comment]
I think we’re ready to go ahead.
