### ISSUE TITLE
The linter does not really catch all of the issues in kube-state-metrics.

### ISSUE THREAD

**Issue by tariq1890** [kubernetes/kube-state-metrics#800]
The Golangci linting tool that we use does not seem to perform a complete scan of the code base for reporting issues with the code quality.

See this [PR](https://github.com/kubernetes/kube-state-metrics/pull/799) for one such example.

**Comment by LiliC** [comment]
/remove-lifecycle stale

I will try to get to the linked PR next week hopefully, and take over, don't think that much needs to be done anyways.

**Comment by olivierlemasle** [comment]
Cf PR #1064 
/remove-help
