### ISSUE TITLE
Implement a readiness endpoint

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#810]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
Currently there is a healthz endpoint which implements somewhat liveness but is used as a readinessProbe in the kubernetes deployment files.
**What you expected to happen**:
A possible option would be to use the healthz endpoint as a path for livenessProbe and have a readyz endpoint for readiness checks.
Probably the readiness probe should return 200 if there is a connection to the cluster possible and should fail otherwise (not sure if the app becomes unhealthy otherwise or would just fail)

**Comment by brancz** [comment]
I think an initial probe to reach the API and then setting readiness would reasonable.

**Comment by Pothulapati** [comment]
I'm willing to take this issue, If its available :)

**Comment by tariq1890** [comment]
Yes please :)!
