### ISSUE TITLE
Support for openshift objects metrics

### ISSUE THREAD

**Issue by kalote** [kubernetes/kube-state-metrics#811]
/kind feature

**What happened**:
I'm working in an openshift context, with buildconfigs, deploymentconfigs and i would like to get metrics from it.

**What you expected to happen**:
In the `--collector` param, i would like to be able to provide openshift objects, such as buildconfigs, deploymentconfigs.

**How to reproduce it (as minimally and precisely as possible)**:
Run kube-state-metrics in openshift, try to get deploymentconfigs metrics. The supported `deployments` doesn't match openshift object.

**Anything else we need to know?**:
What can i do to help make this feature a reality?

**Comment by brancz** [comment]
There is already a dedicated project for this, it uses reusable parts of kube-state-metrics as a library :)

https://github.com/openshift/openshift-state-metrics

**Comment by kalote** [comment]
oh that's good :) thanks for the info.
