### ISSUE TITLE
Kube-state-metrics reports errros for deleted objects

### ISSUE THREAD

**Issue by mkjoerg** [kubernetes/kube-state-metrics#813]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I had a job that was failing and I deleted the job and after this the Pod. In another cluster I deleted a pod that had a sidecar inside that was not starting. 

Job Failed and was then removed:
![image](https://user-images.githubusercontent.com/12080409/60942019-5cd03100-a2e1-11e9-8e7b-7083e4018863.png)
![image](https://user-images.githubusercontent.com/12080409/60942035-6bb6e380-a2e1-11e9-8873-2b906373ba56.png)
![image](https://user-images.githubusercontent.com/12080409/60942043-72455b00-a2e1-11e9-84f2-efcd61d959c5.png)

Sidecar did not start a while:
![image](https://user-images.githubusercontent.com/12080409/60942262-52626700-a2e2-11e9-9c42-0440eba736f7.png)
![image](https://user-images.githubusercontent.com/12080409/60942283-5db59280-a2e2-11e9-9b24-58e6625f9be0.png)
![image](https://user-images.githubusercontent.com/12080409/60942291-660dcd80-a2e2-11e9-87e5-f93ba594054c.png)

Both scenarios were alerted through kube-state-metrics, but the system keeps alerting for this deleted resources.

**What you expected to happen**:

I expected no more alerts for already deleted pods.

**How to reproduce it (as minimally and precisely as possible)**:

It occured to me, when starting a pod with a sidecar that won't come up ( In my case an Istio sidecar) or a job that stucks in error and retries for a while. If I let them run for a while and then deleted them. Error is existing in two different clusters both using the same versions as mentioned below.

**Anything else we need to know?**:

I am using Kube state metrics with the default setup, installed by Helm by the Prometheus Operator Helm Chart.

I also tried restarting the kube-state-metrics pod.

**Environment**:
I am running on Azure Kubernetes (AKS) in version v1.13.5.

- Kubernetes version (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-20T04:49:16Z", GoVersion:"go1.12.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Kube-state-metrics image version: 1.6.0

**Comment by brancz** [comment]
Can you show us the graph of the query that produced the alerts over time? Also for the deployment could you share the full yaml (including status)?

**Comment by LiliC** [comment]
@mkjoerg Thanks for the bug report! Can you answer a few questions:
1. Did the alert resolve itself at some point?
2. Can you query the `/metrics` endpoint of kube-state-metrics directly next time you have this alert and include that as well. This will help us locate where the problem is exactly. Let me know if you need help on how to do that!

I had the same alert the `KubeStateMetricsReplicasMistmach` when using https://github.com/coreos/kube-prometheus manifests, but this was just now fixed in master so should be probably resolved for you as well, if you can retry that. If not please open an issue on that repo, thanks!

**Comment by mkjoerg** [comment]
At first the Graph:

![image](https://user-images.githubusercontent.com/12080409/60975242-f0c6ea80-a32b-11e9-8bc4-db456799e111.png)

1. No the alerts are firing constantly, after I restarted kube state metrics, it resolved one time and fired then again.

2. I crop it for the relevant metrics ok? If you need the full output, I can send it as well.
![image](https://user-images.githubusercontent.com/12080409/60975577-7ba7e500-a32c-11e9-9f38-b6042add58d9.png)

![image](https://user-images.githubusercontent.com/12080409/60975525-6f238c80-a32c-11e9-983a-4e331a1508e8.png)

Here the information to the deployment that is causing the alert:
```log
Name:                   jaeger-operator
Namespace:              mdr-int
CreationTimestamp:      Fri, 21 Jun 2019 13:16:29 +0200
Labels:                 app.kubernetes.io/instance=jaeger-operator
                        app.kubernetes.io/managed-by=Tiller
                        app.kubernetes.io/name=jaeger-operator
                        flux.weave.works/sync-gc-mark=sha256.mCrb-a-v4XCQzHcw5mlzz9_dbIeIMLTq6yU-oyTDpiw
                        helm.sh/chart=jaeger-operator-2.6.0
Annotations:            deployment.kubernetes.io/revision: 2
                        flux.weave.works/sync-checksum: eed2d0dfdc0a13b745fe6fcae9ef93668fd3f065
                        kubectl.kubernetes.io/last-applied-configuration:
                          {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"flux.weave.works/sync-checksum":"eed2d0dfdc0a13b745fe6fcae9ef93668...
Selector:               app.kubernetes.io/instance=jaeger-operator,app.kubernetes.io/name=jaeger-operator
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:           app.kubernetes.io/instance=jaeger-operator
                    app.kubernetes.io/managed-by=Tiller
                    app.kubernetes.io/name=jaeger-operator
                    helm.sh/chart=jaeger-operator-2.6.0
  Annotations:      sidecar.istio.io/inject: false
  Service Account:  jaeger-operator
  Containers:
   jaeger-operator:
    Image:      jaegertracing/jaeger-operator:1.11.0
    Port:       8383/TCP
    Host Port:  0/TCP
    Args:
      start
    Limits:
      cpu:     100m
      memory:  128Mi
    Requests:
      cpu:     100m
      memory:  128Mi
    Environment:
      WATCH_NAMESPACE:   (v1:metadata.namespace)
      POD_NAME:          (v1:metadata.name)
      OPERATOR_NAME:    jaeger-operator
    Mounts:             <none>
  Volumes:              <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   jaeger-operator-84bdd479f7 (1/1 replicas created)
Events:          <none>
```

And here as yaml including state:
```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    flux.weave.works/sync-checksum: eed2d0dfdc0a13b745fe6fcae9ef93668fd3f065
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"flux.weave.works/sync-checksum":"eed2d0dfdc0a13b745fe6fcae9ef93668fd3f065"},"labels":{"app.kubernetes.io/instance":"jaeger-operator","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"jaeger-operator","flux.weave.works/sync-gc-mark":"sha256.mCrb-a-v4XCQzHcw5mlzz9_dbIeIMLTq6yU-oyTDpiw","helm.sh/chart":"jaeger-operator-2.6.0"},"name":"jaeger-operator","namespace":"mdr-int"},"spec":{"replicas":1,"selector":{"matchLabels":{"app.kubernetes.io/instance":"jaeger-operator","app.kubernetes.io/name":"jaeger-operator"}},"template":{"metadata":{"annotations":{"sidecar.istio.io/inject":"false"},"labels":{"app.kubernetes.io/instance":"jaeger-operator","app.kubernetes.io/managed-by":"Tiller","app.kubernetes.io/name":"jaeger-operator","helm.sh/chart":"jaeger-operator-2.6.0"},"name":"jaeger-operator"},"spec":{"containers":[{"args":["start"],"env":[{"name":"WATCH_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}},{"name":"POD_NAME","valueFrom":{"fieldRef":{"fieldPath":"metadata.name"}}},{"name":"OPERATOR_NAME","value":"jaeger-operator"}],"image":"jaegertracing/jaeger-operator:1.11.0","imagePullPolicy":"IfNotPresent","name":"jaeger-operator","ports":[{"containerPort":8383,"name":"metrics"}],"resources":{"limits":{"cpu":"100m","memory":"128Mi"},"requests":{"cpu":"100m","memory":"128Mi"}}}],"serviceAccountName":"jaeger-operator"}}}}
  creationTimestamp: "2019-06-21T11:16:29Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: jaeger-operator
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: jaeger-operator
    flux.weave.works/sync-gc-mark: sha256.mCrb-a-v4XCQzHcw5mlzz9_dbIeIMLTq6yU-oyTDpiw
    helm.sh/chart: jaeger-operator-2.6.0
  name: jaeger-operator
  namespace: mdr-int
  resourceVersion: "2126606"
  selfLink: /apis/extensions/v1beta1/namespaces/mdr-int/deployments/jaeger-operator
  uid: 0440cd7e-9416-11e9-bff3-8278771c0872
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: jaeger-operator
      app.kubernetes.io/name: jaeger-operator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: jaeger-operator
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: jaeger-operator
        helm.sh/chart: jaeger-operator-2.6.0
      name: jaeger-operator
    spec:
      containers:
      - args:
        - start
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: jaeger-operator
        image: jaegertracing/jaeger-operator:1.11.0
        imagePullPolicy: IfNotPresent
        name: jaeger-operator
        ports:
        - containerPort: 8383
          name: metrics
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: jaeger-operator
      serviceAccountName: jaeger-operator
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-06-21T11:16:29Z"
    lastUpdateTime: "2019-06-21T11:24:19Z"
    message: ReplicaSet "jaeger-operator-84bdd479f7" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-06-24T06:22:31Z"
    lastUpdateTime: "2019-06-24T06:22:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
```

**Comment by brancz** [comment]
I'm curious, are the other deployments in this cluster apps/v1 or apps/v1beta2, instead of extensions/v1beta1? (I'm trying to understand the difference in this one and the others)

**Comment by mkjoerg** [comment]
As far as I can see, they are all still apiVersion: extensions/v1beta1

```log
k get deploy authservice -o yaml | grep apiVersion:
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
- apiVersion: extensions/v1beta1
```

maybe something I should tackle soon :)

**Comment by LiliC** [comment]
@mkjoerg I can see the `jaeger-operator` number match in the kube-state-metrics data to the data you pasted directly from kubernetes.

@brancz you agree with the above ^

> No the alerts are firing constantly, after I restarted kube state metrics, it resolved one time and fired then again.

Can you restart prometheus pods to see if this fixes it? Can you also paste the logs from kube-state-metrics pods. Thanks!

**Comment by LiliC** [comment]
@mkjoerg after looking at this again, it seems like you have two `jaeger-operator ` deployed, one in the `default` ns and the other in the `mdr-int `, can you verify that the `default` ns one is at 0 replicas like it says in kube-state-metrics output.

**Comment by mkjoerg** [comment]
@LiliC you are right, I didn't notice that there was a faulty deployment in the default namespace. I must have accidentally deployed it to the wrong namespace and wasn't looking close enough to the labels. Sry for the false alert and thank you for the effort. Closing this now.

**Comment by LiliC** [comment]
@mkjoerg no worries at all!

**Comment by mkjoerg** [comment]
@LiliC Thank you for the quick responses! You guys doing a great job here ☺️
