### ISSUE TITLE
Support for node CPU hyperthreading metric

### ISSUE THREAD

**Issue by chambridge** [kubernetes/kube-state-metrics#817]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

I'm not sure how this should work; but it would be useful to have a metric or label added to node cpu/core metrics that indicates if the cpu has hyperthreading and is it enabled. This can be valuable in reporting and potentially capacity planning scenarios.

**Comment by brancz** [comment]
Does the Kubernetes API expose this in some way? I think this might be more suitable to be done through the Prometheus node-exporter.

**Comment by chambridge** [comment]
/close

As suggest this was done in node_exporter:
https://github.com/prometheus/node_exporter/pull/1489
