### ISSUE TITLE
Support for job_status_duration_time metrics

### ISSUE THREAD

**Issue by int-tt** [kubernetes/kube-state-metrics#821]
/kind feature

**What happened**:
I feel worthwhile to be able to get the  duration time of the job.
**What you expected to happen**:
For example, by continuously monitoring the duration time of jobs generated from Cronjob, you can notice performance degradation and unintended long-term execution.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Ready for implementation :)
https://github.com/int-tt/kube-state-metrics/commit/a3a4a2468dd1d41384b7a9da39d4acce48fbf4f2
**Environment**:

**Comment by brancz** [comment]
Is this exposed by the Kubernetes API? If so happy to have it be added!

**Comment by tariq1890** [comment]
@brancz Yes it is! Please feel free to submit a PR @int-tt :)

**Comment by RajatVaryani** [comment]
Hello. Should we still add this? We can get the duration time by `kube_job_status_completion_time - kube_job_status_start_time`.
