### ISSUE TITLE
How to collect pod GPU limits/requests from pod metrics

### ISSUE THREAD

**Issue by Cherishty** [kubernetes/kube-state-metrics#824]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:
In the former version (e.g. k8s 1.9.5), I was using `kube_pod_container_resource_requests_nvidia_gpu_devices` as well as `kube_pod_container_resource_limits_nvidia_gpu_devices` to collect the `alpha.kubernetes.io/nvidia-gpu`(provided by feature-gate accelerate) limits/requests from a pod, which works well for me.

However, when upgrading to 1.14, the limits/requests of gpu have changed to `nvidia.com/gpu` (provided by nvidia-docker and device-plugin)

I know from kube-state-metrics 1.4,  these metrics are **NOT** provided as [Metrics Documentation](https://github.com/kubernetes/kube-state-metrics/blob/master/README.md#metrics-documentation) claims, but 1.2 can still **NOT** work for `nvidia.com/gpu`  to collect these metrics.  

So I do wonder why they are not provided, and what's the `alternatives`

**What you expected to happen**:
collect pod GPU limits/requests from pod metrics

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.2
- Kube-state-metrics image version v1.2.0

**Comment by tariq1890** [comment]
GPU metrics pertain to a particular vendor and it is recommended as a k8s best practice to make use of device plugins for the managing the life cycle and monitoring of these pods. You can consider using nvidia's pod gpu metrics exporter for getting the metrics in your case.
https://github.com/NVIDIA/gpu-monitoring-tools/blob/master/exporters/prometheus-dcgm/README.md

**Comment by tariq1890** [comment]
@Cherishty Please let me know if this helps so that we may close this issue.

**Comment by Cherishty** [comment]
Yes, it is reasonable and feel free to close it~
