### ISSUE TITLE
Feature request: include pod annotations

### ISSUE THREAD

**Issue by sayarg** [kubernetes/kube-state-metrics#826]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

Hi

There have been a few requests in the past to add annotations, they seem to have been left to rotten and were closed. Are there any current plans to add pod annotations? Alternatively, would you be supportive of a PR to optionally enable annotations on pods.

Found these issues with similar requests: https://github.com/kubernetes/kube-state-metrics/issues/574, https://github.com/kubernetes/kube-state-metrics/issues/250

**Comment by tariq1890** [comment]
@sayarg This feature will be available in 1.7 release of kube-state-metrics. Please feel free to test this feature out with the 1.7 [release candidate](https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.7.0-rc.1) which we had published a week ago.

**Comment by tariq1890** [comment]
@brancz Do you remember why pod annotations weren't included in this PR #770 ? Is this because of a potential cardinality problem?

**Comment by sayarg** [comment]
Hi @tariq1890 will it be supported? I had a notification about a comment from you that it is part of 1.7 and is in the rc, but I don't see the comment. Or have you decided to not include pod in the annotation feature?

**Comment by tariq1890** [comment]
@sayarg I commented that by mistake (sorry :() which is why I had deleted it. It will not be supported.

**Comment by sayarg** [comment]
hi @tariq1890 no worries. how about enabling only for selected annotations? in the config you'd need to opt in the exact annotations you wish to report, to avoid the scale issue and specifically the annotation that is used to keep trail of pod changes.
