### ISSUE TITLE
Link to the gcr.io container on readme

### ISSUE THREAD

**Issue by andrewhowdencom** [kubernetes/kube-state-metrics#83]
Suggest linking to gcr.io/google_containers/kube-state-metrics:v0.3.0 on README. That's what CoreOS are doing. 

https://github.com/coreos/kube-prometheus/blob/master/manifests/exporters/kube-state-metrics-depl.yaml#L14

**Comment by brancz** [comment]
I definitely agree, we're in the middle of doing a release, so we'll add that right after we're done with the release.
