### ISSUE TITLE
kube state metrics shows it's data in all metrics

### ISSUE THREAD

**Issue by Swetad90** [kubernetes/kube-state-metrics#837]
I am using the below versions:
Kubernetes : v1.13.5
kube state metrics : v1.6.0
prometheus: 2.8.1

Any of the metrics given kube-state-metrics gives the below 3 labels of itself:
k8s_app="kube-state-metrics"
kubernetes_namespace="kube-system"
kubernetes_pod_name="kube-state-metrics-74f9f4ddb9-ghxbx"
pod_template_hash="74f9f4ddb9"

Whereas the labels 'namespace' and 'pod' contains the actual data.

For eg:
kube_pod_container_info{container="mytest",container_id="docker://550ffeadadf858731a72ef84c523b07cfaea09d06ddac277e46d11985355b6a3",image="mytest:0.0.72",image_id="docker-pullable://mytest@sha256:1194fd20ce5a2573882b54b571ab9ac3bdabedb554ded6d9be08181e23ae3bcd",instance="staging-node",job="up-dmz-pods",k8s_app="kube-state-metrics",kubernetes_namespace="kube-system",kubernetes_pod_name="kube-state-metrics-74f9f4ddb9-ghxbx",namespace="myactualns",pod="mytest-f67f7fb98-p6z2d",pod_template_hash="74f9f4ddb9"}

Is this expected behaviour or Am I missing anything ?

**Comment by brancz** [comment]
That's your target configuration on Prometheus side, those labels are not produced by kube-state-metrics.

**Comment by Swetad90** [comment]
Thank you.

That was the case. For all the dropped targets, it was by default picking up kube state metrics name/namespace/template hash in the metrics name.
