### ISSUE TITLE
How do I connect remotely?

### ISSUE THREAD

**Issue by carrot-dev** [kubernetes/kube-state-metrics#845]
Hi 

# kubectl get svc  -A 
NAMESPACE     NAME                   TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes             ClusterIP   10.233.0.1      <none>        443/TCP                  24d
kube-system   coredns                ClusterIP   10.233.0.3      <none>        53/UDP,53/TCP,9153/TCP   24d
kube-system   kube-state-metrics     ClusterIP   10.233.35.115   <none>        8080/TCP,8081/TCP        4d
kube-system   kubernetes-dashboard   ClusterIP   10.233.39.107   <none>        443/TCP                  24d

I deployed kube-state-metric , but they have only cluster-IP (10.233.35.115 ), so I can't access by remote.
How to do solve it? I have to collect metric by remote machine.

Thanks

**Comment by LiliC** [comment]
@carrot-dev Best thing you can have a look at is creating an [`Ingress`](https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource) per pod. Also, make sure to secure your metric endpoints.

**Comment by MIBc** [comment]
Create a node-port service for kube-state-metric
