### ISSUE TITLE
Add lifecycle failed reason  to pod waiting reason

### ISSUE THREAD

**Issue by pigletfly** [kubernetes/kube-state-metrics#849]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

I think we should add a reason for lifecycle hook when it fails,as below:
```
state:
    waiting:
    message: 'Exec lifecycle hook ([/bin/sh -c /data/poststart.sh])
        for Container "retail-stock-scm" in Pod "test-78f7dcbf75-47f28_daily(7940c259-af33-11e9-9622-525400df97ed)"
        failed - error: command '/bin/sh -c /data/preload.sh'
        exited with 124: , message: ""'
    reason: 'PostStartHookError: command '/bin/sh -c /data/poststart.sh'
        exited with 124: '
```

**Comment by LiliC** [comment]
@pigletfly If I understand correctly you want to add the `PostStartHookError` to the `kube_pod_container_status_waiting_reason` metric?

**Comment by pigletfly** [comment]
Yes, you got it.Now we have `{"ContainerCreating", "CrashLoopBackOff", "CreateContainerConfigError", "ErrImagePull", "ImagePullBackOff", "CreateContainerError", "InvalidImageName"} 
`for kube_pod_container_status_waiting_reason, the poststart hook failure is not included.

**Comment by LiliC** [comment]
@pigletfly I think the main reason why there is a limited amount of metrics about pods and containers is they scale with other resources. Which is why we are limited to that list.

Is `PostStartHookError` something you would alert on?

**Comment by pigletfly** [comment]
@LiliC I want to keep an eye on `PostStartHookError` state, and there won't be many metrics.I think `PostStartHookError` state is important, should exported as a metric.

**Comment by brancz** [comment]
I'm a little wary of having this grow even more. I'm trying to understand if we could group these states into healthy and unhealthy ones, as this list of reasons doesn't seem to stop growing.

**Comment by pigletfly** [comment]
It needn't to list all concrete reasons for PostStartHookError state,just give a metric that indicates there is a `PostStartHookError` in `kube_pod_container_status_waiting_reason`, because PostStart Hook varies, maybe it's a bash shell or a TCP probe. @brancz

**Comment by brancz** [comment]
I think I can get on board with `PostStartHookError` being added, but any further detail would need to rather be described by a runbook or something, that level of detail doesn't belong in metrics.

**Comment by pigletfly** [comment]
OK, will to create a PR to add `PostStartHookError` metric.
