### ISSUE TITLE
Provide binary for releases 

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/kube-state-metrics#85]
Hello,

It would be great if community could provide Linux/amd64 binaries for releases.

Thoughts ?

**Comment by brancz** [comment]
I am completely for this, however, it would have to be completely automated and as far as I understand this is part of the effort of opening up google's internal release process to non google maintainers.

/cc @saad-ali @grodrigues3 @piosz @david-mcmahon

**Comment by andyxning** [comment]
@rvrignaud I am not sure whether you want release binaries or release images.

As for release binaries, maybe #153 will fully accomplish your requirement.

**Comment by brancz** [comment]
As mentioned in the PR, I don't think we will start releasing binaries, until google opens up the release process to us. For the time being it will just be amd64 container images that are published on gcr by google people and on quay by me or @fabxc.

**Comment by grodrigues3** [comment]
@kubernetes/sig-release-feature-requests

**Comment by coffeepac** [comment]
@brancz is this the issue you were talking about during sig-inst today, re: opening the build process?

**Comment by brancz** [comment]
@coffeepac yes this, [this](https://github.com/kubernetes/kube-state-metrics/pull/134) and [this](https://github.com/kubernetes/kube-state-metrics/pull/246). They all revolve around the same topic, essentially how can we as non-Googlers do releases independently.
