### ISSUE TITLE
Add support for mutatingwebhookconfigurations and validatingwebhookconfigurations

### ISSUE THREAD

**Issue by natalysheinin** [kubernetes/kube-state-metrics#853]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

In the [list of the metrics](https://github.com/kubernetes/kube-state-metrics/tree/master/internal/store) available, there are no metrics available for the k8s resources `mutatingwebhookconfigurations` and `validatingwebhookconfigurations`.

**What you expected to happen**:
I'm hoping that there will be metrics available about this resource similar to what is available for [configmaps](https://github.com/kubernetes/kube-state-metrics/blob/master/docs/configmap-metrics.md)

**Environment**:
Doesn't matter because it's not available on master anyways.

**Comment by brancz** [comment]
Makes sense. Happy to have these!
