### ISSUE TITLE
Namespace memory/cpu quota metrics

### ISSUE THREAD

**Issue by mrueg** [kubernetes/kube-state-metrics#855]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:

Namespaces can have a quotas for CPU, Memory and Pods: https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/cpu-default-namespace/
**What you expected to happen**:

Have a metric for each per namespace
https://github.com/kubernetes/kube-state-metrics/blob/master/docs/namespace-metrics.md

**How to reproduce it (as minimally and precisely as possible)**:

-

**Anything else we need to know?**:

Provide an estimate on the difficulty for this. I might want to PR it myself.

**Environment**:

- Kubernetes version (use `kubectl version`): 1.13.8
- Kube-state-metrics image version: 1.7.1

**Comment by tariq1890** [comment]
Hi @mrueg . What about the resourcequota metrics : https://github.com/kubernetes/kube-state-metrics/blob/master/docs/resourcequota-metrics.md ?

**Comment by mrueg** [comment]
thanks! I missed those. :)
