### ISSUE TITLE
Annotation metrics

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#864]
As discussed in https://github.com/kubernetes/kube-state-metrics/issues/854 and offline we want to have only specific annotation metrics, we mentioned those good candidates for now are:

• deployment revision
• ingress class

This issue is to discuss the design and what we want to include in the metric, etc. There were a couple of ideas in the above-mentioned issue.

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**Comment by tariq1890** [comment]
I also want to point out that the higher significance and importance of these fields, the lesser the justification of these fields to be actually exposed as annotations. I think we must be mindful of this as well and redirect the question to the k8s.io/api folks when appropriate.

**Comment by davidkarlsen** [comment]
+1 another usecase:
Use kube-state-metrics' kube_pod_container_status_restarts_total for alerting frequent container-restarts *) and use annotations to route to the correct team in alert-manager. Annotations can contain characters which label values cannot:
* #: used for slack-channels
* @ used for slack-users
* , to deliver to a comma-delimited list of opsgenie-teams.
I don't see why this is any more problematic than the kube_pod_labels metric, especially as an opt-in metric/feature.


*)
```
(increase(kube_pod_container_status_restarts_total[1h]) > 5) * on (namespace, pod) group_left(label_my_org_com_opsgenieteam) kube_pod_labels
```
