### ISSUE TITLE
Migrate to prow

### ISSUE THREAD

**Issue by LiliC** [kubernetes/kube-state-metrics#865]
Majority of projects in k8s have migrated away from Travis.

As discussed on #prow on k8s slack:

> If you use Prow, you are able to `/retest` for instance, and we can make stronger guarantees about merging
> Today, `tide` will ensure that all jobs pass against the latest version of your PR as well as the latest version of the branch you want to merge into

Besides the above, it would be good to have this because it enables us to tackle including the benchmark results as a comment in each PR see https://github.com/kubernetes/kube-state-metrics/issues/838 for details.

**Comment by brancz** [comment]
For benchmarking the Prometheus project is currently looking at using GitHub actions. I imagine that could be a good fit here as well for portability reasons.

**Comment by tariq1890** [comment]
I am leaning more towards @brancz ‘s suggestion. I am just not a fan of prow’s CI workflow (or even bazel)

**Comment by LiliC** [comment]
Closing this as we don't need to move to prow.
/close
