### ISSUE TITLE
 kube_daemonset_status_number_ready vs kube_daemonset_status_current_number_scheduled

### ISSUE THREAD

**Issue by kkbrat9** [kubernetes/kube-state-metrics#871]
I am trying to understand the difference between kube_daemonset_status_current_number_scheduled & kube_daemonset_status_number_ready. Feels like both are similar from usage perspective. 

One rule i am trying write is to difference in number desired state for a given daemonset vs number scheduled or ready. Is there something obvious i am missing ?

**Comment by kkbrat9** [comment]
I think there are 3 things right ?

kube_daemonset_status_desired_number_scheduled
kube_daemonset_status_current_number_scheduled
kube_daemonset_status_number_ready

number_ready is clear that current pods up and running but scheduled and desired not the same ?

**Comment by tariq1890** [comment]
For Current Number Scheduled - We count the number of nodes that have at least 1 daemon pod running in them.

For Number Ready -  The daemon pods are required to be "running" and "ready" (i.e passing readiness probes) when counting the number of nodes that run a daemon pod.

This is the godoc:

```
type DaemonSetStatus struct {
	// The number of nodes that are running at least 1
	// daemon pod and are supposed to run the daemon pod.
	// More info: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/
	CurrentNumberScheduled int32 `json:"currentNumberScheduled" protobuf:"varint,1,opt,name=currentNumberScheduled"`

...
....
...

	// The number of nodes that should be running the daemon pod and have one
	// or more of the daemon pod running and ready.
	NumberReady int32 `json:"numberReady" protobuf:"varint,4,opt,name=numberReady"`
```
