### ISSUE TITLE
Kubernetes config map labels

### ISSUE THREAD

**Issue by erihanse** [kubernetes/kube-state-metrics#873]
Is there no metric for kubernetes config map labels? We'd like to use those to do queries regarding helm upgrades/installs. Helm labels configmaps to keep track of helm release revisions, and it would be nice to visualize those in grafana.

**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind feature

**Environment**:
- Kube-state-metrics image version: kube-state-metrics:1.6.0

**Comment by LiliC** [comment]
@erihanse Those metrics would produce a high unbound cardinality as the labels can be anything, which is why we do not include them.

If you just need to visualize things, you can always use one of the k8s UIs which displays Resources including ConfigMaps.

**Comment by erihanse** [comment]
But you have metrics for alot of other labels:
![image](https://user-images.githubusercontent.com/9251274/63951201-9de0f800-ca7d-11e9-908f-5ee484077697.png)
What's the difference?

**Comment by LiliC** [comment]
Helm intentionally creates a lot of ConfigMaps for each release, so this would produce a lot of metrics.

Also not sure it would actually work to visualize the labels from helm releases, I could be wrong but but those labels with release values are strings and you can't really do a string comparison in prometheus.

**Comment by LiliC** [comment]
cc @tariq1890 @brancz for further discussions.

**Comment by brancz** [comment]
Yeah I see where you’re coming from, but @LiliC is right. Anything useful you could to with configmap labels would require parsing the label values into a metric value which would be a non standard thing to do in kube state metrics. I think what you’re looking for would be something like a helm exporter.

**Comment by erihanse** [comment]
Yeah, I've looked into helm-exporter as well. Not sure we can achieve what we want with it though.

So this is our use-case:
What we actually need is to have some sort of overview of who has made a helm install/upgrade and when (and maybe why). Helm itself doesn't support custom labels, so there's no way we can attach this information when we run the command. I could be wrong but the only way we could put some metadata on the different revisions without building something ourself is by using the configmaps created by helm for revisioning. We could label those for instance like this:
`kubectl label cm deploy-bot-test.v4 deployer=erik` and make a dashboard showing for instance the 10 last helm modifications on a release.

**Comment by erihanse** [comment]
With cm labels I could display more columns in this view:
![image](https://user-images.githubusercontent.com/9251274/64002108-95360380-cb09-11e9-978c-7c87ed95b000.png)

**Comment by kminehart** [comment]
@LiliC @brancz  definitely agreed on the higher unbound cardinality, but it's not any more volatile than the existing `{foobar}_labels` metrics. If kube-state-metrics is exposing `kube_deployment_labels`, `kube_pod_labels`, and so on, then I don't see any reason to exclude `kube_configmap_labels`. If another popular service comes along and starts to include a lot of labels onto managed deployments, would it then be removed from this project?

i'd be happy to make a PR for this and maybe the discussion can continue there.

**Comment by brancz** [comment]
I agree that probably none of them should have it, and any label exposed should probably be whitelisted. The other label metrics are already there and I think too many people rely on them at this point that we can remove them. But this is something that I would consider changing for the 2.0 release.

**Comment by brancz** [comment]
cc @LiliC @tariq1890

**Comment by gpoirier** [comment]
Using labels is absolutely essential to how we match use pod metrics to their deployment and to figure out which team should get alerts. I don't understand why they should go away, and they generally don't change during the lifespan of a pod. Similarly, I don't quite see the issue on adding labels to configmap, which I would like to use for detecting helm failures.

**Comment by kminehart** [comment]
Good question. The problem is that these `{resource}_{labels}` metrics are very high in cardinality and massively contribute to slow queries.

You can read more about it on Brian Brazil's blog (one of the original creators & current maintainers of Promethues). https://www.robustperception.io/cardinality-is-key

**Comment by lilic** [comment]
/remove-lifecycle rotten

still relavant

**Comment by pavel-khritonenko** [comment]
I have a similar issue for PodDisruptionBudget labels - would like to have labels like "team" and "environment" attached to that resource, to send alert to the appropriate team, when a particular PDB violated.
