### ISSUE TITLE
Feature Request : have the port as a label for endpoint metrics

### ISSUE THREAD

**Issue by arnaudlemaignen** [kubernetes/kube-state-metrics#876]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

**What happened**:
Today the endpoint metrics are collecting a single value summing all endpoints for all ports of the service
https://github.com/kubernetes/kube-state-metrics/blob/master/docs/endpoint-metrics.md

but in case you have several ports in the service you want to know the number of available endpoints **by port**, especially if you have a service SLA based on it

**What you expected to happen**:
have the port as a label in all endpoint metrics
kube_endpoint_address_not_ready{endpoint="test_svc",**port="8080"**,namespace="test_namespace"}
kube_endpoint_address_available{endpoint="test_svc",**port="8080"**,namespace="test_namespace"}
kube_endpoint_info{endpoint="test_svc",**port="8080"**,namespace="test_namespace"}
kube_endpoint_labels{endpoint="test_svc",**port="8080"**,namespace="test_namespace"}
kube_endpoint_created{endpoint="test_svc",**port="8080"**,namespace="test_namespace"}

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
kubernetes v1.6.1+5115d708d7
- Kube-state-metrics image version
kube-state-metrics:v1.5.0

**Comment by brancz** [comment]
Does the `Endpoints` object expose this information in its API object?

**Comment by arnaudlemaignen** [comment]
Sorry can you explain how can I check this?

at kubectl/oc level we have the info at service level

oc describe svc my-service
Name:            my-service
Namespace:        my-namespace
Labels:            <none>
Selector:        app=my-service
Type:            ClusterIP
IP:            172.30.62.142
**Port:            rmi-1099-tcp    1099/TCP**
**Endpoints:        172.16.23.175:1099**
Port:            http-8080-tcp    8080/TCP
Endpoints:        172.16.23.175:8080

thks

**Comment by tariq1890** [comment]
Currently, we only expose the count of `addresses` * `ports` for an endpoint as a metric.

The API Object field is [here](https://github.com/kubernetes/api/blob/master/core/v1/types.go#L4149)

**Comment by arnaudlemaignen** [comment]
thanks
so you do have the port in EndpointPort.
Can it be implemented?

If you don't want to have a breaking change it can be done in new metric names like
kube_endpoint_address_not_ready_by_port{endpoint="test_svc",port="8080",namespace="test_namespace"}
kube_endpoint_address_available_by_port{endpoint="test_svc",port="8080",namespace="test_namespace"}
kube_endpoint_info_by_port{endpoint="test_svc",port="8080",namespace="test_namespace"}
kube_endpoint_labels_by_port{endpoint="test_svc",port="8080",namespace="test_namespace"}
kube_endpoint_created_by_port{endpoint="test_svc",port="8080",namespace="test_namespace"}

**Comment by brancz** [comment]
That information is not available in that structure in the API. I suggest you to join that information at query time.

**Comment by sohaib-rafay** [comment]
As of today, do we have any metrics which stores service ports information?
for example, say my service type is NodePort using port 8080. Is there any way to get this info using kube-state-metrics?
