### ISSUE TITLE
deployment condition metrics

### ISSUE THREAD

**Issue by terinjokes** [kubernetes/kube-state-metrics#886]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind feature

**What happened**:

A deployment rollout stalled, no metrics from Kube State Metrics made this condition clear.

**What you expected to happen**:

KSM to have deployment status conditions available, similar to node status conditions.

```
kube_deployment_status_condition{deployment="example", namespace="default", condition="ReplicaFailure", status="true"} 1
```

**How to reproduce it (as minimally and precisely as possible)**:

Look at the metrics produced by KSM and see no deployment status conditions are created.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version: v1.6.0

**Comment by terinjokes** [comment]
I don't mind implementing this, if the feature request seems sound.

**Comment by LiliC** [comment]
@terinjokes thanks for the feature. Sounds reasonable at first glance, do we know if the conditions are a predefined list, or can they include any error that occurs in deployment creation? Just trying to avoid unbound high cardinality metrics.

**Comment by terinjokes** [comment]
@LiliC Based on the [source code](https://github.com/kubernetes/kubernetes/blob/v1.15.3/staging/src/k8s.io/api/apps/v1/types.go#L417-L430), there are three well-known conditions. These are also the only three I've seen in practice.

Is that a reasonable amount of additional cardinality?

**Comment by tariq1890** [comment]
This seems reasonable to me @terinjokes . Feel free to send in a PR.
