### ISSUE TITLE
Makefile tip

### ISSUE THREAD

**Issue by andrewhowdencom** [kubernetes/kube-state-metrics#89]
You can get the latest git tag in the makefile as follows:

```
# http://stackoverflow.com/questions/1404796/how-to-get-the-latest-tag-name-in-current-branch-in-git
TAG := $(shell git describe --abbrev=0)
```

**Comment by andyxning** [comment]
@andrewhowdencom Awesome. 👍 Can you please make a PR improving tag variable getting.

/ping @brancz

**Comment by brancz** [comment]
sgtm

**Comment by brancz** [comment]
In fact I might pick this up pretty soon, as the current tag in the `Makefile` is outdated.
