### ISSUE TITLE
[feature-request] NetworkPolicy metrics

### ISSUE THREAD

**Issue by milesbxf** [kubernetes/kube-state-metrics#891]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:

Kubernetes has [NetworkPolicy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) objects to control how pods communicate with each other. We'd find it very useful to have kube-state-metrics on these.

We probably wouldn't want to try and export the whole spec (with ingress/egress rules, ip specs, pod selectors etc.), at least not initially - but it'd be useful to export the following information as a starting point:
* `kube_networkpolicy_info` (with metadata)
* `kube_networkpolicy_rules` (count of ingress/egress rules, switched by label)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- Kube-state-metrics image version

Unless there are any existing efforts, I'd be happy to take this on :)

**Comment by brancz** [comment]
I think there was a previous attempt but it was abandoned, at least I'm not aware of anyone actively working on this. Contributions welcome! :)

**Comment by milesbxf** [comment]
> I think there was a previous attempt but it was abandoned, at least I'm not aware of anyone actively working on this. Contributions welcome! :)

https://github.com/kubernetes/kube-state-metrics/pull/893 🙂
