### ISSUE TITLE
Clarify and document stability guarantees for new metrics 

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#892]
Currently, all new metrics get the STABLE status, we tend to only mark metrics are not stable when the resource is not GA, from what I can tell.

I would suggest to instead start with all new metrics in a not stable version, not sure experimental is the right word for that. This gives us some time to catch any problems and change any labels or remove metrics. After some period of time, we can graduate those metrics into a stable status.

This goes also in line with what the SIG instrumentation is doing with kubernetes metrics stability.

cc @tariq1890 @brancz thoughts?

**Comment by brancz** [comment]
> This goes also in line with what the SIG instrumentation is doing with kubernetes metrics stability.

I think this is the key here. We should make sure that we align the messaging, wording, etc. with the metrics stability framework. There the wording is rather just "alpha" and "stable". There are no set rules for what goes in what category but we have a much better idea in kube-state-metrics as the values rely on APIs that already have maturity levels. I think roughly that means metrics in kube-state-metrics must be aligned with the maturity level of the API it relies on.

**Comment by tariq1890** [comment]
This was what I had in mind as well. So I agree with @brancz

> I think roughly that means metrics in kube-state-metrics must be aligned with the maturity level of the API it relies on.

**Comment by brancz** [comment]
Sorry just for clarification, what I meant is:

* Metrics that are based on non-GA API objects cannot be in stable state
* Metrics that _are_ based GA API object _could_ be introduced as non-stable state, because we have gotten naming/labeling wrong a number of times even if the API object was stable (thinking Pod and Node API for example)

So basically only if based on a GA API _and_ gone through some vetting, can a metric become stable.

**Comment by tariq1890** [comment]
What would vetting mean in this context? Do you mean letting a metric bake over a couple of releases?

**Comment by brancz** [comment]
Precisely.

**Comment by tariq1890** [comment]
Sounds good to me :). Thanks for starting this thread @LiliC .

**Comment by LiliC** [comment]
> Do you mean letting a metric bake over a couple of releases?

Yes, I think that might help us prevent some wrong metrics, like labels, or just any high cardinality we can't catch etc. And makes it easier for us to remove metrics.


> Let's decide on specific timelines then. For e.g:- How to long wait until a metric graduate to STABLE state over release cycles etc.

Hmm, my gut says 2-3 minor releases?  But open to suggestions.

**Comment by tariq1890** [comment]
> Yes, I think that might help us prevent some wrong metrics, like labels, or just any high cardinality we can't catch etc. And makes it easier for us to remove metrics.

Makes sense.

> Hmm, my gut says 2-3 minor releases? But open to suggestions.
I'd say that we wait until 2 minor releases for maturation.

**Comment by brancz** [comment]
I think there shouldn't be a hard upper rule, but a lower one. As in no metric can become stable without having baked for at least 2 releases, but may take longer, if we don't feel comfortable giving guarantees about it. Case in point: annotation/label metrics.

**Comment by LiliC** [comment]
Should we do this as part of kube-state-metrics 2.0? Look at the various metrics and add the stability to them?

**Comment by brancz** [comment]
Yes I think that makes sense.

**Comment by lilic** [comment]
@brancz and @tariq1890 any strong ideas around this? We should at least document the current ideas around it. WDYT?

**Comment by brancz** [comment]
Yes I think that makes sense.
