### ISSUE TITLE
Add metrics to expose aggregated/total sum of statuses on node/pod objects

### ISSUE THREAD

**Issue by lruslan** [kubernetes/kube-state-metrics#897]
> /kind bug
/kind feature

In a large k8s cluster with autoscaling enabled and pods/nodes frequently disappearing we most likely less interested in keeping metric per individual pod/nodes. Perfectly I'd like to disable all the detailed metrics with node/pod labels and only have metrics about total occurrence of statuses.
More specifically I'm interested in keeping track of total occurrence of specific statuses of node/pod/pod_container objects ( literally all the metrics with 'status' in name).

Reasoning:
In a busy GKE cluster with enabled autoscaling we have around 2000 pods and 400 nodes.
100 deployments with HPA enabled frequently changing number of replicas in a range between 10-100 replicas (average lifetime of pod is 10 minutes). We also use node pool with autoscaling enabled which also constantly replaces nodes. 

Pod and node related metrics exposed by kube-state-metrics introduce huge memory footprint on prometheus scraping them. We need around 50GB of memory assigned to prometheus only to fit data exposed by kube-state-metrics. And currently kube-state data represents 95% from all data we store in prometheus.

With kube-state-metrics in default configuration we have around 120k of time series exposed.
Also having new pods/nodes frequently added makes 'kube-state-metrics' main 'churner' in prometheus.  kube-state-metrics generates new series with rate 2k/minute (sum_over_time(scrape_series_added[30m]) ). When we have unexpected scale-up event it's most likely kube-state metrics will cause prometheus to crash with OOM (Prometheus has to fit 2h of series in memory)

95% of this load comes from kube_node_.*  and kube_pod_.* 

Suggestion:

What would be extremely useful is to keep track on total values across all node/pod objects.
Having total metrics on states would allow us to disable detailed per node/pod metrics and still be able to alert when we detect objects in undesired status allowing engineers to investigate further.

Like:
- total number of containers terminated because of 'reason'=='OOMKilled' 
current metric:  'kube_pod_container_status_terminated_reason'
additional metric: maybe we can introduce another one with suffixed with '_total', 'kube_pod_container_status_terminated_reason_total' with pod label removed

- total number of containers in specific 'waiting_reason' 
current metric: kube_pod_init_container_status_waiting_reason
additional metric: kube_pod_init_container_status_waiting_reason_total

- total number of nodes in non Ready state
current metric: kube_node_status_condition
additional metric: kube_node_status_condition_total , 'node' label removed

I see something similar was suggested earlier in https://github.com/kubernetes/kube-state-metrics/issues/173 only then main reasoning was around Stackdriver and in this case is mainly about optimising footprint by reducing verbosity while still allowing to expose data critical for alerting.

 I completely agree with idea of keeping metrics in sync/aligned with keys in kubernetes objects but unfortunately see no other way to reduce amount of samples while still be able to alert on states.

**Comment by brancz** [comment]
I understand and agree with the need for something like this, I just feel it should be solved outside of kube-state-metrics.

**Comment by lruslan** [comment]
@brancz  thanks for the feedback.
We were thinking, as a quick and dirty workaround, write component which would periodically scrape kube-state-metrics target and do the aggregation and totals for node/pod status metrics and expose them to prometheus. So we could scrape both kube-state-metrics (with node/pod metrics dropped) and our new component exposing node/pod totals. 
I'll check whether it would be more straightforward to write completely independent component. It just looks like it will have a lot in common with kube-state-metrics.
We also like to keep using kube-state-metrics only in 'reduced' mode - to collect details about less frequently changing objects.  
Curious if it's only us running in prometheus issues with kube-state-metrics on a large frequently changing clusters, maybe we just need to keep our clusters smaller.

**Comment by brancz** [comment]
For what it's worth we run kube-state-metrics with a very high scrape interval: 2m. And yes it's not a bad idea at all to pick out exactly the metrics/collectors that you actually want to reduce the amount of metrics you collect.
