### ISSUE TITLE
Enabling storageclasses causing container crash

### ISSUE THREAD

**Issue by liangrog** [kubernetes/kube-state-metrics#899]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
Metrics container crashed at start caused by enabling "storageclasses". However sometimes it succeeded. 

kube-metrics-kube-state-metrics-679cb65777-rv47l   0/1     CrashLoopBackOff   6          8m28s

I0925 01:05:16.248532       1 main.go:90] Using collectors configmaps,cronjobs,daemonsets,deployments,endpoints,ingresses,jobs,namespaces,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses
I0925 01:05:16.248634       1 main.go:99] Using all namespace
I0925 01:05:16.248649       1 main.go:140] metric white-blacklisting: blacklisting the following items:
W0925 01:05:16.248683       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0925 01:05:16.251069       1 main.go:185] Testing communication with server
I0925 01:05:16.258568       1 main.go:190] Running with Kubernetes cluster version: v1.9. git version: v1.9.3. git tree state: clean. commit: d2835416544f298c919e2ead3be3d0864b52323b. platform: linux/amd64
I0925 01:05:16.258631       1 main.go:192] Communication with server successful
I0925 01:05:16.258925       1 main.go:201] Starting kube-state-metrics self metrics server: 0.0.0.0:8081
I0925 01:05:16.259273       1 builder.go:126] Active collectors: configmaps,cronjobs,daemonsets,deployments,endpoints,ingresses,jobs,namespaces,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses
I0925 01:05:16.259296       1 main.go:226] Starting metrics server: 0.0.0.0:8080
E0925 01:05:16.266880       1 runtime.go:73] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 74 [running]:
k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x129ff40, 0x21c2590)
	/go/src/k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x129ff40, 0x21c2590)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kube-state-metrics/internal/store.glob..func207(0xc000280000, 0x30)
	/go/src/k8s.io/kube-state-metrics/internal/store/storageclass.go:40 +0x108
k8s.io/kube-state-metrics/internal/store.wrapStorageClassFunc.func1(0x13f8b80, 0xc000280000, 0x3)
	/go/src/k8s.io/kube-state-metrics/internal/store/storageclass.go:86 +0x5c
k8s.io/kube-state-metrics/pkg/metric.(*FamilyGenerator).Generate(...)
	/go/src/k8s.io/kube-state-metrics/pkg/metric/generator.go:39
k8s.io/kube-state-metrics/pkg/metric.ComposeMetricGenFuncs.func1(0x13f8b80, 0xc000280000, 0xc00036cd40, 0xc000280000, 0x0)
	/go/src/k8s.io/kube-state-metrics/pkg/metric/generator.go:78 +0x123
k8s.io/kube-state-metrics/pkg/metrics_store.(*MetricsStore).Add(0xc00036cd40, 0x13f8b80, 0xc000280000, 0x0, 0x0)
	/go/src/k8s.io/kube-state-metrics/pkg/metrics_store/metrics_store.go:76 +0xd2
k8s.io/kube-state-metrics/pkg/metrics_store.(*MetricsStore).Replace(0xc00036cd40, 0xc00007ee10, 0x1, 0x1, 0xc0000442e8, 0x8, 0xfe5fcdd0103e1f4, 0x5d8abd4c)
	/go/src/k8s.io/kube-state-metrics/pkg/metrics_store/metrics_store.go:138 +0xa4
k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache.(*Reflector).syncWith(0xc0003e4e60, 0xc00007ee00, 0x1, 0x1, 0xc0000442e8, 0x8, 0x0, 0xc000386fc0)
	/go/src/k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:315 +0xf8
k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc0003e4e60, 0xc0003f2500, 0xc0003860c0, 0xc0004d1cc0, 0x0, 0x0)
	/go/src/k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:215 +0x8ae
k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc0003e4e60, 0xc0003860c0, 0x0, 0x0)
	/go/src/k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:222 +0x17b
k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/go/src/k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:124 +0x33
k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00044e778)
	/go/src/k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x54
k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004d1f78, 0x3b9aca00, 0x0, 0x1, 0xc0003860c0)
	/go/src/k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/wait.Until(...)
	/go/src/k8s.io/kube-state-metrics/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache.(*Reflector).Run(0xc0003e4e60, 0xc0003860c0)
	/go/src/k8s.io/kube-state-metrics/vendor/k8s.io/client-go/tools/cache/reflector.go:123 +0x16b
created by k8s.io/kube-state-metrics/internal/store.(*Builder).reflectorPerNamespace
	/go/src/k8s.io/kube-state-metrics/internal/store/builder.go:296 +0x12b
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x116b378]

**How to reproduce it (as minimally and precisely as possible)**:
Deploy helm chart as normal: https://github.com/helm/charts/tree/master/stable/kube-state-metrics

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 

Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}

- Kube-state-metrics image version
v1.7.2

**Comment by LiliC** [comment]
@liangrog You seem to be using a very old version of Kubernetes, are you sure that `storageclasses` are available in that version already? Also, we don't make any guarantees for that old version of Kubernetes, we don't know how much the API changed since then. https://github.com/kubernetes/kube-state-metrics#compatibility-matrix

**Comment by liangrog** [comment]
@LiliC `storageclasses` had been made available long before the version(1.9.3) I am using. If you are saying kube_state_metrics doesn't support it I can understand, however most time the go-client is backward compatible.

**Comment by LiliC** [comment]
According to the [compatibility matrix of client-go ](https://github.com/kubernetes/client-go#compatibility-matrix)there are no exact guarantees for the current version of client-go and 1.9 version of k8s, my suspicion is something changed with that API, but can't be sure.

Does it work in older versions of kube-state-metrics that use an older client-go version?

**Comment by brancz** [comment]
I think this might actually be a bug. Dereferencing a string pointer legitimately panics. This needs to be guarded: https://github.com/kubernetes/kube-state-metrics/blob/52cbdc1464e3cdab8c9a845d463ab1aadb340003/internal/store/storageclass.go#L40

**Comment by clickyotomy** [comment]
Hello! Can I work on this?

**Comment by tariq1890** [comment]
@clickyotomy Please do!
