### ISSUE TITLE
add 1.16 to Compatibility matrix

### ISSUE THREAD

**Issue by yasongxu** [kubernetes/kube-state-metrics#901]
**Is this a BUG REPORT or FEATURE REQUEST?**:
no

**What happened**:

k8s 1.16 https://github.com/kubernetes/kubernetes/releases

**What you expected to happen**:

k8s 1.16 supported check

**Comment by brancz** [comment]
You're right, can you go ahead and add it? We're not using any of the removed APIs anymore, so it's 1.16 compatible.

**Comment by yasongxu** [comment]
ok
