### ISSUE TITLE
Autogenerate manifests

### ISSUE THREAD

**Issue by brancz** [kubernetes/kube-state-metrics#903]
With the introduction of sharding and autosharding (#613) we now have a number of manifests that are duplicated, and they are 95% the same. I'd like to have these manifests generated using jsonnet, which would not only make our lives easier here but also allow using the definitions by using [jsonnet-bundler](https://github.com/jsonnet-bundler/jsonnet-bundler). This will also make our lives easier in releases as we can have a canonical version bump and have it propagate through the repo.

Just to be clear, this is not actually proposing to change anything, the manifests generated will be identical to the ones we have and kustomize will be possible just as it is today.

@LiliC @tariq1890

**Comment by LiliC** [comment]
This sounds good to me!

I would like to also to also add alert for error rate based on the metrics that were recently introduced to kube-state-metrics. 

Would you like to do this, if not I can do it as well, if we all agree on it of course.

**Comment by tariq1890** [comment]
+100 

Let's do this!
