### ISSUE TITLE
Metric kube_node_spec_unschedulable metric should have node role/type

### ISSUE THREAD

**Issue by aksgithub** [kubernetes/kube-state-metrics#905]
/kind bug

**What happened**:
kube_node_spec_unschedulable reports all the k8s nodes on which scheduling is disabled. There is no way to differentiate between api nodes and worker nodes and due to that, we can not alert on when worker node is in scheduling disabled for too long - ex. someone cordon'ed  worker node and forgot to delete(ready but unschedulable) or there was some issue with bringing up worker node and so it's not schedulable.

**What you expected to happen**:
Need a label to differentiate between api and worker nodes

**How to reproduce it (as minimally and precisely as possible)**:
query metrics endpoint that's exposed by kube_state_metrics.

**Environment**:
- Kubernetes version (use `kubectl version`): v1.12.10
- Kube-state-metrics image version: v1.7.2

**Comment by tariq1890** [comment]
By "api" nodes, do you mean `master` nodes?

**Comment by tariq1890** [comment]
Also, we have a new node metric for the role as seen [here](https://github.com/kubernetes/kube-state-metrics/blob/master/internal/store/node.go#L106).

This is a new metric that will be available in the next release (v1.8.0). If you'd like to test this feature right away, you can pull the v1.8 rc image from [here](https://quay.io/repository/coreos/kube-state-metrics?tag=v1.8.0-rc.1) :)

**Comment by tariq1890** [comment]
Closing this since [v1.8.0](https://github.com/kubernetes/kube-state-metrics/releases/tag/v1.8.0) has been released.
