### ISSUE TITLE
[Feature Request] Namespace whitelist/blacklist

### ISSUE THREAD

**Issue by endzyme** [kubernetes/kube-state-metrics#906]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind feature

It would be wonderful if kube-state-metrics supported a `--namespace-whitelist` flag or `--namespace-blacklist` flag in addition to the `--namespace` flag already available. 

We have a use case where we're collecting so many metrics, it would be nice to  have kube-state-metrics split up the load with "only this namespace" as well as "all but this namespace" type collection. 

Happy to discuss further if needed :)

**Comment by brancz** [comment]
The `--namespace` flag already allows multiple values, so all we need is the opposite. Note that any type of opposite will still incur the same amount of load on the Kubernetes API, so I'm not too sure it's actually worth compared to the real sharding feature we are releasing with 1.8.

**Comment by endzyme** [comment]
Thanks for that valuable insight. I hadn't dug down deep enough to know if my pressure issues are in the KubeAPI itself or just too much data being pushed from kube-state-metrics. My line of thinking was to improve the transactional time to scrape data from a single kube-state-metrics endpoint by limiting the amount of data on each /metrics endpoint. 

I am not too familiar with how this process works today but our datadog agents appear to be choking on the size of the metrics endpoint page, while kube-state-metrics doesn't appear to be sweating much collecting the data from the kube api. 

I would need to take more time to assess if the kube api is also at play in this slow down when a client gets a large /metrics endpoint.

Thanks again and it looks like I have more homework to do.

**Comment by brancz** [comment]
/remove-lifecycle stale

I think this is still a legitimate feature, and we actually even already have the heavy lifting for this in place, we just need to expose this configuration via flags.

**Comment by drael** [comment]
Is there any plans to implement this feature?
As I understand if I want to ignore and don't scrape a specific namespace I need to add a list of namespaces I want.
