### ISSUE TITLE
Running kube-state-metrics container as non-root user

### ISSUE THREAD

**Issue by abokairatsfdc** [kubernetes/kube-state-metrics#913]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
/kind bug
>/kind feature

**What happened**:

Trying to run Kube-state-metrcis container as non root user.

after modifying the security context, following errors show:

User "system:serviceaccount:kube-system:kube-state-metrics" cannot list resource "jobs" in API group "batch" at the cluster scope
     1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Pod: pods is forbidden: User "system:serviceaccount:kube-system:kube-state-metrics" cannot list resource "pods" in API group "" at the cluster scope
       1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.ConfigMap: configmaps is forbidden: User "system:serviceaccount:kube-system:kube-state-metrics" cannot list resource"configmaps" in API group "" at the cluster scope
 1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:serviceaccount:kube-system:kube-state-metrics" cannotlist resource "persistentvolumes" in API group "" at the cluster scope
    1 reflector.go:125] pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/cache/reflector.go:98: Failed to list *v1.Node: nodes is forbidden:User "system:serviceaccount:kube-system:kube-state-metrics" cannot list resource "nodes" in API group "" at the cluster scope

Even though those permission are given as you can see below:

resource "kubernetes_cluster_role" "ksm_cluster_role" {
  metadata {
    name = ""
  }

  rule {
    api_groups = [""]
    resources  = ["configmaps", "secrets", "nodes", "pods", "services", "resourcequotas", "replicationcontrollers", "limitranges", "persistentvolumeclaims", "persistentvolumes", "namespaces", "endpoints"]
    verbs      = ["list", "watch"]
  }

  rule {
    api_groups = ["extensions"]
    resources  = ["daemonsets", "deployments", "replicasets", "ingresses"]
    verbs      = ["list", "watch"]
  }

  rule {
    api_groups = ["apps"]
    resources  = ["daemonsets", "deployments", "replicasets", "statefulsets"]
    verbs      = ["list", "watch"]
  }

  rule {
    api_groups = ["batch"]
    resources  = ["cronjobs", "jobs"]
    verbs      = ["list", "watch"]
  }

  rule {
    api_groups = ["autoscaling"]
    resources  = ["horizontalpodautoscalers"]
    verbs      = ["list", "watch"]
  }

  rule {
    api_groups = ["policy"]
    resources  = ["poddisruptionbudgets"]
    verbs      = ["list", "watch"]
  }

  rule {
    api_groups = ["certificates.k8s.io"]
    resources  = ["certificatesigningrequests"]
    verbs      = ["list", "watch"]
  }

  rule {
    api_groups = ["storage.k8s.io"]
    resources  = ["storageclasses"]
    verbs      = ["list", "watch"]
  }

  rule {
    api_groups = ["autoscaling.k8s.io"]
    resources  = ["verticalpodautoscalers"]
    verbs      = ["list", "watch"]
  }
}

**What you expected to happen**:
changing security context and run and login into the container as non-root user.

**How to reproduce it (as minimally and precisely as possible)**:
add the following security context:
security_context {
  run_as_user = 1000
} 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
v1.12.7
- Kube-state-metrics image version:
v1.7.2

**Comment by brancz** [comment]
Those errors have nothing to do with the user you run kube-state-metrics with. We run kube-state-metrics with a non root user just fine. This looks like you may have not setup RBAC correctly.
