### ISSUE TITLE
Import tool dependencies in go modules instead of go get

### ISSUE THREAD

**Issue by tariq1890** [kubernetes/kube-state-metrics#918]
As per the [best practices](https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module) recommended by the Go team, it is better to add tool dependencies like embedmd, benchcmp etc as module dependencies instead of `go get` as done over [here](https://github.com/kubernetes/kube-state-metrics/blob/master/Makefile#L136).

You can follow the steps mentioned here: https://github.com/kubernetes/kube-state-metrics/blob/master/Makefile#L136

**Comment by jeremyklein** [comment]
I can give this a shot!

**Comment by tariq1890** [comment]
Please do :)
