### ISSUE TITLE
Feature Request: Add support for augmenting metric tags from K8s labels

### ISSUE THREAD

**Issue by FraBle** [kubernetes/kube-state-metrics#931]
/kind feature

**What happened**:
There is currently no way to add additional tags to a metric, e.g. company-specific identifying attributes. The current recommendation is to [join metrics within Prometheus](https://github.com/kubernetes/kube-state-metrics/tree/master/docs#join-metrics) for example with labels, which are exposed as a separate metric for individual K8s objects, e.g. `kube_pod_labels` for pods. However, consuming metrics from kube-state-metrics in other systems, e.g. [Wavefront , makes these kind of joins a tedious task](https://docs.wavefront.com/query_language_series_joining.html).

**What you expected to happen**:
This feature request proposes to optionally extend metric tags based on K8s Labels:
The following the CLI parameters could be added (open to [naming] suggestions):

- `--include-labels-as-tags`: Boolean flag to include all labels of a K8s object as tags in all metrics of that K8s object
- `--label-prefix-filter`: Labels can have an optional prefix (DNS subdomain separated from label name by `/`) that can be leveraged to only include labels as tags that have that prefix, e.g. `example.com/`
- `--strip-label-prefix`: Boolean flag to allow stripping the label prefix, e.g. `example.com/id` becomes `id`

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
Example use case: I want to be able to add my company-specific metric tags to all metrics of a Pod. I would add the required labels to the pod definition:

```
…
metadata:
  …
  labels: 
    app: nginx
    example.com/id: 1234
    example.com/dc: east
  …
…
```

Now, I can leverage the new CLI parameters for kube-state-metrics to set:
`--include-labels-as-tags true --label-prefix-filter example.com/ --strip-label-prefix true`

Every pod metric will now include `id=1234` and `dc=east`, e.g. `kube_pod_status_phase` will provide these tags: `pod`, `namespace`, `phase`, `id`, and `dc`.

**Environment**:
- Kubernetes version (use `kubectl version`): any
- Kube-state-metrics image version: any

**Comment by brancz** [comment]
kube-state-metrics is designed to be ingested by Prometheus, the lack or inconvenience of features by other systems that happen to ingest Prometheus data is not a valid use case in my opinion to introduce features that Prometheus is perfectly capable of achieving.

Don't get me wrong, I totally understand your need for this, but I think this is then something that needs to be done at the conversion layer rather than in kube-state-metrics itself.

**Comment by gevalter** [comment]
I think this feature would be very useful. Im having the same problem
