### ISSUE TITLE
Update kubernetes libraries to v1.16.x

### ISSUE THREAD

**Issue by tariq1890** [kubernetes/kube-state-metrics#937]
Now that the `1.16` is the latest stable minor release of kubernetes, we should be vendoring them to kube-state-metrics.

**Comment by brennerm** [comment]
Would like to take care of this issue but I'm not sure where to find the correct library versions for v1.16.x. Can you give me a hint?

**Comment by tariq1890** [comment]
@brennerm So sorry for the late response. You could add the dependencies to the go.mod by go getting.

So for eg:- you could start with `go get k8s.io/apimachinery@kubernetes-1.16.1` and update the other k8s deps similarly. Let me know if this helps.

**Comment by vorburger** [comment]
According to https://github.com/kubernetes/kube-state-metrics/pull/945#issuecomment-551074188, this is already done now, via #949?

**Comment by tariq1890** [comment]
Yes. This can be closed.
