### ISSUE TITLE
Logging verbosity

### ISSUE THREAD

**Issue by JonasDeGendt** [kubernetes/kube-state-metrics#956]
Referencing issue #369. 

Kube-state-metrics is a bit too verbose to my liking, and I'd like edit the log level. The docs say there's a `--v` flag that takes a number for the log level verbosity. 

Yet I can't seem to find anywhere what the accepted values are, and anything I've tried to set ends up crash-looping the pod. 

Can anyone elaborate on this? Thank you!

**Comment by brancz** [comment]
It's the infamous [klog](https://github.com/kubernetes/klog). The verbosity is specified in numbers. I believe 3 for example hides almost everything.

**Comment by JonasDeGendt** [comment]
Thanks for the quick reply, fixed!

**Comment by eric-gymondo** [comment]
Could you share how this was fixed? I just can't find a way to set the flag on the container

**Comment by geofflancaster** [comment]
@eric-gymondo See https://github.com/kubernetes/kube-state-metrics/blob/master/docs/cli-arguments.md
