### ISSUE TITLE
[Question]: kube_daemonset_status_number_ready instance name

### ISSUE THREAD

**Issue by sincerywaing** [kubernetes/kube-state-metrics#960]
In prometheus if we scrape kube-state-metrics, we will have `kube_daemonset_status_number_ready` stats. But in the stats the instance name is alwasy the name of `targets` or service name of kube-state-metrics.

Is it possible to get per node daemonset status?

if this is the wrong kpi, what is the correct one to get per node daemonset status?

**Comment by brancz** [comment]
The instance label is the label of kube state metrics itself as it is the things exposing this metric once cluster wide. You can use the namespace and daemonset labels to scope it to the daemonset you are looking at.

**Comment by sincerywaing** [comment]
@brancz can you elaborate more on how to configure? say I have a daemonset name abc deployed in ns def. how do I scrape to know if abc is up and running and send alert if certain number of abc is down?

**Comment by brancz** [comment]
Something along the lines of `kube_daemonset_status_number_unavailable != 0` ?
