### ISSUE TITLE
Add kubernetes nodes annotations

### ISSUE THREAD

**Issue by mpashka** [kubernetes/kube-state-metrics#964]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: 
>
> /kind bug

/kind feature

**What happened**:
kubernetes node annotations are not exported

**What you expected to happen**:
I'd like to have kubernetes node annotations exported in kube-state-metrics.
Also I'd like to have numerical annotations exported separately. This is important for us because we use `ingress.kubernetes.io/node-weight` annotation to weight nodes. So it can be useful to have node weight value as metric with pod CPU load to adjust node weights.

**Comment by LiliC** [comment]
@mpashka  Is this a limited set of annotations. Also could they include any sensitive information in those annotations?

**Comment by brancz** [comment]
Is this a standardized annotation that all ingress controllers must respect?

**Comment by mpashka** [comment]
Usually node annotations number is limited. Node count is limited as well.
Probably some default filters can be applied to prevent using annotations with long name or value.
Sensitive information is usually stored in secrets. But sometimes annotations can be used for that as well - e.g. kube-router uses [kube-router.io/peer.passwords](https://github.com/cloudnativelabs/kube-router/blob/master/docs/bgp.md#bgp-peer-password-authentication) annotation to store passwords - so it can be useful to allow filtering out some annotations.

`ingress.kubernetes.io/node-weight` is not a standard annotation

**Comment by brancz** [comment]
> ingress.kubernetes.io/node-weight is not a standard annotation

In that case I feel this rather belongs on the ingress controller.

**Comment by LiliC** [comment]
Relevant PR that introduces ingress annotations -> https://github.com/kubernetes/kube-state-metrics/pull/1041/files
