### ISSUE TITLE
The field kubernetes.replicaset.replicas.available on every log is set to 0

### ISSUE THREAD

**Issue by jdor521** [kubernetes/kube-state-metrics#967]
Is this a BUG REPORT or FEATURE REQUEST?:
/kind bug

What happened:
I am using metricbeat (with elasticsearch) version 6.8.4 to monitor my kubernetes cluster, I am using rancher based kubernetes cluster, and using the kube-state-metrics module.
and all the fields that suppose to have info about the status of my replicasets (replicas.available, replicas.observed etc..) always show 0 no matter what I do.

What you expected to happen:
expect the fields to display number of available pods in my replicaset.

How to reproduce it (as minimally and precisely as possible):
no need to repreduce, the logs always display 0.

Environment: 
offline kubernetes cluster using Rancher

Kubernetes version (use kubectl version): 1.15.5
Kube-state-metrics image version: 1.7.2

**Comment by brancz** [comment]
Can you confirm that the kube-state-metrics `/metrics` output actually exposes 0? Also does the Kubernetes API actually return something other than 0?

**Comment by jdor521** [comment]
> Can you confirm that the kube-state-metrics `/metrics` output actually exposes 0? Also does the Kubernetes API actually return something other than 0?

Well can you help me to check it properly? (tried browsing the route /metrics but got only the metrics and not actually the data it collects)

**Comment by brancz** [comment]
There are two ports that kube-state-metrics has http servers on, one the metrics of kube-state-metrics itself, the other for the metrics about the Kubernetes objects. Make sure to use the right one :)

**Comment by jdor521** [comment]
> There are two ports that kube-state-metrics has http servers on, one the metrics of kube-state-metrics itself, the other for the metrics about the Kubernetes objects. Make sure to use the right one :)

well I managed to check /monitor route and the output is actually 0 :/ (kube_replicaset_status_replicas, kube_replicaset_ready_replicas etc...)

**Comment by brancz** [comment]
And when you check `kubectl get replicaset <name> -oyaml` you see something different in the status? (if you could share the exact samples that would help us immensely)

**Comment by jdor521** [comment]
> And when you check `kubectl get replicaset <name> -oyaml` you see something different in the status? (if you could share the exact samples that would help us immensely)

sorry for the delay, I was trying to get you some samples and I figured out my problem: I had many "ghost" replica sets that spammed my kube-metrics. after deleting them I got the desired logs and everything works just fine now. 
thank you for your response :)
