### ISSUE TITLE
Docs for kube_replicaset metrics don't match implementation

### ISSUE THREAD

**Issue by sophaskins** [kubernetes/kube-state-metrics#97]
The project [README.md](https://github.com/kubernetes/kube-state-metrics/blob/b7458223c078844dc2f8a2c9b63ed5f1829b4d48/README.md) lists the ReplicaSet metrics as:

- kube_replicaset_status_replicas
- kube_replicaset_status_replicas_available
- kube_replicaset_status_replicas_unavailable
- kube_replicaset_status_replicas_updated
- kube_replicaset_status_replicas_observed_generation
- kube_replicaset_spec_replicas
- kube_replicaset_spec_paused
- kube_replicaset_metadata_generation

but the [implementation](https://github.com/kubernetes/kube-state-metrics/blob/b7458223c078844dc2f8a2c9b63ed5f1829b4d48/replicaset.go) defines:

- kube_replicaset_status_replicas
- kube_replicaset_status_fully_labeled_replicas
- kube_replicaset_status_ready_replicas
- kube_replicaset_status_observed_generation
- kube_replicaset_spec_replicas
- kube_replicaset_metadata_generation

It looks like the documentation is just a duplicate of the metrics for Deployments w/ 'replicaset' replacing 'deployment' - should the docs be updated to match? Is the implementation as desired?

**Comment by brancz** [comment]
Looking at the [upstream structs](https://github.com/kubernetes/client-go/blob/ca90456a21c1db4b5b1dadff1dbcc6f75692d0ee/pkg/apis/extensions/types.go) implementation is as intended, it seems the documentation is off. Do you want to open a PR to fix the documentation?
