### ISSUE TITLE
can not find kube-state-metrics/kubernetes file

### ISSUE THREAD

**Issue by douwilliam** [kubernetes/kube-state-metrics#970]
FEATURE REQUEST?**:
> /kind feature

**What happened**:
I am doing the following tutorials:
https://kubernetes.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/#view-the-changes-in-kibana
there is command to create kube-state-metrics:
kubectl create -f kube-state-metrics/kubernetes
but the file kubernetes is not under the folder  kube-state-metrics/

**What you expected to happen**:
could you please tell me what the creation command now. 
thanks

**Comment by tariq1890** [comment]
@douwilliam Thanks for reporting this issue. We have changed the directory layout of the `kube-state-metrics` manifests. Please try this command instead:

```
kubectl create -f examples/standard
```

I have created a PR to the update the tutorials to reflect this change: https://github.com/kubernetes/website/pull/17570

**Comment by douwilliam** [comment]
Thanks for your help!

**Comment by LiliC** [comment]
Closing this issue, as it was solved.
