### ISSUE TITLE
there is no metric for counting labels.

### ISSUE THREAD

**Issue by tmon546596046** [kubernetes/kube-state-metrics#972]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind feature

**What happened**:
kube_.\*_labels metrics value is always 1.
there is no metric for counting deployment labels, the pod labels(label\_*) only show in promethes label.
**What you expected to happen**:
one more metric: kube\_.\*_labels_count = <label_counts>
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- Kube-state-metrics image version
kube-state-metrics:v1.5.0

**Comment by brancz** [comment]
I think it would be ok to have a metric like this.

**Comment by ankitsinhaiiitg** [comment]
I would like to contribute to this issue.
