### ISSUE TITLE
v2: Remove deprecated metrics

### ISSUE THREAD

**Issue by LiliC** [kubernetes/kube-state-metrics#974]
For the breaking v2 release we want remove all the metrics that have been marked as DEPRECATED.

Blocked until after release v1.9.0.

**Comment by yeya24** [comment]
Hi, can I take this?

**Comment by yeya24** [comment]
One question about it.
In https://github.com/kubernetes/kube-state-metrics/blob/c6c261b6b50d861c540c9a15fe0ce58d639faee8/docs/README.md, there are some metrics marked as deprecated.  But in https://github.com/kubernetes/kube-state-metrics/blob/f09db29f7955e5e628c54130fac1ac116836412c/docs/node-metrics.md I found there is a metric `kube_node_status_phase` marked as deprecated, but it is not in the previous doc. So is this metric deprecated? Do we need to remove it as well?

**Comment by LiliC** [comment]
/assign @yeya24 

Go ahead, thanks!

Yes lets remove all that are deprecated, maybe the docs are not matched.

**Comment by yeya24** [comment]
@LiliC  Thanks.
Another question:   Do we still need the two options after removing the deprecated metrics? I guess I need to remove them as well?
``` Go
	if opts.DisablePodNonGenericResourceMetrics {
		whiteBlackList.Exclude([]string{
			"kube_pod_container_resource_requests_cpu_cores",
			"kube_pod_container_resource_requests_memory_bytes",
			"kube_pod_container_resource_limits_cpu_cores",
			"kube_pod_container_resource_limits_memory_bytes",
		})
	}

	if opts.DisableNodeNonGenericResourceMetrics {
		whiteBlackList.Exclude([]string{
			"kube_node_status_capacity_cpu_cores",
			"kube_node_status_capacity_memory_bytes",
			"kube_node_status_capacity_pods",
			"kube_node_status_allocatable_cpu_cores",
			"kube_node_status_allocatable_memory_bytes",
			"kube_node_status_allocatable_pods",
		})
	}
```
