### ISSUE TITLE
v2: Rename black-/whitelist to allow/deny-list

### ISSUE THREAD

**Issue by LiliC** [kubernetes/kube-state-metrics#975]
In all the places in the code and the CLI flags we want to rename the black-/whitelist to allow/deny-list.

Blocked for merging until after the v1.9.0 release.

**Comment by nicolereineke** [comment]
Question -- is the requirement to rename the end-user facing content from 
"Whitelist" to "Allow" and 
"Blacklist" to "Deny"  (example, swagger documentation, CLI output, error messages)

or is the intent to change the customer-visible text and the functionnames/switches/filenames. For example:
kubectl apply --prune -l prune-group=true -f hack/testdata/prune/svc.yaml --prune-whitelist core/v1/Service 2>&1 "${kube_flags[@]:?}"

would become 
kubectl apply --prune -l prune-group=true -f hack/testdata/prune/svc.yaml --prune-allow core/v1/Service 2>&1 "${kube_flags[@]:?}"

**Comment by LiliC** [comment]
@nicolereineke No this is for kube-state-metrics only, both CLI flags and code changes, not sure what you mean by kubectl there?

**Comment by tlereste** [comment]
Hi there, I made my first contribution for kube-state-metrics project.
Hope all is good :)

**Comment by LiliC** [comment]
Hi, @tlereste thanks, reviewed the PR, so lets continue the discussion there :)

**Comment by tlereste** [comment]
Hi @LiliC ! Thanks, I just pushed two fixes for the tests !

**Comment by tlereste** [comment]
Ok, after another PR and many small fixes, my PR is OK yet !
