### ISSUE TITLE
v2: Rename --namespace flag to --namespaces

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#978]
Rename the CLI flag namespace to namespaces.

The merging of this is blocked until after the v1.9.0 release.

**Comment by raunaqness** [comment]
Hey @LiliC. Can I take this up?

**Comment by LiliC** [comment]
@raunaqness go for it! Thanks! Note that it won’t be merged until the current release candidate is released. So a week or two. :) 

/assign @raunaqness

**Comment by raunaqness** [comment]
@LiliC Thanks! 
I'm a little new to open source contribution, can you guide me a little bit about where I should start looking for to make the changes for this?

**Comment by LiliC** [comment]
Just search wherever it says `namespace` in CLI flags and rename to `namespaces`. https://github.com/kubernetes/kube-state-metrics/blob/master/pkg/options/options.go#L88
