### ISSUE TITLE
v2: Rename collector to resources 

### ISSUE THREAD

**Issue by LiliC** [kubernetes/kube-state-metrics#980]
Rename use of "collector" in user facing things (flags, help text, etc.) to "resources", as the collector type pattern does not exist anymore.

Merging of this will be blocked until after the v1.9.0 release.

**Comment by Alexander-Carpenter** [comment]
Hi @LiliC could I go ahead and grab this? Just getting started into contributing for kubernetes

**Comment by Alexander-Carpenter** [comment]
Working on this, are you wanting just the collector options from main, options, builder, and a few md files? Not the actual go files that are collectors and changing all those to resources instead

**Comment by LiliC** [comment]
@Alexander-Carpenter thanks! Everything can be renamed including the files.
