### ISSUE TITLE
Remove resource version metrics

### ISSUE THREAD

**Issue by lilic** [kubernetes/kube-state-metrics#982]
kube_secret_metadata_resource_version, kube_configmap_metadata_resource_version and kube_ingress_metadata_resource_version expose the resource version as a string in its set of labels. This value can change often and would therefore create huge cardinality. This should be a number or not existing at all.

This is a breaking change but we should remove it as its currently causing a cardinality explosion.

@tariq1890 we discussed with @brancz and we should really do this in 1.x already. SGTY

**Comment by brancz** [comment]
I think this should already be fixed in 1.x yes.

**Comment by tariq1890** [comment]
Sounds good to me!

**Comment by lilic** [comment]
I think this was already implemented in my PR.
/close
