### ISSUE TITLE
filtering metrics with --metric-blacklist option using regex

### ISSUE THREAD

**Issue by grayudu** [kubernetes/kube-state-metrics#988]
I would like to filter some of following metrics.
      - args:
        - --collectors=cronjobs
        - --collectors=daemonsets
        - --collectors=deployments
        - --collectors=endpoints
        - --collectors=horizontalpodautoscalers
        - --collectors=jobs
        - --collectors=limitranges
        - --collectors=namespaces
        - --collectors=nodes
        - --collectors=pods
        - --collectors=persistentvolumeclaims
        - --collectors=persistentvolumes
        - --collectors=replicasets
        - --collectors=replicationcontrollers
        - --collectors=resourcequotas
        - --collectors=services
        - --collectors=statefulsets
       - --metricblacklist=kube_cronjob_info,kube_cronjob_created,kube_cronjob_status_last_schedule_time,kube_cronjob_spec_suspend,kube_cronjob_spec_starting_deadline_seconds,kube_cronjob_next_schedule_time,kube_daemonset_created,kube_daemonset_status_current_number_scheduled,kube_daemonset_status_desired_number_scheduled,kube_daemonset_status_number_misscheduled,kube_daemonset_status_number_unavailable,kube_daemonset_updated_number_scheduled,kube_daemonset_metadata_generation,kube_deployment_status_replicas,kube_deployment_status_observed_generation,kube_deployment_spec_replicas,kube_deployment_spec_strategy_rollingupdate_max_unavailable,kube_deployment_spec_strategy_rollingupdate_max_surge,kube_deployment_metadata_generation,kube_endpoint_info,kube_endpoint_created,kube_endpoint_address_available,kube_hpa_metadata_generation

I am not able to filter them using regex. are there any specific format for regex?

**Environment**: 
- Kubernetes version (use `kubectl version`): 1.14
- Kube-state-metrics image version  v1.5

**Comment by brancz** [comment]
What you shared here doesn't look like a regex, but a comma separated list.

cc @tariq1890

**Comment by grayudu** [comment]
Thanks for your reply @brancz  I am just given sample of metrics want to filter.
for example:  when i try using following regex, i don't see regex working fine.
        - --metric-blacklist=kube_cronjob_[s][a-z_]+

**Comment by tariq1890** [comment]
Sorry for the late response.

@grayudu I tested your regex and it works as expected.

The reason why it does not work for you is that you're using an old version of kube-state-metrics. Please ensure that you're using at least `kube-state-metrics-v1.7.x.`
