### ISSUE TITLE
The explanation for `kube-state-metrics-vs-heapster` is not accurate

### ISSUE THREAD

**Issue by gyliu513** [kubernetes/kube-state-metrics#99]
In https://github.com/kubernetes/kube-state-metrics#kube-state-metrics-vs-heapster , it  claims that `some monitoring systems such as Prometheus do not use Heapster for metric collection at all and instead implement their own`.

I think that this may be not accurate, as actually, I can always use Heapster as a prometheus scrape targets, right?

**Comment by brancz** [comment]
If @fabxc agrees, I'd say we just adapt it to the answer he gave on the Prometheus mailing list https://groups.google.com/d/msg/prometheus-developers/3zq4oD7if3s/4VUG7X_4DQAJ . Does that sounds good to you @gyliu513 ?

**Comment by gyliu513** [comment]
Yes, so I think that for here we'd better mention that `the prometheus can be a heapster sink (backend)`, what do you say @brancz ?

**Comment by brancz** [comment]
Sounds good to me. Do you want to open the PR for that @gyliu513 ?

**Comment by gyliu513** [comment]
Sure, will follow up a PR, @brancz
