### ISSUE TITLE
kube-state metrics is not running with HELM

### ISSUE THREAD

**Issue by saniic** [kubernetes/kube-state-metrics#990]
**Is this a BUG REPORT or FEATURE REQUEST?**: May be bug or my mistake 

> Uncomment only one, leave it on its own line: 
>
> /kind bug
> /kind feature

**What happened**: I am trying to use helm for kube-state-metrics installation as i do it for prometheus and it nt working. I have added below entry in helm and it not taking anything 

 --set server.image.tag="v2.11.1" \
 --set kubeStateMetrics.image.tag="v1.7.0" \

Prometheus is working for me and there is no change in kubeStatemetrics when we adding new version here and applying through terraform .

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Yes, i can do it 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): v1.11.9
- Kube-state-metrics image version: trying to use 1.7 and currently its 1.6

**Comment by brancz** [comment]
@tariq1890 I think you somewhat maintain the kube-state-metrics chart right? Could you take a look at this?

**Comment by tariq1890** [comment]
@saniic Could you be a bit more specific here? Are you using the `stable` helm charts? What is the exact issue/error message that you get?

**Comment by whitecolor** [comment]
@tariq1890 
It seems I have a like problem, installed from the latest helm chart, metrics don't seem to update in Metrics explorer in Gcloud Stackdriver Monitoring.

I have the following log output of kube-state-metrics pod:
```
I0218 17:13:30.725098       1 main.go:89] Using collectors certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,namespaces,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses
I0218 17:13:30.725171       1 main.go:98] Using all namespace
I0218 17:13:30.730285       1 main.go:139] metric white-blacklisting: blacklisting the following items:
W0218 17:13:30.730339       1 client_config.go:543] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0218 17:13:30.736123       1 main.go:184] Testing communication with server
I0218 17:13:30.779040       1 main.go:189] Running with Kubernetes cluster version: v1.13+. git version: v1.13.12-gke.25. git tree state: clean. commit: 654de8cac69f1fc5db6f2de0b88d6d027bc15828. platform: linux/amd64
I0218 17:13:30.779307       1 main.go:191] Communication with server successful
I0218 17:13:30.779594       1 main.go:225] Starting metrics server: 0.0.0.0:8080
I0218 17:13:30.779928       1 metrics_handler.go:96] Autosharding disabled
I0218 17:13:30.780635       1 builder.go:146] Active collectors: certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,namespaces,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses
I0218 17:13:30.786516       1 main.go:200] Starting kube-state-metrics self metrics server: 0.0.0.0:8081
```

**Comment by brancz** [comment]
The logs look fine. As we don’t know or maintain anything like a stack driver integration, please refer to their support.

**Comment by whitecolor** [comment]
Probably there is needed this to be added:

https://github.com/GoogleCloudPlatform/k8s-stackdriver/blob/master/prometheus-to-sd/README.md
